# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataProcessingSettingDialog.ui'
#
# Created: Fri May 21 16:12:12 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_DataProcessingSettingDlg(object):
    def setupUi(self, Dialog_DataProcessingSettingDlg):
        Dialog_DataProcessingSettingDlg.setObjectName("Dialog_DataProcessingSettingDlg")
        Dialog_DataProcessingSettingDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_DataProcessingSettingDlg.resize(380, 359)
        Dialog_DataProcessingSettingDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_DataProcessingSettingDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_2 = QtGui.QGridLayout(Dialog_DataProcessingSettingDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_DataProcessingSettingDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.groupBox_WorkSpace_X = QtGui.QGroupBox(Dialog_DataProcessingSettingDlg)
        self.groupBox_WorkSpace_X.setObjectName("groupBox_WorkSpace_X")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_WorkSpace_X)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.radioButton_text_format = QtGui.QRadioButton(self.groupBox_WorkSpace_X)
        self.radioButton_text_format.setChecked(True)
        self.radioButton_text_format.setObjectName("radioButton_text_format")
        self.horizontalLayout_5.addWidget(self.radioButton_text_format)
        self.radioButton_binary_format = QtGui.QRadioButton(self.groupBox_WorkSpace_X)
        self.radioButton_binary_format.setObjectName("radioButton_binary_format")
        self.horizontalLayout_5.addWidget(self.radioButton_binary_format)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_set_prefix = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_set_prefix.setObjectName("checkBox_set_prefix")
        self.horizontalLayout_3.addWidget(self.checkBox_set_prefix)
        self.lineEdit_prefix = QtGui.QLineEdit(self.groupBox_WorkSpace_X)
        self.lineEdit_prefix.setObjectName("lineEdit_prefix")
        self.horizontalLayout_3.addWidget(self.lineEdit_prefix)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_set_suffix = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_set_suffix.setObjectName("checkBox_set_suffix")
        self.horizontalLayout_4.addWidget(self.checkBox_set_suffix)
        self.lineEdit_suffix = QtGui.QLineEdit(self.groupBox_WorkSpace_X)
        self.lineEdit_suffix.setObjectName("lineEdit_suffix")
        self.horizontalLayout_4.addWidget(self.lineEdit_suffix)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setMargin(15)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.checkBox_Time_obser = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_Time_obser.setObjectName("checkBox_Time_obser")
        self.verticalLayout.addWidget(self.checkBox_Time_obser)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.checkBox_space_obser = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_space_obser.setObjectName("checkBox_space_obser")
        self.verticalLayout.addWidget(self.checkBox_space_obser)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.checkBox_contor_plot = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_contor_plot.setObjectName("checkBox_contor_plot")
        self.verticalLayout.addWidget(self.checkBox_contor_plot)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.checkBox_vector_data = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_vector_data.setObjectName("checkBox_vector_data")
        self.verticalLayout.addWidget(self.checkBox_vector_data)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.checkBox_phase_space = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_phase_space.setObjectName("checkBox_phase_space")
        self.verticalLayout.addWidget(self.checkBox_phase_space)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 7, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 3, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_WorkSpace_X, 0, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 1, 0, 1, 1)

        self.retranslateUi(Dialog_DataProcessingSettingDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_DataProcessingSettingDlg)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.pushButton_ok, self.checkBox_Time_obser)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_Time_obser, self.checkBox_space_obser)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_space_obser, self.checkBox_contor_plot)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_contor_plot, self.checkBox_vector_data)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_vector_data, self.checkBox_phase_space)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_phase_space, self.checkBox_set_prefix)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_set_prefix, self.lineEdit_prefix)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.lineEdit_prefix, self.checkBox_set_suffix)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.checkBox_set_suffix, self.lineEdit_suffix)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.lineEdit_suffix, self.radioButton_text_format)
        Dialog_DataProcessingSettingDlg.setTabOrder(self.radioButton_text_format, self.radioButton_binary_format)

    def retranslateUi(self, Dialog_DataProcessingSettingDlg):
        Dialog_DataProcessingSettingDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "数据处理设置", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_X.setTitle(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "数据导出设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "导出格式：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_text_format.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "文本格式", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_binary_format.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "二进制格式", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_set_prefix.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "设置文件前缀", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_set_suffix.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "设置文件后缀", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "导出数据包括：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Time_obser.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "时间观测", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_space_obser.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "空间观测", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_contor_plot.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "等位图数据", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_vector_data.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "矢量图数据", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_phase_space.setText(QtGui.QApplication.translate("Dialog_DataProcessingSettingDlg", "相位空间数据", None, QtGui.QApplication.UnicodeUTF8))

