SET(Physics_Srcs
./.idea/encodings.xml
./.idea/misc.xml
./.idea/modules.xml
./.idea/Physics.iml
./.idea/vcs.xml
./.idea/workspace.xml
./InitGui.py
./PhysicsGui/.idea/misc.xml
./PhysicsGui/.idea/modules.xml
./PhysicsGui/.idea/PhysicsGui.iml
./PhysicsGui/.idea/vcs.xml
./PhysicsGui/.idea/workspace.xml
./PhysicsGui/BatchDlg.py
./PhysicsGui/BatchDlg.ui
./PhysicsGui/BoundPal.py
./PhysicsGui/CntrDlg.py
./PhysicsGui/CntrDlg.ui
./PhysicsGui/DefaultTimerDlg.py
./PhysicsGui/DefaultTimerDlg.ui
./PhysicsGui/DefaultTimerDlgMain.py
./PhysicsGui/EmbDlg.py
./PhysicsGui/EmbDlg.ui
./PhysicsGui/EmeDlg.py
./PhysicsGui/EmeDlg.ui
./PhysicsGui/EmgDlg.py
./PhysicsGui/EmgDlg.ui
./PhysicsGui/EmhDlg.py
./PhysicsGui/EmhDlg.ui
./PhysicsGui/EmseDlg.py
./PhysicsGui/EmseDlg.ui
./PhysicsGui/EmtDlg.py
./PhysicsGui/EmtDlg.ui
./PhysicsGui/ExpDlg.py
./PhysicsGui/ExpDlg.ui
./PhysicsGui/FoilDlg.py
./PhysicsGui/FoilDlg.ui
./PhysicsGui/FreeDlg.py
./PhysicsGui/FreeDlg.ui
./PhysicsGui/GasgasDlg.py
./PhysicsGui/GasgasDlg.ui
./PhysicsGui/IndDlg.py
./PhysicsGui/IndDlg.ui
./PhysicsGui/MarkDlg.py
./PhysicsGui/MarkDlg.ui
./PhysicsGui/MergeDlg.py
./PhysicsGui/MergeDlg.ui
./PhysicsGui/ObsDlg.py
./PhysicsGui/ObsDlg.ui
./PhysicsGui/ObservePal.py
./PhysicsGui/PhaDlg.py
./PhysicsGui/PhaDlg.ui
./PhysicsGui/PopulateDlg.py
./PhysicsGui/PopulateDlg.ui
./PhysicsGui/PortDlg.py
./PhysicsGui/PortDlg.ui
./PhysicsGui/PortDlgMain.py
./PhysicsGui/RanDlg.py
./PhysicsGui/RanDlg.ui
./PhysicsGui/SolDlg.py
./PhysicsGui/SolDlg.ui
./PhysicsGui/SpeciesDlg.py
./PhysicsGui/SpeciesDlg.ui
./PhysicsGui/SymDlg.py
./PhysicsGui/SymDlg.ui
./PhysicsGui/TaskControl.py
./PhysicsGui/TaskControl.ui
./PhysicsGui/TaskControlPal.py
./PhysicsGui/TaskControlPal.ui
./PhysicsGui/TaskControlPalMain.py
./PhysicsGui/TimerDlg.py
./PhysicsGui/TimerDlg.ui
./PhysicsGui/TimerDlgMain.py
./PhysicsGui/TreeStruct.ui
./PhysicsGui/VectorDlg.py
./PhysicsGui/VectorDlg.ui
./PhysicsGui/__init__.py
./PhysicsResources/all-run.svg
./PhysicsResources/batch.svg
./PhysicsResources/check.png
./PhysicsResources/check.svg
./PhysicsResources/cntr.svg
./PhysicsResources/continue.png
./PhysicsResources/continue.svg
./PhysicsResources/continue2.png
./PhysicsResources/continue2.svg
./PhysicsResources/default-timer.svg
./PhysicsResources/driver.svg
./PhysicsResources/emb.png
./PhysicsResources/emb.svg
./PhysicsResources/eme.png
./PhysicsResources/eme.svg
./PhysicsResources/emg.png
./PhysicsResources/emg.svg
./PhysicsResources/emh.png
./PhysicsResources/emh.svg
./PhysicsResources/emt.png
./PhysicsResources/emt.svg
./PhysicsResources/finish.svg
./PhysicsResources/foil.svg
./PhysicsResources/free.png
./PhysicsResources/free.svg
./PhysicsResources/Group.svg
./PhysicsResources/ind.svg
./PhysicsResources/ioni.png
./PhysicsResources/ioni.svg
./PhysicsResources/Item.svg
./PhysicsResources/logFile.svg
./PhysicsResources/mark.png
./PhysicsResources/mark.svg
./PhysicsResources/muti-run.svg
./PhysicsResources/no-result.svg
./PhysicsResources/obs.svg
./PhysicsResources/off.png
./PhysicsResources/off.svg
./PhysicsResources/on.png
./PhysicsResources/on.svg
./PhysicsResources/on2.svg
./PhysicsResources/pause.png
./PhysicsResources/pause.svg
./PhysicsResources/pha.svg
./PhysicsResources/physics-workbench.png
./PhysicsResources/physics-workbench.svg
./PhysicsResources/popu.png
./PhysicsResources/popu.svg
./PhysicsResources/port.png
./PhysicsResources/port.svg
./PhysicsResources/ran.svg
./PhysicsResources/receive.png
./PhysicsResources/receive.svg
./PhysicsResources/receive2.svg
./PhysicsResources/receiving.svg
./PhysicsResources/redoPal.svg
./PhysicsResources/refresh.png
./PhysicsResources/refresh.svg
./PhysicsResources/refresh2.png
./PhysicsResources/refresh2.svg
./PhysicsResources/refreshing.png
./PhysicsResources/refreshing.svg
./PhysicsResources/run.svg
./PhysicsResources/run2.svg
./PhysicsResources/secd.png
./PhysicsResources/secd.svg
./PhysicsResources/sole.svg
./PhysicsResources/sym.png
./PhysicsResources/sym.svg
./PhysicsResources/timer.svg
./PhysicsResources/undoPal.svg
./PhysicsResources/vec.svg
./PhysicsResources/__init__.py
./PhysicsTools/CompleterTools.py
./PhysicsTools/SetColorTools.py
./PhysicsTools/SetVisibilityOfModels.py
./PhysicsTools/__init__.py
./Readme.md
./StyledComboBox.py
./SwitchWorkbench.py
./__init__.py
)
add_custom_target(Physics ALL SOURCES ${Physics_Srcs})
fc_copy_sources(Physics "${CMAKE_BINARY_DIR}/Mod/Physics" ${Physics_Srcs})
install(
	FILES
	${Physics_Srcs}
	DESTINATION
	Mod/Physics
)