SET(Model3D_Srcs
./Command3D/Model3DCommand/Area_Conformal/AreaConformalCommand.py
./Command3D/Model3DCommand/Area_Conformal/AreaConformalDialogMain.py
./Command3D/Model3DCommand/Area_Conformal/AreaConformalInstance.py
./Command3D/Model3DCommand/Area_Conformal/PointWidget.py
./Command3D/Model3DCommand/Area_Conformal/PointWidget.ui
./Command3D/Model3DCommand/Area_Conformal/PointWidgetac.py
./Command3D/Model3DCommand/Area_Conformal/__init__.py
./Command3D/Model3DCommand/Area_Function/AreaFunctionCommand.py
./Command3D/Model3DCommand/Area_Function/AreaFunctionDialogMain.py
./Command3D/Model3DCommand/Area_Function/AreaFunctionInstance.py
./Command3D/Model3DCommand/Area_Function/PointWidget.py
./Command3D/Model3DCommand/Area_Function/PointWidget.ui
./Command3D/Model3DCommand/Area_Function/__init__.py
./Command3D/Model3DCommand/Area_Polygonal/ItemWidget3D.py
./Command3D/Model3DCommand/Area_Polygonal/ItemWidget3D.ui
./Command3D/Model3DCommand/Area_Polygonal/PolygonalCommand.py
./Command3D/Model3DCommand/Area_Polygonal/PolygonalDialog.py
./Command3D/Model3DCommand/Area_Polygonal/PolygonalDialog.ui
./Command3D/Model3DCommand/Area_Polygonal/PolygonalDialogMain.py
./Command3D/Model3DCommand/Area_Polygonal/PolygonalInstance.py
./Command3D/Model3DCommand/Area_Polygonal/__init__.py
./Command3D/Model3DCommand/Area_Rectangle/AreaRectangleCommand.py
./Command3D/Model3DCommand/Area_Rectangle/AreaRectangleDialogMain.py
./Command3D/Model3DCommand/Area_Rectangle/AreaRectangleInstance.py
./Command3D/Model3DCommand/Area_Rectangle/PointWidget.py
./Command3D/Model3DCommand/Area_Rectangle/PointWidget.ui
./Command3D/Model3DCommand/Area_Rectangle/__init__.py
./Command3D/Model3DCommand/BaseUI/BaseDialog.py
./Command3D/Model3DCommand/BaseUI/BaseDialog.ui
./Command3D/Model3DCommand/BaseUI/BaseDialogMain.py
./Command3D/Model3DCommand/BaseUI/CustomWidget.py
./Command3D/Model3DCommand/BaseUI/customWidget.ui
./Command3D/Model3DCommand/BaseUI/__init__.py
./Command3D/Model3DCommand/Boolen/BoolCommand.py
./Command3D/Model3DCommand/Boolen/__init__.py
./Command3D/Model3DCommand/Clip/ClipCommand.py
./Command3D/Model3DCommand/Clip/ClipDialog.py
./Command3D/Model3DCommand/Clip/ClipDialog.ui
./Command3D/Model3DCommand/Clip/ClipDialogMain.py
./Command3D/Model3DCommand/Clip/__init__.py
./Command3D/Model3DCommand/DoubleClickShowDialog/ReShowCommand.py
./Command3D/Model3DCommand/DoubleClickShowDialog/ReShowDialogMain.py
./Command3D/Model3DCommand/DoubleClickShowDialog/__init__.py
./Command3D/Model3DCommand/Draft_Extruded/CustomWidget.py
./Command3D/Model3DCommand/Draft_Extruded/customWidget.ui
./Command3D/Model3DCommand/Draft_Extruded/DraftExtrudedCommand.py
./Command3D/Model3DCommand/Draft_Extruded/DraftExtrudedDialog.py
./Command3D/Model3DCommand/Draft_Extruded/DraftExtrudedDialog.ui
./Command3D/Model3DCommand/Draft_Extruded/DraftExtrudedDialogMain.py
./Command3D/Model3DCommand/Draft_Extruded/DraftExtrudedInstance.py
./Command3D/Model3DCommand/Draft_Extruded/__init__.py
./Command3D/Model3DCommand/Draft_Revolution/CustomWidget.py
./Command3D/Model3DCommand/Draft_Revolution/customWidget.ui
./Command3D/Model3DCommand/Draft_Revolution/DraftRevolutionCommand.py
./Command3D/Model3DCommand/Draft_Revolution/DraftRevolutionDialog.py
./Command3D/Model3DCommand/Draft_Revolution/DraftRevolutionDialog.ui
./Command3D/Model3DCommand/Draft_Revolution/DraftRevolutionDialogMain.py
./Command3D/Model3DCommand/Draft_Revolution/DraftRevolutionInstance.py
./Command3D/Model3DCommand/Draft_Revolution/__init__.py
./Command3D/Model3DCommand/Line_Conformal/LineConformalCommand.py
./Command3D/Model3DCommand/Line_Conformal/LineConformalDialogMain.py
./Command3D/Model3DCommand/Line_Conformal/LineConformalInstance.py
./Command3D/Model3DCommand/Line_Conformal/PointWidget.py
./Command3D/Model3DCommand/Line_Conformal/PointWidget.ui
./Command3D/Model3DCommand/Line_Conformal/PointWidget1.py
./Command3D/Model3DCommand/Line_Conformal/__init__.py
./Command3D/Model3DCommand/Line_Oblique/LineObliqueCommand.py
./Command3D/Model3DCommand/Line_Oblique/LineObliqueDialogMain.py
./Command3D/Model3DCommand/Line_Oblique/LineObliqueInstance.py
./Command3D/Model3DCommand/Line_Oblique/PointWidget.py
./Command3D/Model3DCommand/Line_Oblique/PointWidget.ui
./Command3D/Model3DCommand/Line_Oblique/__init__.py
./Command3D/Model3DCommand/Object_Array/ArrayDraft.py
./Command3D/Model3DCommand/Object_Array/ArrayDraftPack.py
./Command3D/Model3DCommand/Object_Array/CustomWidget.py
./Command3D/Model3DCommand/Object_Array/CustomWidget.ui
./Command3D/Model3DCommand/Object_Array/linearWidget.py
./Command3D/Model3DCommand/Object_Array/linearWidget.ui
./Command3D/Model3DCommand/Object_Array/ObjectArrayCommand.py
./Command3D/Model3DCommand/Object_Array/ObjectArrayDialog.py
./Command3D/Model3DCommand/Object_Array/ObjectArrayDialog.ui
./Command3D/Model3DCommand/Object_Array/ObjectArrayDialogMain.py
./Command3D/Model3DCommand/Object_Array/ObjectArrayInstance.py
./Command3D/Model3DCommand/Object_Array/orthoWidget.py
./Command3D/Model3DCommand/Object_Array/orthoWidget.ui
./Command3D/Model3DCommand/Object_Array/polarWidget.py
./Command3D/Model3DCommand/Object_Array/polarWidget.ui
./Command3D/Model3DCommand/Object_Array/__init__.py
./Command3D/Model3DCommand/Point_3D/Point3DCommand.py
./Command3D/Model3DCommand/Point_3D/Point3DDialogMain.py
./Command3D/Model3DCommand/Point_3D/Point3DInstance.py
./Command3D/Model3DCommand/Point_3D/PointWidget.py
./Command3D/Model3DCommand/Point_3D/PointWidget.ui
./Command3D/Model3DCommand/Point_3D/__init__.py
./Command3D/Model3DCommand/RefreshModel/RefreshCommand.py
./Command3D/Model3DCommand/RefreshModel/__init__.py
./Command3D/Model3DCommand/SingleClickObj/SingleClickTheObj.py
./Command3D/Model3DCommand/SingleClickObj/__init__.py
./Command3D/Model3DCommand/Vol_Annular/AnnularCommand.py
./Command3D/Model3DCommand/Vol_Annular/AnnularDialogMain.py
./Command3D/Model3DCommand/Vol_Annular/AnnularInstance.py
./Command3D/Model3DCommand/Vol_Annular/PointWidget.py
./Command3D/Model3DCommand/Vol_Annular/PointWidget.ui
./Command3D/Model3DCommand/Vol_Annular/__init__.py
./Command3D/Model3DCommand/Vol_Annular_Section/Annular_SectionCommand.py
./Command3D/Model3DCommand/Vol_Annular_Section/Annular_SectionDialogMain.py
./Command3D/Model3DCommand/Vol_Annular_Section/Annular_SectionInstance.py
./Command3D/Model3DCommand/Vol_Annular_Section/PointWidget.py
./Command3D/Model3DCommand/Vol_Annular_Section/PointWidget.ui
./Command3D/Model3DCommand/Vol_Annular_Section/__init__.py
./Command3D/Model3DCommand/Vol_Array/ArrayCommand.py
#./Command3D/Model3DCommand/Vol_Array/ArrayDialog new2.py
#./Command3D/Model3DCommand/Vol_Array/ArrayDialog new3.py
./Command3D/Model3DCommand/Vol_Array/ArrayDialog.py
./Command3D/Model3DCommand/Vol_Array/ArrayDialog.ui
./Command3D/Model3DCommand/Vol_Array/ArrayDialogMain.py
./Command3D/Model3DCommand/Vol_Array/ArrayInstance.py
./Command3D/Model3DCommand/Vol_Array/__init__.py
./Command3D/Model3DCommand/Vol_Conformal/ConformalCommand.py
./Command3D/Model3DCommand/Vol_Conformal/ConformalDialogMain.py
./Command3D/Model3DCommand/Vol_Conformal/ConformalInstance.py
./Command3D/Model3DCommand/Vol_Conformal/PointWidget.py
./Command3D/Model3DCommand/Vol_Conformal/PointWidget.ui
./Command3D/Model3DCommand/Vol_Conformal/PointWidget1.py
./Command3D/Model3DCommand/Vol_Conformal/__init__.py
./Command3D/Model3DCommand/Vol_Cylinder/CylinderCommand.py
./Command3D/Model3DCommand/Vol_Cylinder/CylinderDialogMain.py
./Command3D/Model3DCommand/Vol_Cylinder/CylinderInstance.py
./Command3D/Model3DCommand/Vol_Cylinder/PointWidget.py
./Command3D/Model3DCommand/Vol_Cylinder/PointWidget.ui
./Command3D/Model3DCommand/Vol_Cylinder/__init__.py
./Command3D/Model3DCommand/Vol_Extruded/ExtrudedCommand.py
./Command3D/Model3DCommand/Vol_Extruded/ExtrudedDialog.ui
./Command3D/Model3DCommand/Vol_Extruded/ExtrudedDialogMain.py
./Command3D/Model3DCommand/Vol_Extruded/ExtrudedInstance.py
./Command3D/Model3DCommand/Vol_Extruded/ExtrudedWidget.py
./Command3D/Model3DCommand/Vol_Extruded/ExtrudedWidget.ui
./Command3D/Model3DCommand/Vol_Extruded/__init__.py
./Command3D/Model3DCommand/Vol_Function/FunctionCommand.py
./Command3D/Model3DCommand/Vol_Function/FunctionDialogMain.py
./Command3D/Model3DCommand/Vol_Function/FunctionInstance.py
./Command3D/Model3DCommand/Vol_Function/PointWidget.py
./Command3D/Model3DCommand/Vol_Function/PointWidget.ui
./Command3D/Model3DCommand/Vol_Function/__init__.py
./Command3D/Model3DCommand/Vol_Helical/HelicalCommand.py
./Command3D/Model3DCommand/Vol_Helical/HelicalDialogMain.py
./Command3D/Model3DCommand/Vol_Helical/HelicalInstance.py
./Command3D/Model3DCommand/Vol_Helical/PointWidget.py
./Command3D/Model3DCommand/Vol_Helical/PointWidget.ui
./Command3D/Model3DCommand/Vol_Helical/__init__.py
./Command3D/Model3DCommand/Vol_Parallelepipedal/ParallelepipedalCommand.py
./Command3D/Model3DCommand/Vol_Parallelepipedal/ParallelepipedalDialogMain.py
./Command3D/Model3DCommand/Vol_Parallelepipedal/ParallelepipedalInstance.py
./Command3D/Model3DCommand/Vol_Parallelepipedal/PointWidget.py
./Command3D/Model3DCommand/Vol_Parallelepipedal/PointWidget.ui
./Command3D/Model3DCommand/Vol_Parallelepipedal/__init__.py
./Command3D/Model3DCommand/Vol_Pyramid/PointWidget.py
./Command3D/Model3DCommand/Vol_Pyramid/PointWidget.ui
./Command3D/Model3DCommand/Vol_Pyramid/PyramidCommand.py
./Command3D/Model3DCommand/Vol_Pyramid/PyramidDialogMain.py
./Command3D/Model3DCommand/Vol_Pyramid/PyramidInstance.py
./Command3D/Model3DCommand/Vol_Pyramid/__init__.py
./Command3D/Model3DCommand/Vol_Revolution/PointWidget.py
./Command3D/Model3DCommand/Vol_Revolution/PointWidget.ui
./Command3D/Model3DCommand/Vol_Revolution/RevolutionCommand.py
./Command3D/Model3DCommand/Vol_Revolution/RevolutionDialogMain.py
./Command3D/Model3DCommand/Vol_Revolution/RevolutionInstance.py
./Command3D/Model3DCommand/Vol_Revolution/__init__.py
./Command3D/Model3DCommand/Vol_Rhombus/PointWidget.py
./Command3D/Model3DCommand/Vol_Rhombus/PointWidget.ui
./Command3D/Model3DCommand/Vol_Rhombus/RhombusCommand.py
./Command3D/Model3DCommand/Vol_Rhombus/RhombusDialogMain.py
./Command3D/Model3DCommand/Vol_Rhombus/RhombusInstance.py
./Command3D/Model3DCommand/Vol_Rhombus/__init__.py
./Command3D/Model3DCommand/Vol_SpecialCone/PointWidget.py
./Command3D/Model3DCommand/Vol_SpecialCone/PointWidget.ui
./Command3D/Model3DCommand/Vol_SpecialCone/SpecialConeCommand.py
./Command3D/Model3DCommand/Vol_SpecialCone/SpecialConeDialogMain.py
./Command3D/Model3DCommand/Vol_SpecialCone/SpecialConeInstance.py
./Command3D/Model3DCommand/Vol_SpecialCone/__init__.py
./Command3D/Model3DCommand/Vol_Spherical/PointWidget.py
./Command3D/Model3DCommand/Vol_Spherical/PointWidget.ui
./Command3D/Model3DCommand/Vol_Spherical/SphericalCommand.py
./Command3D/Model3DCommand/Vol_Spherical/SphericalDialogMain.py
./Command3D/Model3DCommand/Vol_Spherical/SphericalInstance.py
./Command3D/Model3DCommand/Vol_Spherical/__init__.py
./Command3D/Model3DCommand/Vol_Tetrahedron/PointWidget.py
./Command3D/Model3DCommand/Vol_Tetrahedron/PointWidget.ui
./Command3D/Model3DCommand/Vol_Tetrahedron/TetrahedronCommand.py
./Command3D/Model3DCommand/Vol_Tetrahedron/TetrahedronDialogMain.py
./Command3D/Model3DCommand/Vol_Tetrahedron/TetrahedronInstance.py
./Command3D/Model3DCommand/Vol_Tetrahedron/__init__.py
./Command3D/Model3DCommand/Vol_Toroidal_Section/PointWidget.py
./Command3D/Model3DCommand/Vol_Toroidal_Section/PointWidget.ui
./Command3D/Model3DCommand/Vol_Toroidal_Section/Toroidal_SectionCommand.py
./Command3D/Model3DCommand/Vol_Toroidal_Section/Toroidal_SectionDialogMain.py
./Command3D/Model3DCommand/Vol_Toroidal_Section/Toroidal_SectionInstance.py
./Command3D/Model3DCommand/Vol_Toroidal_Section/__init__.py
./Command3D/Model3DCommand/Vol_Wedge/PointWidget.py
./Command3D/Model3DCommand/Vol_Wedge/PointWidget.ui
./Command3D/Model3DCommand/Vol_Wedge/WedgeCommand.py
./Command3D/Model3DCommand/Vol_Wedge/WedgeDialogMain.py
./Command3D/Model3DCommand/Vol_Wedge/WedgeInstance.py
./Command3D/Model3DCommand/Vol_Wedge/__init__.py
./Command3D/Model3DCommand/__init__.py
./Command3D/Physics3DCommand/AreaRan/AreaRanCommand.py
./Command3D/Physics3DCommand/AreaRan/AreaRanDialog.py
./Command3D/Physics3DCommand/AreaRan/AreaRanDialog.ui
./Command3D/Physics3DCommand/AreaRan/AreaRanDialogMain.py
./Command3D/Physics3DCommand/AreaRan/AreaRanInstance.py
./Command3D/Physics3DCommand/AreaRan/__init__.py
./Command3D/Physics3DCommand/Beam/BeamCommand.py
./Command3D/Physics3DCommand/Beam/BeamDialog.py
./Command3D/Physics3DCommand/Beam/BeamDialog.ui
./Command3D/Physics3DCommand/Beam/BeamDialogMain.py
./Command3D/Physics3DCommand/Beam/BeamInstance.py
./Command3D/Physics3DCommand/Beam/__init__.py
./Command3D/Physics3DCommand/Cntr/CntrCommand.py
./Command3D/Physics3DCommand/Cntr/CntrDialog.py
./Command3D/Physics3DCommand/Cntr/CntrDialog.ui
./Command3D/Physics3DCommand/Cntr/CntrDialogMain.py
./Command3D/Physics3DCommand/Cntr/CntrInstance.py
./Command3D/Physics3DCommand/Cntr/__init__.py
./Command3D/Physics3DCommand/CustomTimer/CustomTimerCommand.py
./Command3D/Physics3DCommand/CustomTimer/CustomTimerDialog.py
./Command3D/Physics3DCommand/CustomTimer/CustomTimerDialog.ui
./Command3D/Physics3DCommand/CustomTimer/CustomTimerDialogMain.py
./Command3D/Physics3DCommand/CustomTimer/CustomTimerInstance.py
./Command3D/Physics3DCommand/CustomTimer/__init__.py
./Command3D/Physics3DCommand/DataProcessingSetting/DataProcessingSettingCommand.py
./Command3D/Physics3DCommand/DataProcessingSetting/DataProcessingSettingDialog.py
./Command3D/Physics3DCommand/DataProcessingSetting/DataProcessingSettingDialog.ui
./Command3D/Physics3DCommand/DataProcessingSetting/DataProcessingSettingDialogMain.py
./Command3D/Physics3DCommand/DataProcessingSetting/DataProcessingSettingInstance.py
./Command3D/Physics3DCommand/DataProcessingSetting/__init__.py
./Command3D/Physics3DCommand/DefTimer/DefTimerCommand.py
./Command3D/Physics3DCommand/DefTimer/DefTimerDialog.py
./Command3D/Physics3DCommand/DefTimer/DefTimerDialog.ui
./Command3D/Physics3DCommand/DefTimer/DefTimerDialogMain.py
./Command3D/Physics3DCommand/DefTimer/DefTimerInstance.py
./Command3D/Physics3DCommand/DefTimer/__init__.py
./Command3D/Physics3DCommand/Driv/DrivCommand.py
./Command3D/Physics3DCommand/Driv/DrivDialog.py
./Command3D/Physics3DCommand/Driv/DrivDialog.ui
./Command3D/Physics3DCommand/Driv/DrivDialogMain.py
./Command3D/Physics3DCommand/Driv/DrivInstance.py
./Command3D/Physics3DCommand/Driv/__init__.py
./Command3D/Physics3DCommand/Exps/ExpsCommand.py
./Command3D/Physics3DCommand/Exps/ExpsDialog.py
./Command3D/Physics3DCommand/Exps/ExpsDialog.ui
./Command3D/Physics3DCommand/Exps/ExpsDialogMain.py
./Command3D/Physics3DCommand/Exps/ExpsInstance.py
./Command3D/Physics3DCommand/Exps/__init__.py
./Command3D/Physics3DCommand/Feld/FeldCommand.py
./Command3D/Physics3DCommand/Feld/FeldDialog.py
./Command3D/Physics3DCommand/Feld/FeldDialog.ui
./Command3D/Physics3DCommand/Feld/FeldDialogMain.py
./Command3D/Physics3DCommand/Feld/FeldInstance.py
./Command3D/Physics3DCommand/Feld/__init__.py
./Command3D/Physics3DCommand/FieldSetting/FieldSettingCommand.py
./Command3D/Physics3DCommand/FieldSetting/FieldSettingDialog.py
./Command3D/Physics3DCommand/FieldSetting/FieldSettingDialog.ui
./Command3D/Physics3DCommand/FieldSetting/FieldSettingDialogMain.py
./Command3D/Physics3DCommand/FieldSetting/FieldSettingInstance.py
./Command3D/Physics3DCommand/FieldSetting/__init__.py
./Command3D/Physics3DCommand/Foil/FoilCommand.py
./Command3D/Physics3DCommand/Foil/FoilDialog.py
./Command3D/Physics3DCommand/Foil/FoilDialog.ui
./Command3D/Physics3DCommand/Foil/FoilDialogMain.py
./Command3D/Physics3DCommand/Foil/FoilInstance.py
./Command3D/Physics3DCommand/Foil/__init__.py
./Command3D/Physics3DCommand/FreeSpace/FreeSpaceCommand.py
./Command3D/Physics3DCommand/FreeSpace/FreeSpaceDialog.py
./Command3D/Physics3DCommand/FreeSpace/FreeSpaceDialog.ui
./Command3D/Physics3DCommand/FreeSpace/FreeSpaceDialogMain.py
./Command3D/Physics3DCommand/FreeSpace/FreeSpaceInstance.py
./Command3D/Physics3DCommand/FreeSpace/__init__.py
./Command3D/Physics3DCommand/Gyro/GyroCommand.py
./Command3D/Physics3DCommand/Gyro/GyroDialog.py
./Command3D/Physics3DCommand/Gyro/GyroDialog.ui
./Command3D/Physics3DCommand/Gyro/GyroDialogMain.py
./Command3D/Physics3DCommand/Gyro/GyroInstance.py
./Command3D/Physics3DCommand/Gyro/__init__.py
./Command3D/Physics3DCommand/Inductor/InductorCommand.py
./Command3D/Physics3DCommand/Inductor/InductorDialog.py
./Command3D/Physics3DCommand/Inductor/InductorDialog.ui
./Command3D/Physics3DCommand/Inductor/InductorDialogMain.py
./Command3D/Physics3DCommand/Inductor/InductorInstance.py
./Command3D/Physics3DCommand/Inductor/__init__.py
./Command3D/Physics3DCommand/Ioni/IoniCommand.py
./Command3D/Physics3DCommand/Ioni/IoniDialog.py
./Command3D/Physics3DCommand/Ioni/IoniDialog.ui
./Command3D/Physics3DCommand/Ioni/IoniDialogMain.py
./Command3D/Physics3DCommand/Ioni/IoniInstance.py
./Command3D/Physics3DCommand/Ioni/__init__.py
./Command3D/Physics3DCommand/MacroParticle/MacroParticleCommand.py
./Command3D/Physics3DCommand/MacroParticle/MacroParticleDialog.py
./Command3D/Physics3DCommand/MacroParticle/MacroParticleDialog.ui
./Command3D/Physics3DCommand/MacroParticle/MacroParticleDialogMain.py
./Command3D/Physics3DCommand/MacroParticle/MacroParticleInstance.py
./Command3D/Physics3DCommand/MacroParticle/__init__.py
./Command3D/Physics3DCommand/Mark/MarkCommand.py
./Command3D/Physics3DCommand/Mark/MarkDialog.py
./Command3D/Physics3DCommand/Mark/MarkDialog.ui
./Command3D/Physics3DCommand/Mark/MarkDialogMain.py
./Command3D/Physics3DCommand/Mark/MarkInstance.py
./Command3D/Physics3DCommand/Mark/__init__.py
./Command3D/Physics3DCommand/ModelingInfo/ModelingInfoCommand.py
./Command3D/Physics3DCommand/ModelingInfo/ModelingInfoDialog.py
./Command3D/Physics3DCommand/ModelingInfo/ModelingInfoDialog.ui
./Command3D/Physics3DCommand/ModelingInfo/ModelingInfoDialogMain.py
./Command3D/Physics3DCommand/ModelingInfo/ModelingInfoInstance.py
./Command3D/Physics3DCommand/ModelingInfo/__init__.py
./Command3D/Physics3DCommand/NetStepSetting/NetStepSettingCommand.py
./Command3D/Physics3DCommand/NetStepSetting/NetStepSettingDialog.py
./Command3D/Physics3DCommand/NetStepSetting/NetStepSettingDialog.ui
./Command3D/Physics3DCommand/NetStepSetting/NetStepSettingDialogMain.py
./Command3D/Physics3DCommand/NetStepSetting/NetStepSettingInstance.py
./Command3D/Physics3DCommand/NetStepSetting/__init__.py
./Command3D/Physics3DCommand/NewMaterial/NewMaterialCommand.py
./Command3D/Physics3DCommand/NewMaterial/NewMaterialDialog.py
./Command3D/Physics3DCommand/NewMaterial/NewMaterialDialog.ui
./Command3D/Physics3DCommand/NewMaterial/NewMaterialDialogMain.py
./Command3D/Physics3DCommand/NewMaterial/NewMaterialInstance.py
./Command3D/Physics3DCommand/NewMaterial/__init__.py
./Command3D/Physics3DCommand/Observe/ObserveCommand.py
./Command3D/Physics3DCommand/Observe/ObserveDialog.py
./Command3D/Physics3DCommand/Observe/ObserveDialog.ui
./Command3D/Physics3DCommand/Observe/ObserveDialogMain.py
./Command3D/Physics3DCommand/Observe/ObserveInstance.py
./Command3D/Physics3DCommand/Observe/__init__.py
./Command3D/Physics3DCommand/ParticleDefine/ParticleDefineCommand.py
./Command3D/Physics3DCommand/ParticleDefine/ParticleDefineDialog.py
./Command3D/Physics3DCommand/ParticleDefine/ParticleDefineDialog.ui
./Command3D/Physics3DCommand/ParticleDefine/ParticleDefineDialogMain.py
./Command3D/Physics3DCommand/ParticleDefine/ParticleDefineInstance.py
./Command3D/Physics3DCommand/ParticleDefine/__init__.py
./Command3D/Physics3DCommand/PhasSpace/PhasSpaceCommand.py
./Command3D/Physics3DCommand/PhasSpace/PhasSpaceDialog.py
./Command3D/Physics3DCommand/PhasSpace/PhasSpaceDialog.ui
./Command3D/Physics3DCommand/PhasSpace/PhasSpaceDialogMain.py
./Command3D/Physics3DCommand/PhasSpace/PhasSpaceInstance.py
./Command3D/Physics3DCommand/PhasSpace/__init__.py
./Command3D/Physics3DCommand/Popu/PopuCommand.py
./Command3D/Physics3DCommand/Popu/PopuDialog.py
./Command3D/Physics3DCommand/Popu/PopuDialog.ui
./Command3D/Physics3DCommand/Popu/PopuDialogMain.py
./Command3D/Physics3DCommand/Popu/PopuInstance.py
./Command3D/Physics3DCommand/Popu/__init__.py
./Command3D/Physics3DCommand/Port/PortCommand.py
./Command3D/Physics3DCommand/Port/PortDialog.py
./Command3D/Physics3DCommand/Port/PortDialog.ui
./Command3D/Physics3DCommand/Port/PortDialogMain.py
./Command3D/Physics3DCommand/Port/PortInstance.py
./Command3D/Physics3DCommand/Port/__init__.py
./Command3D/Physics3DCommand/RunOptions/RunOptionsCommand.py
./Command3D/Physics3DCommand/RunOptions/RunOptionsDialog.py
./Command3D/Physics3DCommand/RunOptions/RunOptionsDialog.ui
./Command3D/Physics3DCommand/RunOptions/RunOptionsDialogMain.py
./Command3D/Physics3DCommand/RunOptions/RunOptionsInstance.py
./Command3D/Physics3DCommand/RunOptions/__init__.py
./Command3D/Physics3DCommand/Secd/SecdCommand.py
./Command3D/Physics3DCommand/Secd/SecdDialog.py
./Command3D/Physics3DCommand/Secd/SecdDialog.ui
./Command3D/Physics3DCommand/Secd/SecdDialogMain.py
./Command3D/Physics3DCommand/Secd/SecdInstance.py
./Command3D/Physics3DCommand/Secd/__init__.py
./Command3D/Physics3DCommand/Solend/SolendCommand.py
./Command3D/Physics3DCommand/Solend/SolendDialog.py
./Command3D/Physics3DCommand/Solend/SolendDialog.ui
./Command3D/Physics3DCommand/Solend/SolendDialogMain.py
./Command3D/Physics3DCommand/Solend/SolendInstance.py
./Command3D/Physics3DCommand/Solend/__init__.py
./Command3D/Physics3DCommand/Sysmtry/SymtryCommand.py
./Command3D/Physics3DCommand/Sysmtry/SymtryDialog.py
./Command3D/Physics3DCommand/Sysmtry/SymtryDialog.ui
./Command3D/Physics3DCommand/Sysmtry/SymtryDialogMain.py
./Command3D/Physics3DCommand/Sysmtry/SymtryInstance.py
./Command3D/Physics3DCommand/Sysmtry/text.py
./Command3D/Physics3DCommand/Sysmtry/__init__.py
./Command3D/Physics3DCommand/Ther/TherCommand.py
./Command3D/Physics3DCommand/Ther/TherDialog.py
./Command3D/Physics3DCommand/Ther/TherDialog.ui
./Command3D/Physics3DCommand/Ther/TherDialogMain.py
./Command3D/Physics3DCommand/Ther/TherInstance.py
./Command3D/Physics3DCommand/Ther/__init__.py
./Command3D/Physics3DCommand/TimeDomainSetting/TimeDomainSettingCommand.py
./Command3D/Physics3DCommand/TimeDomainSetting/TimeDomainSettingDialog.py
./Command3D/Physics3DCommand/TimeDomainSetting/TimeDomainSettingDialog.ui
./Command3D/Physics3DCommand/TimeDomainSetting/TimeDomainSettingDialogMain.py
./Command3D/Physics3DCommand/TimeDomainSetting/TimeDomainSettingInstance.py
./Command3D/Physics3DCommand/TimeDomainSetting/__init__.py
./Command3D/Physics3DCommand/Vector/VectorCommand.py
./Command3D/Physics3DCommand/Vector/VectorDialog.py
./Command3D/Physics3DCommand/Vector/VectorDialog.ui
./Command3D/Physics3DCommand/Vector/VectorDialogMain.py
./Command3D/Physics3DCommand/Vector/VectorInstance.py
./Command3D/Physics3DCommand/Vector/__init__.py
./Command3D/Physics3DCommand/__init__.py
./Command3D/__init__.py
./Gui3D/TestMenu.py
./Gui3D/TestToolBar.py
./Gui3D/__init__.py
./Init.py
./InitGui.py
./M3DFileNew/M3DContainer.py
./M3DFileNew/M3DEmission.py
./M3DFileNew/M3DObject.py
./M3DFileNew/M3DObserve.py
./M3DFileNew/M3DPhysices.py
./M3DFileNew/M3DProject.py
./M3DFileNew/M3DShare.py
./M3DFileNew/__init__.py
./ReadmeWithVolume.md
./Resources3D/model/3DCone.svg
./Resources3D/model/3DCylinder.svg
./Resources3D/model/3DFunctionArea.svg
./Resources3D/model/3DHollowedCylinder.svg
./Resources3D/model/3DModelingWorkbench.png
./Resources3D/model/3DModelingWorkbench.svg
./Resources3D/model/3DOrthographicBody.svg
./Resources3D/model/3DParallelogram.svg
./Resources3D/model/3DPoint.svg
./Resources3D/model/3DPyramid.svg
./Resources3D/model/3DRevolution.svg
./Resources3D/model/3DSpecialCone.svg
./Resources3D/model/3DSphere.svg
./Resources3D/model/3DTorus.svg
./Resources3D/model/3DTorusFace.svg
./Resources3D/model/3DWedge.svg
./Resources3D/model/3D_Area_Conformal.svg
./Resources3D/model/3D_Area_Polygonal.svg
./Resources3D/model/3D_Area_Rectangular.svg
./Resources3D/model/3D_Array.svg
./Resources3D/model/3D_LineOblique.svg
./Resources3D/model/3D_Line_Conformal.svg
./Resources3D/model/3D_Point.svg
./Resources3D/model/3D_Vol_Annular.svg
./Resources3D/model/3D_Vol_Annular_Section.svg
./Resources3D/model/3D_Vol_Conformal.svg
./Resources3D/model/3D_Vol_Cylinder.svg
./Resources3D/model/3D_Vol_Extruded.svg
./Resources3D/model/3D_Vol_Function.png
./Resources3D/model/3D_Vol_Function.svg
./Resources3D/model/3D_Vol_Helical.svg
./Resources3D/model/3D_Vol_Parallelepipedal.svg
./Resources3D/model/3D_Vol_ParamArray.svg
./Resources3D/model/3D_Vol_Pyramid.svg
#./Resources3D/model/3D_Vol_Rhombus (2).svg
./Resources3D/model/3D_Vol_Rhombus.svg
./Resources3D/model/3D_Vol_SpecialCone.svg
./Resources3D/model/3D_Vol_Spherical.svg
./Resources3D/model/3D_Vol_Tetrahedron.svg
./Resources3D/model/3D_Vol_Toroidal_Section.svg
./Resources3D/model/3D_Vol_Wedge.svg
./Resources3D/model/DraftExtrusion.svg
./Resources3D/model/DraftRevolution.svg
./Resources3D/model/f9wing.FCStd
./Resources3D/model/Modeling3D.qrc
./Resources3D/model/refreshAll.svg
./Resources3D/model/refreshPart.svg
./Resources3D/model/save.svg
./Resources3D/model/translations/3DModeling.pro
./Resources3D/model/translations/3DModeling_zh-CN.qm
./Resources3D/model/translations/3DModeling_zh-CN.ts
./Resources3D/model/translations/Modeling3D_zh-CN.pro
./Resources3D/model/translations/Modeling3D_zh-CN.qm
./Resources3D/model/translations/Modeling3D_zh-CN.ts
./Resources3D/model/_Operation_Clip.svg
./Resources3D/model/_Operation_Copy.svg
./Resources3D/model/_Operation_Cut.svg
./Resources3D/model/_Operation_Paste.svg
./Resources3D/physics/all-run.svg
./Resources3D/physics/batch.svg
./Resources3D/physics/check.png
./Resources3D/physics/check.svg
./Resources3D/physics/cntr.svg
./Resources3D/physics/continue.png
./Resources3D/physics/continue.svg
./Resources3D/physics/continue2.png
./Resources3D/physics/continue2.svg
./Resources3D/physics/default-timer.svg
./Resources3D/physics/driver.svg
./Resources3D/physics/emb.png
./Resources3D/physics/emb.svg
./Resources3D/physics/eme.png
./Resources3D/physics/eme.svg
./Resources3D/physics/emg.png
./Resources3D/physics/emg.svg
./Resources3D/physics/emh.png
./Resources3D/physics/emh.svg
./Resources3D/physics/emt.png
./Resources3D/physics/emt.svg
./Resources3D/physics/finish.svg
./Resources3D/physics/foil.svg
./Resources3D/physics/free.png
./Resources3D/physics/free.svg
./Resources3D/physics/Group.svg
./Resources3D/physics/ind.svg
./Resources3D/physics/ioni.png
./Resources3D/physics/ioni.svg
./Resources3D/physics/Item.svg
./Resources3D/physics/logFile.svg
./Resources3D/physics/mark.png
./Resources3D/physics/mark.svg
./Resources3D/physics/muti-run.svg
./Resources3D/physics/no-result.svg
./Resources3D/physics/obs.svg
./Resources3D/physics/off.png
./Resources3D/physics/off.svg
./Resources3D/physics/on.png
./Resources3D/physics/on.svg
./Resources3D/physics/on2.svg
./Resources3D/physics/pause.png
./Resources3D/physics/pause.svg
./Resources3D/physics/pha.svg
./Resources3D/physics/physics-workbench.png
./Resources3D/physics/physics-workbench.svg
./Resources3D/physics/popu.png
./Resources3D/physics/popu.svg
./Resources3D/physics/port.png
./Resources3D/physics/port.svg
./Resources3D/physics/ran.svg
./Resources3D/physics/receive.png
./Resources3D/physics/receive.svg
./Resources3D/physics/receive2.svg
./Resources3D/physics/receiving.svg
./Resources3D/physics/redoPal.svg
./Resources3D/physics/refresh.png
./Resources3D/physics/refresh.svg
./Resources3D/physics/refresh2.png
./Resources3D/physics/refresh2.svg
./Resources3D/physics/refreshing.png
./Resources3D/physics/refreshing.svg
./Resources3D/physics/run.svg
./Resources3D/physics/run2.svg
./Resources3D/physics/secd.png
./Resources3D/physics/secd.svg
./Resources3D/physics/sole.svg
./Resources3D/physics/sym.png
./Resources3D/physics/sym.svg
./Resources3D/physics/timer.svg
./Resources3D/physics/undoPal.svg
./Resources3D/physics/vec.svg
./Resources3D/physics/__init__.py
./Resources3D/ProjectSetting/DataProcessingSetting.svg
./Resources3D/ProjectSetting/FiledSetting.svg
./Resources3D/ProjectSetting/ModelingInfo.svg
./Resources3D/ProjectSetting/NewMaterial.png
./Resources3D/ProjectSetting/NewMaterical.svg
./Resources3D/ProjectSetting/NewSpecies.png
./Resources3D/ProjectSetting/NewSpecies.svg
./Resources3D/ProjectSetting/ParticleMerge.png
./Resources3D/ProjectSetting/refresh.svg
./Resources3D/ProjectSetting/RunOptions.svg
./Resources3D/ProjectSetting/TimeDomainComputingMenu.svg
./Resources3D/ProjectSetting/WorkSpaceSettings.svg
./Resources3D/ProjectSetting/宏粒子合并.svg
./Resources3D/__init__.py
./Tools/Completer.py
./Tools/ExpressionTools3D.py
./Tools/FileView3D.py
./Tools/InitDoc3D.py
./Tools/M3DTools.py
./Tools/ObjectTools.py
./Tools/SaveM3D.py
./Tools/Tools3D.py
./Tools/UpdataBoolen3D.py
./Tools/__init__.py
./__init__.py
)
add_custom_target(Model3D ALL SOURCES ${Model3D_Srcs})
fc_copy_sources(Model3D "${CMAKE_BINARY_DIR}/Mod/Model3D" ${Model3D_Srcs})
install(
	FILES
	${Model3D_Srcs}
	DESTINATION
	Mod/Model3D
)
