# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomTimerDialog.ui'
#
# Created: Fri May 21 16:11:44 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CustomTimerDlg(object):
    def setupUi(self, CustomTimerDlg):
        CustomTimerDlg.setObjectName("CustomTimerDlg")
        CustomTimerDlg.resize(246, 253)
        CustomTimerDlg.setMaximumSize(QtCore.QSize(3670000, 16777215))
        CustomTimerDlg.setModal(False)
        self.gridLayout = QtGui.QGridLayout(CustomTimerDlg)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_period = QtGui.QLabel(CustomTimerDlg)
        self.label_period.setObjectName("label_period")
        self.horizontalLayout_4.addWidget(self.label_period)
        self.LineEdit_period = QtGui.QLineEdit(CustomTimerDlg)
        self.LineEdit_period.setObjectName("LineEdit_period")
        self.horizontalLayout_4.addWidget(self.LineEdit_period)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_setTime = QtGui.QLabel(CustomTimerDlg)
        self.label_setTime.setObjectName("label_setTime")
        self.horizontalLayout.addWidget(self.label_setTime)
        self.radioButton_step = QtGui.QRadioButton(CustomTimerDlg)
        self.radioButton_step.setChecked(True)
        self.radioButton_step.setObjectName("radioButton_step")
        self.horizontalLayout.addWidget(self.radioButton_step)
        self.radioButton_simulate = QtGui.QRadioButton(CustomTimerDlg)
        self.radioButton_simulate.setObjectName("radioButton_simulate")
        self.horizontalLayout.addWidget(self.radioButton_simulate)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_end = QtGui.QLabel(CustomTimerDlg)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_3.addWidget(self.label_end)
        self.LineEdit_end = QtGui.QLineEdit(CustomTimerDlg)
        self.LineEdit_end.setObjectName("LineEdit_end")
        self.horizontalLayout_3.addWidget(self.LineEdit_end)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.typeLabel = QtGui.QLabel(CustomTimerDlg)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.typeLabel)
        self.typeComboBox = StyledComboBox(CustomTimerDlg)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.typeComboBox)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_ok = QtGui.QPushButton(CustomTimerDlg)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_10.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(CustomTimerDlg)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_10.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_10, 12, 0, 1, 2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtGui.QLabel(CustomTimerDlg)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.LineEdit_Name = QtGui.QLineEdit(CustomTimerDlg)
        self.LineEdit_Name.setEnabled(True)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEdit_Name)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_start = QtGui.QLabel(CustomTimerDlg)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_2.addWidget(self.label_start)
        self.LineEdit_start = QtGui.QLineEdit(CustomTimerDlg)
        self.LineEdit_start.setObjectName("LineEdit_start")
        self.horizontalLayout_2.addWidget(self.LineEdit_start)
        self.label = QtGui.QLabel(CustomTimerDlg)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_period_2 = QtGui.QLabel(CustomTimerDlg)
        self.label_period_2.setObjectName("label_period_2")
        self.horizontalLayout_5.addWidget(self.label_period_2)
        self.LineEdit_Discrete_time = QtGui.QLineEdit(CustomTimerDlg)
        self.LineEdit_Discrete_time.setObjectName("LineEdit_Discrete_time")
        self.horizontalLayout_5.addWidget(self.LineEdit_Discrete_time)
        self.gridLayout.addLayout(self.horizontalLayout_5, 10, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 11, 0, 1, 1)

        self.retranslateUi(CustomTimerDlg)
        QtCore.QMetaObject.connectSlotsByName(CustomTimerDlg)
        CustomTimerDlg.setTabOrder(self.pb_ok, self.pb_cancel)
        CustomTimerDlg.setTabOrder(self.pb_cancel, self.LineEdit_Name)
        CustomTimerDlg.setTabOrder(self.LineEdit_Name, self.typeComboBox)
        CustomTimerDlg.setTabOrder(self.typeComboBox, self.radioButton_step)
        CustomTimerDlg.setTabOrder(self.radioButton_step, self.radioButton_simulate)
        CustomTimerDlg.setTabOrder(self.radioButton_simulate, self.LineEdit_start)
        CustomTimerDlg.setTabOrder(self.LineEdit_start, self.LineEdit_end)
        CustomTimerDlg.setTabOrder(self.LineEdit_end, self.LineEdit_period)
        CustomTimerDlg.setTabOrder(self.LineEdit_period, self.LineEdit_Discrete_time)

    def retranslateUi(self, CustomTimerDlg):
        CustomTimerDlg.setWindowTitle(QtGui.QApplication.translate("CustomTimerDlg", "CustomTimer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_period.setText(QtGui.QApplication.translate("CustomTimerDlg", "定时周期", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_period.setText(QtGui.QApplication.translate("CustomTimerDlg", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_setTime.setText(QtGui.QApplication.translate("CustomTimerDlg", "定时基准", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_step.setText(QtGui.QApplication.translate("CustomTimerDlg", "按时间步数", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_simulate.setText(QtGui.QApplication.translate("CustomTimerDlg", "按模拟时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("CustomTimerDlg", "结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end.setText(QtGui.QApplication.translate("CustomTimerDlg", "100000", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("CustomTimerDlg", "类型", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(0, QtGui.QApplication.translate("CustomTimerDlg", "周期型", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(1, QtGui.QApplication.translate("CustomTimerDlg", "离散型", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("CustomTimerDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("CustomTimerDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("CustomTimerDlg", "名称", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("CustomTimerDlg", "Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("CustomTimerDlg", "起始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start.setText(QtGui.QApplication.translate("CustomTimerDlg", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CustomTimerDlg", "步", None, QtGui.QApplication.UnicodeUTF8))
        self.label_period_2.setText(QtGui.QApplication.translate("CustomTimerDlg", "离散时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Discrete_time.setText(QtGui.QApplication.translate("CustomTimerDlg", "10 12 15 24  85  168 468", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
