# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeDomainSettingDialog.ui'
#
# Created: Fri May 21 16:19:17 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_TimeDomainComputingSettingDlg(object):
    def setupUi(self, Dialog_TimeDomainComputingSettingDlg):
        Dialog_TimeDomainComputingSettingDlg.setObjectName("Dialog_TimeDomainComputingSettingDlg")
        Dialog_TimeDomainComputingSettingDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_TimeDomainComputingSettingDlg.resize(510, 463)
        Dialog_TimeDomainComputingSettingDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_TimeDomainComputingSettingDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog_TimeDomainComputingSettingDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Dialog_TimeDomainComputingSettingDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_compute_time = QtGui.QLineEdit(Dialog_TimeDomainComputingSettingDlg)
        self.lineEdit_compute_time.setObjectName("lineEdit_compute_time")
        self.horizontalLayout.addWidget(self.lineEdit_compute_time)
        self.label_3 = QtGui.QLabel(Dialog_TimeDomainComputingSettingDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_WorkSpace_X = QtGui.QGroupBox(Dialog_TimeDomainComputingSettingDlg)
        self.groupBox_WorkSpace_X.setObjectName("groupBox_WorkSpace_X")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_WorkSpace_X)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start.addItem(spacerItem)
        self.comboBox_filed_arithmetic = StyledComboBox(self.groupBox_WorkSpace_X)
        self.comboBox_filed_arithmetic.setObjectName("comboBox_filed_arithmetic")
        self.comboBox_filed_arithmetic.addItem("")
        self.comboBox_filed_arithmetic.addItem("")
        self.comboBox_filed_arithmetic.addItem("")
        self.horizontalLayout_start.addWidget(self.comboBox_filed_arithmetic)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 1, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.checkBox_setting_mode = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_setting_mode.setObjectName("checkBox_setting_mode")
        self.horizontalLayout_end.addWidget(self.checkBox_setting_mode)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_end.addItem(spacerItem1)
        self.radioButton_EM = QtGui.QRadioButton(self.groupBox_WorkSpace_X)
        self.radioButton_EM.setObjectName("radioButton_EM")
        self.horizontalLayout_end.addWidget(self.radioButton_EM)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_end.addItem(spacerItem2)
        self.radioButton_TE = QtGui.QRadioButton(self.groupBox_WorkSpace_X)
        self.radioButton_TE.setObjectName("radioButton_TE")
        self.horizontalLayout_end.addWidget(self.radioButton_TE)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_end.addItem(spacerItem3)
        self.radioButton_TM = QtGui.QRadioButton(self.groupBox_WorkSpace_X)
        self.radioButton_TM.setObjectName("radioButton_TM")
        self.horizontalLayout_end.addWidget(self.radioButton_TM)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 4, 0, 1, 1)
        self.horizontalLayout_end_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_2.setObjectName("horizontalLayout_end_2")
        self.checkBox_setting_stride = QtGui.QCheckBox(self.groupBox_WorkSpace_X)
        self.checkBox_setting_stride.setObjectName("checkBox_setting_stride")
        self.horizontalLayout_end_2.addWidget(self.checkBox_setting_stride)
        self.lineEdit_setting_stride = QtGui.QLineEdit(self.groupBox_WorkSpace_X)
        self.lineEdit_setting_stride.setObjectName("lineEdit_setting_stride")
        self.horizontalLayout_end_2.addWidget(self.lineEdit_setting_stride)
        self.label_2 = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_end_2.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_2, 5, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 6, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_WorkSpace_X)
        self.groupBox_WorkSpace_Y = QtGui.QGroupBox(Dialog_TimeDomainComputingSettingDlg)
        self.groupBox_WorkSpace_Y.setObjectName("groupBox_WorkSpace_Y")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_WorkSpace_Y)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_setting_step = QtGui.QCheckBox(self.groupBox_WorkSpace_Y)
        self.checkBox_setting_step.setObjectName("checkBox_setting_step")
        self.gridLayout_4.addWidget(self.checkBox_setting_step, 2, 0, 1, 1)
        self.checkBox_setting_chargeContinuity = QtGui.QCheckBox(self.groupBox_WorkSpace_Y)
        self.checkBox_setting_chargeContinuity.setObjectName("checkBox_setting_chargeContinuity")
        self.gridLayout_4.addWidget(self.checkBox_setting_chargeContinuity, 1, 0, 1, 1)
        self.radioButton_nonre = QtGui.QRadioButton(self.groupBox_WorkSpace_Y)
        self.radioButton_nonre.setObjectName("radioButton_nonre")
        self.gridLayout_4.addWidget(self.radioButton_nonre, 3, 1, 1, 1)
        self.radioButton_re = QtGui.QRadioButton(self.groupBox_WorkSpace_Y)
        self.radioButton_re.setChecked(True)
        self.radioButton_re.setObjectName("radioButton_re")
        self.gridLayout_4.addWidget(self.radioButton_re, 3, 2, 1, 1)
        self.lineEdit_setting_step = QtGui.QLineEdit(self.groupBox_WorkSpace_Y)
        self.lineEdit_setting_step.setObjectName("lineEdit_setting_step")
        self.gridLayout_4.addWidget(self.lineEdit_setting_step, 2, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.verticalLayout_2.addWidget(self.groupBox_WorkSpace_Y)
        self.groupBox_WorkSpace_Y_2 = QtGui.QGroupBox(Dialog_TimeDomainComputingSettingDlg)
        self.groupBox_WorkSpace_Y_2.setObjectName("groupBox_WorkSpace_Y_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_WorkSpace_Y_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_start_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_start_6.setObjectName("horizontalLayout_start_6")
        self.checkBox_part = QtGui.QCheckBox(self.groupBox_WorkSpace_Y_2)
        self.checkBox_part.setObjectName("checkBox_part")
        self.horizontalLayout_start_6.addWidget(self.checkBox_part)
        self.verticalLayout.addLayout(self.horizontalLayout_start_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_max = QtGui.QLineEdit(self.groupBox_WorkSpace_Y_2)
        self.lineEdit_max.setObjectName("lineEdit_max")
        self.gridLayout.addWidget(self.lineEdit_max, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_WorkSpace_Y_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_WorkSpace_Y_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_every = QtGui.QLineEdit(self.groupBox_WorkSpace_Y_2)
        self.lineEdit_every.setObjectName("lineEdit_every")
        self.gridLayout.addWidget(self.lineEdit_every, 1, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_WorkSpace_Y_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_WorkSpace_Y_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_WorkSpace_Y_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_TimeDomainComputingSettingDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Dialog_TimeDomainComputingSettingDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_TimeDomainComputingSettingDlg)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.pushButton_ok, self.lineEdit_compute_time)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.lineEdit_compute_time, self.comboBox_filed_arithmetic)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.comboBox_filed_arithmetic, self.checkBox_setting_mode)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.checkBox_setting_mode, self.radioButton_EM)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.radioButton_EM, self.radioButton_TE)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.radioButton_TE, self.radioButton_TM)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.radioButton_TM, self.checkBox_setting_stride)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.checkBox_setting_stride, self.lineEdit_setting_stride)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.lineEdit_setting_stride, self.checkBox_setting_chargeContinuity)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.checkBox_setting_chargeContinuity, self.checkBox_setting_step)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.checkBox_setting_step, self.lineEdit_setting_step)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.lineEdit_setting_step, self.radioButton_nonre)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.radioButton_nonre, self.radioButton_re)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.radioButton_re, self.checkBox_part)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.checkBox_part, self.comboBox)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.comboBox, self.lineEdit_every)
        Dialog_TimeDomainComputingSettingDlg.setTabOrder(self.lineEdit_every, self.lineEdit_max)

    def retranslateUi(self, Dialog_TimeDomainComputingSettingDlg):
        Dialog_TimeDomainComputingSettingDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "时域计算设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "计算时间", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_compute_time.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "SIMUVOLUME", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_X.setTitle(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "场计算设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "场算法：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filed_arithmetic.setItemText(0, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "中心差分FDTD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filed_arithmetic.setItemText(1, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "时偏FDTD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filed_arithmetic.setItemText(2, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "高Q值FDTD", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setting_mode.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "设置模式", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_EM.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "EM", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_TE.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "TE", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_TM.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "TM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setting_stride.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "设置步长", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_setting_stride.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_Y.setTitle(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "粒子计算设置", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setting_step.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "粒子计算时间步间隔", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setting_chargeContinuity.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "设置电荷连续性算法", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_nonre.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "NONRELATIVISTIC", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_re.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "RELATIVISTIC", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_Y_2.setTitle(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "宏粒子合并", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_part.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "开启宏粒子合并", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_max.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "50000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "每个网格区粒子数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "最大宏粒子数：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_every.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "IONS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "ELECTRON", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "PROTON", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "粒子种类：", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_TimeDomainComputingSettingDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
