# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vol_RevolutionDlg.ui'
#
# Created: Fri Jan 03 15:14:24 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Modeling.Common.Tools import Completer

class Ui_Dialog_VolRevolution(object):
    def setupUi(self, Dialog_VolRevolution):
        Dialog_VolRevolution.setObjectName("Dialog_VolRevolution")
        Dialog_VolRevolution.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_VolRevolution.resize(675, 428)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_VolRevolution.sizePolicy().hasHeightForWidth())
        Dialog_VolRevolution.setSizePolicy(sizePolicy)
        Dialog_VolRevolution.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_VolRevolution.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_5 = QtGui.QGridLayout(Dialog_VolRevolution)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtGui.QGroupBox(Dialog_VolRevolution)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_name = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout.addWidget(self.lineEdit_name)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_Order = QtGui.QSpinBox(self.groupBox)
        self.spinBox_Order.setMaximum(200)
        self.spinBox_Order.setProperty("value", 100)
        self.spinBox_Order.setObjectName("spinBox_Order")
        self.horizontalLayout.addWidget(self.spinBox_Order)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_main = QtGui.QGroupBox(Dialog_VolRevolution)
        self.groupBox_main.setObjectName("groupBox_main")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox_main)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_Attribute = QtGui.QComboBox(self.groupBox_main)
        self.comboBox_Attribute.setObjectName("comboBox_Attribute")
        self.comboBox_Attribute.addItem("")
        self.comboBox_Attribute.addItem("")
        self.comboBox_Attribute.addItem("")
        self.comboBox_Attribute.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_Attribute)
        self.gridLayout_5.addWidget(self.groupBox_main, 1, 0, 1, 1)
        self.groupBox_NonUniform = QtGui.QGroupBox(Dialog_VolRevolution)
        self.groupBox_NonUniform.setObjectName("groupBox_NonUniform")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_NonUniform)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_UniformY = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformY.setObjectName("lineEdit_UniformY")
        self.gridLayout.addWidget(self.lineEdit_UniformY, 1, 1, 1, 1)
        self.checkBox_UniformX = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformX.setChecked(True)
        self.checkBox_UniformX.setObjectName("checkBox_UniformX")
        self.gridLayout.addWidget(self.checkBox_UniformX, 0, 0, 1, 1)
        self.checkBox_UniformZ = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformZ.setChecked(True)
        self.checkBox_UniformZ.setObjectName("checkBox_UniformZ")
        self.gridLayout.addWidget(self.checkBox_UniformZ, 0, 2, 1, 1)
        self.checkBox_UniformY = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformY.setChecked(True)
        self.checkBox_UniformY.setObjectName("checkBox_UniformY")
        self.gridLayout.addWidget(self.checkBox_UniformY, 0, 1, 1, 1)
        self.lineEdit_UniformZ = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformZ.setObjectName("lineEdit_UniformZ")
        self.gridLayout.addWidget(self.lineEdit_UniformZ, 1, 2, 1, 1)
        self.lineEdit_UniformX = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformX.setObjectName("lineEdit_UniformX")
        self.gridLayout.addWidget(self.lineEdit_UniformX, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_NonUniform, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog_VolRevolution)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_Areas = StyledComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Areas.sizePolicy().hasHeightForWidth())
        self.comboBox_Areas.setSizePolicy(sizePolicy)
        self.comboBox_Areas.setObjectName("comboBox_Areas")
        self.gridLayout_4.addWidget(self.comboBox_Areas, 0, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEdit_PointTopZ = Completer.AutoCompleteEdit(self.groupBox_2)
        self.lineEdit_PointTopZ.setObjectName("lineEdit_PointTopZ")
        self.gridLayout_4.addWidget(self.lineEdit_PointTopZ, 3, 4, 1, 1)
        self.lineEdit_PointTopY = Completer.AutoCompleteEdit(self.groupBox_2)
        self.lineEdit_PointTopY.setObjectName("lineEdit_PointTopY")
        self.gridLayout_4.addWidget(self.lineEdit_PointTopY, 3, 2, 1, 1)
        self.lineEdit_PointTopX = Completer.AutoCompleteEdit(self.groupBox_2)
        self.lineEdit_PointTopX.setObjectName("lineEdit_PointTopX")
        self.gridLayout_4.addWidget(self.lineEdit_PointTopX, 3, 1, 1, 1)
        self.lineEdit_PointBaseZ = Completer.AutoCompleteEdit(self.groupBox_2)
        self.lineEdit_PointBaseZ.setObjectName("lineEdit_PointBaseZ")
        self.gridLayout_4.addWidget(self.lineEdit_PointBaseZ, 2, 4, 1, 1)
        self.lineEdit_PointBaseY = Completer.AutoCompleteEdit(self.groupBox_2)
        self.lineEdit_PointBaseY.setObjectName("lineEdit_PointBaseY")
        self.gridLayout_4.addWidget(self.lineEdit_PointBaseY, 2, 2, 1, 1)
        self.lineEdit_PointBaseX = Completer.AutoCompleteEdit(self.groupBox_2)
        self.lineEdit_PointBaseX.setObjectName("lineEdit_PointBaseX")
        self.gridLayout_4.addWidget(self.lineEdit_PointBaseX, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.horizontalLayout_okAndCancel = QtGui.QHBoxLayout()
        self.horizontalLayout_okAndCancel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_okAndCancel.setObjectName("horizontalLayout_okAndCancel")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_okAndCancel.addItem(spacerItem)
        self.pushButton_ok = QtGui.QPushButton(Dialog_VolRevolution)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog_VolRevolution)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_cancel)
        self.gridLayout_5.addLayout(self.horizontalLayout_okAndCancel, 4, 0, 1, 1)

        self.retranslateUi(Dialog_VolRevolution)
        QtCore.QMetaObject.connectSlotsByName(Dialog_VolRevolution)
        Dialog_VolRevolution.setTabOrder(self.checkBox_UniformX, self.lineEdit_UniformX)
        Dialog_VolRevolution.setTabOrder(self.lineEdit_UniformX, self.checkBox_UniformY)
        Dialog_VolRevolution.setTabOrder(self.checkBox_UniformY, self.lineEdit_UniformY)
        Dialog_VolRevolution.setTabOrder(self.lineEdit_UniformY, self.checkBox_UniformZ)
        Dialog_VolRevolution.setTabOrder(self.checkBox_UniformZ, self.lineEdit_UniformZ)
        Dialog_VolRevolution.setTabOrder(self.lineEdit_UniformZ, self.pushButton_ok)
        Dialog_VolRevolution.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Dialog_VolRevolution):
        Dialog_VolRevolution.setWindowTitle(QtGui.QApplication.translate("Dialog_VolRevolution", "旋转体", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_VolRevolution", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_name.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "vol_Revolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_main.setTitle(QtGui.QApplication.translate("Dialog_VolRevolution", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Attribute.setItemText(0, QtGui.QApplication.translate("Dialog_VolRevolution", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Attribute.setItemText(1, QtGui.QApplication.translate("Dialog_VolRevolution", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Attribute.setItemText(2, QtGui.QApplication.translate("Dialog_VolRevolution", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Attribute.setItemText(3, QtGui.QApplication.translate("Dialog_VolRevolution", "Vacuo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_NonUniform.setTitle(QtGui.QApplication.translate("Dialog_VolRevolution", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformY.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "dx2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformX.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformZ.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformY.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformZ.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "dx2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformX.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "dx1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_VolRevolution", "Object of a Revolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "BaseArea:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Point_Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "Point_Top:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog_VolRevolution", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
