# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VectorDialog.ui'
#
# Created: Sat Nov 28 14:43:17 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(522, 498)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Label_Name_2 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_4.addWidget(self.Label_Name_2)
        self.le_name = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_name.sizePolicy().hasHeightForWidth())
        self.le_name.setSizePolicy(sizePolicy)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout_4.addWidget(self.le_name)
        self.Label_Shadow_2 = QtGui.QLabel(Dialog)
        self.Label_Shadow_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_4.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow = QtGui.QComboBox(Dialog)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_Shadow)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.le_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.le_start_y.setObjectName("le_start_y")
        self.gridLayout.addWidget(self.le_start_y, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_Port)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 11, 2, 1, 1)
        self.le_SL2 = QtGui.QLineEdit(self.groupBox_Port)
        self.le_SL2.setEnabled(False)
        self.le_SL2.setObjectName("le_SL2")
        self.gridLayout.addWidget(self.le_SL2, 11, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 1, 1, 1)
        self.le_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.le_start_x.setObjectName("le_start_x")
        self.gridLayout.addWidget(self.le_start_x, 1, 1, 1, 1)
        self.checkBox_vector = QtGui.QCheckBox(self.groupBox_Port)
        self.checkBox_vector.setObjectName("checkBox_vector")
        self.gridLayout.addWidget(self.checkBox_vector, 11, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.le_SL1 = QtGui.QLineEdit(self.groupBox_Port)
        self.le_SL1.setEnabled(False)
        self.le_SL1.setObjectName("le_SL1")
        self.gridLayout.addWidget(self.le_SL1, 11, 1, 1, 1)
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.gridLayout.addWidget(self.label_end, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.ComboBox_end = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.gridLayout.addWidget(self.ComboBox_end, 3, 4, 1, 1)
        self.label_end_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_2.setObjectName("label_end_2")
        self.gridLayout.addWidget(self.label_end_2, 5, 0, 1, 1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout.addWidget(self.label_Y, 0, 3, 1, 1)
        self.ComboBox_C2 = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_C2.setObjectName("ComboBox_C2")
        self.gridLayout.addWidget(self.ComboBox_C2, 7, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 8, 1, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.gridLayout.addWidget(self.label_X, 0, 1, 1, 1)
        self.le_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.le_end_x.setEnabled(True)
        self.le_end_x.setObjectName("le_end_x")
        self.gridLayout.addWidget(self.le_end_x, 3, 1, 1, 1)
        self.ComboBox_timer = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.gridLayout.addWidget(self.ComboBox_timer, 9, 1, 1, 1)
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 1, 0, 1, 1)
        self.label_end_3 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_3.setObjectName("label_end_3")
        self.gridLayout.addWidget(self.label_end_3, 9, 0, 1, 1)
        self.label_end_4 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_4.setObjectName("label_end_4")
        self.gridLayout.addWidget(self.label_end_4, 7, 0, 1, 1)
        self.le_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.le_end_y.setEnabled(True)
        self.le_end_y.setObjectName("le_end_y")
        self.gridLayout.addWidget(self.le_end_y, 3, 3, 1, 1)
        self.ComboBox_C1 = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_C1.setObjectName("ComboBox_C1")
        self.gridLayout.addWidget(self.ComboBox_C1, 5, 1, 1, 1)
        self.ComboBox_start = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.gridLayout.addWidget(self.ComboBox_start, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 12, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_Port, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.le_name)
        Dialog.setTabOrder(self.le_name, self.ComboBox_Shadow)
        Dialog.setTabOrder(self.ComboBox_Shadow, self.le_start_x)
        Dialog.setTabOrder(self.le_start_x, self.le_start_y)
        Dialog.setTabOrder(self.le_start_y, self.ComboBox_start)
        Dialog.setTabOrder(self.ComboBox_start, self.le_end_x)
        Dialog.setTabOrder(self.le_end_x, self.le_end_y)
        Dialog.setTabOrder(self.le_end_y, self.ComboBox_end)
        Dialog.setTabOrder(self.ComboBox_end, self.ComboBox_C1)
        Dialog.setTabOrder(self.ComboBox_C1, self.ComboBox_C2)
        Dialog.setTabOrder(self.ComboBox_C2, self.ComboBox_timer)
        Dialog.setTabOrder(self.ComboBox_timer, self.checkBox_vector)
        Dialog.setTabOrder(self.checkBox_vector, self.le_SL1)
        Dialog.setTabOrder(self.le_SL1, self.le_SL2)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "矢量图观测", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_name.setText(QtGui.QApplication.translate("Dialog", "Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog", "观测面", None, QtGui.QApplication.UnicodeUTF8))
        self.le_start_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.le_SL2.setText(QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.le_start_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_vector.setText(QtGui.QApplication.translate("Dialog", "指定矢量个数", None, QtGui.QApplication.UnicodeUTF8))
        self.le_SL1.setText(QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_2.setText(QtGui.QApplication.translate("Dialog", "观测场1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.le_end_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_3.setText(QtGui.QApplication.translate("Dialog", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_4.setText(QtGui.QApplication.translate("Dialog", "观测场2：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_end_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

