# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArrayDialog.ui'
#
# Created: Mon Nov 18 11:23:24 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Modeling.Common.Tools import Completer


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 377)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Base_label_1 = QtGui.QLabel(self.groupBox)
        self.Base_label_1.setObjectName("Base_label_1")
        self.horizontalLayout.addWidget(self.Base_label_1)
        self.Base_lineEdit_1 = QtGui.QLineEdit(self.groupBox)
        self.Base_lineEdit_1.setObjectName("Base_lineEdit_1")
        self.horizontalLayout.addWidget(self.Base_lineEdit_1)
        self.Base_label_2 = QtGui.QLabel(self.groupBox)
        self.Base_label_2.setObjectName("Base_label_2")
        self.horizontalLayout.addWidget(self.Base_label_2)
        self.Base_lineEdit_2 = QtGui.QSpinBox(self.groupBox)
        self.Base_lineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.Base_lineEdit_2.setObjectName("Base_lineEdit_2")
        self.horizontalLayout.addWidget(self.Base_lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Att_label = QtGui.QLabel(self.groupBox_2)
        self.Att_label.setObjectName("Att_label")
        self.horizontalLayout_2.addWidget(self.Att_label)
        self.comboBox = StyledComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_2 = StyledComboBox(self.groupBox_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_01 = QtGui.QLabel(self.groupBox_4)
        self.label_01.setObjectName("label_01")
        self.gridLayout_2.addWidget(self.label_01, 2, 0, 1, 1)
        self.label_type = QtGui.QLabel(self.groupBox_4)
        self.label_type.setObjectName("label_type")
        self.gridLayout_2.addWidget(self.label_type, 1, 1, 1, 1)
        self.label_02 = QtGui.QLabel(self.groupBox_4)
        self.label_02.setObjectName("label_02")
        self.gridLayout_2.addWidget(self.label_02, 3, 0, 1, 1)
        self.label_04 = QtGui.QLabel(self.groupBox_4)
        self.label_04.setObjectName("label_04")
        self.gridLayout_2.addWidget(self.label_04, 5, 0, 1, 1)
        self.label_03 = QtGui.QLabel(self.groupBox_4)
        self.label_03.setObjectName("label_03")
        self.gridLayout_2.addWidget(self.label_03, 4, 0, 1, 1)
        self.lineEdit = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.label_05 = QtGui.QLabel(self.groupBox_4)
        self.label_05.setObjectName("label_05")
        self.gridLayout_2.addWidget(self.label_05, 6, 0, 1, 1)
        self.lineEdit_3 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.lineEdit_4 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.comboBox_3 = StyledComboBox(self.groupBox_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 6, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.OK_pushButton = QtGui.QPushButton(Dialog)
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout_3.addWidget(self.OK_pushButton)
        self.Cancel_pushButton = QtGui.QPushButton(Dialog)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.horizontalLayout_3.addWidget(self.Cancel_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Base_lineEdit_1, self.Base_lineEdit_2)
        Dialog.setTabOrder(self.Base_lineEdit_2, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.OK_pushButton)
        Dialog.setTabOrder(self.OK_pushButton, self.Cancel_pushButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.Base_label_1.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.Base_label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.Att_label.setText(QtGui.QApplication.translate("Dialog", "          Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Object of a Array", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Dialog", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Dialog", "ortho", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("Dialog", "polar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_01.setText(QtGui.QApplication.translate("Dialog", "IntervalX:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_type.setText(QtGui.QApplication.translate("Dialog", "something", None, QtGui.QApplication.UnicodeUTF8))
        self.label_02.setText(QtGui.QApplication.translate("Dialog", "IntervalY:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_04.setText(QtGui.QApplication.translate("Dialog", "Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_03.setText(QtGui.QApplication.translate("Dialog", "IntervalZ:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_05.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Array Type", None, QtGui.QApplication.UnicodeUTF8))
        self.OK_pushButton.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel_pushButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
