# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkSpaceSettingsDlg.ui'
#
# Created: Wed Jan 15 10:59:56 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_WorkSpaceDlg(object):
    def setupUi(self, Dialog_WorkSpaceDlg):
        Dialog_WorkSpaceDlg.setObjectName("Dialog_WorkSpaceDlg")
        Dialog_WorkSpaceDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_WorkSpaceDlg.resize(393, 421)
        Dialog_WorkSpaceDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_WorkSpaceDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_4 = QtGui.QGridLayout(Dialog_WorkSpaceDlg)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_WorkSpace_X = QtGui.QGroupBox(Dialog_WorkSpaceDlg)
        self.groupBox_WorkSpace_X.setObjectName("groupBox_WorkSpace_X")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_WorkSpace_X)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_stride_x = QtGui.QLineEdit(self.groupBox_WorkSpace_X)
        self.LineEdit_stride_x.setEnabled(True)
        self.LineEdit_stride_x.setObjectName("LineEdit_stride_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_stride_x)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 2, 0, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start.addItem(spacerItem)
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_WorkSpace_X)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.groupBox_WorkSpace_X)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_start.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start.addItem(spacerItem2)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_WorkSpace_X)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_end_x)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_WorkSpace_X, 1, 0, 1, 1)
        self.groupBox_WorkSpace_Y = QtGui.QGroupBox(Dialog_WorkSpaceDlg)
        self.groupBox_WorkSpace_Y.setObjectName("groupBox_WorkSpace_Y")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_WorkSpace_Y)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 2, 0, 1, 1)
        self.horizontalLayout_end_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_6.setObjectName("horizontalLayout_end_6")
        self.label_end_6 = QtGui.QLabel(self.groupBox_WorkSpace_Y)
        self.label_end_6.setObjectName("label_end_6")
        self.horizontalLayout_end_6.addWidget(self.label_end_6)
        self.LineEdit_stride_y = QtGui.QLineEdit(self.groupBox_WorkSpace_Y)
        self.LineEdit_stride_y.setEnabled(True)
        self.LineEdit_stride_y.setObjectName("LineEdit_stride_y")
        self.horizontalLayout_end_6.addWidget(self.LineEdit_stride_y)
        self.gridLayout_3.addLayout(self.horizontalLayout_end_6, 3, 0, 1, 1)
        self.horizontalLayout_start_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_start_5.setObjectName("horizontalLayout_start_5")
        self.label_8 = QtGui.QLabel(self.groupBox_WorkSpace_Y)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_start_5.addWidget(self.label_8)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start_5.addItem(spacerItem5)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_WorkSpace_Y)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start_5.addWidget(self.LineEdit_start_y)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start_5.addItem(spacerItem6)
        self.label_9 = QtGui.QLabel(self.groupBox_WorkSpace_Y)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_start_5.addWidget(self.label_9)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start_5.addItem(spacerItem7)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_WorkSpace_Y)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_start_5.addWidget(self.LineEdit_end_y)
        self.gridLayout_3.addLayout(self.horizontalLayout_start_5, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_WorkSpace_Y, 2, 0, 1, 1)
        self.groupBox_WorkSpace_Z = QtGui.QGroupBox(Dialog_WorkSpaceDlg)
        self.groupBox_WorkSpace_Z.setObjectName("groupBox_WorkSpace_Z")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_WorkSpace_Z)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 0, 0, 1, 1)
        self.horizontalLayout_start_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_start_4.setObjectName("horizontalLayout_start_4")
        self.label_6 = QtGui.QLabel(self.groupBox_WorkSpace_Z)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_start_4.addWidget(self.label_6)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start_4.addItem(spacerItem10)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_WorkSpace_Z)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start_4.addWidget(self.LineEdit_start_z)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start_4.addItem(spacerItem11)
        self.label_7 = QtGui.QLabel(self.groupBox_WorkSpace_Z)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_start_4.addWidget(self.label_7)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_start_4.addItem(spacerItem12)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_WorkSpace_Z)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_start_4.addWidget(self.LineEdit_end_z)
        self.gridLayout.addLayout(self.horizontalLayout_start_4, 1, 0, 1, 1)
        self.horizontalLayout_end_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_7.setObjectName("horizontalLayout_end_7")
        self.label_end_7 = QtGui.QLabel(self.groupBox_WorkSpace_Z)
        self.label_end_7.setObjectName("label_end_7")
        self.horizontalLayout_end_7.addWidget(self.label_end_7)
        self.LineEdit_stride_z = QtGui.QLineEdit(self.groupBox_WorkSpace_Z)
        self.LineEdit_stride_z.setEnabled(True)
        self.LineEdit_stride_z.setObjectName("LineEdit_stride_z")
        self.horizontalLayout_end_7.addWidget(self.LineEdit_stride_z)
        self.gridLayout.addLayout(self.horizontalLayout_end_7, 3, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_WorkSpace_Z, 3, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(Dialog_WorkSpaceDlg)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Dialog_WorkSpaceDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_Name = QtGui.QLineEdit(Dialog_WorkSpaceDlg)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.horizontalLayout.addWidget(self.lineEdit_Name)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_WorkSpaceDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.pushButton = QtGui.QPushButton(Dialog_WorkSpaceDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 4, 0, 1, 1)

        self.retranslateUi(Dialog_WorkSpaceDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_WorkSpaceDlg)
        Dialog_WorkSpaceDlg.setTabOrder(self.lineEdit_Name, self.LineEdit_start_x)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_start_x, self.LineEdit_end_x)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_end_x, self.LineEdit_stride_x)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_stride_x, self.LineEdit_start_y)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_start_y, self.LineEdit_end_y)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_end_y, self.LineEdit_stride_y)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_stride_y, self.LineEdit_start_z)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_start_z, self.LineEdit_end_z)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_end_z, self.LineEdit_stride_z)
        Dialog_WorkSpaceDlg.setTabOrder(self.LineEdit_stride_z, self.pushButton_ok)
        Dialog_WorkSpaceDlg.setTabOrder(self.pushButton_ok, self.pushButton)

    def retranslateUi(self, Dialog_WorkSpaceDlg):
        Dialog_WorkSpaceDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "工作区间设置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_X.setTitle(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "步长：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_stride_x.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0.5mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "范围：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0.0255m", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_Y.setTitle(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_6.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "步长：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_stride_y.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "36deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "范围：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "360deg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_WorkSpace_Z.setTitle(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "范围：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0.6m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_7.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "步长：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_stride_z.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "0.4mm", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "启用", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Name.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "SIMUVOLUME", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_WorkSpaceDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

