# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IoniDialog.ui'
#
# Created: Fri May 21 16:15:19 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(526, 199)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_type = QtGui.QComboBox(self.groupBox)
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.verticalLayout.addWidget(self.cb_type)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.le_temperature = QtGui.QLineEdit(self.groupBox)
        self.le_temperature.setObjectName("le_temperature")
        self.gridLayout.addWidget(self.le_temperature, 2, 1, 1, 1)
        self.le_pressure = QtGui.QLineEdit(self.groupBox)
        self.le_pressure.setObjectName("le_pressure")
        self.gridLayout.addWidget(self.le_pressure, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.lb_name = QtGui.QLabel(self.groupBox)
        self.lb_name.setObjectName("lb_name")
        self.gridLayout.addWidget(self.lb_name, 0, 0, 1, 1)
        self.le_name = QtGui.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.cb_type)
        Dialog.setTabOrder(self.cb_type, self.le_name)
        Dialog.setTabOrder(self.le_name, self.le_pressure)
        Dialog.setTabOrder(self.le_pressure, self.le_temperature)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "气体电离", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "气体电离", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(0, QtGui.QApplication.translate("Dialog", "ARGON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(1, QtGui.QApplication.translate("Dialog", "NITROGEN_GAS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(2, QtGui.QApplication.translate("Dialog", "OXYGEN_GAS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(3, QtGui.QApplication.translate("Dialog", "HYDROGEN_GAS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(4, QtGui.QApplication.translate("Dialog", "HELIUM", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(5, QtGui.QApplication.translate("Dialog", "MERCURY", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(6, QtGui.QApplication.translate("Dialog", "WATER_VAPOR", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(7, QtGui.QApplication.translate("Dialog", "NEON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(8, QtGui.QApplication.translate("Dialog", "KRYPTON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(9, QtGui.QApplication.translate("Dialog", "XENON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(10, QtGui.QApplication.translate("Dialog", "CARBON_DIOXIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "气体温度：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "气体压强：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_temperature.setText(QtGui.QApplication.translate("Dialog", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.le_pressure.setText(QtGui.QApplication.translate("Dialog", "1333.22", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Pa", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_name.setText(QtGui.QApplication.translate("Dialog", "名字：", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

