# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IoniDialog.ui'
#
# Created: Wed Mar 15 16:31:58 2023
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(565, 290)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 552, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Label_type = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_type.sizePolicy().hasHeightForWidth())
        self.Label_type.setSizePolicy(sizePolicy)
        self.Label_type.setObjectName("Label_type")
        self.gridLayout_3.addWidget(self.Label_type, 0, 0, 1, 1)
        self.cb_type = QtGui.QComboBox(self.groupBox)
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.gridLayout_3.addWidget(self.cb_type, 0, 1, 1, 1)
        self.Label_Shadow = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.gridLayout_3.addWidget(self.Label_Shadow, 0, 2, 1, 1)
        self.ComboBox_Shadow = StyledComboBox(self.groupBox)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.gridLayout_3.addWidget(self.ComboBox_Shadow, 0, 3, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Port.sizePolicy().hasHeightForWidth())
        self.groupBox_Port.setSizePolicy(sizePolicy)
        self.groupBox_Port.setFlat(True)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_Port)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        #self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.gridLayout.addWidget(self.LineEdit_end_y, 2, 3, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.gridLayout.addWidget(self.label_X, 0, 1, 1, 2)
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 1, 0, 1, 1)
        #self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(True)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.gridLayout.addWidget(self.LineEdit_end_x, 2, 1, 1, 2)
        #self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.gridLayout.addWidget(self.LineEdit_start_z, 1, 4, 1, 1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout.addWidget(self.label_Y, 0, 3, 1, 1)
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.gridLayout.addWidget(self.label_end, 2, 0, 1, 1)
        #self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.gridLayout.addWidget(self.LineEdit_end_z, 2, 4, 1, 1)
        #self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.gridLayout.addWidget(self.LineEdit_start_x, 1, 1, 1, 2)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.gridLayout.addWidget(self.ComboBox_start, 1, 5, 1, 1)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.gridLayout.addWidget(self.ComboBox_end, 2, 5, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout.addWidget(self.label_Z, 0, 4, 1, 1)
        #self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.gridLayout.addWidget(self.LineEdit_start_y, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.groupBox_Port, 1, 0, 1, 4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_name = QtGui.QLabel(self.groupBox)
        self.lb_name.setObjectName("lb_name")
        self.gridLayout_2.addWidget(self.lb_name, 0, 0, 1, 1)
        self.le_name = QtGui.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.le_temperature = QtGui.QLineEdit(self.groupBox)
        self.le_temperature.setObjectName("le_temperature")
        self.gridLayout_2.addWidget(self.le_temperature, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 2)
        self.le_pressure = QtGui.QTextEdit(self.groupBox)
        self.le_pressure.setEnabled(True)
        self.le_pressure.setObjectName("le_pressure")
        self.gridLayout_2.addWidget(self.le_pressure, 2, 2, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 5, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 4)
        self.pb_cancel = QtGui.QPushButton(self.groupBox)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_3.addWidget(self.pb_cancel, 3, 3, 1, 1)
        self.pb_ok = QtGui.QPushButton(self.groupBox)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout_3.addWidget(self.pb_ok, 3, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.cb_type)
        Dialog.setTabOrder(self.cb_type, self.le_name)
        Dialog.setTabOrder(self.le_name, self.le_temperature)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "气体电离", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_type.setText(QtGui.QApplication.translate("Dialog", "气体电离：", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(0, QtGui.QApplication.translate("Dialog", "ARGON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(1, QtGui.QApplication.translate("Dialog", "NITROGEN_GAS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(2, QtGui.QApplication.translate("Dialog", "OXYGEN_GAS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(3, QtGui.QApplication.translate("Dialog", "HYDROGEN_GAS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(4, QtGui.QApplication.translate("Dialog", "HELIUM", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(5, QtGui.QApplication.translate("Dialog", "MERCURY", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(6, QtGui.QApplication.translate("Dialog", "WATER_VAPOR", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(7, QtGui.QApplication.translate("Dialog", "NEON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(8, QtGui.QApplication.translate("Dialog", "KRYPTON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(9, QtGui.QApplication.translate("Dialog", "XENON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setItemText(10, QtGui.QApplication.translate("Dialog", "CARBON_DIOXIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog", "正交投影体：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog", " Z", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_name.setText(QtGui.QApplication.translate("Dialog", "名字：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "气体温度：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_temperature.setText(QtGui.QApplication.translate("Dialog", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "  气体压强\n"
"时间函数F(T)：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Pa", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
