# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPConfigDlg.ui'
#
# Created: Tue Sep 03 10:53:46 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_ConfigDlg(object):
    def setupUi(self, Dialog_ConfigDlg):
        Dialog_ConfigDlg.setObjectName("Dialog_ConfigDlg")
        Dialog_ConfigDlg.resize(537, 287)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog_ConfigDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(Dialog_ConfigDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_WorkPath = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_WorkPath.setObjectName("lineEdit_WorkPath")
        self.horizontalLayout_4.addWidget(self.lineEdit_WorkPath)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.pushBtn_chooseWorkPath = QtGui.QPushButton(self.groupBox_2)
        self.pushBtn_chooseWorkPath.setObjectName("pushBtn_chooseWorkPath")
        self.gridLayout_3.addWidget(self.pushBtn_chooseWorkPath, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog_ConfigDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setFrameShape(QtGui.QFrame.WinPanel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_IPAddress = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_IPAddress.setObjectName("lineEdit_IPAddress")
        self.horizontalLayout.addWidget(self.lineEdit_IPAddress)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_Port = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.horizontalLayout_3.addWidget(self.lineEdit_Port)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(Dialog_ConfigDlg)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ok = QtGui.QPushButton(Dialog_ConfigDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog_ConfigDlg)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(Dialog_ConfigDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ConfigDlg)

    def retranslateUi(self, Dialog_ConfigDlg):
        Dialog_ConfigDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_ConfigDlg", "配置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_ConfigDlg", "工作路径配置", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "工作路径：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_WorkPath.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "E:\\FreeCAD\\workpath", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBtn_chooseWorkPath.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "···", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_ConfigDlg", "网络配置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "IP地址：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_IPAddress.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "端口号：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Port.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "3200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "设置完成后，重启生效！", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog_ConfigDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

