#/src/Mod/Modeling/Modeling3D/Modeling3DCommand
SET(Modeling3DCommand_Srcs
./Modeling3DGuiTest.py
./__init__.py
)
SET(Area_Conformal_Srcs
./Area_Conformal/ConformalAreaCommand.py
./Area_Conformal/ConformalAreaDialog.py
./Area_Conformal/ConformalAreaInstance.py
./Area_Conformal/ConformalAreaNewDialog.py
./Area_Conformal/CreateConformalArea.py
./Area_Conformal/__init__.py
)
SET(Area_Function_Srcs
./Area_Function/AreaFunctionCommand.py
./Area_Function/AreaFunctionDlgMain.py
./Area_Function/AreaFunctionInstance.py
./Area_Function/CreateAreaFunction.py
./Area_Function/UI/Area_FunctionDlg.py
./Area_Function/UI/Area_FunctionDlg.ui
./Area_Function/UI/__init__.py
./Area_Function/__init__.py
)
SET(Area_Polygonal_Srcs
./Area_Polygonal/CreatePolygonal.py
./Area_Polygonal/ItemDialog.py
./Area_Polygonal/PolygonalCommand.py
./Area_Polygonal/PolygonalDialog.py
./Area_Polygonal/PolygonalInstance.py
./Area_Polygonal/PolygonalNewDialog.py
./Area_Polygonal/__init__.py
)
SET(Area_Rectangular_Srcs
./Area_Rectangular/CreateRectangular.py
./Area_Rectangular/RectangularAreaDialog.py
./Area_Rectangular/RectangularAreaNewDialog.py
./Area_Rectangular/RectangularCommand.py
./Area_Rectangular/RectangularInstance.py
./Area_Rectangular/__init__.py
)
SET(Area_TorusFace_Srcs
./Area_TorusFace/CreateTorusFace.py
./Area_TorusFace/TorusFaceCommand.py
./Area_TorusFace/TorusFaceInstance.py
./Area_TorusFace/__init__.py
)
SET(Cone_Srcs
./Cone/ConeCommand.py
./Cone/ConeInstance.py
./Cone/CreateCone.py
./Cone/__init__.py
)
SET(Cylinder_Srcs
./Cylinder/CreateCylinder.py
./Cylinder/CylinderCommand.py
./Cylinder/CylinderInstance.py
./Cylinder/__init__.py
)
SET(DialogReShow_Srcs
./DialogReShow/DialogReShowCommand.py
./DialogReShow/ReShow.py
./DialogReShow/__init__.py
)
SET(DraftModeling_Extrude_Srcs
./DraftModeling_Extrude/Command/CreateDraftModeling_Extrude.py
./DraftModeling_Extrude/Command/DraftModeling_ExtrudeDlgMain.py
./DraftModeling_Extrude/Command/DraftModeling_ExtrudeInstance.py
./DraftModeling_Extrude/Command/__init__.py
./DraftModeling_Extrude/UI/DraftModeling_ExtrudeDlg.py
./DraftModeling_Extrude/UI/DraftModeling_ExtrudeDlg.ui
./DraftModeling_Extrude/UI/__init__.py
./DraftModeling_Extrude/__init__.py
)
SET(DraftModeling_Revolution_Srcs
./DraftModeling_Revolution/Command/CreateDraftModeling_Revolution.py
./DraftModeling_Revolution/Command/DraftModeling_RevolutionDlgMain.py
./DraftModeling_Revolution/Command/DraftModeling_RevolutionInstance.py
./DraftModeling_Revolution/Command/__init__.py
./DraftModeling_Revolution/UI/DraftModeling_RevolutionDlg.py
./DraftModeling_Revolution/UI/DraftModeling_RevolutionDlg.ui
./DraftModeling_Revolution/UI/__init__.py
./DraftModeling_Revolution/__init__.py
)
SET(HollowedCylinder_Srcs
./HollowedCylinder/CreateHollowedCylinder.py
./HollowedCylinder/HollowedCylinderCommand.py
./HollowedCylinder/HollowedCylinderInstance.py
./HollowedCylinder/__init__.py
)
SET(Line_Circular_Srcs
./Line_Circular/CircularCommand.py
./Line_Circular/CircularInstance.py
./Line_Circular/CreateCircular.py
./Line_Circular/__init__.py
)
SET(Line_Conformal_Srcs
./Line_Conformal/ConformalLineCommand.py
./Line_Conformal/ConformalLineDialog.py
./Line_Conformal/ConformalLineInstance.py
./Line_Conformal/ConformalLineNewDialog.py
./Line_Conformal/CreateConformalLine.py
./Line_Conformal/__init__.py
)
SET(Line_Oblique_Srcs
./Line_Oblique/CreateObliqueLine.py
./Line_Oblique/ObliqueLineCommand.py
./Line_Oblique/ObliqueLineDialog.py
./Line_Oblique/ObliqueLineInstance.py
./Line_Oblique/ObliqueLineNewDialog.py
./Line_Oblique/__init__.py
)
#SET(modeling3DCmdBase_Srcs
#./modeling3DCmdBase/Modeling3DCmdBase.pyc
#./modeling3DCmdBase/__init__.pyc
#)

SET(Object_Array_Srcs
./Object_Array/ArrayCommand.py
./Object_Array/ArrayDialog.py
./Object_Array/ArrayDraft.py
./Object_Array/ArrayNewDialog.py
./Object_Array/__init__.py
)

SET(OrthographicBody_Srcs
./OrthographicBody/CreateOrthographicBody.py
./OrthographicBody/OrthographicBodyCommand.py
./OrthographicBody/OrthographicBodyInstance.py
./OrthographicBody/__init__.py
)
SET(Parallelogram_Srcs
./Parallelogram/CreateParallelogram.py
./Parallelogram/ParallelogramCommand.py
./Parallelogram/ParallelogramInstance.py
./Parallelogram/__init__.py
)
SET(Point_Srcs
./Point/CreatePoint.py
./Point/PointCommand.py
./Point/PointDialog.py
./Point/PointInstance.py
./Point/PointNewDialog.py
./Point/__init__.py
)
SET(Pyramid_Srcs
./Pyramid/CreatePyramid.py
./Pyramid/PyramidCommand.py
./Pyramid/PyramidInstance.py
./Pyramid/__init__.py
)
SET(ShowAllFunction_Srcs
./ShowAllFunction/FunctionBoolCommand.py
./ShowAllFunction/SAFDialogMain.py
./ShowAllFunction/ShowAllFunction.ui
./ShowAllFunction/ShowAllFunctionDialog.py
./ShowAllFunction/__init__.py
)
SET(SingleClickObj_Srcs
./SingleClickObj/SingleClickTheObj.py
./SingleClickObj/__init__.py
)
SET(SpecialCone_Srcs
./SpecialCone/CreateSpecialCone.py
./SpecialCone/SpecialConeInstance.py
./SpecialCone/SpeicalConeCommand.py
./SpecialCone/__init__.py
)
SET(Sphere_Srcs
./Sphere/CreateSphere.py
./Sphere/SphereCommand.py
./Sphere/SphereInstance.py
./Sphere/__init__.py
)
SET(Torus_Srcs
./Torus/CreateTorus.py
./Torus/TorusCommand.py
./Torus/TorusInstance.py
./Torus/__init__.py
)
SET(TorusFace_Srcs
./TorusFace/CreateTorusFace.py
./TorusFace/TorusFaceCommand.py
./TorusFace/TorusFaceInstance.py
./TorusFace/__init__.py
)
SET(Vol_Annular_Srcs
./Vol_Annular/AnnularCommand.py
./Vol_Annular/AnnularDialog.py
./Vol_Annular/AnnularInstance.py
./Vol_Annular/AnnularNewDialog.py
./Vol_Annular/CreateAnnular.py
./Vol_Annular/__init__.py
./Vol_Annular_Section/AnnularSectionDialog.py
./Vol_Annular_Section/AnnularSectionNewDialog.py
./Vol_Annular_Section/Annular_SectionCommand.py
./Vol_Annular_Section/Annular_SectionInstance.py
./Vol_Annular_Section/CreateAnnular_Section.py
./Vol_Annular_Section/__init__.py
)
SET(Vol_Array_Srcs
./Vol_Array/Command/ArrayInstance.py
./Vol_Array/Command/Vol_Array_Dlg_Main.py
./Vol_Array/Command/__init__.py
./Vol_Array/UI/Vol_Array_Dlg.py
./Vol_Array/UI/Vol_Array_Dlg.ui
./Vol_Array/UI/__init__.py
./Vol_Array/Vol_Array_Dlg.py
./Vol_Array/Vol_Array_Dlg.ui
./Vol_Array/__init__.py
)
SET(Vol_Boolean_Srcs
./Vol_Boolean/BooleanCommand.py
./Vol_Boolean/__init__.py
)
SET(Vol_Cone_Srcs
./Vol_Cone/ConeCommand.py
./Vol_Cone/ConeInstance.py
./Vol_Cone/CreateCone.py
./Vol_Cone/__init__.py
)
SET(Vol_Conformal_Srcs
./Vol_Conformal/ConformalCommand.py
./Vol_Conformal/ConformalDialog.py
./Vol_Conformal/ConformalInstance.py
./Vol_Conformal/ConformalNewDialog.py
./Vol_Conformal/CreateConformal.py
./Vol_Conformal/__init__.py
)
SET(Vol_Cylinder_Srcs
./Vol_Cylinder/CreateCylinder.py
./Vol_Cylinder/CylinderCommand.py
./Vol_Cylinder/CylinderDialog.py
./Vol_Cylinder/CylinderInstance.py
./Vol_Cylinder/CylinderNewDialog.py
./Vol_Cylinder/__init__.py
)
SET(Vol_Extruded_Srcs
./Vol_Extruded/CreateExtruded.py
./Vol_Extruded/ExtrudedCommand.py
./Vol_Extruded/ExtrudedInstance.py
./Vol_Extruded/__init__.py
)
SET(Vol_Function_Srcs
./Vol_Function/CreateFunction.py
./Vol_Function/FunctionCommand.py
./Vol_Function/FunctionDialog.py
./Vol_Function/FunctionInstance.py
./Vol_Function/FunctionNewDialog.py
./Vol_Function/__init__.py
)
SET(Vol_Helical_Srcs
./Vol_Helical/CreateHelical.py
./Vol_Helical/HelicalCommand.py
./Vol_Helical/HelicalDialog.py
./Vol_Helical/HelicalInstance.py
./Vol_Helical/HelicalNewDialog.py
./Vol_Helical/__init__.py
)
SET(Vol_OrthographicBody_Srcs
./Vol_OrthographicBody/CreateOrthographicBody.py
./Vol_OrthographicBody/OrthographicBodyCommand.py
./Vol_OrthographicBody/OrthographicBodyInstance.py
./Vol_OrthographicBody/__init__.py
)
SET(Vol_Parallelepipedal_Srcs
./Vol_Parallelepipedal/CreateParallelepipedal.py
./Vol_Parallelepipedal/ParallelepipedalCommand.py
./Vol_Parallelepipedal/ParallelepipedalDialog.py
./Vol_Parallelepipedal/ParallelepipedalInstance.py
./Vol_Parallelepipedal/ParallelepipedalNewDialog.py
./Vol_Parallelepipedal/__init__.py
)
SET(Vol_Pyramid_Srcs
./Vol_Pyramid/CreatePyramid.py
./Vol_Pyramid/PyramidCommand.py
./Vol_Pyramid/PyramidDialog.py
./Vol_Pyramid/PyramidInstance.py
./Vol_Pyramid/PyramidNewDialog.py
./Vol_Pyramid/__init__.py
)
SET(Vol_Revolution_Srcs
./Vol_Revolution/Command/CreateRevolution.py
./Vol_Revolution/Command/RevolutionCommand.py
./Vol_Revolution/Command/RevolutionDlgMain.py
./Vol_Revolution/Command/RevolutionInstance.py
./Vol_Revolution/Command/__init__.py
./Vol_Revolution/UI/Vol_RevolutionDlg.py
./Vol_Revolution/UI/Vol_RevolutionDlg.ui
./Vol_Revolution/UI/__init__.py
./Vol_Revolution/__init__.py
)
SET(Vol_Rhombus_Srcs
./Vol_Rhombus/CreateRhombus.py
./Vol_Rhombus/RhombusCommand.py
./Vol_Rhombus/RhombusDialog.py
./Vol_Rhombus/RhombusInstance.py
./Vol_Rhombus/RhombusNewDialog.py
./Vol_Rhombus/__init__.py
)
SET(Vol_SpecialCone_Srcs
./Vol_SpecialCone/CreateSpecialCone.py
./Vol_SpecialCone/SpecialConeDialog.py
./Vol_SpecialCone/SpecialConeInstance.py
./Vol_SpecialCone/SpecicalConeNewDialog.py
./Vol_SpecialCone/SpeicalConeCommand.py
./Vol_SpecialCone/__init__.py
)
SET(Vol_Spherical_Srcs
./Vol_Spherical/CreateSpherical.py
./Vol_Spherical/SphericalCommand.py
./Vol_Spherical/SphericalDialog.py
./Vol_Spherical/SphericalInstance.py
./Vol_Spherical/SphericalNewDialog.py
./Vol_Spherical/__init__.py
)
SET(Vol_Tetrahedron_Srcs
./Vol_Tetrahedron/CreateTetrahedron.py
./Vol_Tetrahedron/TetrahedronCommand.py
./Vol_Tetrahedron/TetrahedronDialog.py
./Vol_Tetrahedron/TetrahedronInstance.py
./Vol_Tetrahedron/TetrahedronNewDialog.py
./Vol_Tetrahedron/__init__.py
)
SET(Vol_Toroidal_Section_Srcs
./Vol_Toroidal_Section/CreateToroidal_Section.py
./Vol_Toroidal_Section/ToroidalSectionDialog.py
./Vol_Toroidal_Section/ToroidalSectionNewDialog.py
./Vol_Toroidal_Section/Toroidal_SectionCommand.py
./Vol_Toroidal_Section/Toroidal_SectionInstance.py
./Vol_Toroidal_Section/__init__.py
)
SET(Vol_Torus_Srcs
./Vol_Torus/CreateTorus.py
./Vol_Torus/TorusCommand.py
./Vol_Torus/TorusInstance.py
./Vol_Torus/__init__.py
)
SET(Vol_Wedge_Srcs
./Vol_Wedge/CreateWedge.py
./Vol_Wedge/WedgeCommand.py
./Vol_Wedge/WedgeDialog.py
./Vol_Wedge/WedgeInstance.py
./Vol_Wedge/WedgeNewDialog.py
./Vol_Wedge/__init__.py
)
SET(Wedge_Srcs
./Wedge/CreateWedge.py
./Wedge/WedgeCommand.py
./Wedge/WedgeInstance.py
./Wedge/__init__.py
)
SET(_Operation_Clip_Srcs
./_Operation_Clip/Clip.py
./_Operation_Clip/ClipCommand.py
./_Operation_Clip/Command/ClipCommand.py
./_Operation_Clip/Command/ClipDlg.py
./_Operation_Clip/Command/__init__.py
./_Operation_Clip/UI/Clip_Dlg.ui
./_Operation_Clip/UI/Vol_Array_Dlg.ui
./_Operation_Clip/UI/Vol_Clip_Dlg.py
./_Operation_Clip/UI/__init__.py
./_Operation_Clip/__init__.py
)
SET(_Operation_Copy_Srcs
./_Operation_Copy/Copy.py
./_Operation_Copy/CopyCommand.py
./_Operation_Copy/__init__.py
)
SET(all_Srcs
${Modeling3DCommand_Srcs}
${Area_Conformal_Srcs}
${Area_Function_Srcs}
${Area_Polygonal_Srcs}
${Area_Rectangular_Srcs}
${Area_TorusFace_Srcs}
${Cone_Srcs}
${Cylinder_Srcs}
${DialogReShow_Srcs}
${DraftModeling_Extrude_Srcs}
${DraftModeling_Revolution_Srcs}
${HollowedCylinder_Srcs}
${Line_Conformal_Srcs}
${Line_Oblique_Srcs}
${Object_Array_Srcs}
${Point_Srcs}
${SingleClickObj_Srcs}
${ShowAllFunction_Srcs}
${Pyramid_Srcs}
${SpecialCone_Srcs}
${Sphere_Srcs}
${Torus_Srcs}
${TorusFace_Srcs}
${Vol_Annular_Srcs}
${Vol_Array_Srcs}
${Vol_Boolean_Srcs}
${Vol_Cone_Srcs}
${Vol_Conformal_Srcs}
${Vol_Cylinder_Srcs}
${Vol_Extruded_Srcs}
${Vol_Function_Srcs}
${Vol_Helical_Srcs}
${Vol_OrthographicBody_Srcs}
${OrthographicBody_Srcs}
${Vol_Parallelepipedal_Srcs}
${Vol_Pyramid_Srcs}
${Vol_Revolution_Srcs}
${Vol_Rhombus_Srcs}
${Vol_SpecialCone_Srcs}
${Vol_Spherical_Srcs}
${Vol_Tetrahedron_Srcs}
${Vol_Toroidal_Section_Srcs}
${Vol_Torus_Srcs}
${Vol_Wedge_Srcs}
${Wedge_Srcs}
${_Operation_Clip_Srcs}
${_Operation_Copy_Srcs}
${Line_Circular_Srcs}
${Parallelogram_Srcs}
)
add_custom_target(Modeling3DCommand ALL SOURCES ${all_Srcs})
fc_copy_sources(Modeling3DCommand "${CMAKE_BINARY_DIR}/Mod/Modeling/Modeling3D/Modeling3DCommand" ${all_Srcs})
install(
	FILES
	${all_Srcs}
	DESTINATION
	Mod/Modeling/Modeling3D/Modeling3DCommand
)
