# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WireDialog.ui'
#
# Created: Mon Feb  1 23:45:49 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1025, 609)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.cb_attribute = QtGui.QComboBox(self.groupBox_2)
        self.cb_attribute.setObjectName("cb_attribute")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.gridLayout_4.addWidget(self.cb_attribute, 0, 1, 1, 1)
        self.Layout_custom = QtGui.QHBoxLayout()
        self.Layout_custom.setObjectName("Layout_custom")
        self.gridLayout_4.addLayout(self.Layout_custom, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_x = QtGui.QLabel(self.groupBox_3)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.le_markx = QtGui.QLineEdit(self.groupBox_3)
        self.le_markx.setObjectName("le_markx")
        self.gridLayout.addWidget(self.le_markx, 1, 1, 1, 3)
        self.label_y = QtGui.QLabel(self.groupBox_3)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        self.le_marky = QtGui.QLineEdit(self.groupBox_3)
        self.le_marky.setObjectName("le_marky")
        self.gridLayout.addWidget(self.le_marky, 1, 4, 1, 3)
        self.checkBox_isMarkX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkX.setObjectName("checkBox_isMarkX")
        self.gridLayout.addWidget(self.checkBox_isMarkX, 2, 1, 1, 3)
        self.checkBox_isMarkY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkY.setObjectName("checkBox_isMarkY")
        self.gridLayout.addWidget(self.checkBox_isMarkY, 2, 4, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_name = QtGui.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.le_order = QtGui.QLineEdit(self.groupBox)
        self.le_order.setObjectName("le_order")
        self.horizontalLayout.addWidget(self.le_order)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_ok = QtGui.QPushButton(self.groupBox_4)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_2.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(self.groupBox_4)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dsp_radius = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.dsp_radius.setMinimum(0.0)
        self.dsp_radius.setMaximum(99999.0)
        self.dsp_radius.setProperty("value", 0.01)
        self.dsp_radius.setObjectName("dsp_radius")
        self.gridLayout_5.addWidget(self.dsp_radius, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.isFillet = QtGui.QCheckBox(self.groupBox_6)
        self.isFillet.setObjectName("isFillet")
        self.gridLayout_5.addWidget(self.isFillet, 0, 0, 1, 1)
        self.sb_fillet_num = QtGui.QSpinBox(self.groupBox_6)
        self.sb_fillet_num.setObjectName("sb_fillet_num")
        self.gridLayout_5.addWidget(self.sb_fillet_num, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_2.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 285))
        self.groupBox_5.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.spinBox_num = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_num.setMinimum(3)
        self.spinBox_num.setMaximum(200)
        self.spinBox_num.setObjectName("spinBox_num")
        self.gridLayout_3.addWidget(self.spinBox_num, 0, 1, 1, 3)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 6, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.listWidget = QtGui.QListWidget(self.groupBox_5)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(0, QtGui.QApplication.translate("Dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(1, QtGui.QApplication.translate("Dialog", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(2, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(3, QtGui.QApplication.translate("Dialog", "Void", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkX.setText(QtGui.QApplication.translate("Dialog", "isMarkX", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkY.setText(QtGui.QApplication.translate("Dialog", "isMarkY", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Fillet", None, QtGui.QApplication.UnicodeUTF8))
        self.dsp_radius.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "/*Tips: 第n-1,n,n+1三个点所构成的角为第n个角*/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Fillet:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.isFillet.setText(QtGui.QApplication.translate("Dialog", "是否添加倒角", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Object of a Polygonal Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "NumbersofPoints", None, QtGui.QApplication.UnicodeUTF8))

