# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\NewPicGui\FreeCAD\src\Mod\Model3D\Command3D\Physics3DCommand\Observe\ObserveDialog.ui'
#
# Created: Mon Jul 22 09:22:53 2024
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(539, 635)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_13 = QtGui.QGridLayout(Dialog)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 494, 712))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_12 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.le_name = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 0, 0, 1, 2)
        self.cb_observationType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cb_observationType.setObjectName("cb_observationType")
        self.cb_observationType.addItem("")
        self.cb_observationType.addItem("")
        self.cb_observationType.addItem("")
        self.cb_observationType.addItem("")
        self.gridLayout.addWidget(self.cb_observationType, 0, 2, 1, 1)
        self.le_alias = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_alias.setObjectName("le_alias")
        self.gridLayout.addWidget(self.le_alias, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.cb_optionType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cb_optionType.setObjectName("cb_optionType")
        self.cb_optionType.addItem("")
        self.gridLayout.addWidget(self.cb_optionType, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout_12.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.gridLayout_2.addWidget(self.LineEdit_start_x, 1, 2, 1, 1)
        self.cb_point1_name = QtGui.QComboBox(self.groupBox)
        self.cb_point1_name.setObjectName("cb_point1_name")
        self.cb_point1_name.addItem("")
        self.gridLayout_2.addWidget(self.cb_point1_name, 1, 5, 1, 1)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_end_y.setEnabled(True)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.gridLayout_2.addWidget(self.LineEdit_end_y, 2, 3, 1, 1)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.gridLayout_2.addWidget(self.LineEdit_start_y, 1, 3, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox)
        self.label_X.setObjectName("label_X")
        self.gridLayout_2.addWidget(self.label_X, 0, 2, 1, 1)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_end_x.setEnabled(True)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.gridLayout_2.addWidget(self.LineEdit_end_x, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_Y = QtGui.QLabel(self.groupBox)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_2.addWidget(self.label_Y, 0, 3, 1, 1)
        self.cb_point2_name = QtGui.QComboBox(self.groupBox)
        self.cb_point2_name.setObjectName("cb_point2_name")
        self.cb_point2_name.addItem("")
        self.gridLayout_2.addWidget(self.cb_point2_name, 2, 5, 1, 1)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.gridLayout_2.addWidget(self.LineEdit_start_z, 1, 4, 1, 1)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.gridLayout_2.addWidget(self.LineEdit_end_z, 2, 4, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_2.addWidget(self.label_Z, 0, 4, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setStyleSheet("border:none")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_x.setEnabled(True)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_y.setEnabled(True)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_z.setEnabled(True)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout.addWidget(self.radioButton_z)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 2, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 2, 0, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.rb_isTimeAverage = QtGui.QRadioButton(self.groupBox_7)
        self.rb_isTimeAverage.setEnabled(False)
        self.rb_isTimeAverage.setChecked(True)
        self.rb_isTimeAverage.setObjectName("rb_isTimeAverage")
        self.gridLayout_10.addWidget(self.rb_isTimeAverage, 0, 1, 1, 1)
        self.rb_isRcAnalyze = QtGui.QRadioButton(self.groupBox_7)
        self.rb_isRcAnalyze.setEnabled(False)
        self.rb_isRcAnalyze.setObjectName("rb_isRcAnalyze")
        self.gridLayout_10.addWidget(self.rb_isRcAnalyze, 0, 2, 1, 1)
        self.cb_isDataDisplay = QtGui.QCheckBox(self.groupBox_7)
        self.cb_isDataDisplay.setObjectName("cb_isDataDisplay")
        self.gridLayout_10.addWidget(self.cb_isDataDisplay, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 1, 2, 1, 1)
        self.le_filteringTimeParameter = QtGui.QLineEdit(self.groupBox_7)
        self.le_filteringTimeParameter.setEnabled(False)
        self.le_filteringTimeParameter.setObjectName("le_filteringTimeParameter")
        self.gridLayout_10.addWidget(self.le_filteringTimeParameter, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_ok = QtGui.QPushButton(self.groupBox_7)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_3.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(self.groupBox_7)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_3.addWidget(self.pb_cancel)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 4, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMouseTracking(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cb_fieldPower = QtGui.QComboBox(self.groupBox_5)
        self.cb_fieldPower.setEnabled(False)
        self.cb_fieldPower.setObjectName("cb_fieldPower")
        self.cb_fieldPower.addItem("")
        self.gridLayout_5.addWidget(self.cb_fieldPower, 0, 2, 1, 1)
        self.cb_field = QtGui.QComboBox(self.groupBox_5)
        self.cb_field.setObjectName("cb_field")
        self.gridLayout_5.addWidget(self.cb_field, 0, 0, 1, 1)
        self.cb_fieldIntegral = QtGui.QComboBox(self.groupBox_5)
        self.cb_fieldIntegral.setEnabled(False)
        self.cb_fieldIntegral.setObjectName("cb_fieldIntegral")
        self.cb_fieldIntegral.addItem("")
        self.cb_fieldIntegral.addItem("")
        self.cb_fieldIntegral.addItem("")
        self.gridLayout_5.addWidget(self.cb_fieldIntegral, 0, 1, 1, 1)
        self.cb_fieldEnergy = QtGui.QComboBox(self.groupBox_5)
        self.cb_fieldEnergy.setEnabled(False)
        self.cb_fieldEnergy.setObjectName("cb_fieldEnergy")
        self.cb_fieldEnergy.addItem("")
        self.cb_fieldEnergy.addItem("")
        self.cb_fieldEnergy.addItem("")
        self.gridLayout_5.addWidget(self.cb_fieldEnergy, 0, 3, 1, 1)
        self.le_particles1 = QtGui.QLineEdit(self.groupBox_5)
        self.le_particles1.setEnabled(False)
        self.le_particles1.setObjectName("le_particles1")
        self.gridLayout_5.addWidget(self.le_particles1, 1, 0, 1, 1)
        self.cb_particles2 = QtGui.QComboBox(self.groupBox_5)
        self.cb_particles2.setEnabled(False)
        self.cb_particles2.setObjectName("cb_particles2")
        self.cb_particles2.addItem("")
        self.cb_particles2.addItem("")
        self.cb_particles2.addItem("")
        self.cb_particles2.addItem("")
        self.gridLayout_5.addWidget(self.cb_particles2, 1, 1, 1, 1)
        self.cb_particles3 = QtGui.QComboBox(self.groupBox_5)
        self.cb_particles3.setEnabled(False)
        self.cb_particles3.setObjectName("cb_particles3")
        self.cb_particles3.addItem("")
        self.cb_particles3.addItem("")
        self.cb_particles3.addItem("")
        self.cb_particles3.addItem("")
        self.cb_particles3.addItem("")
        self.gridLayout_5.addWidget(self.cb_particles3, 1, 2, 1, 1)
        self.cb_particles4 = QtGui.QComboBox(self.groupBox_5)
        self.cb_particles4.setEnabled(False)
        self.cb_particles4.setObjectName("cb_particles4")
        self.cb_particles4.addItem("")
        self.cb_particles4.addItem("")
        self.cb_particles4.addItem("")
        self.gridLayout_5.addWidget(self.cb_particles4, 1, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_isFFT = QtGui.QCheckBox(self.groupBox_6)
        self.cb_isFFT.setObjectName("cb_isFFT")
        self.horizontalLayout_2.addWidget(self.cb_isFFT)
        self.rb_isRealAnalysis = QtGui.QRadioButton(self.groupBox_6)
        self.rb_isRealAnalysis.setEnabled(False)
        self.rb_isRealAnalysis.setChecked(True)
        self.rb_isRealAnalysis.setObjectName("rb_isRealAnalysis")
        self.horizontalLayout_2.addWidget(self.rb_isRealAnalysis)
        self.rb_isComplexAnalysis = QtGui.QRadioButton(self.groupBox_6)
        self.rb_isComplexAnalysis.setEnabled(False)
        self.rb_isComplexAnalysis.setObjectName("rb_isComplexAnalysis")
        self.horizontalLayout_2.addWidget(self.rb_isComplexAnalysis)
        self.gridLayout_8.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rb_isFieldPower = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isFieldPower.setEnabled(True)
        self.rb_isFieldPower.setObjectName("rb_isFieldPower")
        self.gridLayout_4.addWidget(self.rb_isFieldPower, 0, 2, 1, 1)
        self.rb_isField = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isField.setChecked(True)
        self.rb_isField.setObjectName("rb_isField")
        self.gridLayout_4.addWidget(self.rb_isField, 0, 0, 1, 1)
        self.rb_isFieldIntegral = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isFieldIntegral.setEnabled(True)
        self.rb_isFieldIntegral.setObjectName("rb_isFieldIntegral")
        self.gridLayout_4.addWidget(self.rb_isFieldIntegral, 0, 1, 1, 1)
        self.rb_isFieldEnergy = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isFieldEnergy.setEnabled(True)
        self.rb_isFieldEnergy.setObjectName("rb_isFieldEnergy")
        self.gridLayout_4.addWidget(self.rb_isFieldEnergy, 0, 3, 1, 1)
        self.rb_isParticleStatistics = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isParticleStatistics.setEnabled(True)
        self.rb_isParticleStatistics.setObjectName("rb_isParticleStatistics")
        self.gridLayout_4.addWidget(self.rb_isParticleStatistics, 1, 0, 1, 1)
        self.rb_isCollectedParticles = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isCollectedParticles.setEnabled(True)
        self.rb_isCollectedParticles.setObjectName("rb_isCollectedParticles")
        self.gridLayout_4.addWidget(self.rb_isCollectedParticles, 1, 1, 1, 1)
        self.rb_isEmittedParticle = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isEmittedParticle.setEnabled(True)
        self.rb_isEmittedParticle.setObjectName("rb_isEmittedParticle")
        self.gridLayout_4.addWidget(self.rb_isEmittedParticle, 1, 2, 1, 1)
        self.rb_isAnnihilatingParticle = QtGui.QRadioButton(self.groupBox_4)
        self.rb_isAnnihilatingParticle.setEnabled(True)
        self.rb_isAnnihilatingParticle.setObjectName("rb_isAnnihilatingParticle")
        self.gridLayout_4.addWidget(self.rb_isAnnihilatingParticle, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cb_isFrequencyRange = QtGui.QCheckBox(self.groupBox_3)
        self.cb_isFrequencyRange.setObjectName("cb_isFrequencyRange")
        self.gridLayout_9.addWidget(self.cb_isFrequencyRange, 0, 0, 1, 1)
        self.le_timeRange1 = QtGui.QLineEdit(self.groupBox_3)
        self.le_timeRange1.setEnabled(False)
        self.le_timeRange1.setObjectName("le_timeRange1")
        self.gridLayout_9.addWidget(self.le_timeRange1, 1, 1, 1, 1)
        self.cb_isTimeRange = QtGui.QCheckBox(self.groupBox_3)
        self.cb_isTimeRange.setObjectName("cb_isTimeRange")
        self.gridLayout_9.addWidget(self.cb_isTimeRange, 1, 0, 1, 1)
        self.le_frequencyRange1 = QtGui.QLineEdit(self.groupBox_3)
        self.le_frequencyRange1.setEnabled(False)
        self.le_frequencyRange1.setObjectName("le_frequencyRange1")
        self.gridLayout_9.addWidget(self.le_frequencyRange1, 0, 1, 1, 1)
        self.le_frequencyRange2 = QtGui.QLineEdit(self.groupBox_3)
        self.le_frequencyRange2.setEnabled(False)
        self.le_frequencyRange2.setObjectName("le_frequencyRange2")
        self.gridLayout_9.addWidget(self.le_frequencyRange2, 0, 3, 1, 1)
        self.le_timeRange2 = QtGui.QLineEdit(self.groupBox_3)
        self.le_timeRange2.setEnabled(False)
        self.le_timeRange2.setObjectName("le_timeRange2")
        self.gridLayout_9.addWidget(self.le_timeRange2, 1, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 1, 4, 1, 1)
        self.cb_isObservationInterval = QtGui.QCheckBox(self.groupBox_3)
        self.cb_isObservationInterval.setObjectName("cb_isObservationInterval")
        self.gridLayout_9.addWidget(self.cb_isObservationInterval, 2, 0, 1, 1)
        self.le_observationInterval = QtGui.QLineEdit(self.groupBox_3)
        self.le_observationInterval.setEnabled(False)
        self.le_observationInterval.setObjectName("le_observationInterval")
        self.gridLayout_9.addWidget(self.le_observationInterval, 2, 1, 1, 3)
        self.gridLayout_8.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_13.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.le_name)
        Dialog.setTabOrder(self.le_name, self.cb_observationType)
        Dialog.setTabOrder(self.cb_observationType, self.le_alias)
        Dialog.setTabOrder(self.le_alias, self.cb_optionType)
        Dialog.setTabOrder(self.cb_optionType, self.LineEdit_start_x)
        Dialog.setTabOrder(self.LineEdit_start_x, self.LineEdit_start_y)
        Dialog.setTabOrder(self.LineEdit_start_y, self.LineEdit_start_z)
        Dialog.setTabOrder(self.LineEdit_start_z, self.cb_point1_name)
        Dialog.setTabOrder(self.cb_point1_name, self.LineEdit_end_x)
        Dialog.setTabOrder(self.LineEdit_end_x, self.LineEdit_end_y)
        Dialog.setTabOrder(self.LineEdit_end_y, self.LineEdit_end_z)
        Dialog.setTabOrder(self.LineEdit_end_z, self.cb_point2_name)
        Dialog.setTabOrder(self.cb_point2_name, self.radioButton_x)
        Dialog.setTabOrder(self.radioButton_x, self.radioButton_y)
        Dialog.setTabOrder(self.radioButton_y, self.radioButton_z)
        Dialog.setTabOrder(self.radioButton_z, self.rb_isField)
        Dialog.setTabOrder(self.rb_isField, self.rb_isFieldIntegral)
        Dialog.setTabOrder(self.rb_isFieldIntegral, self.rb_isFieldPower)
        Dialog.setTabOrder(self.rb_isFieldPower, self.rb_isFieldEnergy)
        Dialog.setTabOrder(self.rb_isFieldEnergy, self.rb_isParticleStatistics)
        Dialog.setTabOrder(self.rb_isParticleStatistics, self.rb_isCollectedParticles)
        Dialog.setTabOrder(self.rb_isCollectedParticles, self.rb_isEmittedParticle)
        Dialog.setTabOrder(self.rb_isEmittedParticle, self.rb_isAnnihilatingParticle)
        Dialog.setTabOrder(self.rb_isAnnihilatingParticle, self.cb_field)
        Dialog.setTabOrder(self.cb_field, self.cb_fieldIntegral)
        Dialog.setTabOrder(self.cb_fieldIntegral, self.cb_fieldPower)
        Dialog.setTabOrder(self.cb_fieldPower, self.cb_fieldEnergy)
        Dialog.setTabOrder(self.cb_fieldEnergy, self.le_particles1)
        Dialog.setTabOrder(self.le_particles1, self.cb_particles2)
        Dialog.setTabOrder(self.cb_particles2, self.cb_particles3)
        Dialog.setTabOrder(self.cb_particles3, self.cb_particles4)
        Dialog.setTabOrder(self.cb_particles4, self.cb_isFFT)
        Dialog.setTabOrder(self.cb_isFFT, self.rb_isRealAnalysis)
        Dialog.setTabOrder(self.rb_isRealAnalysis, self.rb_isComplexAnalysis)
        Dialog.setTabOrder(self.rb_isComplexAnalysis, self.cb_isFrequencyRange)
        Dialog.setTabOrder(self.cb_isFrequencyRange, self.le_frequencyRange1)
        Dialog.setTabOrder(self.le_frequencyRange1, self.le_frequencyRange2)
        Dialog.setTabOrder(self.le_frequencyRange2, self.cb_isTimeRange)
        Dialog.setTabOrder(self.cb_isTimeRange, self.le_timeRange1)
        Dialog.setTabOrder(self.le_timeRange1, self.le_timeRange2)
        Dialog.setTabOrder(self.le_timeRange2, self.cb_isObservationInterval)
        Dialog.setTabOrder(self.cb_isObservationInterval, self.le_observationInterval)
        Dialog.setTabOrder(self.le_observationInterval, self.cb_isDataDisplay)
        Dialog.setTabOrder(self.cb_isDataDisplay, self.rb_isTimeAverage)
        Dialog.setTabOrder(self.rb_isTimeAverage, self.rb_isRcAnalyze)
        Dialog.setTabOrder(self.rb_isRcAnalyze, self.le_filteringTimeParameter)
        Dialog.setTabOrder(self.le_filteringTimeParameter, self.scrollArea)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "时间观测设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "别名：", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_observationType.setItemText(0, QtGui.QApplication.translate("Dialog", "时间观测点", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_observationType.setItemText(1, QtGui.QApplication.translate("Dialog", "时间观测线", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_observationType.setItemText(2, QtGui.QApplication.translate("Dialog", "时间观测面", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_observationType.setItemText(3, QtGui.QApplication.translate("Dialog", "时间观测体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_optionType.setItemText(0, QtGui.QApplication.translate("Dialog", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "观测类型", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_point1_name.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "终点:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_point2_name.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog", "参数", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isTimeAverage.setText(QtGui.QApplication.translate("Dialog", "时间平均", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isRcAnalyze.setText(QtGui.QApplication.translate("Dialog", "RC分析", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isDataDisplay.setText(QtGui.QApplication.translate("Dialog", "数据平滑处理：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "过滤时间参数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "观测项", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "分类子项", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldPower.setItemText(0, QtGui.QApplication.translate("Dialog", "S.DA", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldIntegral.setItemText(0, QtGui.QApplication.translate("Dialog", "E.DL", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldIntegral.setItemText(1, QtGui.QApplication.translate("Dialog", "H.DL", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldIntegral.setItemText(2, QtGui.QApplication.translate("Dialog", "J.DA", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldEnergy.setItemText(0, QtGui.QApplication.translate("Dialog", "EM", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldEnergy.setItemText(1, QtGui.QApplication.translate("Dialog", "ELECTRIC", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldEnergy.setItemText(2, QtGui.QApplication.translate("Dialog", "MAGNETIC", None, QtGui.QApplication.UnicodeUTF8))
        self.le_particles1.setText(QtGui.QApplication.translate("Dialog", "phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles2.setItemText(0, QtGui.QApplication.translate("Dialog", "EMIT_EPS", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles2.setItemText(1, QtGui.QApplication.translate("Dialog", "CHARGE", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles2.setItemText(2, QtGui.QApplication.translate("Dialog", "ENERGY", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles2.setItemText(3, QtGui.QApplication.translate("Dialog", "VRATIO", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles3.setItemText(0, QtGui.QApplication.translate("Dialog", "CHARGE", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles3.setItemText(1, QtGui.QApplication.translate("Dialog", "CURRENT", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles3.setItemText(2, QtGui.QApplication.translate("Dialog", "ENERGY", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles3.setItemText(3, QtGui.QApplication.translate("Dialog", "POWER", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles3.setItemText(4, QtGui.QApplication.translate("Dialog", "VOLTAGE", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles4.setItemText(0, QtGui.QApplication.translate("Dialog", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles4.setItemText(1, QtGui.QApplication.translate("Dialog", "ELECTRON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_particles4.setItemText(2, QtGui.QApplication.translate("Dialog", "PROTON", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isFFT.setText(QtGui.QApplication.translate("Dialog", "进行快速傅里叶变换", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isRealAnalysis.setText(QtGui.QApplication.translate("Dialog", "实分析", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isComplexAnalysis.setText(QtGui.QApplication.translate("Dialog", "复分析", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "分类项", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isFieldPower.setText(QtGui.QApplication.translate("Dialog", "场功率", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isField.setText(QtGui.QApplication.translate("Dialog", "场", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isFieldIntegral.setText(QtGui.QApplication.translate("Dialog", "场积分", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isFieldEnergy.setText(QtGui.QApplication.translate("Dialog", "场能量", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isParticleStatistics.setText(QtGui.QApplication.translate("Dialog", "粒子统计", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isCollectedParticles.setText(QtGui.QApplication.translate("Dialog", "收集粒子", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isEmittedParticle.setText(QtGui.QApplication.translate("Dialog", "发射粒子", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_isAnnihilatingParticle.setText(QtGui.QApplication.translate("Dialog", "湮灭粒子", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isFrequencyRange.setText(QtGui.QApplication.translate("Dialog", "频率范围", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isTimeRange.setText(QtGui.QApplication.translate("Dialog", "时间范围", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Ghz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isObservationInterval.setText(QtGui.QApplication.translate("Dialog", "观察间隔", None, QtGui.QApplication.UnicodeUTF8))

