# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeldDialog.ui'
#
# Created: Fri May 21 16:13:30 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_EmhDlg(object):
    def setupUi(self, Dialog_EmhDlg):
        Dialog_EmhDlg.setObjectName("Dialog_EmhDlg")
        Dialog_EmhDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_EmhDlg.resize(550, 600)
        Dialog_EmhDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_EmhDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_9 = QtGui.QGridLayout(Dialog_EmhDlg)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea = QtGui.QScrollArea(Dialog_EmhDlg)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 513, 693))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Label_Name_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_10.addWidget(self.Label_Name_2)
        self.LineEdit_Name = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_10.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_10.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow = StyledComboBox(self.scrollAreaWidgetContents_2)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_10.addWidget(self.ComboBox_Shadow)
        self.gridLayout_10.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.LineEdit_PHI = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_PHI.setEnabled(True)
        self.LineEdit_PHI.setObjectName("LineEdit_PHI")
        self.horizontalLayout_9.addWidget(self.LineEdit_PHI)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.LineEdit_FNA = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_FNA.setObjectName("LineEdit_FNA")
        self.horizontalLayout_6.addWidget(self.LineEdit_FNA)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.LineEdit_FNB = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_FNB.setEnabled(True)
        self.LineEdit_FNB.setObjectName("LineEdit_FNB")
        self.horizontalLayout_7.addWidget(self.LineEdit_FNB)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_surface = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_surface.setObjectName("checkBox_surface")
        self.gridLayout_6.addWidget(self.checkBox_surface, 0, 0, 1, 1)
        self.radioButton_randomm = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_randomm.setEnabled(False)
        self.radioButton_randomm.setChecked(True)
        self.radioButton_randomm.setObjectName("radioButton_randomm")
        self.gridLayout_6.addWidget(self.radioButton_randomm, 0, 1, 1, 1)
        self.radioButton_uniform = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_uniform.setEnabled(False)
        self.radioButton_uniform.setObjectName("radioButton_uniform")
        self.gridLayout_6.addWidget(self.radioButton_uniform, 0, 2, 1, 1)
        self.radioButton_fixed = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_fixed.setEnabled(False)
        self.radioButton_fixed.setObjectName("radioButton_fixed")
        self.gridLayout_6.addWidget(self.radioButton_fixed, 0, 3, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_strictTiming = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_strictTiming.setEnabled(False)
        self.radioButton_strictTiming.setObjectName("radioButton_strictTiming")
        self.gridLayout_7.addWidget(self.radioButton_strictTiming, 0, 2, 1, 1)
        self.spinBox_timesStep = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_timesStep.setEnabled(False)
        self.spinBox_timesStep.setObjectName("spinBox_timesStep")
        self.gridLayout_7.addWidget(self.spinBox_timesStep, 0, 3, 1, 1)
        self.radioButton_random = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_random.setEnabled(False)
        self.radioButton_random.setChecked(True)
        self.radioButton_random.setObjectName("radioButton_random")
        self.gridLayout_7.addWidget(self.radioButton_random, 0, 1, 1, 1)
        self.checkBox_transmittingInterval = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_transmittingInterval.setObjectName("checkBox_transmittingInterval")
        self.gridLayout_7.addWidget(self.checkBox_transmittingInterval, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 4, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.LineEdit_Dn = QtGui.QLineEdit(self.groupBox_2)
        self.LineEdit_Dn.setEnabled(False)
        self.LineEdit_Dn.setObjectName("LineEdit_Dn")
        self.horizontalLayout_5.addWidget(self.LineEdit_Dn)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_randommm = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_randommm.setEnabled(False)
        self.radioButton_randommm.setChecked(True)
        self.radioButton_randommm.setObjectName("radioButton_randommm")
        self.gridLayout.addWidget(self.radioButton_randommm, 0, 1, 1, 1)
        self.checkBox_outSurface = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_outSurface.setObjectName("checkBox_outSurface")
        self.gridLayout.addWidget(self.checkBox_outSurface, 0, 0, 1, 1)
        self.radioButton_alongOutsideFixed = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_alongOutsideFixed.setEnabled(False)
        self.radioButton_alongOutsideFixed.setObjectName("radioButton_alongOutsideFixed")
        self.gridLayout.addWidget(self.radioButton_alongOutsideFixed, 0, 2, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.spinBox_generationRate = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_generationRate.setEnabled(False)
        self.spinBox_generationRate.setObjectName("spinBox_generationRate")
        self.gridLayout_8.addWidget(self.spinBox_generationRate, 0, 3, 1, 1)
        self.ComboBox_particleType = StyledComboBox(self.groupBox_8)
        self.ComboBox_particleType.setEnabled(False)
        self.ComboBox_particleType.setObjectName("ComboBox_particleType")
        self.ComboBox_particleType.addItem("")
        self.ComboBox_particleType.addItem("")
        self.gridLayout_8.addWidget(self.ComboBox_particleType, 0, 1, 1, 1)
        self.checkBox_generationRate = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_generationRate.setObjectName("checkBox_generationRate")
        self.gridLayout_8.addWidget(self.checkBox_generationRate, 0, 2, 1, 1)
        self.checkBox_particleType = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_particleType.setObjectName("checkBox_particleType")
        self.gridLayout_8.addWidget(self.checkBox_particleType, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 4, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 5, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 7, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.ComboBox_notInclued = StyledComboBox(self.groupBox_3)
        self.ComboBox_notInclued.setObjectName("ComboBox_notInclued")
        self.ComboBox_notInclued.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_notInclued)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.ComboBox_notIncludedd = StyledComboBox(self.groupBox_3)
        self.ComboBox_notIncludedd.setObjectName("ComboBox_notIncludedd")
        self.ComboBox_notIncludedd.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_notIncludedd)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 4, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 2, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem13, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.ComboBox_included = StyledComboBox(self.groupBox_4)
        self.ComboBox_included.setObjectName("ComboBox_included")
        self.ComboBox_included.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_included)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.ComboBox_includedd = StyledComboBox(self.groupBox_4)
        self.ComboBox_includedd.setObjectName("ComboBox_includedd")
        self.ComboBox_includedd.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_includedd)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 3, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 4, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 5, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pb_ok = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_18.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_18.addWidget(self.pb_cancel)
        self.gridLayout_10.addLayout(self.horizontalLayout_18, 6, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem15, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog_EmhDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_EmhDlg)
        Dialog_EmhDlg.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog_EmhDlg.setTabOrder(self.pb_cancel, self.LineEdit_Name)
        Dialog_EmhDlg.setTabOrder(self.LineEdit_Name, self.ComboBox_Shadow)
        Dialog_EmhDlg.setTabOrder(self.ComboBox_Shadow, self.LineEdit_FNA)
        Dialog_EmhDlg.setTabOrder(self.LineEdit_FNA, self.LineEdit_FNB)
        Dialog_EmhDlg.setTabOrder(self.LineEdit_FNB, self.LineEdit_PHI)
        Dialog_EmhDlg.setTabOrder(self.LineEdit_PHI, self.checkBox_particleType)
        Dialog_EmhDlg.setTabOrder(self.checkBox_particleType, self.ComboBox_particleType)
        Dialog_EmhDlg.setTabOrder(self.ComboBox_particleType, self.checkBox_generationRate)
        Dialog_EmhDlg.setTabOrder(self.checkBox_generationRate, self.spinBox_generationRate)
        Dialog_EmhDlg.setTabOrder(self.spinBox_generationRate, self.checkBox_transmittingInterval)
        Dialog_EmhDlg.setTabOrder(self.checkBox_transmittingInterval, self.radioButton_random)
        Dialog_EmhDlg.setTabOrder(self.radioButton_random, self.radioButton_strictTiming)
        Dialog_EmhDlg.setTabOrder(self.radioButton_strictTiming, self.spinBox_timesStep)
        Dialog_EmhDlg.setTabOrder(self.spinBox_timesStep, self.checkBox_surface)
        Dialog_EmhDlg.setTabOrder(self.checkBox_surface, self.radioButton_randomm)
        Dialog_EmhDlg.setTabOrder(self.radioButton_randomm, self.radioButton_uniform)
        Dialog_EmhDlg.setTabOrder(self.radioButton_uniform, self.radioButton_fixed)
        Dialog_EmhDlg.setTabOrder(self.radioButton_fixed, self.checkBox_outSurface)
        Dialog_EmhDlg.setTabOrder(self.checkBox_outSurface, self.radioButton_randommm)
        Dialog_EmhDlg.setTabOrder(self.radioButton_randommm, self.radioButton_alongOutsideFixed)
        Dialog_EmhDlg.setTabOrder(self.radioButton_alongOutsideFixed, self.LineEdit_Dn)
        Dialog_EmhDlg.setTabOrder(self.LineEdit_Dn, self.ComboBox_notInclued)
        Dialog_EmhDlg.setTabOrder(self.ComboBox_notInclued, self.ComboBox_notIncludedd)
        Dialog_EmhDlg.setTabOrder(self.ComboBox_notIncludedd, self.ComboBox_included)
        Dialog_EmhDlg.setTabOrder(self.ComboBox_included, self.ComboBox_includedd)
        Dialog_EmhDlg.setTabOrder(self.ComboBox_includedd, self.scrollArea)

    def retranslateUi(self, Dialog_EmhDlg):
        Dialog_EmhDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_EmhDlg", "强场发射", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "Emit_Field", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "发射体：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_EmhDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_EmhDlg", "强场发射", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "工作函数.PHI(T,X,Y,Z)= ", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_PHI.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>eV</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>Fowler-Nordheim常数.A= </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_FNA.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "1.5414e-006", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>A/m</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "Fowler-Nordheim常数.B= ", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_FNB.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "6830800000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>/mV^.5</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_EmhDlg", "发射选项", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_surface.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "沿表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randomm.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_uniform.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "均匀", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fixed.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_strictTiming.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "严格定时", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_random.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "随机分布", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_transmittingInterval.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "发射间隔：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "倍时间步长", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>偏移Dn(T,X,Y,Z)=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Dn.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p><span style=\" font-size:14pt;\">m</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randommm.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_outSurface.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "沿外表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_alongOutsideFixed.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(0, QtGui.QApplication.translate("Dialog_EmhDlg", "电子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(1, QtGui.QApplication.translate("Dialog_EmhDlg", "质子", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_generationRate.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "产生率：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_particleType.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "粒子类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "个/网格/步长", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog_EmhDlg", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notInclued.setItemText(0, QtGui.QApplication.translate("Dialog_EmhDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notIncludedd.setItemText(0, QtGui.QApplication.translate("Dialog_EmhDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>进一步限定发射区域，使不包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog_EmhDlg", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_included.setItemText(0, QtGui.QApplication.translate("Dialog_EmhDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_includedd.setItemText(0, QtGui.QApplication.translate("Dialog_EmhDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "<html><head/><body><p>进一步限定发射区域，使包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_EmhDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
