# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Area_FunctionDlg.ui'
#
# Created: Sat Jan 11 12:20:14 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_AreaFunction(object):
    def setupUi(self, Dialog_AreaFunction):
        Dialog_AreaFunction.setObjectName("Dialog_AreaFunction")
        Dialog_AreaFunction.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_AreaFunction.resize(569, 353)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_AreaFunction.sizePolicy().hasHeightForWidth())
        Dialog_AreaFunction.setSizePolicy(sizePolicy)
        Dialog_AreaFunction.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_AreaFunction.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_AreaFunction)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(Dialog_AreaFunction)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_Name = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.horizontalLayout.addWidget(self.lineEdit_Name)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_Order = QtGui.QSpinBox(self.groupBox)
        self.spinBox_Order.setObjectName("spinBox_Order")
        self.horizontalLayout.addWidget(self.spinBox_Order)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Dialog_AreaFunction)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEdit_UniformX = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_UniformX.setObjectName("lineEdit_UniformX")
        self.gridLayout.addWidget(self.lineEdit_UniformX, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.checkBox_UniformX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_UniformX.setChecked(True)
        self.checkBox_UniformX.setObjectName("checkBox_UniformX")
        self.gridLayout.addWidget(self.checkBox_UniformX, 2, 1, 1, 1)
        self.checkBox_UniformY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_UniformY.setChecked(True)
        self.checkBox_UniformY.setObjectName("checkBox_UniformY")
        self.gridLayout.addWidget(self.checkBox_UniformY, 2, 2, 1, 1)
        self.lineEdit_UniformY = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_UniformY.setObjectName("lineEdit_UniformY")
        self.gridLayout.addWidget(self.lineEdit_UniformY, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.lineEdit_UniformZ = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_UniformZ.setObjectName("lineEdit_UniformZ")
        self.gridLayout.addWidget(self.lineEdit_UniformZ, 1, 3, 1, 1)
        self.checkBox_UniformZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_UniformZ.setChecked(True)
        self.checkBox_UniformZ.setObjectName("checkBox_UniformZ")
        self.gridLayout.addWidget(self.checkBox_UniformZ, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog_AreaFunction)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.lineEdit_Point_1Y = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Point_1Y.setObjectName("lineEdit_Point_1Y")
        self.gridLayout_2.addWidget(self.lineEdit_Point_1Y, 1, 2, 1, 1)
        self.lineEdit_Point_2Y = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Point_2Y.setObjectName("lineEdit_Point_2Y")
        self.gridLayout_2.addWidget(self.lineEdit_Point_2Y, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.lineEdit_Point_2X = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Point_2X.setObjectName("lineEdit_Point_2X")
        self.gridLayout_2.addWidget(self.lineEdit_Point_2X, 2, 1, 1, 1)
        self.lineEdit_Point_1X = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Point_1X.setObjectName("lineEdit_Point_1X")
        self.gridLayout_2.addWidget(self.lineEdit_Point_1X, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_ExpressionStr = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_ExpressionStr.setObjectName("lineEdit_ExpressionStr")
        self.gridLayout_2.addWidget(self.lineEdit_ExpressionStr, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 3, 1, 1)
        self.lineEdit_Point_1Z = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Point_1Z.setObjectName("lineEdit_Point_1Z")
        self.gridLayout_2.addWidget(self.lineEdit_Point_1Z, 1, 3, 1, 1)
        self.lineEdit_Point_2Z = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Point_2Z.setObjectName("lineEdit_Point_2Z")
        self.gridLayout_2.addWidget(self.lineEdit_Point_2Z, 2, 3, 1, 1)
        self.spinBox_Precision = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_Precision.setMinimum(10)
        self.spinBox_Precision.setProperty("value", 16)
        self.spinBox_Precision.setObjectName("spinBox_Precision")
        self.gridLayout_2.addWidget(self.spinBox_Precision, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_ok = QtGui.QPushButton(Dialog_AreaFunction)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_3.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog_AreaFunction)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog_AreaFunction)
        QtCore.QMetaObject.connectSlotsByName(Dialog_AreaFunction)

    def retranslateUi(self, Dialog_AreaFunction):
        Dialog_AreaFunction.setWindowTitle(QtGui.QApplication.translate("Dialog_AreaFunction", "函数面", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_AreaFunction", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Name.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "AreaFunction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog_AreaFunction", "Uon Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformX.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformX.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformY.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformY.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformZ.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformZ.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog_AreaFunction", "Object of a Function Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Point_1Y.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Point_2Y.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Precision:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Point_2X.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Point_1X.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Point_2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Point_1:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ExpressionStr.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "x+y+z-1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Point_1Z.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Point_2Z.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog_AreaFunction", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

