# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GridDialog.ui'
#
# Created: Wed Jan 13 17:03:48 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(498, 298)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridSizeY = QtGui.QSpinBox(Dialog)
        self.gridSizeY.setMinimum(1)
        self.gridSizeY.setMaximum(999999)
        self.gridSizeY.setObjectName("gridSizeY")
        self.gridLayout.addWidget(self.gridSizeY, 5, 1, 1, 3)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.p2_x = QtGui.QDoubleSpinBox(Dialog)
        self.p2_x.setMinimum(-9999999999.0)
        self.p2_x.setMaximum(9999999999.0)
        self.p2_x.setObjectName("p2_x")
        self.gridLayout.addWidget(self.p2_x, 2, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.p1_x = QtGui.QDoubleSpinBox(Dialog)
        self.p1_x.setMinimum(-9999999999.0)
        self.p1_x.setMaximum(9999999999.0)
        self.p1_x.setProperty("value", 0.0)
        self.p1_x.setObjectName("p1_x")
        self.gridLayout.addWidget(self.p1_x, 1, 1, 1, 3)
        self.p1_y = QtGui.QDoubleSpinBox(Dialog)
        self.p1_y.setMinimum(-9999999999.0)
        self.p1_y.setMaximum(9999999999.0)
        self.p1_y.setObjectName("p1_y")
        self.gridLayout.addWidget(self.p1_y, 1, 4, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.gridSizeX = QtGui.QSpinBox(Dialog)
        self.gridSizeX.setMinimum(1)
        self.gridSizeX.setMaximum(999999)
        self.gridSizeX.setObjectName("gridSizeX")
        self.gridLayout.addWidget(self.gridSizeX, 4, 1, 1, 3)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.label_41 = QtGui.QLabel(Dialog)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 5, 0, 1, 1)
        self.p2_y = QtGui.QDoubleSpinBox(Dialog)
        self.p2_y.setMinimum(-9999999999.0)
        self.p2_y.setMaximum(9999999999.0)
        self.p2_y.setObjectName("p2_y")
        self.gridLayout.addWidget(self.p2_y, 2, 4, 1, 3)
        self.gridNum = QtGui.QSpinBox(Dialog)
        self.gridNum.setMinimum(100)
        self.gridNum.setMaximum(99999999)
        self.gridNum.setSingleStep(20)
        self.gridNum.setObjectName("gridNum")
        self.gridLayout.addWidget(self.gridNum, 3, 1, 1, 3)
        self.isShow = QtGui.QCheckBox(Dialog)
        self.isShow.setChecked(True)
        self.isShow.setObjectName("isShow")
        self.gridLayout.addWidget(self.isShow, 6, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.pb_OK = QtGui.QPushButton(Dialog)
        self.pb_OK.setObjectName("pb_OK")
        self.gridLayout_2.addWidget(self.pb_OK, 4, 0, 1, 1)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_2.addWidget(self.pb_cancel, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "背景设置", None, QtGui.QApplication.UnicodeUTF8))
        self.gridSizeY.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Point1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "网格数量：", None, QtGui.QApplication.UnicodeUTF8))
        self.p2_x.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.p1_x.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.p1_y.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.gridSizeX.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Point2：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "网格大小X：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Dialog", "网格大小Y：", None, QtGui.QApplication.UnicodeUTF8))
        self.p2_y.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.isShow.setText(QtGui.QApplication.translate("Dialog", "显示网格", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "/* Tip1：网格数量最少为100，且必须为20的倍数 */", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "/* Tip2: 坐标必须为网格大小X或网格大小Y最大值的倍数 */", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_OK.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

