# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseDialog.ui'
#
# Created: Fri May 21 14:55:19 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(496, 409)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_name = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_4.addWidget(self.lineEdit_name)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_order = QtGui.QSpinBox(self.groupBox)
        self.spinBox_order.setObjectName("spinBox_order")
        self.horizontalLayout_4.addWidget(self.spinBox_order)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 3)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_attribute = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_attribute.setObjectName("comboBox_attribute")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_attribute)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_attribute = QtGui.QVBoxLayout()
        self.verticalLayout_attribute.setObjectName("verticalLayout_attribute")
        self.verticalLayout_2.addLayout(self.verticalLayout_attribute)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_y1 = QtGui.QLabel(self.groupBox_3)
        self.label_y1.setObjectName("label_y1")
        self.gridLayout.addWidget(self.label_y1, 0, 5, 1, 1)
        self.label_z1 = QtGui.QLabel(self.groupBox_3)
        self.label_z1.setObjectName("label_z1")
        self.gridLayout.addWidget(self.label_z1, 0, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 7, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 9, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        self.label_x1 = QtGui.QLabel(self.groupBox_3)
        self.label_x1.setObjectName("label_x1")
        self.gridLayout.addWidget(self.label_x1, 0, 2, 1, 1)
        self.checkBox_midX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_midX.setObjectName("checkBox_midX")
        self.gridLayout.addWidget(self.checkBox_midX, 4, 1, 1, 3)
        self.checkBox_maxX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_maxX.setObjectName("checkBox_maxX")
        self.gridLayout.addWidget(self.checkBox_maxX, 5, 1, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.lineEdit_dx1 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dx1.setObjectName("lineEdit_dx1")
        self.gridLayout.addWidget(self.lineEdit_dx1, 1, 1, 1, 3)
        self.checkBox_minX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_minX.setObjectName("checkBox_minX")
        self.gridLayout.addWidget(self.checkBox_minX, 3, 1, 1, 3)
        self.checkBox_X = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_X.setObjectName("checkBox_X")
        self.gridLayout.addWidget(self.checkBox_X, 2, 1, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 4, 1, 1)
        self.checkBox_maxY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_maxY.setObjectName("checkBox_maxY")
        self.gridLayout.addWidget(self.checkBox_maxY, 5, 4, 1, 3)
        self.checkBox_midY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_midY.setObjectName("checkBox_midY")
        self.gridLayout.addWidget(self.checkBox_midY, 4, 4, 1, 3)
        self.lineEdit_dx3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dx3.setObjectName("lineEdit_dx3")
        self.gridLayout.addWidget(self.lineEdit_dx3, 1, 7, 1, 3)
        self.checkBox_Y = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_Y.setObjectName("checkBox_Y")
        self.gridLayout.addWidget(self.checkBox_Y, 2, 4, 1, 3)
        self.checkBox_minY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_minY.setObjectName("checkBox_minY")
        self.gridLayout.addWidget(self.checkBox_minY, 3, 4, 1, 3)
        self.checkBox_minZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_minZ.setObjectName("checkBox_minZ")
        self.gridLayout.addWidget(self.checkBox_minZ, 3, 7, 1, 3)
        self.lineEdit_dx2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_dx2.setObjectName("lineEdit_dx2")
        self.gridLayout.addWidget(self.lineEdit_dx2, 1, 4, 1, 3)
        self.checkBox_Z = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.gridLayout.addWidget(self.checkBox_Z, 2, 7, 1, 3)
        self.checkBox_maxZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_maxZ.setObjectName("checkBox_maxZ")
        self.gridLayout.addWidget(self.checkBox_maxZ, 5, 7, 1, 3)
        self.checkBox_midZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_midZ.setObjectName("checkBox_midZ")
        self.gridLayout.addWidget(self.checkBox_midZ, 4, 7, 1, 3)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_object = QtGui.QGridLayout()
        self.gridLayout_object.setObjectName("gridLayout_object")
        self.gridLayout_6.addLayout(self.gridLayout_object, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.pushButton_cancel = QtGui.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_4.addWidget(self.pushButton_cancel, 4, 0, 1, 1)
        self.pushButton_ok = QtGui.QPushButton(Dialog)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout_4.addWidget(self.pushButton_ok, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_ok, self.pushButton_cancel)
        Dialog.setTabOrder(self.pushButton_cancel, self.lineEdit_name)
        Dialog.setTabOrder(self.lineEdit_name, self.spinBox_order)
        Dialog.setTabOrder(self.spinBox_order, self.comboBox_attribute)
        Dialog.setTabOrder(self.comboBox_attribute, self.lineEdit_dx1)
        Dialog.setTabOrder(self.lineEdit_dx1, self.checkBox_X)
        Dialog.setTabOrder(self.checkBox_X, self.checkBox_minX)
        Dialog.setTabOrder(self.checkBox_minX, self.checkBox_midX)
        Dialog.setTabOrder(self.checkBox_midX, self.checkBox_maxX)
        Dialog.setTabOrder(self.checkBox_maxX, self.lineEdit_dx2)
        Dialog.setTabOrder(self.lineEdit_dx2, self.checkBox_Y)
        Dialog.setTabOrder(self.checkBox_Y, self.checkBox_minY)
        Dialog.setTabOrder(self.checkBox_minY, self.checkBox_midY)
        Dialog.setTabOrder(self.checkBox_midY, self.checkBox_maxY)
        Dialog.setTabOrder(self.checkBox_maxY, self.lineEdit_dx3)
        Dialog.setTabOrder(self.lineEdit_dx3, self.checkBox_Z)
        Dialog.setTabOrder(self.checkBox_Z, self.checkBox_minZ)
        Dialog.setTabOrder(self.checkBox_minZ, self.checkBox_midZ)
        Dialog.setTabOrder(self.checkBox_midZ, self.checkBox_maxZ)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Atrribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(0, QtGui.QApplication.translate("Dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(1, QtGui.QApplication.translate("Dialog", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(2, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(3, QtGui.QApplication.translate("Dialog", "Void", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y1.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_z1.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x1.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_midX.setText(QtGui.QApplication.translate("Dialog", "MIDMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_maxX.setText(QtGui.QApplication.translate("Dialog", "MAXMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_minX.setText(QtGui.QApplication.translate("Dialog", "MINMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_X.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_maxY.setText(QtGui.QApplication.translate("Dialog", "MAXMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_midY.setText(QtGui.QApplication.translate("Dialog", "MIDMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Y.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_minY.setText(QtGui.QApplication.translate("Dialog", "MINMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_minZ.setText(QtGui.QApplication.translate("Dialog", "MINMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Z.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_maxZ.setText(QtGui.QApplication.translate("Dialog", "MAXMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_midZ.setText(QtGui.QApplication.translate("Dialog", "MIDMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))

