# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomWidget.ui'
#
# Created: Tue Mar  2 10:03:32 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(482, 118)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.lineEdit_setEps1 = QtGui.QLineEdit(Form)
        self.lineEdit_setEps1.setObjectName("lineEdit_setEps1")
        self.gridLayout.addWidget(self.lineEdit_setEps1, 1, 3, 1, 1)
        self.lineEdit_setEps2 = QtGui.QLineEdit(Form)
        self.lineEdit_setEps2.setObjectName("lineEdit_setEps2")
        self.gridLayout.addWidget(self.lineEdit_setEps2, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.lineEdit_sigma1 = QtGui.QLineEdit(Form)
        self.lineEdit_sigma1.setObjectName("lineEdit_sigma1")
        self.gridLayout.addWidget(self.lineEdit_sigma1, 1, 1, 1, 1)
        self.comboBox_sigma = QtGui.QComboBox(Form)
        self.comboBox_sigma.setObjectName("comboBox_sigma")
        self.comboBox_sigma.addItem("")
        self.comboBox_sigma.addItem("")
        self.comboBox_sigma.addItem("")
        self.gridLayout.addWidget(self.comboBox_sigma, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_setEps = QtGui.QComboBox(Form)
        self.comboBox_setEps.setObjectName("comboBox_setEps")
        self.comboBox_setEps.addItem("")
        self.comboBox_setEps.addItem("")
        self.comboBox_setEps.addItem("")
        self.gridLayout.addWidget(self.comboBox_setEps, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_setEps3 = QtGui.QLineEdit(Form)
        self.lineEdit_setEps3.setObjectName("lineEdit_setEps3")
        self.gridLayout.addWidget(self.lineEdit_setEps3, 3, 3, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_sigma2 = QtGui.QLineEdit(Form)
        self.lineEdit_sigma2.setObjectName("lineEdit_sigma2")
        self.gridLayout.addWidget(self.lineEdit_sigma2, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.lineEdit_sigma3 = QtGui.QLineEdit(Form)
        self.lineEdit_sigma3.setObjectName("lineEdit_sigma3")
        self.gridLayout.addWidget(self.lineEdit_sigma3, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "RelativeDielectricConstant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Set EPS3:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigma.setItemText(0, QtGui.QApplication.translate("Form", "Isotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigma.setItemText(1, QtGui.QApplication.translate("Form", "Anisotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sigma.setItemText(2, QtGui.QApplication.translate("Form", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "SIGMA2:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_setEps.setItemText(0, QtGui.QApplication.translate("Form", "Isotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_setEps.setItemText(1, QtGui.QApplication.translate("Form", "Anisotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_setEps.setItemText(2, QtGui.QApplication.translate("Form", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "SIGMA1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "SIGMA3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Conductivity SIGMA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Set EPS1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Set EPS2:", None, QtGui.QApplication.UnicodeUTF8))

