# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'point.ui'
#
# Created: Mon Oct 28 16:38:36 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Modeling.Common.Tools import Completer


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(493, 323)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(9999, 9999))
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.C_label_1 = QtGui.QLabel(self.groupBox_4)
        self.C_label_1.setObjectName("C_label_1")
        self.gridLayout_2.addWidget(self.C_label_1, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_3 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.C_label_2 = QtGui.QLabel(self.groupBox_4)
        self.C_label_2.setObjectName("C_label_2")
        self.gridLayout_2.addWidget(self.C_label_2, 0, 2, 1, 1)
        self.C_label_3 = QtGui.QLabel(self.groupBox_4)
        self.C_label_3.setObjectName("C_label_3")
        self.gridLayout_2.addWidget(self.C_label_3, 0, 3, 1, 1)
        self.lineEdit = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.NUG_lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.NUG_lineEdit_3.setObjectName("NUG_lineEdit_3")
        self.gridLayout.addWidget(self.NUG_lineEdit_3, 1, 3, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 3, 1, 1)
        self.NUG_label_1 = QtGui.QLabel(self.groupBox_3)
        self.NUG_label_1.setObjectName("NUG_label_1")
        self.gridLayout.addWidget(self.NUG_label_1, 0, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 2, 1, 1)
        self.NUG_label_2 = QtGui.QLabel(self.groupBox_3)
        self.NUG_label_2.setObjectName("NUG_label_2")
        self.gridLayout.addWidget(self.NUG_label_2, 0, 2, 1, 1)
        self.NUG_label_3 = QtGui.QLabel(self.groupBox_3)
        self.NUG_label_3.setObjectName("NUG_label_3")
        self.gridLayout.addWidget(self.NUG_label_3, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.NUG_lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.NUG_lineEdit_2.setObjectName("NUG_lineEdit_2")
        self.gridLayout.addWidget(self.NUG_lineEdit_2, 1, 2, 1, 1)
        self.NUG_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.NUG_lineEdit.setObjectName("NUG_lineEdit")
        self.gridLayout.addWidget(self.NUG_lineEdit, 1, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 3)
        self.gridLayout.setRowStretch(2, 3)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Base_label_1 = QtGui.QLabel(self.groupBox)
        self.Base_label_1.setObjectName("Base_label_1")
        self.horizontalLayout.addWidget(self.Base_label_1)
        self.Base_lineEdit_1 = QtGui.QLineEdit(self.groupBox)
        self.Base_lineEdit_1.setObjectName("Base_lineEdit_1")
        self.horizontalLayout.addWidget(self.Base_lineEdit_1)
        self.Base_label_2 = QtGui.QLabel(self.groupBox)
        self.Base_label_2.setObjectName("Base_label_2")
        self.horizontalLayout.addWidget(self.Base_label_2)
        self.Base_lineEdit_2 = QtGui.QSpinBox(self.groupBox)
        self.Base_lineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.Base_lineEdit_2.setObjectName("Base_lineEdit_2")
        self.horizontalLayout.addWidget(self.Base_lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.OK_pushButton = QtGui.QPushButton(Dialog)
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout_3.addWidget(self.OK_pushButton)
        self.Cancel_pushButton = QtGui.QPushButton(Dialog)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.horizontalLayout_3.addWidget(self.Cancel_pushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Base_lineEdit_1, self.Base_lineEdit_2)
        Dialog.setTabOrder(self.Base_lineEdit_2, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.OK_pushButton)
        Dialog.setTabOrder(self.OK_pushButton, self.Cancel_pushButton)
        Dialog.setTabOrder(self.Cancel_pushButton, self.NUG_lineEdit)
        Dialog.setTabOrder(self.NUG_lineEdit, self.NUG_lineEdit_2)
        Dialog.setTabOrder(self.NUG_lineEdit_2, self.NUG_lineEdit_3)
        Dialog.setTabOrder(self.NUG_lineEdit_3, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.checkBox_2)
        Dialog.setTabOrder(self.checkBox_2, self.checkBox_3)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Object of a Cylinder", None, QtGui.QApplication.UnicodeUTF8))
        self.C_label_1.setText(QtGui.QApplication.translate("Dialog", "        X", None, QtGui.QApplication.UnicodeUTF8))
        self.C_label_2.setText(QtGui.QApplication.translate("Dialog", "        Y", None, QtGui.QApplication.UnicodeUTF8))
        self.C_label_3.setText(QtGui.QApplication.translate("Dialog", "          Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Point_1:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.NUG_label_1.setText(QtGui.QApplication.translate("Dialog", "          X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.NUG_label_2.setText(QtGui.QApplication.translate("Dialog", "          Y ", None, QtGui.QApplication.UnicodeUTF8))
        self.NUG_label_3.setText(QtGui.QApplication.translate("Dialog", "          Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.Base_label_1.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.Base_label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.OK_pushButton.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel_pushButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

