# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecdDialog.ui'
#
# Created: Sun Nov 22 20:57:11 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 739)
        self.gridLayout_10 = QtGui.QGridLayout(Dialog)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 421, 739))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.LineEdit_Name = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_12.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_12.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_12.addWidget(self.ComboBox_Shadow)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 1)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.groupBox_9 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_energyDistribution = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_energyDistribution.setText("")
        self.checkBox_energyDistribution.setObjectName("checkBox_energyDistribution")
        self.horizontalLayout_4.addWidget(self.checkBox_energyDistribution)
        self.label_10 = QtGui.QLabel(self.groupBox_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_ED = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_ED.setEnabled(False)
        self.lineEdit_ED.setObjectName("lineEdit_ED")
        self.horizontalLayout_4.addWidget(self.lineEdit_ED)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 4)
        self.label = QtGui.QLabel(self.groupBox_9)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox_9)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_angularDistribution = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_angularDistribution.setText("")
        self.checkBox_angularDistribution.setObjectName("checkBox_angularDistribution")
        self.horizontalLayout.addWidget(self.checkBox_angularDistribution)
        self.label_9 = QtGui.QLabel(self.groupBox_9)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit_AD = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_AD.setEnabled(False)
        self.lineEdit_AD.setObjectName("lineEdit_AD")
        self.horizontalLayout.addWidget(self.lineEdit_AD)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_weightCoefficient = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_weightCoefficient.setText("")
        self.checkBox_weightCoefficient.setObjectName("checkBox_weightCoefficient")
        self.horizontalLayout_5.addWidget(self.checkBox_weightCoefficient)
        self.label_11 = QtGui.QLabel(self.groupBox_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lineEdit_WF = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_WF.setEnabled(False)
        self.lineEdit_WF.setObjectName("lineEdit_WF")
        self.horizontalLayout_5.addWidget(self.lineEdit_WF)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_energyMin = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_energyMin.setEnabled(False)
        self.lineEdit_energyMin.setObjectName("lineEdit_energyMin")
        self.horizontalLayout_2.addWidget(self.lineEdit_energyMin)
        self.label_3 = QtGui.QLabel(self.groupBox_9)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_7 = QtGui.QLabel(self.groupBox_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_energyMax = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_energyMax.setEnabled(False)
        self.lineEdit_energyMax.setObjectName("lineEdit_energyMax")
        self.horizontalLayout_2.addWidget(self.lineEdit_energyMax)
        self.label_21 = QtGui.QLabel(self.groupBox_9)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 4)
        self.lineEdit_energy = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_energy.setObjectName("lineEdit_energy")
        self.gridLayout.addWidget(self.lineEdit_energy, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_9)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.lineEdit_maxNum = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_maxNum.setObjectName("lineEdit_maxNum")
        self.gridLayout.addWidget(self.lineEdit_maxNum, 1, 2, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_surface = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_surface.setObjectName("checkBox_surface")
        self.gridLayout_6.addWidget(self.checkBox_surface, 0, 0, 1, 1)
        self.radioButton_randomm = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_randomm.setEnabled(False)
        self.radioButton_randomm.setChecked(True)
        self.radioButton_randomm.setObjectName("radioButton_randomm")
        self.gridLayout_6.addWidget(self.radioButton_randomm, 0, 1, 1, 1)
        self.radioButton_uniform = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_uniform.setEnabled(False)
        self.radioButton_uniform.setObjectName("radioButton_uniform")
        self.gridLayout_6.addWidget(self.radioButton_uniform, 0, 2, 1, 1)
        self.radioButton_fixed = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_fixed.setEnabled(False)
        self.radioButton_fixed.setObjectName("radioButton_fixed")
        self.gridLayout_6.addWidget(self.radioButton_fixed, 0, 3, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_strictTiming = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_strictTiming.setEnabled(False)
        self.radioButton_strictTiming.setObjectName("radioButton_strictTiming")
        self.gridLayout_7.addWidget(self.radioButton_strictTiming, 0, 2, 1, 1)
        self.spinBox_timesStep = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_timesStep.setEnabled(False)
        self.spinBox_timesStep.setObjectName("spinBox_timesStep")
        self.gridLayout_7.addWidget(self.spinBox_timesStep, 0, 3, 1, 1)
        self.radioButton_random = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_random.setEnabled(False)
        self.radioButton_random.setChecked(True)
        self.radioButton_random.setObjectName("radioButton_random")
        self.gridLayout_7.addWidget(self.radioButton_random, 0, 1, 1, 1)
        self.checkBox_transmittingInterval = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_transmittingInterval.setObjectName("checkBox_transmittingInterval")
        self.gridLayout_7.addWidget(self.checkBox_transmittingInterval, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 4, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.LineEdit_Dn = QtGui.QLineEdit(self.groupBox_2)
        self.LineEdit_Dn.setEnabled(False)
        self.LineEdit_Dn.setObjectName("LineEdit_Dn")
        self.horizontalLayout_8.addWidget(self.LineEdit_Dn)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 8, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_randommm = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_randommm.setEnabled(False)
        self.radioButton_randommm.setChecked(True)
        self.radioButton_randommm.setObjectName("radioButton_randommm")
        self.gridLayout_2.addWidget(self.radioButton_randommm, 0, 1, 1, 1)
        self.radioButton_alongOutsideFixed = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_alongOutsideFixed.setEnabled(False)
        self.radioButton_alongOutsideFixed.setObjectName("radioButton_alongOutsideFixed")
        self.gridLayout_2.addWidget(self.radioButton_alongOutsideFixed, 0, 2, 1, 1)
        self.checkBox_outSurface = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_outSurface.setObjectName("checkBox_outSurface")
        self.gridLayout_2.addWidget(self.checkBox_outSurface, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.spinBox_generationRate = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_generationRate.setEnabled(False)
        self.spinBox_generationRate.setObjectName("spinBox_generationRate")
        self.gridLayout_8.addWidget(self.spinBox_generationRate, 0, 3, 1, 1)
        self.ComboBox_particleType = StyledComboBox(self.groupBox_8)
        self.ComboBox_particleType.setEnabled(False)
        self.ComboBox_particleType.setObjectName("ComboBox_particleType")
        self.ComboBox_particleType.addItem("")
        self.ComboBox_particleType.addItem("")
        self.gridLayout_8.addWidget(self.ComboBox_particleType, 0, 1, 1, 1)
        self.checkBox_generationRate = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_generationRate.setObjectName("checkBox_generationRate")
        self.gridLayout_8.addWidget(self.checkBox_generationRate, 0, 2, 1, 1)
        self.checkBox_particleType = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_particleType.setObjectName("checkBox_particleType")
        self.gridLayout_8.addWidget(self.checkBox_particleType, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_8)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 4, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 7, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.ComboBox_notInclued = StyledComboBox(self.groupBox_3)
        self.ComboBox_notInclued.setObjectName("ComboBox_notInclued")
        self.ComboBox_notInclued.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_notInclued)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.ComboBox_notIncludedd = StyledComboBox(self.groupBox_3)
        self.ComboBox_notIncludedd.setObjectName("ComboBox_notIncludedd")
        self.ComboBox_notIncludedd.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_notIncludedd)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.ComboBox_included = StyledComboBox(self.groupBox_4)
        self.ComboBox_included.setObjectName("ComboBox_included")
        self.ComboBox_included.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_included)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.ComboBox_includedd = StyledComboBox(self.groupBox_4)
        self.ComboBox_includedd.setObjectName("ComboBox_includedd")
        self.ComboBox_includedd.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_includedd)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 3, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_ok = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_3.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_3.addWidget(self.pb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog", "EmSE", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog", "发射体：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Dialog", "二次发射", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "能量分布", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "最大发射系数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "最大发射系数所对应的能量：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "角分布  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "权重系数", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_WF.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "   最小能量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "eV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "最大能量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "eV", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_energy.setText(QtGui.QApplication.translate("Dialog", "400", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "eV", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_maxNum.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "发射选项", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_surface.setText(QtGui.QApplication.translate("Dialog", "沿表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randomm.setText(QtGui.QApplication.translate("Dialog", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_uniform.setText(QtGui.QApplication.translate("Dialog", "均匀", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fixed.setText(QtGui.QApplication.translate("Dialog", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_strictTiming.setText(QtGui.QApplication.translate("Dialog", "严格定时", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_random.setText(QtGui.QApplication.translate("Dialog", "随机分布", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_transmittingInterval.setText(QtGui.QApplication.translate("Dialog", "发射间隔：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "倍时间步长", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>偏移Dn(T,X,Y,Z)=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Dn.setText(QtGui.QApplication.translate("Dialog", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">m</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randommm.setText(QtGui.QApplication.translate("Dialog", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_alongOutsideFixed.setText(QtGui.QApplication.translate("Dialog", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_outSurface.setText(QtGui.QApplication.translate("Dialog", "沿外表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(0, QtGui.QApplication.translate("Dialog", "电子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(1, QtGui.QApplication.translate("Dialog", "质子", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_generationRate.setText(QtGui.QApplication.translate("Dialog", "产生率：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_particleType.setText(QtGui.QApplication.translate("Dialog", "粒子类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "个/网格/步长", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notInclued.setItemText(0, QtGui.QApplication.translate("Dialog", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notIncludedd.setItemText(0, QtGui.QApplication.translate("Dialog", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>进一步限定发射区域，使不包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>进一步限定发射区域，使包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_included.setItemText(0, QtGui.QApplication.translate("Dialog", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_includedd.setItemText(0, QtGui.QApplication.translate("Dialog", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
