# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GasOutDialog.ui'
#
# Created: Sun Mar 26 17:57:19 2023
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_GasOutDlg(object):
    def setupUi(self, Dialog_GasOutDlg):
        Dialog_GasOutDlg.setObjectName("Dialog_GasOutDlg")
        Dialog_GasOutDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_GasOutDlg.resize(392, 225)
        Dialog_GasOutDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_GasOutDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget = QtGui.QWidget(Dialog_GasOutDlg)
        self.widget.setGeometry(QtCore.QRect(10, 10, 371, 205))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Label_Name = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.gridLayout_2.addWidget(self.Label_Name, 0, 0, 1, 1)
        self.LineEdit_Name = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.gridLayout_2.addWidget(self.LineEdit_Name, 0, 1, 1, 1)
        self.Label_Shadow = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.gridLayout_2.addWidget(self.Label_Shadow, 0, 2, 1, 1)
        self.ComboBox_Vol = QtGui.QComboBox(self.widget)
        self.ComboBox_Vol.setObjectName("ComboBox_Vol")
        self.ComboBox_Vol.addItem("")
        self.gridLayout_2.addWidget(self.ComboBox_Vol, 0, 3, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.LineEdit_density = QtGui.QLineEdit(self.widget)
        self.LineEdit_density.setEnabled(True)
        self.LineEdit_density.setObjectName("LineEdit_density")
        self.gridLayout.addWidget(self.LineEdit_density, 0, 1, 1, 5)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.LineEdit_area = QtGui.QLineEdit(self.widget)
        self.LineEdit_area.setEnabled(True)
        self.LineEdit_area.setObjectName("LineEdit_area")
        self.gridLayout.addWidget(self.LineEdit_area, 1, 1, 1, 5)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.LineEdit_threshold = QtGui.QLineEdit(self.widget)
        self.LineEdit_threshold.setEnabled(True)
        self.LineEdit_threshold.setObjectName("LineEdit_threshold")
        self.gridLayout.addWidget(self.LineEdit_threshold, 2, 1, 1, 5)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 6, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 2)
        self.LineEdit_grid = QtGui.QLineEdit(self.widget)
        self.LineEdit_grid.setEnabled(True)
        self.LineEdit_grid.setObjectName("LineEdit_grid")
        self.gridLayout.addWidget(self.LineEdit_grid, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 4, 1, 1)
        self.ComboBox_Current = StyledComboBox(self.widget)
        self.ComboBox_Current.setObjectName("ComboBox_Current")
        self.ComboBox_Current.addItem("")
        self.ComboBox_Current.addItem("")
        self.ComboBox_Current.addItem("")
        self.gridLayout.addWidget(self.ComboBox_Current, 3, 5, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 4)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.radioButton_opposite = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_opposite.setChecked(True)
        self.radioButton_opposite.setObjectName("radioButton_opposite")
        self.horizontalLayout_2.addWidget(self.radioButton_opposite)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.radioButton_forward = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_forward.setObjectName("radioButton_forward")
        self.horizontalLayout_2.addWidget(self.radioButton_forward)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 4)
        self.pb_ok = QtGui.QPushButton(self.widget)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout_2.addWidget(self.pb_ok, 3, 0, 1, 2)
        self.pb_cancel = QtGui.QPushButton(self.widget)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_2.addWidget(self.pb_cancel, 3, 2, 1, 2)

        self.retranslateUi(Dialog_GasOutDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_GasOutDlg)
        Dialog_GasOutDlg.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog_GasOutDlg.setTabOrder(self.pb_cancel, self.LineEdit_Name)
        Dialog_GasOutDlg.setTabOrder(self.LineEdit_Name, self.ComboBox_Vol)
        Dialog_GasOutDlg.setTabOrder(self.ComboBox_Vol, self.ComboBox_Current)
        Dialog_GasOutDlg.setTabOrder(self.ComboBox_Current, self.LineEdit_density)

    def retranslateUi(self, Dialog_GasOutDlg):
        Dialog_GasOutDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_GasOutDlg", "气体解吸附", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "Gas_Out", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "解吸附体：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vol.setItemText(0, QtGui.QApplication.translate("Dialog_GasOutDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "初始吸附面密度：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_density.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "1E19", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "个/m^2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "解吸附截面：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_area.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "1E-19", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "m^2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "解吸附阈值：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_threshold.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "气体填充表面网格数：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_grid.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "个", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Current.setItemText(0, QtGui.QApplication.translate("Dialog_GasOutDlg", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Current.setItemText(1, QtGui.QApplication.translate("Dialog_GasOutDlg", "X2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Current.setItemText(2, QtGui.QApplication.translate("Dialog_GasOutDlg", "X3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_opposite.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "反向", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_forward.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "正向", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_GasOutDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
