# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PhasSpaceDialog.ui'
#
# Created: Sat Nov 28 14:54:35 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(662, 195)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout.addWidget(self.pb_cancel, 7, 3, 1, 2)
        self.le_phase = QtGui.QLineEdit(Dialog)
        self.le_phase.setEnabled(False)
        self.le_phase.setObjectName("le_phase")
        self.gridLayout.addWidget(self.le_phase, 6, 2, 1, 1)
        self.ComboBox_Vertical = QtGui.QComboBox(Dialog)
        self.ComboBox_Vertical.setObjectName("ComboBox_Vertical")
        self.gridLayout.addWidget(self.ComboBox_Vertical, 3, 4, 1, 1)
        self.le_thick2 = QtGui.QLineEdit(Dialog)
        self.le_thick2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_thick2.sizePolicy().hasHeightForWidth())
        self.le_thick2.setSizePolicy(sizePolicy)
        self.le_thick2.setObjectName("le_thick2")
        self.gridLayout.addWidget(self.le_thick2, 5, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.ComboBox_Observation_particle = QtGui.QComboBox(Dialog)
        self.ComboBox_Observation_particle.setObjectName("ComboBox_Observation_particle")
        self.ComboBox_Observation_particle.addItem("")
        self.ComboBox_Observation_particle.addItem("")
        self.ComboBox_Observation_particle.addItem("")
        self.gridLayout.addWidget(self.ComboBox_Observation_particle, 1, 2, 1, 1)
        self.Label_Name = QtGui.QLabel(Dialog)
        self.Label_Name.setObjectName("Label_Name")
        self.gridLayout.addWidget(self.Label_Name, 0, 0, 1, 1)
        self.ComboBox_Horizon = QtGui.QComboBox(Dialog)
        self.ComboBox_Horizon.setObjectName("ComboBox_Horizon")
        self.gridLayout.addWidget(self.ComboBox_Horizon, 3, 2, 1, 1)
        self.le_thick1 = QtGui.QLineEdit(Dialog)
        self.le_thick1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_thick1.sizePolicy().hasHeightForWidth())
        self.le_thick1.setSizePolicy(sizePolicy)
        self.le_thick1.setObjectName("le_thick1")
        self.gridLayout.addWidget(self.le_thick1, 5, 3, 1, 1)
        self.checkBox_thick = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_thick.sizePolicy().hasHeightForWidth())
        self.checkBox_thick.setSizePolicy(sizePolicy)
        self.checkBox_thick.setObjectName("checkBox_thick")
        self.gridLayout.addWidget(self.checkBox_thick, 5, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.checkBox_suffix = QtGui.QCheckBox(Dialog)
        self.checkBox_suffix.setObjectName("checkBox_suffix")
        self.gridLayout.addWidget(self.checkBox_suffix, 6, 0, 1, 1)
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout.addWidget(self.pb_ok, 7, 0, 1, 3)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
        self.ComboBox_timer = QtGui.QComboBox(Dialog)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.gridLayout.addWidget(self.ComboBox_timer, 1, 4, 1, 1)
        self.le_name = QtGui.QLineEdit(Dialog)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 0, 2, 1, 1)
        self.ComboBox_thick = QtGui.QComboBox(Dialog)
        self.ComboBox_thick.setObjectName("ComboBox_thick")
        self.gridLayout.addWidget(self.ComboBox_thick, 5, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.le_name)
        Dialog.setTabOrder(self.le_name, self.ComboBox_Observation_particle)
        Dialog.setTabOrder(self.ComboBox_Observation_particle, self.ComboBox_timer)
        Dialog.setTabOrder(self.ComboBox_timer, self.ComboBox_Horizon)
        Dialog.setTabOrder(self.ComboBox_Horizon, self.ComboBox_Vertical)
        Dialog.setTabOrder(self.ComboBox_Vertical, self.checkBox_thick)
        Dialog.setTabOrder(self.checkBox_thick, self.le_thick1)
        Dialog.setTabOrder(self.le_thick1, self.le_thick2)
        Dialog.setTabOrder(self.le_thick2, self.checkBox_suffix)
        Dialog.setTabOrder(self.checkBox_suffix, self.le_phase)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "粒子相空间观测", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.le_phase.setText(QtGui.QApplication.translate("Dialog", "phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.le_thick2.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "横轴显示：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "观测粒子：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Observation_particle.setItemText(0, QtGui.QApplication.translate("Dialog", "全部", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Observation_particle.setItemText(1, QtGui.QApplication.translate("Dialog", "电子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Observation_particle.setItemText(2, QtGui.QApplication.translate("Dialog", "质子", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_thick1.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_thick.setText(QtGui.QApplication.translate("Dialog", "显示厚度：", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_suffix.setText(QtGui.QApplication.translate("Dialog", "后缀：", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "纵轴显示：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.le_name.setText(QtGui.QApplication.translate("Dialog", "PhasSpace", None, QtGui.QApplication.UnicodeUTF8))

