# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArrayDialog.ui'
#
# Created: Fri May 21 09:37:25 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_Vol_Array(object):
    def setupUi(self, Dialog_Vol_Array):
        Dialog_Vol_Array.setObjectName("Dialog_Vol_Array")
        Dialog_Vol_Array.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_Vol_Array.resize(702, 567)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Vol_Array.sizePolicy().hasHeightForWidth())
        Dialog_Vol_Array.setSizePolicy(sizePolicy)
        Dialog_Vol_Array.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_Vol_Array.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_3 = QtGui.QGridLayout(Dialog_Vol_Array)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_type = QtGui.QHBoxLayout()
        self.horizontalLayout_type.setSpacing(5)
        self.horizontalLayout_type.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_type.setObjectName("horizontalLayout_type")
        self.label = QtGui.QLabel(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_type.addWidget(self.label)
        self.comboBox_type = StyledComboBox(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type.sizePolicy().hasHeightForWidth())
        self.comboBox_type.setSizePolicy(sizePolicy)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_type.addWidget(self.comboBox_type)
        self.label_2 = QtGui.QLabel(Dialog_Vol_Array)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_type.addWidget(self.label_2)
        self.spinBox_order = QtGui.QSpinBox(Dialog_Vol_Array)
        self.spinBox_order.setObjectName("spinBox_order")
        self.horizontalLayout_type.addWidget(self.spinBox_order)
        self.gridLayout_3.addLayout(self.horizontalLayout_type, 0, 0, 1, 1)
        self.horizontalLayout_name = QtGui.QHBoxLayout()
        self.horizontalLayout_name.setObjectName("horizontalLayout_name")
        self.Label_Name_2 = QtGui.QLabel(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_name.addWidget(self.Label_Name_2)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_name.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_name.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow_Attribute = StyledComboBox(Dialog_Vol_Array)
        self.ComboBox_Shadow_Attribute.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow_Attribute.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow_Attribute.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow_Attribute.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow_Attribute.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow_Attribute.setEditable(False)
        self.ComboBox_Shadow_Attribute.setObjectName("ComboBox_Shadow_Attribute")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.horizontalLayout_name.addWidget(self.ComboBox_Shadow_Attribute)
        self.gridLayout_3.addLayout(self.horizontalLayout_name, 1, 0, 1, 1)
        self.groupBox_main = QtGui.QGroupBox(Dialog_Vol_Array)
        self.groupBox_main.setObjectName("groupBox_main")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_main)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_main)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_start_i = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_start_i.setObjectName("lineEdit_start_i")
        self.horizontalLayout.addWidget(self.lineEdit_start_i)
        self.label_7 = QtGui.QLabel(self.groupBox_main)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEdit_end_i = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_end_i.setObjectName("lineEdit_end_i")
        self.horizontalLayout.addWidget(self.lineEdit_end_i)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.groupBox_main)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_X0 = QtGui.QLabel(self.tab_8)
        self.label_X0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X0.setObjectName("label_X0")
        self.gridLayout_6.addWidget(self.label_X0, 0, 1, 1, 1)
        self.label_Y0 = QtGui.QLabel(self.tab_8)
        self.label_Y0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y0.setObjectName("label_Y0")
        self.gridLayout_6.addWidget(self.label_Y0, 0, 2, 1, 1)
        self.label_Z0 = QtGui.QLabel(self.tab_8)
        self.label_Z0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z0.setObjectName("label_Z0")
        self.gridLayout_6.addWidget(self.label_Z0, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_8)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_Conformal_Ptn1X = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_Conformal_Ptn1X.setObjectName("lineEdit_Conformal_Ptn1X")
        self.gridLayout_6.addWidget(self.lineEdit_Conformal_Ptn1X, 1, 1, 1, 1)
        self.lineEdit_Conformal_Ptn1Y = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_Conformal_Ptn1Y.setObjectName("lineEdit_Conformal_Ptn1Y")
        self.gridLayout_6.addWidget(self.lineEdit_Conformal_Ptn1Y, 1, 2, 1, 1)
        self.lineEdit_Conformal_Ptn1Z = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_Conformal_Ptn1Z.setObjectName("lineEdit_Conformal_Ptn1Z")
        self.gridLayout_6.addWidget(self.lineEdit_Conformal_Ptn1Z, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_Conformal_Ptn2X = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_Conformal_Ptn2X.setObjectName("lineEdit_Conformal_Ptn2X")
        self.gridLayout_6.addWidget(self.lineEdit_Conformal_Ptn2X, 2, 1, 1, 1)
        self.lineEdit_Conformal_Ptn2Y = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_Conformal_Ptn2Y.setObjectName("lineEdit_Conformal_Ptn2Y")
        self.gridLayout_6.addWidget(self.lineEdit_Conformal_Ptn2Y, 2, 2, 1, 1)
        self.lineEdit_Conformal_Ptn2Z = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_Conformal_Ptn2Z.setObjectName("lineEdit_Conformal_Ptn2Z")
        self.gridLayout_6.addWidget(self.lineEdit_Conformal_Ptn2Z, 2, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_Annular_Ptn2X = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn2X.setObjectName("lineEdit_Annular_Ptn2X")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn2X, 2, 1, 1, 1)
        self.lineEdit_Annular_Ptn2Y = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn2Y.setObjectName("lineEdit_Annular_Ptn2Y")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn2Y, 2, 2, 1, 1)
        self.lineEdit_Annular_Ptn2Z = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn2Z.setObjectName("lineEdit_Annular_Ptn2Z")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn2Z, 2, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 3, 0, 1, 1)
        self.lineEdit_Annular_RadInner = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_RadInner.setObjectName("lineEdit_Annular_RadInner")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_RadInner, 3, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 4, 0, 1, 1)
        self.lineEdit_Annular_Ptn1Z = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn1Z.setObjectName("lineEdit_Annular_Ptn1Z")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn1Z, 1, 3, 1, 1)
        self.label_Z1 = QtGui.QLabel(self.tab)
        self.label_Z1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z1.setObjectName("label_Z1")
        self.gridLayout_7.addWidget(self.label_Z1, 0, 3, 1, 1)
        self.lineEdit_Annular_Ptn1Y = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn1Y.setObjectName("lineEdit_Annular_Ptn1Y")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn1Y, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_Y1 = QtGui.QLabel(self.tab)
        self.label_Y1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y1.setObjectName("label_Y1")
        self.gridLayout_7.addWidget(self.label_Y1, 0, 2, 1, 1)
        self.lineEdit_Annular_Ptn1X = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn1X.setObjectName("lineEdit_Annular_Ptn1X")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn1X, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.lineEdit_Annular_RadOuter = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_RadOuter.setObjectName("lineEdit_Annular_RadOuter")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_RadOuter, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 97, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 5, 1, 1, 1)
        self.label_X1 = QtGui.QLabel(self.tab)
        self.label_X1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X1.setObjectName("label_X1")
        self.gridLayout_7.addWidget(self.label_X1, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_X2 = QtGui.QLabel(self.tab_4)
        self.label_X2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X2.setObjectName("label_X2")
        self.gridLayout_4.addWidget(self.label_X2, 0, 1, 1, 1)
        self.label_Y2 = QtGui.QLabel(self.tab_4)
        self.label_Y2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y2.setObjectName("label_Y2")
        self.gridLayout_4.addWidget(self.label_Y2, 0, 2, 1, 1)
        self.label_Z2 = QtGui.QLabel(self.tab_4)
        self.label_Z2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z2.setObjectName("label_Z2")
        self.gridLayout_4.addWidget(self.label_Z2, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit_Cylinder_Ptn1X = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Ptn1X.setObjectName("lineEdit_Cylinder_Ptn1X")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Ptn1X, 1, 1, 1, 1)
        self.lineEdit_Cylinder_Ptn1Y = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Ptn1Y.setObjectName("lineEdit_Cylinder_Ptn1Y")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Ptn1Y, 1, 2, 1, 1)
        self.lineEdit_Cylinder_Ptn1Z = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Ptn1Z.setObjectName("lineEdit_Cylinder_Ptn1Z")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Ptn1Z, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_Cylinder_Ptn2X = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Ptn2X.setObjectName("lineEdit_Cylinder_Ptn2X")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Ptn2X, 2, 1, 1, 1)
        self.lineEdit_Cylinder_Ptn2Y = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Ptn2Y.setObjectName("lineEdit_Cylinder_Ptn2Y")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Ptn2Y, 2, 2, 1, 1)
        self.lineEdit_Cylinder_Ptn2Z = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Ptn2Z.setObjectName("lineEdit_Cylinder_Ptn2Z")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Ptn2Z, 2, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit_Cylinder_Rad = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_Cylinder_Rad.setObjectName("lineEdit_Cylinder_Rad")
        self.gridLayout_4.addWidget(self.lineEdit_Cylinder_Rad, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 125, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 6, 0, 1, 1)
        self.lineEdit_Cone_RadUp = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_RadUp.setObjectName("lineEdit_Cone_RadUp")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_RadUp, 6, 1, 1, 2)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 3, 0, 1, 1)
        self.lineEdit_Cone_Ptn1X = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_Ptn1X.setObjectName("lineEdit_Cone_Ptn1X")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_Ptn1X, 3, 1, 1, 2)
        self.lineEdit_Cone_Ptn1Y = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_Ptn1Y.setObjectName("lineEdit_Cone_Ptn1Y")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_Ptn1Y, 3, 3, 1, 1)
        self.lineEdit_Cone_Ptn1Z = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_Ptn1Z.setObjectName("lineEdit_Cone_Ptn1Z")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_Ptn1Z, 3, 4, 1, 1)
        self.lineEdit_Cone_Ptn2Z = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_Ptn2Z.setObjectName("lineEdit_Cone_Ptn2Z")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_Ptn2Z, 4, 4, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 4, 0, 1, 1)
        self.lineEdit_Cone_Ptn2X = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_Ptn2X.setObjectName("lineEdit_Cone_Ptn2X")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_Ptn2X, 4, 1, 1, 2)
        self.lineEdit_Cone_Ptn2Y = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_Ptn2Y.setObjectName("lineEdit_Cone_Ptn2Y")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_Ptn2Y, 4, 3, 1, 1)
        self.lineEdit_Cone_RadBott = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_Cone_RadBott.setObjectName("lineEdit_Cone_RadBott")
        self.gridLayout_9.addWidget(self.lineEdit_Cone_RadBott, 5, 1, 1, 2)
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 5, 0, 1, 1)
        self.label_Y3 = QtGui.QLabel(self.tab_3)
        self.label_Y3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y3.setObjectName("label_Y3")
        self.gridLayout_9.addWidget(self.label_Y3, 0, 3, 1, 1)
        self.label_Z3 = QtGui.QLabel(self.tab_3)
        self.label_Z3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z3.setObjectName("label_Z3")
        self.gridLayout_9.addWidget(self.label_Z3, 0, 4, 1, 1)
        self.label_X3 = QtGui.QLabel(self.tab_3)
        self.label_X3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X3.setObjectName("label_X3")
        self.gridLayout_9.addWidget(self.label_X3, 0, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 110, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 8, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 54, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_Spherical_Ptn1X = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_Spherical_Ptn1X.setGeometry(QtCore.QRect(60, 30, 189, 20))
        self.lineEdit_Spherical_Ptn1X.setObjectName("lineEdit_Spherical_Ptn1X")
        self.lineEdit_Spherical_Ptn1Y = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_Spherical_Ptn1Y.setGeometry(QtCore.QRect(250, 30, 190, 20))
        self.lineEdit_Spherical_Ptn1Y.setObjectName("lineEdit_Spherical_Ptn1Y")
        self.lineEdit_Spherical_Ptn1Z = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_Spherical_Ptn1Z.setGeometry(QtCore.QRect(440, 30, 189, 20))
        self.lineEdit_Spherical_Ptn1Z.setObjectName("lineEdit_Spherical_Ptn1Z")
        self.lineEdit_Spherical_Radius_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_Spherical_Radius_3.setGeometry(QtCore.QRect(60, 60, 189, 20))
        self.lineEdit_Spherical_Radius_3.setObjectName("lineEdit_Spherical_Radius_3")
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 54, 20))
        self.label_10.setObjectName("label_10")
        self.label_X4 = QtGui.QLabel(self.tab_2)
        self.label_X4.setGeometry(QtCore.QRect(80, 10, 133, 12))
        self.label_X4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X4.setObjectName("label_X4")
        self.label_Y4 = QtGui.QLabel(self.tab_2)
        self.label_Y4.setGeometry(QtCore.QRect(280, 10, 133, 12))
        self.label_Y4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y4.setObjectName("label_Y4")
        self.label_Z4 = QtGui.QLabel(self.tab_2)
        self.label_Z4.setGeometry(QtCore.QRect(470, 10, 133, 12))
        self.label_Z4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z4.setObjectName("label_Z4")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_main, 2, 0, 1, 1)
        self.groupBox_NonUniform = QtGui.QGroupBox(Dialog_Vol_Array)
        self.groupBox_NonUniform.setObjectName("groupBox_NonUniform")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_NonUniform)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_UniformY = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformY.setChecked(True)
        self.checkBox_UniformY.setObjectName("checkBox_UniformY")
        self.gridLayout.addWidget(self.checkBox_UniformY, 0, 1, 1, 1)
        self.checkBox_UniformZ = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformZ.setChecked(True)
        self.checkBox_UniformZ.setObjectName("checkBox_UniformZ")
        self.gridLayout.addWidget(self.checkBox_UniformZ, 0, 2, 1, 1)
        self.checkBox_UniformX = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformX.setChecked(True)
        self.checkBox_UniformX.setObjectName("checkBox_UniformX")
        self.gridLayout.addWidget(self.checkBox_UniformX, 0, 0, 1, 1)
        self.lineEdit_UniformX = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformX.setObjectName("lineEdit_UniformX")
        self.gridLayout.addWidget(self.lineEdit_UniformX, 1, 0, 1, 1)
        self.lineEdit_UniformY = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformY.setObjectName("lineEdit_UniformY")
        self.gridLayout.addWidget(self.lineEdit_UniformY, 1, 1, 1, 1)
        self.lineEdit_UniformZ = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformZ.setObjectName("lineEdit_UniformZ")
        self.gridLayout.addWidget(self.lineEdit_UniformZ, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_NonUniform, 3, 0, 1, 1)
        self.horizontalLayout_okAndCancel = QtGui.QHBoxLayout()
        self.horizontalLayout_okAndCancel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_okAndCancel.setObjectName("horizontalLayout_okAndCancel")
        self.pushButton_ok = QtGui.QPushButton(Dialog_Vol_Array)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog_Vol_Array)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout_okAndCancel, 4, 0, 1, 1)

        self.retranslateUi(Dialog_Vol_Array)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Vol_Array)
        Dialog_Vol_Array.setTabOrder(self.comboBox_type, self.LineEdit_Name)
        Dialog_Vol_Array.setTabOrder(self.LineEdit_Name, self.ComboBox_Shadow_Attribute)
        Dialog_Vol_Array.setTabOrder(self.ComboBox_Shadow_Attribute, self.lineEdit_start_i)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_start_i, self.lineEdit_end_i)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_end_i, self.tabWidget)
        Dialog_Vol_Array.setTabOrder(self.tabWidget, self.lineEdit_Annular_Ptn1X)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_Ptn1X, self.lineEdit_Annular_Ptn1Y)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_Ptn1Y, self.lineEdit_Annular_Ptn1Z)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_Ptn1Z, self.lineEdit_Annular_Ptn2X)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_Ptn2X, self.lineEdit_Annular_Ptn2Y)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_Ptn2Y, self.lineEdit_Annular_Ptn2Z)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_Ptn2Z, self.lineEdit_Annular_RadInner)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_RadInner, self.lineEdit_Annular_RadOuter)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Annular_RadOuter, self.lineEdit_Cylinder_Ptn1X)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Ptn1X, self.lineEdit_Cylinder_Ptn1Y)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Ptn1Y, self.lineEdit_Cylinder_Ptn1Z)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Ptn1Z, self.lineEdit_Cylinder_Ptn2X)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Ptn2X, self.lineEdit_Cylinder_Ptn2Y)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Ptn2Y, self.lineEdit_Cylinder_Ptn2Z)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Ptn2Z, self.lineEdit_Cylinder_Rad)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_Cylinder_Rad, self.checkBox_UniformX)
        Dialog_Vol_Array.setTabOrder(self.checkBox_UniformX, self.lineEdit_UniformX)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_UniformX, self.checkBox_UniformY)
        Dialog_Vol_Array.setTabOrder(self.checkBox_UniformY, self.lineEdit_UniformY)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_UniformY, self.checkBox_UniformZ)
        Dialog_Vol_Array.setTabOrder(self.checkBox_UniformZ, self.lineEdit_UniformZ)
        Dialog_Vol_Array.setTabOrder(self.lineEdit_UniformZ, self.pushButton_ok)
        Dialog_Vol_Array.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Dialog_Vol_Array):
        Dialog_Vol_Array.setWindowTitle(QtGui.QApplication.translate("Dialog_Vol_Array", "阵列设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "循环体结构类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(0, QtGui.QApplication.translate("Dialog_Vol_Array", "正投影体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(1, QtGui.QApplication.translate("Dialog_Vol_Array", "环形体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(2, QtGui.QApplication.translate("Dialog_Vol_Array", "圆柱体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(3, QtGui.QApplication.translate("Dialog_Vol_Array", "圆台体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(4, QtGui.QApplication.translate("Dialog_Vol_Array", "球形体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "属性：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(0, QtGui.QApplication.translate("Dialog_Vol_Array", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(1, QtGui.QApplication.translate("Dialog_Vol_Array", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(2, QtGui.QApplication.translate("Dialog_Vol_Array", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(3, QtGui.QApplication.translate("Dialog_Vol_Array", "Vacuo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_main.setTitle(QtGui.QApplication.translate("Dialog_Vol_Array", "结构类型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "变量i起始：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_start_i.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "变量i结束：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_end_i.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X0.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y0.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z0.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点2：", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("Dialog_Vol_Array", "正投影体", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_Ptn2X.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "rlf\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_Ptn2Y.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "thetai\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_Ptn2Z.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "thetaf\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "内半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_RadInner.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "radius_inner\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "外半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_Ptn1Z.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "rli\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z1.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_Ptn1Y.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "zlf\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y1.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_Ptn1X.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "zli\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点2：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Annular_RadOuter.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "radius_outer\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X1.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog_Vol_Array", "环形体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点2：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog_Vol_Array", "圆柱体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "顶面半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_RadUp.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "radius_outer\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "底点：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_Ptn1X.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "zli\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_Ptn1Y.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "zlf\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_Ptn1Z.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "rli\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_Ptn2Z.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "thetaf\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "顶点：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_Ptn2X.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "rlf\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_Ptn2Y.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "thetai\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Cone_RadBott.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "radius_inner\'i\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "底面半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y3.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z3.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X3.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog_Vol_Array", "圆台体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X4.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y4.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z4.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog_Vol_Array", "球体", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_NonUniform.setTitle(QtGui.QApplication.translate("Dialog_Vol_Array", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformY.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformZ.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformX.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformX.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformY.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformZ.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
