# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PolygonalDialogap.ui'
#
# Created: Fri May 21 12:03:44 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1025, 609)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 285))
        self.groupBox_5.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_z2 = QtGui.QLabel(self.groupBox_5)
        self.label_z2.setObjectName("label_z2")
        self.gridLayout_3.addWidget(self.label_z2, 1, 8, 1, 1)
        self.label_x2 = QtGui.QLabel(self.groupBox_5)
        self.label_x2.setObjectName("label_x2")
        self.gridLayout_3.addWidget(self.label_x2, 1, 2, 1, 1)
        self.label_y2 = QtGui.QLabel(self.groupBox_5)
        self.label_y2.setObjectName("label_y2")
        self.gridLayout_3.addWidget(self.label_y2, 1, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 7, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 9, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.spinBox_num = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_num.setMinimum(3)
        self.spinBox_num.setMaximum(200)
        self.spinBox_num.setObjectName("spinBox_num")
        self.gridLayout_3.addWidget(self.spinBox_num, 0, 1, 1, 6)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.listWidget = QtGui.QListWidget(self.groupBox_5)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_midZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_midZ.setObjectName("checkBox_midZ")
        self.gridLayout_6.addWidget(self.checkBox_midZ, 4, 7, 1, 2)
        self.checkBox_isMarkZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkZ.setObjectName("checkBox_isMarkZ")
        self.gridLayout_6.addWidget(self.checkBox_isMarkZ, 2, 7, 1, 2)
        self.label_y1 = QtGui.QLabel(self.groupBox_3)
        self.label_y1.setObjectName("label_y1")
        self.gridLayout_6.addWidget(self.label_y1, 0, 5, 1, 1)
        self.le_markx = QtGui.QLineEdit(self.groupBox_3)
        self.le_markx.setObjectName("le_markx")
        self.gridLayout_6.addWidget(self.le_markx, 1, 1, 1, 3)
        self.le_marky = QtGui.QLineEdit(self.groupBox_3)
        self.le_marky.setObjectName("le_marky")
        self.gridLayout_6.addWidget(self.le_marky, 1, 4, 1, 3)
        self.checkBox_minY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_minY.setObjectName("checkBox_minY")
        self.gridLayout_6.addWidget(self.checkBox_minY, 3, 4, 1, 2)
        self.le_markz = QtGui.QLineEdit(self.groupBox_3)
        self.le_markz.setObjectName("le_markz")
        self.gridLayout_6.addWidget(self.le_markz, 1, 7, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 4, 1, 1)
        self.checkBox_midX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_midX.setObjectName("checkBox_midX")
        self.gridLayout_6.addWidget(self.checkBox_midX, 4, 1, 1, 2)
        self.checkBox_minX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_minX.setObjectName("checkBox_minX")
        self.gridLayout_6.addWidget(self.checkBox_minX, 3, 1, 1, 2)
        self.checkBox_isMarkX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkX.setObjectName("checkBox_isMarkX")
        self.gridLayout_6.addWidget(self.checkBox_isMarkX, 2, 1, 1, 2)
        self.label_z1 = QtGui.QLabel(self.groupBox_3)
        self.label_z1.setObjectName("label_z1")
        self.gridLayout_6.addWidget(self.label_z1, 0, 8, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 1)
        self.checkBox_minZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_minZ.setObjectName("checkBox_minZ")
        self.gridLayout_6.addWidget(self.checkBox_minZ, 3, 7, 1, 2)
        self.checkBox_midY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_midY.setObjectName("checkBox_midY")
        self.gridLayout_6.addWidget(self.checkBox_midY, 4, 4, 1, 2)
        self.checkBox_isMarkY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkY.setObjectName("checkBox_isMarkY")
        self.gridLayout_6.addWidget(self.checkBox_isMarkY, 2, 4, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 1, 1, 1)
        self.label_x1 = QtGui.QLabel(self.groupBox_3)
        self.label_x1.setObjectName("label_x1")
        self.gridLayout_6.addWidget(self.label_x1, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 7, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 0, 6, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 0, 9, 1, 1)
        self.checkBox_maxX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_maxX.setObjectName("checkBox_maxX")
        self.gridLayout_6.addWidget(self.checkBox_maxX, 5, 1, 1, 2)
        self.checkBox_maxY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_maxY.setObjectName("checkBox_maxY")
        self.gridLayout_6.addWidget(self.checkBox_maxY, 5, 4, 1, 2)
        self.checkBox_maxZ = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_maxZ.setObjectName("checkBox_maxZ")
        self.gridLayout_6.addWidget(self.checkBox_maxZ, 5, 7, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_6, 0, 7, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_name = QtGui.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_order = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_order.sizePolicy().hasHeightForWidth())
        self.spinBox_order.setSizePolicy(sizePolicy)
        self.spinBox_order.setObjectName("spinBox_order")
        self.horizontalLayout.addWidget(self.spinBox_order)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_ok = QtGui.QPushButton(self.groupBox_4)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_2.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(self.groupBox_4)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.le_name)
        Dialog.setTabOrder(self.le_name, self.spinBox_order)
        Dialog.setTabOrder(self.spinBox_order, self.le_markx)
        Dialog.setTabOrder(self.le_markx, self.checkBox_isMarkX)
        Dialog.setTabOrder(self.checkBox_isMarkX, self.checkBox_minX)
        Dialog.setTabOrder(self.checkBox_minX, self.checkBox_midX)
        Dialog.setTabOrder(self.checkBox_midX, self.checkBox_maxX)
        Dialog.setTabOrder(self.checkBox_maxX, self.le_marky)
        Dialog.setTabOrder(self.le_marky, self.checkBox_isMarkY)
        Dialog.setTabOrder(self.checkBox_isMarkY, self.checkBox_minY)
        Dialog.setTabOrder(self.checkBox_minY, self.checkBox_midY)
        Dialog.setTabOrder(self.checkBox_midY, self.checkBox_maxY)
        Dialog.setTabOrder(self.checkBox_maxY, self.le_markz)
        Dialog.setTabOrder(self.le_markz, self.checkBox_isMarkZ)
        Dialog.setTabOrder(self.checkBox_isMarkZ, self.checkBox_minZ)
        Dialog.setTabOrder(self.checkBox_minZ, self.checkBox_midZ)
        Dialog.setTabOrder(self.checkBox_midZ, self.checkBox_maxZ)
        Dialog.setTabOrder(self.checkBox_maxZ, self.spinBox_num)
        Dialog.setTabOrder(self.spinBox_num, self.listWidget)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Object of a Polygonal Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_z2.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x2.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y2.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "NumbersofPoints", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_midZ.setText(QtGui.QApplication.translate("Dialog", "MIDMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkZ.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y1.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_minY.setText(QtGui.QApplication.translate("Dialog", "MINMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_midX.setText(QtGui.QApplication.translate("Dialog", "MIDMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_minX.setText(QtGui.QApplication.translate("Dialog", "MINMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkX.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_z1.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_minZ.setText(QtGui.QApplication.translate("Dialog", "MINMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_midY.setText(QtGui.QApplication.translate("Dialog", "MIDMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkY.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x1.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_maxX.setText(QtGui.QApplication.translate("Dialog", "MAXMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_maxY.setText(QtGui.QApplication.translate("Dialog", "MAXMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_maxZ.setText(QtGui.QApplication.translate("Dialog", "MAXMUM", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

