# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FoilDialog.ui'
#
# Created: Fri May 21 16:14:10 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_FoilDlg(object):
    def setupUi(self, Dialog_FoilDlg):
        Dialog_FoilDlg.setObjectName("Dialog_FoilDlg")
        Dialog_FoilDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_FoilDlg.resize(543, 319)
        Dialog_FoilDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_FoilDlg.setMaximumSize(QtCore.QSize(4160000, 16777215))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog_FoilDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_Name = QtGui.QLabel(Dialog_FoilDlg)
        self.Label_Name.setObjectName("Label_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_FoilDlg)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEdit_Name)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.ComboBox_Shadow = StyledComboBox(Dialog_FoilDlg)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ComboBox_Shadow)
        self.Label_Shadow = QtGui.QLabel(Dialog_FoilDlg)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_Shadow)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_FoilDlg)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_end_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_2.setObjectName("horizontalLayout_end_2")
        self.label_end_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_2.setObjectName("label_end_2")
        self.horizontalLayout_end_2.addWidget(self.label_end_2)
        self.LineEdit_thick = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_thick.setEnabled(True)
        self.LineEdit_thick.setObjectName("LineEdit_thick")
        self.horizontalLayout_end_2.addWidget(self.LineEdit_thick)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_2, 4, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_start, 1, 10, 1, 1)
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.gridLayout_5.addWidget(self.label_start, 1, 0, 1, 1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_5.addWidget(self.label_Y, 0, 5, 1, 1)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.gridLayout_5.addWidget(self.LineEdit_end_x, 2, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 7, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_5.addWidget(self.label_Z, 0, 8, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.gridLayout_5.addWidget(self.label_X, 0, 2, 1, 1)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_end, 2, 10, 1, 1)
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.gridLayout_5.addWidget(self.LineEdit_start_x, 1, 1, 1, 3)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.gridLayout_5.addWidget(self.LineEdit_start_y, 1, 4, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 9, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 4, 1, 1)
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.gridLayout_5.addWidget(self.label_end, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 3, 1, 1)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.gridLayout_5.addWidget(self.LineEdit_end_y, 2, 4, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 6, 1, 1)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.gridLayout_5.addWidget(self.LineEdit_end_z, 2, 7, 1, 3)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.gridLayout_5.addWidget(self.LineEdit_start_z, 1, 7, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_Port)
        self.groupBox = QtGui.QGroupBox(Dialog_FoilDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.CustomMaterial = QtGui.QRadioButton(self.groupBox)
        self.CustomMaterial.setObjectName("CustomMaterial")
        self.horizontalLayout_6.addWidget(self.CustomMaterial)
        self.ComboBox_Material = StyledComboBox(self.groupBox)
        self.ComboBox_Material.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Material.sizePolicy().hasHeightForWidth())
        self.ComboBox_Material.setSizePolicy(sizePolicy)
        self.ComboBox_Material.setObjectName("ComboBox_Material")
        self.ComboBox_Material.addItem("")
        self.horizontalLayout_6.addWidget(self.ComboBox_Material)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.DefaultMaterial = QtGui.QRadioButton(self.groupBox)
        self.DefaultMaterial.setObjectName("DefaultMaterial")
        self.horizontalLayout_7.addWidget(self.DefaultMaterial)
        self.Gold = QtGui.QLineEdit(self.groupBox)
        self.Gold.setEnabled(False)
        self.Gold.setObjectName("Gold")
        self.horizontalLayout_7.addWidget(self.Gold)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_cancel = QtGui.QPushButton(Dialog_FoilDlg)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_4.addWidget(self.pb_cancel, 0, 1, 1, 1)
        self.pb_ok = QtGui.QPushButton(Dialog_FoilDlg)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout_4.addWidget(self.pb_ok, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)

        self.retranslateUi(Dialog_FoilDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_FoilDlg)
        Dialog_FoilDlg.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog_FoilDlg.setTabOrder(self.pb_cancel, self.LineEdit_Name)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_Name, self.ComboBox_Shadow)
        Dialog_FoilDlg.setTabOrder(self.ComboBox_Shadow, self.LineEdit_start_x)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_start_x, self.LineEdit_start_y)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_start_y, self.LineEdit_start_z)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_start_z, self.ComboBox_start)
        Dialog_FoilDlg.setTabOrder(self.ComboBox_start, self.LineEdit_end_x)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_end_x, self.LineEdit_end_y)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_end_y, self.LineEdit_end_z)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_end_z, self.ComboBox_end)
        Dialog_FoilDlg.setTabOrder(self.ComboBox_end, self.LineEdit_thick)
        Dialog_FoilDlg.setTabOrder(self.LineEdit_thick, self.CustomMaterial)
        Dialog_FoilDlg.setTabOrder(self.CustomMaterial, self.ComboBox_Material)
        Dialog_FoilDlg.setTabOrder(self.ComboBox_Material, self.DefaultMaterial)
        Dialog_FoilDlg.setTabOrder(self.DefaultMaterial, self.Gold)

    def retranslateUi(self, Dialog_FoilDlg):
        Dialog_FoilDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_FoilDlg", "箔片", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "Foil", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_FoilDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "类型箔片：", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_FoilDlg", "结构与元件参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_2.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "箔片厚度.THICK=：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_thick.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "1mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_FoilDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_FoilDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_FoilDlg", "材料名称", None, QtGui.QApplication.UnicodeUTF8))
        self.CustomMaterial.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "自定义材料", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Material.setItemText(0, QtGui.QApplication.translate("Dialog_FoilDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.DefaultMaterial.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "默认材料", None, QtGui.QApplication.UnicodeUTF8))
        self.Gold.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "GOLD", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_FoilDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
