# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DraftRevolutionDialog.ui'
#
# Created: Fri May 21 15:51:32 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 395)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_name = Completer.AutoCompleteEdit(self.groupBox)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.spinBox_order = QtGui.QSpinBox(self.groupBox)
        self.spinBox_order.setObjectName("spinBox_order")
        self.gridLayout.addWidget(self.spinBox_order, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_Attribute = QtGui.QGroupBox(Dialog)
        self.groupBox_Attribute.setObjectName("groupBox_Attribute")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_Attribute)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_Attribute)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_attribute = QtGui.QComboBox(self.groupBox_Attribute)
        self.comboBox_attribute.setObjectName("comboBox_attribute")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_attribute)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_Attribute)
        self.groupBox_object = QtGui.QGroupBox(Dialog)
        self.groupBox_object.setObjectName("groupBox_object")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_object)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_top = QtGui.QLabel(self.groupBox_object)
        self.label_top.setObjectName("label_top")
        self.gridLayout_2.addWidget(self.label_top, 4, 0, 1, 1)
        self.label_Base = QtGui.QLabel(self.groupBox_object)
        self.label_Base.setObjectName("label_Base")
        self.gridLayout_2.addWidget(self.label_Base, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 6, 1, 1)
        self.lineEdit_point1z = Completer.AutoCompleteEdit(self.groupBox_object)
        self.lineEdit_point1z.setObjectName("lineEdit_point1z")
        self.gridLayout_2.addWidget(self.lineEdit_point1z, 3, 7, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 7, 1, 1)
        self.lineEdit_point2z = Completer.AutoCompleteEdit(self.groupBox_object)
        self.lineEdit_point2z.setObjectName("lineEdit_point2z")
        self.gridLayout_2.addWidget(self.lineEdit_point2z, 4, 7, 1, 3)
        self.label_9 = QtGui.QLabel(self.groupBox_object)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_object)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_object)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 9, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_object)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 3, 1, 1)
        self.lineEdit_point1y = Completer.AutoCompleteEdit(self.groupBox_object)
        self.lineEdit_point1y.setObjectName("lineEdit_point1y")
        self.gridLayout_2.addWidget(self.lineEdit_point1y, 3, 4, 1, 3)
        self.lineEdit_point2y = Completer.AutoCompleteEdit(self.groupBox_object)
        self.lineEdit_point2y.setObjectName("lineEdit_point2y")
        self.gridLayout_2.addWidget(self.lineEdit_point2y, 4, 4, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 1, 1, 1)
        self.lineEdit_point1x = Completer.AutoCompleteEdit(self.groupBox_object)
        self.lineEdit_point1x.setObjectName("lineEdit_point1x")
        self.gridLayout_2.addWidget(self.lineEdit_point1x, 3, 1, 1, 3)
        self.lineEdit_point2x = Completer.AutoCompleteEdit(self.groupBox_object)
        self.lineEdit_point2x.setObjectName("lineEdit_point2x")
        self.gridLayout_2.addWidget(self.lineEdit_point2x, 4, 1, 1, 3)
        self.comboBox_area = QtGui.QComboBox(self.groupBox_object)
        self.comboBox_area.setObjectName("comboBox_area")
        self.gridLayout_2.addWidget(self.comboBox_area, 0, 1, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_object)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Y = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_Y.setObjectName("checkBox_Y")
        self.gridLayout_3.addWidget(self.checkBox_Y, 0, 4, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 6, 1, 1)
        self.checkBox_X = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_X.setObjectName("checkBox_X")
        self.gridLayout_3.addWidget(self.checkBox_X, 0, 1, 1, 1)
        self.checkBox_Z = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.gridLayout_3.addWidget(self.checkBox_Z, 0, 7, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 5, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 8, 1, 1)
        self.lineEdit_DX3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_DX3.setObjectName("lineEdit_DX3")
        self.gridLayout_3.addWidget(self.lineEdit_DX3, 1, 6, 1, 3)
        self.lineEdit_DX2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_DX2.setObjectName("lineEdit_DX2")
        self.gridLayout_3.addWidget(self.lineEdit_DX2, 1, 3, 1, 3)
        self.lineEdit_DX1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_DX1.setObjectName("lineEdit_DX1")
        self.gridLayout_3.addWidget(self.lineEdit_DX1, 1, 0, 1, 3)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_4.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_4.addWidget(self.pb_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.lineEdit_name)
        Dialog.setTabOrder(self.lineEdit_name, self.spinBox_order)
        Dialog.setTabOrder(self.spinBox_order, self.comboBox_attribute)
        Dialog.setTabOrder(self.comboBox_attribute, self.comboBox_area)
        Dialog.setTabOrder(self.comboBox_area, self.lineEdit_point1x)
        Dialog.setTabOrder(self.lineEdit_point1x, self.lineEdit_point1y)
        Dialog.setTabOrder(self.lineEdit_point1y, self.lineEdit_point1z)
        Dialog.setTabOrder(self.lineEdit_point1z, self.lineEdit_point2x)
        Dialog.setTabOrder(self.lineEdit_point2x, self.lineEdit_point2y)
        Dialog.setTabOrder(self.lineEdit_point2y, self.lineEdit_point2z)
        Dialog.setTabOrder(self.lineEdit_point2z, self.checkBox_X)
        Dialog.setTabOrder(self.checkBox_X, self.checkBox_Y)
        Dialog.setTabOrder(self.checkBox_Y, self.checkBox_Z)
        Dialog.setTabOrder(self.checkBox_Z, self.lineEdit_DX1)
        Dialog.setTabOrder(self.lineEdit_DX1, self.lineEdit_DX2)
        Dialog.setTabOrder(self.lineEdit_DX2, self.lineEdit_DX3)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "顺序：", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Attribute.setTitle(QtGui.QApplication.translate("Dialog", "属性", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "属性：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(0, QtGui.QApplication.translate("Dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(1, QtGui.QApplication.translate("Dialog", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(2, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(3, QtGui.QApplication.translate("Dialog", "Void", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_object.setTitle(QtGui.QApplication.translate("Dialog", "结构类型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_top.setText(QtGui.QApplication.translate("Dialog", "Point_Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Base.setText(QtGui.QApplication.translate("Dialog", "Point_Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "基础面", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_X.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

