# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DrivDialog.ui'
#
# Created: Fri May 21 16:12:59 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Dialog_ExpDlg(object):
    def setupUi(self, Dialog_ExpDlg):
        Dialog_ExpDlg.setObjectName("Dialog_ExpDlg")
        Dialog_ExpDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_ExpDlg.resize(542, 318)
        Dialog_ExpDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_ExpDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog_ExpDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtGui.QLabel(Dialog_ExpDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.LineEdit_JFunc = QtGui.QLineEdit(Dialog_ExpDlg)
        self.LineEdit_JFunc.setEnabled(True)
        self.LineEdit_JFunc.setObjectName("LineEdit_JFunc")
        self.horizontalLayout_6.addWidget(self.LineEdit_JFunc)
        self.label_4 = QtGui.QLabel(Dialog_ExpDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_ExpDlg)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.ComboBox_Current = StyledComboBox(self.groupBox_Port)
        self.ComboBox_Current.setObjectName("ComboBox_Current")
        self.ComboBox_Current.addItem("")
        self.ComboBox_Current.addItem("")
        self.ComboBox_Current.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_Current)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_9.addWidget(self.label_X)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_9.addWidget(self.label_Y)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_9.addWidget(self.label_Z)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_Port)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        #self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        #self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        #self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 1, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        #self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        #self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(False)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        #self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(False)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 8, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 6, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Port, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_ok = QtGui.QPushButton(Dialog_ExpDlg)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_10.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog_ExpDlg)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_10.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(Dialog_ExpDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_ExpDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(Dialog_ExpDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(Dialog_ExpDlg)
        self.ComboBox_Shadow.setEnabled(True)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.ComboBox_Shadow.addItem("")
        self.ComboBox_Shadow.addItem("")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.comboBox = QtGui.QComboBox(Dialog_ExpDlg)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 3, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 5, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 7, 0, 1, 1)

        self.retranslateUi(Dialog_ExpDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ExpDlg)
        Dialog_ExpDlg.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog_ExpDlg.setTabOrder(self.pb_cancel, self.LineEdit_Name)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_Name, self.ComboBox_Shadow)
        Dialog_ExpDlg.setTabOrder(self.ComboBox_Shadow, self.comboBox)
        Dialog_ExpDlg.setTabOrder(self.comboBox, self.LineEdit_start_x)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_start_x, self.LineEdit_start_y)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_start_y, self.LineEdit_start_z)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_start_z, self.ComboBox_start)
        Dialog_ExpDlg.setTabOrder(self.ComboBox_start, self.LineEdit_end_x)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_end_x, self.LineEdit_end_y)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_end_y, self.LineEdit_end_z)
        Dialog_ExpDlg.setTabOrder(self.LineEdit_end_z, self.ComboBox_end)
        Dialog_ExpDlg.setTabOrder(self.ComboBox_end, self.radioButton_x)
        Dialog_ExpDlg.setTabOrder(self.radioButton_x, self.radioButton_y)
        Dialog_ExpDlg.setTabOrder(self.radioButton_y, self.radioButton_z)
        Dialog_ExpDlg.setTabOrder(self.radioButton_z, self.ComboBox_Current)
        Dialog_ExpDlg.setTabOrder(self.ComboBox_Current, self.LineEdit_JFunc)

    def retranslateUi(self, Dialog_ExpDlg):
        Dialog_ExpDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_ExpDlg", "空间电流源", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "函数.JFUNC(T,X,Y,Z)=", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_JFunc.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "A/m^2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_ExpDlg", "电流激励参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "指定电流密度：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Current.setItemText(0, QtGui.QApplication.translate("Dialog_ExpDlg", "J1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Current.setItemText(1, QtGui.QApplication.translate("Dialog_ExpDlg", "J2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Current.setItemText(2, QtGui.QApplication.translate("Dialog_ExpDlg", "J3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "起点坐标：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_ExpDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "止点坐标：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_ExpDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "CurrentSrc", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_ExpDlg", "类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_ExpDlg", "点电流源", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(1, QtGui.QApplication.translate("Dialog_ExpDlg", "线电流源", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(2, QtGui.QApplication.translate("Dialog_ExpDlg", "面电流源", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(3, QtGui.QApplication.translate("Dialog_ExpDlg", "体电流源", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog_ExpDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
