# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMaterialDlg.ui'
#
# Created: Thu Jun 13 10:54:49 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_NewMaterialDlg(object):
    def setupUi(self, Dialog_NewMaterialDlg):
        Dialog_NewMaterialDlg.setObjectName("Dialog_NewMaterialDlg")
        Dialog_NewMaterialDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_NewMaterialDlg.resize(389, 304)
        Dialog_NewMaterialDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_NewMaterialDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog_NewMaterialDlg)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_atomic_number = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_NewMaterialDlg)
        self.lineEdit_atomic_number.setObjectName("lineEdit_atomic_number")
        self.horizontalLayout_2.addWidget(self.lineEdit_atomic_number)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_NewMaterialDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(Dialog_NewMaterialDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 12, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_conductivity = QtGui.QCheckBox(Dialog_NewMaterialDlg)
        self.checkBox_conductivity.setObjectName("checkBox_conductivity")
        self.horizontalLayout_5.addWidget(self.checkBox_conductivity)
        self.lineEdit_conductivity = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_NewMaterialDlg)
        self.lineEdit_conductivity.setObjectName("lineEdit_conductivity")
        self.horizontalLayout_5.addWidget(self.lineEdit_conductivity)
        self.label_5 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_atomic_desity = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_NewMaterialDlg)
        self.lineEdit_atomic_desity.setObjectName("lineEdit_atomic_desity")
        self.horizontalLayout_4.addWidget(self.lineEdit_atomic_desity)
        self.label_6 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_atomic_mass_number = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_NewMaterialDlg)
        self.lineEdit_atomic_mass_number.setObjectName("lineEdit_atomic_mass_number")
        self.horizontalLayout_3.addWidget(self.lineEdit_atomic_mass_number)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_NewMaterialDlg)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.horizontalLayout.addWidget(self.lineEdit_Name)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_dielectric_constant = QtGui.QCheckBox(Dialog_NewMaterialDlg)
        self.checkBox_dielectric_constant.setObjectName("checkBox_dielectric_constant")
        self.horizontalLayout_6.addWidget(self.checkBox_dielectric_constant)
        self.lineEdit_dielectric_constant = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_NewMaterialDlg)
        self.lineEdit_dielectric_constant.setObjectName("lineEdit_dielectric_constant")
        self.horizontalLayout_6.addWidget(self.lineEdit_dielectric_constant)
        self.gridLayout.addLayout(self.horizontalLayout_6, 10, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 11, 0, 1, 1)

        self.retranslateUi(Dialog_NewMaterialDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_NewMaterialDlg)
        Dialog_NewMaterialDlg.setTabOrder(self.lineEdit_Name, self.lineEdit_atomic_number)
        Dialog_NewMaterialDlg.setTabOrder(self.lineEdit_atomic_number, self.lineEdit_atomic_mass_number)
        Dialog_NewMaterialDlg.setTabOrder(self.lineEdit_atomic_mass_number, self.lineEdit_atomic_desity)
        Dialog_NewMaterialDlg.setTabOrder(self.lineEdit_atomic_desity, self.checkBox_conductivity)
        Dialog_NewMaterialDlg.setTabOrder(self.checkBox_conductivity, self.lineEdit_conductivity)
        Dialog_NewMaterialDlg.setTabOrder(self.lineEdit_conductivity, self.checkBox_dielectric_constant)
        Dialog_NewMaterialDlg.setTabOrder(self.checkBox_dielectric_constant, self.lineEdit_dielectric_constant)
        Dialog_NewMaterialDlg.setTabOrder(self.lineEdit_dielectric_constant, self.pushButton_ok)
        Dialog_NewMaterialDlg.setTabOrder(self.pushButton_ok, self.pushButton)

    def retranslateUi(self, Dialog_NewMaterialDlg):
        Dialog_NewMaterialDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "新材料", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料原子序数：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_atomic_number.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_conductivity.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料电导率：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_conductivity.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1/ohm-m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料密度：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_atomic_desity.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "kg/m^3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料原子质量数：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_atomic_mass_number.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Name.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "NewMaterial", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dielectric_constant.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料相对介电常数：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_dielectric_constant.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))

