# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PointWidget.ui'
#
# Created: Fri May 21 15:31:14 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(514, 222)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_point_basez = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_basez.setObjectName("lineEdit_point_basez")
        self.gridLayout.addWidget(self.lineEdit_point_basez, 1, 7, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.label_x2 = QtGui.QLabel(Form)
        self.label_x2.setObjectName("label_x2")
        self.gridLayout.addWidget(self.label_x2, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_z2 = QtGui.QLabel(Form)
        self.label_z2.setObjectName("label_z2")
        self.gridLayout.addWidget(self.label_z2, 0, 8, 1, 1)
        self.label_y2 = QtGui.QLabel(Form)
        self.label_y2.setObjectName("label_y2")
        self.gridLayout.addWidget(self.label_y2, 0, 5, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 9, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 7, 1, 1)
        self.lineEdit_point_topy = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_topy.setObjectName("lineEdit_point_topy")
        self.gridLayout.addWidget(self.lineEdit_point_topy, 2, 4, 1, 3)
        self.lineEdit_point_basex = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_basex.setObjectName("lineEdit_point_basex")
        self.gridLayout.addWidget(self.lineEdit_point_basex, 1, 1, 1, 3)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_point_topx = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_topx.setObjectName("lineEdit_point_topx")
        self.gridLayout.addWidget(self.lineEdit_point_topx, 2, 1, 1, 3)
        self.lineEdit_point_basey = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_basey.setObjectName("lineEdit_point_basey")
        self.gridLayout.addWidget(self.lineEdit_point_basey, 1, 4, 1, 3)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_point_topz = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_topz.setObjectName("lineEdit_point_topz")
        self.gridLayout.addWidget(self.lineEdit_point_topz, 2, 7, 1, 3)
        self.lineEdit_radius_inside = Completer.AutoCompleteEdit(Form)
        self.lineEdit_radius_inside.setObjectName("lineEdit_radius_inside")
        self.gridLayout.addWidget(self.lineEdit_radius_inside, 4, 1, 1, 3)
        self.lineEdit_point_startx = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_startx.setObjectName("lineEdit_point_startx")
        self.gridLayout.addWidget(self.lineEdit_point_startx, 3, 1, 1, 3)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_point_starty = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_starty.setObjectName("lineEdit_point_starty")
        self.gridLayout.addWidget(self.lineEdit_point_starty, 3, 4, 1, 3)
        self.lineEdit_point_startz = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point_startz.setObjectName("lineEdit_point_startz")
        self.gridLayout.addWidget(self.lineEdit_point_startz, 3, 7, 1, 3)
        self.lineEdit_radius_out = Completer.AutoCompleteEdit(Form)
        self.lineEdit_radius_out.setObjectName("lineEdit_radius_out")
        self.gridLayout.addWidget(self.lineEdit_radius_out, 5, 1, 1, 3)
        self.lineEdit_pitch = Completer.AutoCompleteEdit(Form)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.gridLayout.addWidget(self.lineEdit_pitch, 6, 1, 1, 3)
        self.lineEdit_width = Completer.AutoCompleteEdit(Form)
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.gridLayout.addWidget(self.lineEdit_width, 7, 1, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_point_basex, self.lineEdit_point_basey)
        Form.setTabOrder(self.lineEdit_point_basey, self.lineEdit_point_basez)
        Form.setTabOrder(self.lineEdit_point_basez, self.lineEdit_point_topx)
        Form.setTabOrder(self.lineEdit_point_topx, self.lineEdit_point_topy)
        Form.setTabOrder(self.lineEdit_point_topy, self.lineEdit_point_topz)
        Form.setTabOrder(self.lineEdit_point_topz, self.lineEdit_point_startx)
        Form.setTabOrder(self.lineEdit_point_startx, self.lineEdit_point_starty)
        Form.setTabOrder(self.lineEdit_point_starty, self.lineEdit_point_startz)
        Form.setTabOrder(self.lineEdit_point_startz, self.lineEdit_radius_inside)
        Form.setTabOrder(self.lineEdit_radius_inside, self.lineEdit_radius_out)
        Form.setTabOrder(self.lineEdit_radius_out, self.lineEdit_pitch)
        Form.setTabOrder(self.lineEdit_pitch, self.lineEdit_width)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x2.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_z2.setText(QtGui.QApplication.translate("Form", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y2.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Base Point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Top Point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Radius_inside:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Start Point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Pitch:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Radius_out:", None, QtGui.QApplication.UnicodeUTF8))

