# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineConformalDialog.ui'
#
# Created: Tue Jan  5 21:08:24 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!
import FreeCAD
from PySide import QtCore, QtGui
from Modeling.Common.Tools import Completer

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(490, 407)
        self.gridLayout_3 = QtGui.QGridLayout(dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtGui.QGroupBox(dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_name = QtGui.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.le_order = QtGui.QLineEdit(self.groupBox)
        self.le_order.setObjectName("le_order")
        self.horizontalLayout.addWidget(self.le_order)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.cb_attribute = QtGui.QComboBox(self.groupBox_2)
        self.cb_attribute.setObjectName("cb_attribute")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.gridLayout_4.addWidget(self.cb_attribute, 0, 1, 1, 1)
        self.Layout_custom = QtGui.QHBoxLayout()
        self.Layout_custom.setObjectName("Layout_custom")
        self.gridLayout_4.addLayout(self.Layout_custom, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_x = QtGui.QLabel(self.groupBox_3)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.le_markx = QtGui.QLineEdit(self.groupBox_3)
        self.le_markx.setObjectName("le_markx")
        self.gridLayout.addWidget(self.le_markx, 1, 1, 1, 3)
        self.label_y = QtGui.QLabel(self.groupBox_3)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        self.le_marky = QtGui.QLineEdit(self.groupBox_3)
        self.le_marky.setObjectName("le_marky")
        self.gridLayout.addWidget(self.le_marky, 1, 4, 1, 3)
        self.checkBox_isMarkX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkX.setObjectName("checkBox_isMarkX")
        self.gridLayout.addWidget(self.checkBox_isMarkX, 2, 1, 1, 3)
        self.checkBox_isMarkY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkY.setObjectName("checkBox_isMarkY")
        self.gridLayout.addWidget(self.checkBox_isMarkY, 2, 4, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_point1_y = Completer.AutoCompleteEdit(self.groupBox_4)
        self.le_point1_y.setObjectName("le_point1_y")
        self.gridLayout_2.addWidget(self.le_point1_y, 2, 4, 1, 3)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 4, 1, 1)
        self.le_point1_x = Completer.AutoCompleteEdit(self.groupBox_4)
        self.le_point1_x.setObjectName("le_point1_x")
        self.gridLayout_2.addWidget(self.le_point1_x, 2, 1, 1, 3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.cb_normal = QtGui.QComboBox(self.groupBox_4)
        self.cb_normal.setObjectName("cb_normal")
        self.cb_normal.addItem("")
        self.cb_normal.addItem("")
        self.gridLayout_2.addWidget(self.cb_normal, 1, 1, 1, 3)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.le_point2_x = Completer.AutoCompleteEdit(self.groupBox_4)
        self.le_point2_x.setObjectName("le_point2_x")
        self.gridLayout_2.addWidget(self.le_point2_x, 3, 1, 1, 3)
        self.le_point2_y = Completer.AutoCompleteEdit(self.groupBox_4)
        self.le_point2_y.setObjectName("le_point2_y")
        self.gridLayout_2.addWidget(self.le_point2_y, 3, 4, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.pb_ok = QtGui.QPushButton(dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout_3.addWidget(self.pb_ok, 4, 0, 1, 1)
        self.pb_cancel = QtGui.QPushButton(dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_3.addWidget(self.pb_cancel, 4, 1, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dialog", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(0, QtGui.QApplication.translate("dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(1, QtGui.QApplication.translate("dialog", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(2, QtGui.QApplication.translate("dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(3, QtGui.QApplication.translate("dialog", "Void", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dialog", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x.setText(QtGui.QApplication.translate("dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dialog", "Value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y.setText(QtGui.QApplication.translate("dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkX.setText(QtGui.QApplication.translate("dialog", "isMarkX", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkY.setText(QtGui.QApplication.translate("dialog", "isMarkY", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("dialog", "Object of Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dialog", "Point1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dialog", "Normal:", None, QtGui.QApplication.UnicodeUTF8))
        coodinate = FreeCAD.ActiveDocument.CoordinateSystem
        if coodinate == u'Rectangular':
            self.cb_normal.setItemText(0, QtGui.QApplication.translate("dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
            self.cb_normal.setItemText(1, QtGui.QApplication.translate("dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        elif coodinate == u'Cylindrical':
            self.cb_normal.setItemText(0, QtGui.QApplication.translate("dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
            self.cb_normal.setItemText(1, QtGui.QApplication.translate("dialog", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dialog", "Point2:", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

