# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReplaceDialog.ui'
#
# Created: Tue Dec 31 10:41:47 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(400, 200)
        font = QtGui.QFont()
        font.setFamily("Arial")
        dialog.setFont(font)
        self.gridLayout = QtGui.QGridLayout(dialog)
        self.gridLayout.setHorizontalSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.checkWhole = QtGui.QCheckBox(dialog)
        self.checkWhole.setObjectName("checkWhole")
        self.gridLayout.addWidget(self.checkWhole, 2, 2, 1, 1)
        self.findText = QtGui.QLineEdit(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findText.sizePolicy().hasHeightForWidth())
        self.findText.setSizePolicy(sizePolicy)
        self.findText.setMinimumSize(QtCore.QSize(0, 30))
        self.findText.setObjectName("findText")
        self.gridLayout.addWidget(self.findText, 0, 1, 1, 2)
        self.replaceButton = QtGui.QPushButton(dialog)
        self.replaceButton.setObjectName("replaceButton")
        self.gridLayout.addWidget(self.replaceButton, 3, 1, 1, 1)
        self.label_1 = QtGui.QLabel(dialog)
        self.label_1.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.checkSensitive = QtGui.QCheckBox(dialog)
        self.checkSensitive.setObjectName("checkSensitive")
        self.gridLayout.addWidget(self.checkSensitive, 2, 1, 1, 1)
        self.replaceAllButton = QtGui.QPushButton(dialog)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.gridLayout.addWidget(self.replaceAllButton, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(dialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.replaceText = QtGui.QLineEdit(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replaceText.sizePolicy().hasHeightForWidth())
        self.replaceText.setSizePolicy(sizePolicy)
        self.replaceText.setMinimumSize(QtCore.QSize(0, 30))
        self.replaceText.setObjectName("replaceText")
        self.gridLayout.addWidget(self.replaceText, 1, 1, 1, 2)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.findText, self.replaceText)
        dialog.setTabOrder(self.replaceText, self.checkSensitive)
        dialog.setTabOrder(self.checkSensitive, self.checkWhole)
        dialog.setTabOrder(self.checkWhole, self.replaceButton)
        dialog.setTabOrder(self.replaceButton, self.replaceAllButton)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "替换", None, QtGui.QApplication.UnicodeUTF8))
        self.checkWhole.setText(QtGui.QApplication.translate("dialog", "整个单词", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceButton.setText(QtGui.QApplication.translate("dialog", "替换", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("dialog", "找到：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSensitive.setText(QtGui.QApplication.translate("dialog", "大小写敏感", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceAllButton.setText(QtGui.QApplication.translate("dialog", "全部替换", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dialog", "替换为：", None, QtGui.QApplication.UnicodeUTF8))

