# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMaterialDialog.ui'
#
# Created: Fri May 21 16:16:48 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_NewMaterialDlg(object):
    def setupUi(self, Dialog_NewMaterialDlg):
        Dialog_NewMaterialDlg.setObjectName("Dialog_NewMaterialDlg")
        Dialog_NewMaterialDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_NewMaterialDlg.resize(591, 222)
        Dialog_NewMaterialDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_NewMaterialDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_NewMaterialDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_conductivity = QtGui.QCheckBox(Dialog_NewMaterialDlg)
        self.checkBox_conductivity.setObjectName("checkBox_conductivity")
        self.gridLayout.addWidget(self.checkBox_conductivity, 4, 0, 1, 1)
        self.label_hm = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_hm.setObjectName("label_hm")
        self.gridLayout.addWidget(self.label_hm, 4, 2, 1, 1)
        self.LineEdit_atomic_desity = QtGui.QLineEdit(Dialog_NewMaterialDlg)
        self.LineEdit_atomic_desity.setObjectName("LineEdit_atomic_desity")
        self.gridLayout.addWidget(self.LineEdit_atomic_desity, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_kg = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_kg.setObjectName("label_kg")
        self.gridLayout.addWidget(self.label_kg, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_name = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog_NewMaterialDlg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.LineEdit_conductivity = QtGui.QLineEdit(Dialog_NewMaterialDlg)
        self.LineEdit_conductivity.setObjectName("LineEdit_conductivity")
        self.gridLayout.addWidget(self.LineEdit_conductivity, 4, 1, 1, 1)
        self.checkBox_dielectric_constant = QtGui.QCheckBox(Dialog_NewMaterialDlg)
        self.checkBox_dielectric_constant.setObjectName("checkBox_dielectric_constant")
        self.gridLayout.addWidget(self.checkBox_dielectric_constant, 5, 0, 1, 1)
        self.LineEdit_dielectric_constant = QtGui.QLineEdit(Dialog_NewMaterialDlg)
        self.LineEdit_dielectric_constant.setObjectName("LineEdit_dielectric_constant")
        self.gridLayout.addWidget(self.LineEdit_dielectric_constant, 5, 1, 1, 2)
        self.LineEdit_atomic_mass_number = QtGui.QLineEdit(Dialog_NewMaterialDlg)
        self.LineEdit_atomic_mass_number.setObjectName("LineEdit_atomic_mass_number")
        self.gridLayout.addWidget(self.LineEdit_atomic_mass_number, 2, 1, 1, 2)
        self.LineEdit_atomic_number = QtGui.QLineEdit(Dialog_NewMaterialDlg)
        self.LineEdit_atomic_number.setObjectName("LineEdit_atomic_number")
        self.gridLayout.addWidget(self.LineEdit_atomic_number, 1, 1, 1, 2)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_NewMaterialDlg)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.gridLayout.addWidget(self.LineEdit_Name, 0, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_ok = QtGui.QPushButton(Dialog_NewMaterialDlg)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_10.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog_NewMaterialDlg)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_10.addWidget(self.pb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Dialog_NewMaterialDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_NewMaterialDlg)
        Dialog_NewMaterialDlg.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog_NewMaterialDlg.setTabOrder(self.pb_cancel, self.LineEdit_Name)
        Dialog_NewMaterialDlg.setTabOrder(self.LineEdit_Name, self.LineEdit_atomic_number)
        Dialog_NewMaterialDlg.setTabOrder(self.LineEdit_atomic_number, self.LineEdit_atomic_mass_number)
        Dialog_NewMaterialDlg.setTabOrder(self.LineEdit_atomic_mass_number, self.LineEdit_atomic_desity)
        Dialog_NewMaterialDlg.setTabOrder(self.LineEdit_atomic_desity, self.checkBox_conductivity)
        Dialog_NewMaterialDlg.setTabOrder(self.checkBox_conductivity, self.LineEdit_conductivity)
        Dialog_NewMaterialDlg.setTabOrder(self.LineEdit_conductivity, self.checkBox_dielectric_constant)
        Dialog_NewMaterialDlg.setTabOrder(self.checkBox_dielectric_constant, self.LineEdit_dielectric_constant)

    def retranslateUi(self, Dialog_NewMaterialDlg):
        Dialog_NewMaterialDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "新材料", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_conductivity.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料电导率：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_hm.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1/ohm-m", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_atomic_desity.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料原子质量数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_kg.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "kg/m^3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料原子序数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_name.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料密度：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_conductivity.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dielectric_constant.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "指定材料相对介电常数：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_dielectric_constant.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_atomic_mass_number.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_atomic_number.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "NewMaterial", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_NewMaterialDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

