SET(Modeling2DCommand_Srcs
	__init__.py
	Modeling2DGuiTest.py
)
#
SET(AreaConformal_Srcs
./AreaConformal/AreaConformalDialog.py
./AreaConformal/AreaConformalDialog.ui
./AreaConformal/AreaConformalDlgMain.py
./AreaConformal/AreaConformalInstance.py
./AreaConformal/__init__.py
)
SET(AreaFunction_Srcs
./AreaFunction/AreaFunctionCommand.py
./AreaFunction/AreaFunctionDialog.py
./AreaFunction/AreaFunctionDialog.ui
./AreaFunction/AreaFunctionDlgMain.py
./AreaFunction/AreaFunctionInstance.py
./AreaFunction/__init__.py
)
SET(AreaRan_Srcs
./AreaRan/AreaRanCommand.py
./AreaRan/AreaRanDialog.py
./AreaRan/AreaRanDialog.ui
./AreaRan/AreaRanDlgMain.py
./AreaRan/AreaRanInstance.py
./AreaRan/__init__.py
)
SET(AutoFillet_Srcs
./AutoFillet/AutoFilletCommand.py
./AutoFillet/__init__.py
)
SET(BaseUI_Srcs
./BaseUI/BaseDialog.py
./BaseUI/customWidget.py
./BaseUI/customWidget.ui
./BaseUI/__init__.py
)
SET(Beam_Srcs
./Beam/BeamCommand.py
./Beam/BeamDialog.py
./Beam/BeamDialog.ui
./Beam/BeamDialogMain.py
./Beam/BeamDlgMain.py
./Beam/BeamInstance.py
./Beam/__init__.py
)
SET(Boolean_Srcs
./Boolean/BooleanCommand.py
./Boolean/__init__.py
)
SET(CallBack_Srcs
./CallBack/CallBackTools.py
./CallBack/__init__.py
)
SET(Circular_Srcs
./Circular/CircularDialog.py
./Circular/CircularDialog.ui
./Circular/CircularDlgMain.py
./Circular/CircularInstance.py
./Circular/__init__.py
)
SET(Cntr_Srcs
./Cntr/CntrCommand.py
./Cntr/CntrDialog.py
./Cntr/CntrDialog.ui
./Cntr/CntrDlgMain.py
./Cntr/CntrInstance.py
./Cntr/__init__.py
)
SET(CustomTimer_Srcs
./CustomTimer/CustomTimerCommand.py
./CustomTimer/CustomTimerDlgMain.py
./CustomTimer/CustomTimerInstance.py
./CustomTimer/__init__.py
)
SET(DataExportSetting_Srcs
./DataExportSetting/DataExportSettingCommand.py
./DataExportSetting/DataExportSettingDialog.py
./DataExportSetting/DataExportSettingDialog.ui
./DataExportSetting/DataExportSettingDlgMain.py
./DataExportSetting/DataExportSettingInstance.py
./DataExportSetting/__init__.py
)
SET(DefTimer_Srcs
./DefTimer/DefTimerCommand.py
./DefTimer/DefTimerDialog.py
./DefTimer/DefTimerDialog.ui
./DefTimer/DefTimerDlgMain.py
./DefTimer/DefTimerInstance.py
./DefTimer/__init__.py
)
SET(Dimension_Srcs
./Dimension/DimensionInstance.py
./Dimension/__init__.py
)
SET(DisplayDialog_Srcs
./DisplayDialog/DisplayDlgCommand.py
./DisplayDialog/DisplayDlgMain.py
./DisplayDialog/__init__.py
)
SET(Distance_Srcs
./Distance/DistanceCommand.py
./Distance/DistanceInstacne.py
./Distance/__init__.py
)
SET(Driv_Srcs
./Driv/DrivCommand.py
./Driv/DrivDialog.py
./Driv/DrivDialog.ui
./Driv/DrivDialogMain.py
./Driv/DrivInstance.py
./Driv/__init__.py
)
SET(Exps_Srcs
./Exps/ExpsCommand.py
./Exps/ExpsDialog.py
./Exps/ExpsDialog.ui
./Exps/ExpsDialogMain.py
./Exps/ExpsInstance.py
./Exps/__init__.py
)
SET(Feld_Srcs
./Feld/FeldCommand.py
./Feld/FeldDialog.py
./Feld/FeldDialog.ui
./Feld/FeldDialogMain.py
./Feld/FeldInstance.py
./Feld/__init__.py
)
SET(FiledSetting_Srcs
./FiledSetting/FiledSettingCommand.py
./FiledSetting/FiledSettingDialog.py
./FiledSetting/FiledSettingDialog.ui
./FiledSetting/FiledSettingDialogMain.py
./FiledSetting/FiledSettingInstance.py
./FiledSetting/__init__.py
)
SET(Fillet_Srcs
./Fillet/FilletDialog.py
./Fillet/FilletDialog.ui
./Fillet/FilletDlgMain.py
./Fillet/FilletInstance.py
./Fillet/__init__.py
)
SET(Foil_Srcs
./Foil/ExpDlg.py
./Foil/ExpsDlg.py
./Foil/FoilCommand.py
./Foil/FoilDialog.py
./Foil/FoilDialog.ui
./Foil/FoilDialogMain.py
./Foil/FoilInstance.py
./Foil/__init__.py
)
SET(FreeSpace_Srcs
./FreeSpace/FreeDialog.py
./FreeSpace/FreeDialog.ui
./FreeSpace/FreeDialogMain.py
./FreeSpace/FreeSpaceCommand.py
./FreeSpace/FreeSpaceInstance.py
./FreeSpace/__init__.py
)
SET(Grid_Srcs
./Grid/GridCommand.py
./Grid/GridDialog.py
./Grid/GridDialog.ui
./Grid/GridInstance.py
./Grid/__init__.py
)
SET(Gyro_Srcs
./Gyro/GyroCommand.py
./Gyro/GyroDialog.py
./Gyro/GyroDialog.ui
./Gyro/GyroDialogMain.py
./Gyro/GyroInstance.py
./Gyro/__init__.py
)
SET(Inductor_Srcs
./Inductor/IndDialog.py
./Inductor/IndDialog.ui
./Inductor/IndDialogMain.py
./Inductor/InductorCommand.py
./Inductor/InductorInstance.py
./Inductor/__init__.py
)
SET(Ioni_Srcs
./Ioni/IoniCommand.py
./Ioni/IoniDialog.py
./Ioni/IoniDialog.ui
./Ioni/IoniDlgMain.py
./Ioni/IoniInstance.py
./Ioni/__init__.py
)
SET(Line_Srcs
./Line/ItemWidget.py
./Line/ItemWidget.ui
./Line/LineDialog.py
./Line/LineDialog.ui
./Line/LineDlgMain.py
./Line/LineInstance.py
./Line/__init__.py
)
SET(LineConformal_Srcs
./LineConformal/LineConformalDialog.py
./LineConformal/LineConformalDialog.ui
./LineConformal/LineConformalDlgMain.py
./LineConformal/LineConformalInstance.py
./LineConformal/__init__.py
)
SET(MacroParticle_Srcs
./MacroParticle/MacroParticleCommand.py
./MacroParticle/MacroParticleDialog.py
./MacroParticle/MacroParticleDialog.ui
./MacroParticle/MacroParticleInstance.py
./MacroParticle/MarcoParticleDlgMain.py
./MacroParticle/__init__.py
)
SET(Mark_Srcs
./Mark/MarkCommand.py
./Mark/MarkDialog.py
./Mark/MarkDialog.ui
./Mark/MarkDialogMain.py
./Mark/MarkInstance.py
./Mark/__init__.py
)
SET(ModelInfo_Srcs
./ModelInfo/ModeInfoDialog.py
./ModelInfo/ModeInfoDialog.ui
./ModelInfo/ModelInfoCommand.py
./ModelInfo/ModelInfoDialogMain.py
./ModelInfo/ModelInfoInstance.py
./ModelInfo/__init__.py
)
SET(NetStepSetting_Srcs
./NetStepSetting/NetStepSettingCommand.py
./NetStepSetting/NetStepSettingDialog.py
./NetStepSetting/NetStepSettingDialog.ui
./NetStepSetting/NetStepSettingDialogMain.py
./NetStepSetting/NetStepSettingInstance.py
./NetStepSetting/__init__.py
)
SET(NewMaterial_Srcs
./NewMaterial/NewMaterialCommand.py
./NewMaterial/NewMaterialDialog.py
./NewMaterial/NewMaterialDialog.ui
./NewMaterial/NewMaterialDlgMain.py
./NewMaterial/NewMaterialInstance.py
./NewMaterial/__init__.py
)
SET(Observe_Srcs
./Observe/ObserveCommand.py
./Observe/ObserveDialog.py
./Observe/ObserveDialog.ui
./Observe/ObserveDlgMain.py
./Observe/ObserveInstance.py
./Observe/__init__.py
)
SET(ParticleDefine_Srcs
./ParticleDefine/ParticleDefineCommand.py
./ParticleDefine/ParticleDefineDialog.py
./ParticleDefine/ParticleDefineDialog.ui
./ParticleDefine/ParticleDefineDlgMain.py
./ParticleDefine/ParticleDefineInstance.py
./ParticleDefine/__init__.py
)
SET(PhasSpace_Srcs
./PhasSpace/PhasSpaceCommand.py
./PhasSpace/PhasSpaceDialog.py
./PhasSpace/PhasSpaceDialog.ui
./PhasSpace/PhasSpaceDlgMain.py
./PhasSpace/PhasSpaceInstance.py
./PhasSpace/__init__.py
)
SET(Point_Srcs
./Point/PointDialog.py
./Point/PointDialog.ui
./Point/PointDlgMain.py
./Point/PointInstance.py
./Point/__init__.py
)
SET(Popu_Srcs
./Popu/PopuCommand.py
./Popu/PopuDialog.py
./Popu/PopuDialog.ui
./Popu/PopuDialogMain.py
./Popu/PopuInstance.py
./Popu/__init__.py
)
SET(Port_Srcs
./Port/PortCommand.py
./Port/PortDialog.py
./Port/PortDialog.ui
./Port/PortDialogMain.py
./Port/PortInstance.py
./Port/__init__.py
)
SET(Rectangle_Srcs
./Rectangle/RectangleDialog.py
./Rectangle/RectangleDialog.ui
./Rectangle/RectangleDlgMain.py
./Rectangle/RectangleInstance.py
./Rectangle/__init__.py
)
SET(RegularPolygon_Srcs
./RegularPolygon/RegularPolygonDialog.py
./RegularPolygon/RegularPolygonDialog.ui
./RegularPolygon/RegularPolygonDlgMain.py
./RegularPolygon/RegularPolygonInstance.py
./RegularPolygon/__init__.py
)
SET(RunProcessingOptions_Srcs
./RunProcessingOptions/RunProcessingOptionsCommand.py
./RunProcessingOptions/RunProcessingOptionsDialog.py
./RunProcessingOptions/RunProcessingOptionsDialog.ui
./RunProcessingOptions/RunProcessingOptionsDlgMain.py
./RunProcessingOptions/RunProcessingOptionsInstance.py
./RunProcessingOptions/__init__.py
)
SET(Secd_Srcs
./Secd/SecdCommand.py
./Secd/SecdDialog.py
./Secd/SecdDialog.ui
./Secd/SecdDialogMain.py
./Secd/SecdInstance.py
./Secd/__init__.py
)
SET(Sector_Srcs
./Sector/SectorDialog.py
./Sector/SectorDialog.ui
./Sector/SectorDlgMain.py
./Sector/SectorInstance.py
./Sector/__init__.py
)
SET(SingleClickObj_Srcs
./SingleClickObj/SingleClickTheObj.py
./SingleClickObj/__init__.py
)
SET(Symtry_Srcs
./Symtry/SymtryCommand.py
./Symtry/SymtryDialog.py
./Symtry/SymtryDialog.ui
./Symtry/SymtryDialogMain.py
./Symtry/SymtryInstance.py
./Symtry/__init__.py
)
SET(Text_Srcs
./Text/TextDialog.py
./Text/TextDialog.ui
./Text/TextDlgMain.py
./Text/TextInstance.py
./Text/__init__.py
)
SET(Ther_Srcs
./Ther/TherCommand.py
./Ther/TherDialog.py
./Ther/TherDialog.ui
./Ther/TherDialogMain.py
./Ther/TherInstance.py
./Ther/__init__.py
)
SET(TimeDomainSetting_Srcs
./TimeDomainSetting/TimeDomainSettingCommand.py
./TimeDomainSetting/TimeDomainSettingDialog.py
./TimeDomainSetting/TimeDomainSettingDialog.ui
./TimeDomainSetting/TimeDomainSettingDlgMain.py
./TimeDomainSetting/TimeDomainSettingInstance.py
./TimeDomainSetting/__init__.py
)
SET(Vector_Srcs
./Vector/VectorCommand.py
./Vector/VectorDialog.py
./Vector/VectorDialog.ui
./Vector/VectorDlgMain.py
./Vector/VectorInstance.py
./Vector/__init__.py
)
SET(View_Srcs
./View/GridCommand.py
./View/GridDialog.py
./View/GridDialog.ui
./View/ViewCommand.py
./View/__init__.py
)
SET(Wire_Srcs
./Wire/ItemWidget2D.py
./Wire/ItemWidget2D.ui
./Wire/WireDialog.py
./Wire/WireDialog.ui
./Wire/WireDlgMain.py
./Wire/WireInstance.py
./Wire/__init__.py
)
SET(all_Srcs
${AreaConformal_Srcs}
${AreaFunction_Srcs}
${AreaRan_Srcs}
${AutoFillet_Srcs}
${BaseUI_Srcs}
${Beam_Srcs}
${Boolean_Srcs}
${CallBack_Srcs}
${Circular_Srcs}
${Cntr_Srcs}
${CustomTimer_Srcs}
${DataExportSetting_Srcs}
${DefTimer_Srcs}
${Dimension_Srcs}
${DisplayDialog_Srcs}
${Distance_Srcs}
${Driv_Srcs}
${Exps_Srcs}
${Feld_Srcs}
${FiledSetting_Srcs}
${Fillet_Srcs}
${Foil_Srcs}
${FreeSpace_Srcs}
${Grid_Srcs}
${Gyro_Srcs}
${Inductor_Srcs}
${Ioni_Srcs}
${Line_Srcs}
${LineConformal_Srcs}
${MacroParticle_Srcs}
${Mark_Srcs}
${ModelInfo_Srcs}
${NetStepSetting_Srcs}
${NewMaterial_Srcs}
${Observe_Srcs}
${ParticleDefine_Srcs}
${PhasSpace_Srcs}
${Point_Srcs}
${Popu_Srcs}
${Port_Srcs}
${Rectangle_Srcs}
${RegularPolygon_Srcs}
${RunProcessingOptions_Srcs}
${Secd_Srcs}
${Sector_Srcs}
${SingleClickObj_Srcs}
${Symtry_Srcs}
${Text_Srcs}
${Ther_Srcs}
${TimeDomainSetting_Srcs}
${Vector_Srcs}
${View_Srcs}
${Wire_Srcs}
${Modeling2DCommand_Srcs}
)
add_custom_target(Modeling2DCommand ALL SOURCES ${all_Srcs})
fc_copy_sources(Modeling2DCommand "${CMAKE_BINARY_DIR}/Mod/Modeling/Modeling2D/Modeling2DCommand" ${all_Srcs})
install(FILES ${all_Srcs} DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand)
#install(FILES ${Modeling2DCommand_Srcs}   DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand)
#install(FILES ${AreaConformal_Srcs}       DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/AreaConformal)
#install(FILES ${AreaFunction_Srcs}        DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/AreaFunction)
#install(FILES ${AreaRan_Srcs}             DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/AreaRan)
#install(FILES ${AutoFillet_Srcs}          DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/AutoFillet)
#install(FILES ${BaseUI_Srcs}              DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/BaseUI)
#install(FILES ${Beam_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Beam)
#install(FILES ${Boolean_Srcs}             DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Boolean)
#install(FILES ${CallBack_Srcs}            DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/CallBack)
#install(FILES ${Circular_Srcs}            DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Circular)
#install(FILES ${Cntr_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Cntr)
#install(FILES ${CustomTimer_Srcs}         DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/CustomTimer)
#install(FILES ${DataExportSetting_Srcs}   DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/DataExportSetting)
#install(FILES ${DefTimer_Srcs}            DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/DefTimer)
#install(FILES ${Dimension_Srcs}           DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Dimension)
#install(FILES ${DisplayDialog_Srcs}       DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/DisplayDialog)
#install(FILES ${Distance_Srcs}            DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Distance)
#install(FILES ${Driv_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Driv)
#install(FILES ${Exps_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Exps)
#install(FILES ${Feld_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Feld)
#install(FILES ${FiledSetting_Srcs}        DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/FiledSetting)
#install(FILES ${Fillet_Srcs}              DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Fillet)
#install(FILES ${Foil_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Foil)
#install(FILES ${FreeSpace_Srcs}           DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/FreeSpace)
#install(FILES ${Grid_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Grid)
#install(FILES ${Gyro_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Gyro)
#install(FILES ${Inductor_Srcs}            DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Inductor)
#install(FILES ${Ioni_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Ioni)
#install(FILES ${Line_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Line)
#install(FILES ${LineConformal_Srcs}       DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/LineConformal)
#install(FILES ${MacroParticle_Srcs}       DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/MacroParticle)
#install(FILES ${Mark_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Mark)
#install(FILES ${ModelInfo_Srcs}           DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/ModelInfo)
#install(FILES ${NetStepSetting_Srcs}      DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/NetStepSetting)
#install(FILES ${NewMaterial_Srcs}         DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/NewMaterial)
#install(FILES ${Observe_Srcs}             DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Observe)
#install(FILES ${ParticleDefine_Srcs}      DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/ParticleDefine)
#install(FILES ${PhasSpace_Srcs}           DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/PhasSpace)
#install(FILES ${Point_Srcs}               DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Point)
#install(FILES ${Popu_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Popu)
#install(FILES ${Port_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Port)
#install(FILES ${Rectangle_Srcs}           DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Rectangle)
#install(FILES ${RegularPolygon_Srcs}      DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/RegularPolygon)
#install(FILES ${RunProcessingOptions_Srcs} DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/RunProcessingOptions)
#install(FILES ${Secd_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Secd)
#install(FILES ${Sector_Srcs}              DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Sector)
#install(FILES ${SingleClickObj_Srcs}      DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/SingleClickObj)
#install(FILES ${Symtry_Srcs}              DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Symtry)
#install(FILES ${Text_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Text)
#install(FILES ${Ther_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Ther)
#install(FILES ${TimeDomainSetting_Srcs}   DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/TimeDomainSetting)
#install(FILES ${Vector_Srcs}              DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Vector)
#install(FILES ${View_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/View  )
#install(FILES ${Wire_Srcs}                DESTINATION Mod/Modeling/Modeling2D/Modeling2DCommand/Wire  )