# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObjectArrayDialog.ui'
#
# Created: Fri Apr 30 11:21:28 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 364)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_name = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.spinBox_order = QtGui.QSpinBox(self.groupBox)
        self.spinBox_order.setObjectName("spinBox_order")
        self.gridLayout.addWidget(self.spinBox_order, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_Attribute = QtGui.QGroupBox(Dialog)
        self.groupBox_Attribute.setObjectName("groupBox_Attribute")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_Attribute)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_Attribute)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_attribute = QtGui.QComboBox(self.groupBox_Attribute)
        self.comboBox_attribute.setObjectName("comboBox_attribute")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_attribute)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_Attribute)
        self.groupBox_object = QtGui.QGroupBox(Dialog)
        self.groupBox_object.setObjectName("groupBox_object")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_object)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox_object)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_arrayType = QtGui.QComboBox(self.groupBox_object)
        self.comboBox_arrayType.setObjectName("comboBox_arrayType")
        self.comboBox_arrayType.addItem("")
        self.comboBox_arrayType.addItem("")
        self.comboBox_arrayType.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_arrayType, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_object)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_base = QtGui.QComboBox(self.groupBox_object)
        self.comboBox_base.setObjectName("comboBox_base")
        self.gridLayout_2.addWidget(self.comboBox_base, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout_array = QtGui.QGridLayout()
        self.gridLayout_array.setObjectName("gridLayout_array")
        self.verticalLayout_3.addLayout(self.gridLayout_array)
        self.verticalLayout_4.addWidget(self.groupBox_object)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_4.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_4.addWidget(self.pb_cancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Attribute.setTitle(QtGui.QApplication.translate("Dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(0, QtGui.QApplication.translate("Dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(1, QtGui.QApplication.translate("Dialog", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(2, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_attribute.setItemText(3, QtGui.QApplication.translate("Dialog", "Void", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_object.setTitle(QtGui.QApplication.translate("Dialog", "Object of a Array", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Array Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arrayType.setItemText(0, QtGui.QApplication.translate("Dialog", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arrayType.setItemText(1, QtGui.QApplication.translate("Dialog", "ortho", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arrayType.setItemText(2, QtGui.QApplication.translate("Dialog", "polar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

