# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CntrDialog.ui'
#
# Created: Fri May 21 16:11:12 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(531, 438)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(40700, 41300))
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.le_name = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_name.sizePolicy().hasHeightForWidth())
        self.le_name.setSizePolicy(sizePolicy)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.Label_Shadow = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = QtGui.QComboBox(Dialog)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtGui.QCheckBox(self.groupBox_Port)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 13, 1, 1, 2)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Y.sizePolicy().hasHeightForWidth())
        self.label_Y.setSizePolicy(sizePolicy)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout.addWidget(self.label_Y, 0, 2, 1, 1)
        #self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.gridLayout.addWidget(self.LineEdit_end_x, 5, 1, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_X.sizePolicy().hasHeightForWidth())
        self.label_X.setSizePolicy(sizePolicy)
        self.label_X.setObjectName("label_X")
        self.gridLayout.addWidget(self.label_X, 0, 1, 1, 1)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.gridLayout.addWidget(self.radioButton_x, 7, 1, 1, 1)
        #self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.gridLayout.addWidget(self.LineEdit_start_x, 2, 1, 1, 1)
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.gridLayout.addWidget(self.label_end, 5, 0, 1, 1)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.gridLayout.addWidget(self.ComboBox_start, 2, 4, 1, 1)
        #self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(True)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.gridLayout.addWidget(self.LineEdit_end_y, 5, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.label_end_5 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_5.setObjectName("label_end_5")
        self.gridLayout.addWidget(self.label_end_5, 11, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 12, 1, 1, 1)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.gridLayout.addWidget(self.radioButton_y, 7, 2, 1, 1)
        #self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.gridLayout.addWidget(self.LineEdit_start_y, 2, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 8, 1, 1, 1)
        self.label_end_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_2.setObjectName("label_end_2")
        self.gridLayout.addWidget(self.label_end_2, 9, 0, 1, 1)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.gridLayout.addWidget(self.ComboBox_end, 5, 4, 1, 1)
        self.comboBox_timer = QtGui.QComboBox(self.groupBox_Port)
        self.comboBox_timer.setObjectName("comboBox_timer")
        self.comboBox_timer.addItem("")
        self.comboBox_timer.addItem("")
        self.comboBox_timer.addItem("")
        self.gridLayout.addWidget(self.comboBox_timer, 11, 1, 1, 2)
        self.ComboBox = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox.setObjectName("ComboBox")
        self.gridLayout.addWidget(self.ComboBox, 9, 1, 1, 2)
        #self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.gridLayout.addWidget(self.LineEdit_start_z, 2, 3, 1, 1)
        #self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z = Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(True)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.gridLayout.addWidget(self.LineEdit_end_z, 5, 3, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Z.sizePolicy().hasHeightForWidth())
        self.label_Z.setSizePolicy(sizePolicy)
        self.label_Z.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout.addWidget(self.label_Z, 0, 3, 1, 1)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.gridLayout.addWidget(self.radioButton_z, 7, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 11, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_Port, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_10.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_10.addWidget(self.pb_cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_ok, self.pb_cancel)
        Dialog.setTabOrder(self.pb_cancel, self.le_name)
        Dialog.setTabOrder(self.le_name, self.ComboBox_Shadow)
        Dialog.setTabOrder(self.ComboBox_Shadow, self.LineEdit_start_x)
        Dialog.setTabOrder(self.LineEdit_start_x, self.LineEdit_start_y)
        Dialog.setTabOrder(self.LineEdit_start_y, self.LineEdit_start_z)
        Dialog.setTabOrder(self.LineEdit_start_z, self.ComboBox_start)
        Dialog.setTabOrder(self.ComboBox_start, self.LineEdit_end_x)
        Dialog.setTabOrder(self.LineEdit_end_x, self.LineEdit_end_y)
        Dialog.setTabOrder(self.LineEdit_end_y, self.LineEdit_end_z)
        Dialog.setTabOrder(self.LineEdit_end_z, self.ComboBox_end)
        Dialog.setTabOrder(self.ComboBox_end, self.radioButton_x)
        Dialog.setTabOrder(self.radioButton_x, self.radioButton_y)
        Dialog.setTabOrder(self.radioButton_y, self.radioButton_z)
        Dialog.setTabOrder(self.radioButton_z, self.ComboBox)
        Dialog.setTabOrder(self.ComboBox, self.comboBox_timer)
        Dialog.setTabOrder(self.comboBox_timer, self.checkBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "等位图观测", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_name.setText(QtGui.QApplication.translate("Dialog", "Cntr", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog", "观测面", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "等值线填充显示", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_5.setText(QtGui.QApplication.translate("Dialog", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_2.setText(QtGui.QApplication.translate("Dialog", "观测场：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
