# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpsDialog.ui'
#
# Created: Wed Dec  2 12:55:55 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_EmeDlg(object):
    def setupUi(self, Dialog_EmeDlg):
        Dialog_EmeDlg.setObjectName("Dialog_EmeDlg")
        Dialog_EmeDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_EmeDlg.resize(550, 600)
        Dialog_EmeDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_EmeDlg.setMaximumSize(QtCore.QSize(39200, 64200))
        self.gridLayout_10 = QtGui.QGridLayout(Dialog_EmeDlg)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtGui.QScrollArea(Dialog_EmeDlg)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 513, 801))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Label_Name = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout_11.addWidget(self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_11.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout_11.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(12000000, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(0, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_11.addWidget(self.ComboBox_Shadow)
        self.gridLayout_9.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_RField = QtGui.QCheckBox(self.groupBox)
        self.checkBox_RField.setObjectName("checkBox_RField")
        self.horizontalLayout_7.addWidget(self.checkBox_RField)
        self.textEdit_RField = QtGui.QTextBrowser(self.groupBox)
        self.textEdit_RField.setEnabled(False)
        self.textEdit_RField.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_RField.setUndoRedoEnabled(True)
        self.textEdit_RField.setReadOnly(False)
        self.textEdit_RField.setObjectName("textEdit_RField")
        self.horizontalLayout_7.addWidget(self.textEdit_RField)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_TField = QtGui.QCheckBox(self.groupBox)
        self.checkBox_TField.setObjectName("checkBox_TField")
        self.horizontalLayout_6.addWidget(self.checkBox_TField)
        self.textEdit_TField = QtGui.QTextEdit(self.groupBox)
        self.textEdit_TField.setEnabled(False)
        self.textEdit_TField.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_TField.setObjectName("textEdit_TField")
        self.horizontalLayout_6.addWidget(self.textEdit_TField)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_FRate = QtGui.QCheckBox(self.groupBox)
        self.checkBox_FRate.setObjectName("checkBox_FRate")
        self.horizontalLayout_10.addWidget(self.checkBox_FRate)
        self.textEdit_FRate = QtGui.QTextEdit(self.groupBox)
        self.textEdit_FRate.setEnabled(False)
        self.textEdit_FRate.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_FRate.setObjectName("textEdit_FRate")
        self.horizontalLayout_10.addWidget(self.textEdit_FRate)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_Charg = QtGui.QCheckBox(self.groupBox)
        self.checkBox_Charg.setObjectName("checkBox_Charg")
        self.horizontalLayout_9.addWidget(self.checkBox_Charg)
        self.textEdit_Charg = QtGui.QTextEdit(self.groupBox)
        self.textEdit_Charg.setEnabled(False)
        self.textEdit_Charg.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_Charg.setObjectName("textEdit_Charg")
        self.horizontalLayout_9.addWidget(self.textEdit_Charg)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 7, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_strictTiming = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_strictTiming.setEnabled(False)
        self.radioButton_strictTiming.setObjectName("radioButton_strictTiming")
        self.gridLayout_7.addWidget(self.radioButton_strictTiming, 0, 2, 1, 1)
        self.spinBox_timesStep = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_timesStep.setEnabled(False)
        self.spinBox_timesStep.setObjectName("spinBox_timesStep")
        self.gridLayout_7.addWidget(self.spinBox_timesStep, 0, 3, 1, 1)
        self.radioButton_random = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_random.setEnabled(False)
        self.radioButton_random.setChecked(True)
        self.radioButton_random.setObjectName("radioButton_random")
        self.gridLayout_7.addWidget(self.radioButton_random, 0, 1, 1, 1)
        self.checkBox_transmittingInterval = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_transmittingInterval.setObjectName("checkBox_transmittingInterval")
        self.gridLayout_7.addWidget(self.checkBox_transmittingInterval, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 4, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.LineEdit_Dn = QtGui.QLineEdit(self.groupBox_2)
        self.LineEdit_Dn.setEnabled(False)
        self.LineEdit_Dn.setObjectName("LineEdit_Dn")
        self.horizontalLayout_5.addWidget(self.LineEdit_Dn)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 7, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.spinBox_generationRate = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_generationRate.setEnabled(False)
        self.spinBox_generationRate.setProperty("value", 1)
        self.spinBox_generationRate.setObjectName("spinBox_generationRate")
        self.gridLayout_8.addWidget(self.spinBox_generationRate, 0, 3, 1, 1)
        self.ComboBox_particleType = StyledComboBox(self.groupBox_8)
        self.ComboBox_particleType.setEnabled(False)
        self.ComboBox_particleType.setObjectName("ComboBox_particleType")
        self.ComboBox_particleType.addItem("")
        self.ComboBox_particleType.addItem("")
        self.gridLayout_8.addWidget(self.ComboBox_particleType, 0, 1, 1, 1)
        self.checkBox_generationRate = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_generationRate.setObjectName("checkBox_generationRate")
        self.gridLayout_8.addWidget(self.checkBox_generationRate, 0, 2, 1, 1)
        self.checkBox_particleType = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_particleType.setObjectName("checkBox_particleType")
        self.gridLayout_8.addWidget(self.checkBox_particleType, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 4, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_randommm = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_randommm.setEnabled(False)
        self.radioButton_randommm.setChecked(True)
        self.radioButton_randommm.setObjectName("radioButton_randommm")
        self.gridLayout.addWidget(self.radioButton_randommm, 0, 1, 1, 1)
        self.radioButton_alongOutsideFixed = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_alongOutsideFixed.setEnabled(False)
        self.radioButton_alongOutsideFixed.setObjectName("radioButton_alongOutsideFixed")
        self.gridLayout.addWidget(self.radioButton_alongOutsideFixed, 0, 2, 1, 1)
        self.checkBox_outSurface = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_outSurface.setObjectName("checkBox_outSurface")
        self.gridLayout.addWidget(self.checkBox_outSurface, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_surface = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_surface.setObjectName("checkBox_surface")
        self.gridLayout_6.addWidget(self.checkBox_surface, 0, 0, 1, 1)
        self.radioButton_randomm = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_randomm.setEnabled(False)
        self.radioButton_randomm.setChecked(True)
        self.radioButton_randomm.setObjectName("radioButton_randomm")
        self.gridLayout_6.addWidget(self.radioButton_randomm, 0, 1, 1, 1)
        self.radioButton_uniform = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_uniform.setEnabled(False)
        self.radioButton_uniform.setObjectName("radioButton_uniform")
        self.gridLayout_6.addWidget(self.radioButton_uniform, 0, 2, 1, 1)
        self.radioButton_fixed = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_fixed.setEnabled(False)
        self.radioButton_fixed.setObjectName("radioButton_fixed")
        self.gridLayout_6.addWidget(self.radioButton_fixed, 0, 3, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.ComboBox_notInclued = StyledComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_notInclued.sizePolicy().hasHeightForWidth())
        self.ComboBox_notInclued.setSizePolicy(sizePolicy)
        self.ComboBox_notInclued.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_notInclued.setObjectName("ComboBox_notInclued")
        self.ComboBox_notInclued.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_notInclued)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.ComboBox_notIncludedd = StyledComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_notIncludedd.sizePolicy().hasHeightForWidth())
        self.ComboBox_notIncludedd.setSizePolicy(sizePolicy)
        self.ComboBox_notIncludedd.setObjectName("ComboBox_notIncludedd")
        self.ComboBox_notIncludedd.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_notIncludedd)
        self.gridLayout_4.addLayout(self.horizontalLayout_17, 3, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.ComboBox_included = StyledComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_included.sizePolicy().hasHeightForWidth())
        self.ComboBox_included.setSizePolicy(sizePolicy)
        self.ComboBox_included.setObjectName("ComboBox_included")
        self.ComboBox_included.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_included)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.ComboBox_includedd = StyledComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_includedd.sizePolicy().hasHeightForWidth())
        self.ComboBox_includedd.setSizePolicy(sizePolicy)
        self.ComboBox_includedd.setObjectName("ComboBox_includedd")
        self.ComboBox_includedd.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_includedd)
        self.gridLayout_5.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem13, 2, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem14, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 5, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pb_ok = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_18.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_18.addWidget(self.pb_cancel)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 6, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem15, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog_EmeDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_EmeDlg)

    def retranslateUi(self, Dialog_EmeDlg):
        Dialog_EmeDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_EmeDlg", "爆炸式发射", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "Emit_Explo", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "发射面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_EmeDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_EmeDlg", "爆炸式发射", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_RField.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "空间余场.RField(T,X,Y,Z)=", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_RField.setHtml(QtGui.QApplication.translate("Dialog_EmeDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>V/m</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_TField.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "极限场值.TField(T,X,Y,Z)=", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_TField.setHtml(QtGui.QApplication.translate("Dialog_EmeDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.3E7</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>V/m</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FRate.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "等离子体产生率.FRate(T,X,Y,Z)=", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_FRate.setHtml(QtGui.QApplication.translate("Dialog_EmeDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">THETA(T-5,E-9)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>(0&lt;FRate&lt;1)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Charg.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "最小电荷.Charg(T,X,Y,Z)=", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_Charg.setHtml(QtGui.QApplication.translate("Dialog_EmeDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>V/m</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_EmeDlg", "发射选项", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_strictTiming.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "严格定时", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_random.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "随机分布", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_transmittingInterval.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "发射间隔：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "倍时间步长", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>偏移Dn(T,X,Y,Z)=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Dn.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p><span style=\" font-size:14pt;\">m</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(0, QtGui.QApplication.translate("Dialog_EmeDlg", "电子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(1, QtGui.QApplication.translate("Dialog_EmeDlg", "质子", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_generationRate.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "产生率：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_particleType.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "粒子类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "个/网格/步长", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randommm.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_alongOutsideFixed.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_outSurface.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "沿外表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_surface.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "沿表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randomm.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_uniform.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "均匀", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fixed.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog_EmeDlg", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>进一步限定发射区域，使不包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notInclued.setItemText(0, QtGui.QApplication.translate("Dialog_EmeDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notIncludedd.setItemText(0, QtGui.QApplication.translate("Dialog_EmeDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog_EmeDlg", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_included.setItemText(0, QtGui.QApplication.translate("Dialog_EmeDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_includedd.setItemText(0, QtGui.QApplication.translate("Dialog_EmeDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "<html><head/><body><p>进一步限定发射区域，使包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_EmeDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
