# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AreaRanDialog.ui'
#
# Created: Fri May 21 16:08:19 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(547, 477)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.le_name = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_name.sizePolicy().hasHeightForWidth())
        self.le_name.setSizePolicy(sizePolicy)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.Label_Shadow = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = QtGui.QComboBox(Dialog)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.gridLayout_5.addWidget(self.label_end, 2, 0, 1, 1)
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.gridLayout_5.addWidget(self.label_start, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_Port)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 3, 0, 1, 1)
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.gridLayout_5.addWidget(self.LineEdit_start_x, 1, 1, 1, 1)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(True)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.gridLayout_5.addWidget(self.LineEdit_end_x, 2, 1, 1, 1)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(True)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.gridLayout_5.addWidget(self.LineEdit_end_y, 2, 2, 1, 1)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.gridLayout_5.addWidget(self.LineEdit_start_y, 1, 2, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.gridLayout_5.addWidget(self.label_X, 0, 1, 1, 1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_5.addWidget(self.label_Y, 0, 2, 1, 1)
        self.ComboBox_start = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_start, 1, 4, 1, 1)
        self.ComboBox_end = QtGui.QComboBox(self.groupBox_Port)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_end, 2, 4, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_Port)
        self.groupBox_5.setStyleSheet("QGroupBox{border:none}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_x.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_x.sizePolicy().hasHeightForWidth())
        self.radioButton_x.setSizePolicy(sizePolicy)
        self.radioButton_x.setCheckable(True)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_6.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_y.sizePolicy().hasHeightForWidth())
        self.radioButton_y.setSizePolicy(sizePolicy)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_6.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_z.sizePolicy().hasHeightForWidth())
        self.radioButton_z.setSizePolicy(sizePolicy)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_6.addWidget(self.radioButton_z)
        self.gridLayout_5.addWidget(self.groupBox_5, 3, 1, 1, 3)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.gridLayout_5.addWidget(self.LineEdit_start_z, 1, 3, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_5.addWidget(self.label_Z, 0, 3, 1, 1)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(True)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.gridLayout_5.addWidget(self.LineEdit_end_z, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 7, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Port, 1, 0, 1, 1)
        self.groupBox_Port_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_Port_2.setObjectName("groupBox_Port_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_Port_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtGui.QGroupBox(self.groupBox_Port_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_Fourier = QtGui.QCheckBox(self.groupBox)
        self.checkBox_Fourier.setObjectName("checkBox_Fourier")
        self.gridLayout_6.addWidget(self.checkBox_Fourier, 0, 0, 1, 1)
        self.ComboBox_timer = QtGui.QComboBox(self.groupBox)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.gridLayout_6.addWidget(self.ComboBox_timer, 1, 1, 1, 1)
        self.label_end_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_end_3.sizePolicy().hasHeightForWidth())
        self.label_end_3.setSizePolicy(sizePolicy)
        self.label_end_3.setObjectName("label_end_3")
        self.gridLayout_6.addWidget(self.label_end_3, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setStyleSheet("QGroupBox{border:none}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_real = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_real.setEnabled(False)
        self.radioButton_real.setChecked(True)
        self.radioButton_real.setObjectName("radioButton_real")
        self.horizontalLayout_4.addWidget(self.radioButton_real)
        self.radioButton_complex = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_complex.setEnabled(False)
        self.radioButton_complex.setObjectName("radioButton_complex")
        self.horizontalLayout_4.addWidget(self.radioButton_complex)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ComboBox_E1 = QtGui.QComboBox(self.groupBox)
        self.ComboBox_E1.setEnabled(True)
        self.ComboBox_E1.setObjectName("ComboBox_E1")
        self.horizontalLayout_2.addWidget(self.ComboBox_E1)
        self.ComboBox_EDL = QtGui.QComboBox(self.groupBox)
        self.ComboBox_EDL.setEnabled(False)
        self.ComboBox_EDL.setObjectName("ComboBox_EDL")
        self.ComboBox_EDL.addItem("")
        self.ComboBox_EDL.addItem("")
        self.ComboBox_EDL.addItem("")
        self.horizontalLayout_2.addWidget(self.ComboBox_EDL)
        self.ComboBox_SDA = QtGui.QComboBox(self.groupBox)
        self.ComboBox_SDA.setEnabled(False)
        self.ComboBox_SDA.setObjectName("ComboBox_SDA")
        self.ComboBox_SDA.addItem("")
        self.horizontalLayout_2.addWidget(self.ComboBox_SDA)
        self.ComboBox_EM = QtGui.QComboBox(self.groupBox)
        self.ComboBox_EM.setEnabled(False)
        self.ComboBox_EM.setObjectName("ComboBox_EM")
        self.ComboBox_EM.addItem("")
        self.ComboBox_EM.addItem("")
        self.ComboBox_EM.addItem("")
        self.horizontalLayout_2.addWidget(self.ComboBox_EM)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_particle = QtGui.QComboBox(self.groupBox)
        self.comboBox_particle.setEnabled(False)
        self.comboBox_particle.setObjectName("comboBox_particle")
        self.horizontalLayout_7.addWidget(self.comboBox_particle)
        self.comboBox_particleType = QtGui.QComboBox(self.groupBox)
        self.comboBox_particleType.setEnabled(False)
        self.comboBox_particleType.setObjectName("comboBox_particleType")
        self.horizontalLayout_7.addWidget(self.comboBox_particleType)
        self.comboBox_axis = QtGui.QComboBox(self.groupBox)
        self.comboBox_axis.setEnabled(False)
        self.comboBox_axis.setObjectName("comboBox_axis")
        self.horizontalLayout_7.addWidget(self.comboBox_axis)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_start_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_start_2.setObjectName("horizontalLayout_start_2")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_Port_2)
        self.groupBox_3.setStyleSheet("QGroupBox{border:none}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_start_2 = QtGui.QLabel(self.groupBox_3)
        self.label_start_2.setObjectName("label_start_2")
        self.horizontalLayout_5.addWidget(self.label_start_2)
        self.radioButton_field = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_field.setChecked(True)
        self.radioButton_field.setObjectName("radioButton_field")
        self.horizontalLayout_5.addWidget(self.radioButton_field)
        self.radioButton_integral = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_integral.setObjectName("radioButton_integral")
        self.horizontalLayout_5.addWidget(self.radioButton_integral)
        self.radioButton_power = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_power.setObjectName("radioButton_power")
        self.horizontalLayout_5.addWidget(self.radioButton_power)
        self.radioButton_energy = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_energy.setObjectName("radioButton_energy")
        self.horizontalLayout_5.addWidget(self.radioButton_energy)
        self.radioButton_particles = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_particles.setObjectName("radioButton_particles")
        self.horizontalLayout_5.addWidget(self.radioButton_particles)
        self.horizontalLayout_start_2.addWidget(self.groupBox_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_start_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Port_2, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_ok = QtGui.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_10.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_10.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_cancel, self.pb_ok)
        Dialog.setTabOrder(self.pb_ok, self.le_name)
        Dialog.setTabOrder(self.le_name, self.ComboBox_Shadow)
        Dialog.setTabOrder(self.ComboBox_Shadow, self.LineEdit_start_x)
        Dialog.setTabOrder(self.LineEdit_start_x, self.LineEdit_start_y)
        Dialog.setTabOrder(self.LineEdit_start_y, self.LineEdit_start_z)
        Dialog.setTabOrder(self.LineEdit_start_z, self.ComboBox_start)
        Dialog.setTabOrder(self.ComboBox_start, self.LineEdit_end_x)
        Dialog.setTabOrder(self.LineEdit_end_x, self.LineEdit_end_y)
        Dialog.setTabOrder(self.LineEdit_end_y, self.LineEdit_end_z)
        Dialog.setTabOrder(self.LineEdit_end_z, self.ComboBox_end)
        Dialog.setTabOrder(self.ComboBox_end, self.radioButton_x)
        Dialog.setTabOrder(self.radioButton_x, self.radioButton_y)
        Dialog.setTabOrder(self.radioButton_y, self.radioButton_z)
        Dialog.setTabOrder(self.radioButton_z, self.radioButton_field)
        Dialog.setTabOrder(self.radioButton_field, self.radioButton_integral)
        Dialog.setTabOrder(self.radioButton_integral, self.radioButton_power)
        Dialog.setTabOrder(self.radioButton_power, self.radioButton_energy)
        Dialog.setTabOrder(self.radioButton_energy, self.radioButton_particles)
        Dialog.setTabOrder(self.radioButton_particles, self.ComboBox_E1)
        Dialog.setTabOrder(self.ComboBox_E1, self.ComboBox_EDL)
        Dialog.setTabOrder(self.ComboBox_EDL, self.ComboBox_SDA)
        Dialog.setTabOrder(self.ComboBox_SDA, self.ComboBox_EM)
        Dialog.setTabOrder(self.ComboBox_EM, self.comboBox_particle)
        Dialog.setTabOrder(self.comboBox_particle, self.comboBox_particleType)
        Dialog.setTabOrder(self.comboBox_particleType, self.comboBox_axis)
        Dialog.setTabOrder(self.comboBox_axis, self.checkBox_Fourier)
        Dialog.setTabOrder(self.checkBox_Fourier, self.radioButton_real)
        Dialog.setTabOrder(self.radioButton_real, self.radioButton_complex)
        Dialog.setTabOrder(self.radioButton_complex, self.ComboBox_timer)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "空间观测设置", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.le_name.setText(QtGui.QApplication.translate("Dialog", "AreaRan", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog", "类型：空间观测线", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog", "观测类型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port_2.setTitle(QtGui.QApplication.translate("Dialog", "观测项", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "分类子项", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Fourier.setText(QtGui.QApplication.translate("Dialog", "进行快速傅里叶变换：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_3.setText(QtGui.QApplication.translate("Dialog", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_real.setText(QtGui.QApplication.translate("Dialog", "实分析", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_complex.setText(QtGui.QApplication.translate("Dialog", "复分析", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EDL.setItemText(0, QtGui.QApplication.translate("Dialog", "E.DL", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EDL.setItemText(1, QtGui.QApplication.translate("Dialog", "J.DA", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EDL.setItemText(2, QtGui.QApplication.translate("Dialog", "H.DL", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_SDA.setItemText(0, QtGui.QApplication.translate("Dialog", "S.DA", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EM.setItemText(0, QtGui.QApplication.translate("Dialog", "EM", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EM.setItemText(1, QtGui.QApplication.translate("Dialog", "MAGNETIC", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EM.setItemText(2, QtGui.QApplication.translate("Dialog", "ELECTRIC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start_2.setText(QtGui.QApplication.translate("Dialog", "分类项：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_field.setText(QtGui.QApplication.translate("Dialog", "场", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_integral.setText(QtGui.QApplication.translate("Dialog", "场积分", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_power.setText(QtGui.QApplication.translate("Dialog", "场功率", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_energy.setText(QtGui.QApplication.translate("Dialog", "场能量", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_particles.setText(QtGui.QApplication.translate("Dialog", "粒子", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog", "取消", None, QtGui.QApplication.UnicodeUTF8))

