# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vol_Array_Dlg.ui'
#
# Created: Wed May  6 22:23:44 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(353, 340)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_X = QtGui.QLabel(self.groupBox)
        self.label_X.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X.setObjectName("label_X")
        self.gridLayout_3.addWidget(self.label_X, 0, 0, 1, 1)
        self.doubleSpinBox_Y = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Y.setObjectName("doubleSpinBox_Y")
        self.gridLayout_3.addWidget(self.doubleSpinBox_Y, 1, 1, 1, 1)
        self.doubleSpinBox_Z = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Z.setObjectName("doubleSpinBox_Z")
        self.gridLayout_3.addWidget(self.doubleSpinBox_Z, 2, 1, 1, 1)
        self.doubleSpinBox_X = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_X.setObjectName("doubleSpinBox_X")
        self.gridLayout_3.addWidget(self.doubleSpinBox_X, 0, 1, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox)
        self.label_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_3.addWidget(self.label_Z, 2, 0, 1, 1)
        self.label_Y = QtGui.QLabel(self.groupBox)
        self.label_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_3.addWidget(self.label_Y, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSlider = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 1)
        self.doubleSpinBox_progress = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_progress.setProperty("value", 50.0)
        self.doubleSpinBox_progress.setObjectName("doubleSpinBox_progress")
        self.gridLayout_2.addWidget(self.doubleSpinBox_progress, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_outline = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_outline.setChecked(True)
        self.radioButton_outline.setObjectName("radioButton_outline")
        self.horizontalLayout.addWidget(self.radioButton_outline)
        self.radioButton_object = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_object.setObjectName("radioButton_object")
        self.horizontalLayout.addWidget(self.radioButton_object)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.checkBox_savePic = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_savePic.setObjectName("checkBox_savePic")
        self.gridLayout.addWidget(self.checkBox_savePic, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.horizontalLayout_okAndCancel = QtGui.QHBoxLayout()
        self.horizontalLayout_okAndCancel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_okAndCancel.setObjectName("horizontalLayout_okAndCancel")
        self.pushButton_ok = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_cancel)
        self.gridLayout_4.addLayout(self.horizontalLayout_okAndCancel, 3, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QtGui.QApplication.translate("DockWidget", "Clip", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DockWidget", "法向量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("DockWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("DockWidget", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("DockWidget", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DockWidget", "由模型中心沿法向的偏移量", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("DockWidget", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_outline.setText(QtGui.QApplication.translate("DockWidget", "显示轮廓", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_object.setText(QtGui.QApplication.translate("DockWidget", "显示实体", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_savePic.setText(QtGui.QApplication.translate("DockWidget", "保存图片", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("DockWidget", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("DockWidget", "取消", None, QtGui.QApplication.UnicodeUTF8))

