# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PortDialog.ui'
#
# Created: Wed Dec  1 12:09:40 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_PortDlg(object):
    def setupUi(self, Dialog_PortDlg):
        Dialog_PortDlg.setObjectName("Dialog_PortDlg")
        Dialog_PortDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_PortDlg.resize(772, 687)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_PortDlg.sizePolicy().hasHeightForWidth())
        Dialog_PortDlg.setSizePolicy(sizePolicy)
        Dialog_PortDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_PortDlg.setMaximumSize(QtCore.QSize(4160, 6420))
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog_PortDlg)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtGui.QScrollArea(Dialog_PortDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 752, 667))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_Port = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Port.sizePolicy().hasHeightForWidth())
        self.groupBox_Port.setSizePolicy(sizePolicy)
        self.groupBox_Port.setFlat(True)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_Port)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout.addWidget(self.label_Y, 0, 3, 1, 1)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout.addWidget(self.label_Z, 0, 4, 1, 1)
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.gridLayout.addWidget(self.LineEdit_start_x, 1, 1, 1, 2)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.gridLayout.addWidget(self.LineEdit_start_y, 1, 3, 1, 1)
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 1, 0, 1, 1)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.gridLayout.addWidget(self.LineEdit_start_z, 1, 4, 1, 1)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.gridLayout.addWidget(self.ComboBox_start, 1, 5, 1, 1)
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.gridLayout.addWidget(self.label_end, 2, 0, 1, 1)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.gridLayout.addWidget(self.LineEdit_end_x, 2, 1, 1, 2)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.gridLayout.addWidget(self.LineEdit_end_z, 2, 4, 1, 1)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.gridLayout.addWidget(self.LineEdit_end_y, 2, 3, 1, 1)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.gridLayout.addWidget(self.radioButton_y, 3, 3, 1, 1)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.gridLayout.addWidget(self.radioButton_z, 3, 4, 1, 1)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.gridLayout.addWidget(self.radioButton_x, 3, 1, 1, 1)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.gridLayout.addWidget(self.ComboBox_end, 2, 5, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.gridLayout.addWidget(self.label_X, 0, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_Port)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.radioButton_opposite = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_opposite.setChecked(True)
        self.radioButton_opposite.setObjectName("radioButton_opposite")
        self.horizontalLayout_2.addWidget(self.radioButton_opposite)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.radioButton_forward = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_forward.setObjectName("radioButton_forward")
        self.horizontalLayout_2.addWidget(self.radioButton_forward)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.groupBox_Port)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LineEdit_DX1 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_DX1.setEnabled(False)
        self.LineEdit_DX1.setObjectName("LineEdit_DX1")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX1)
        self.LineEdit_DX2 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_DX2.setEnabled(False)
        self.LineEdit_DX2.setObjectName("LineEdit_DX2")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX2)
        self.LineEdit_DX3 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_DX3.setEnabled(False)
        self.LineEdit_DX3.setObjectName("LineEdit_DX3")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX3)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_x = QtGui.QCheckBox(self.groupBox)
        self.checkBox_x.setObjectName("checkBox_x")
        self.horizontalLayout_6.addWidget(self.checkBox_x)
        self.checkBox_y = QtGui.QCheckBox(self.groupBox)
        self.checkBox_y.setObjectName("checkBox_y")
        self.horizontalLayout_6.addWidget(self.checkBox_y)
        self.checkBox_z = QtGui.QCheckBox(self.groupBox)
        self.checkBox_z.setObjectName("checkBox_z")
        self.horizontalLayout_6.addWidget(self.checkBox_z)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_vport = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_vport.setObjectName("checkBox_vport")
        self.gridLayout_2.addWidget(self.checkBox_vport, 0, 0, 1, 1)
        self.LineEdit_vport = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.LineEdit_vport.setEnabled(False)
        self.LineEdit_vport.setObjectName("LineEdit_vport")
        self.gridLayout_2.addWidget(self.LineEdit_vport, 0, 1, 1, 1)
        self.checkBox_scale = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_scale.setObjectName("checkBox_scale")
        self.gridLayout_2.addWidget(self.checkBox_scale, 0, 2, 1, 1)
        self.LineEdit_scale = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.LineEdit_scale.setEnabled(False)
        self.LineEdit_scale.setObjectName("LineEdit_scale")
        self.gridLayout_2.addWidget(self.LineEdit_scale, 0, 3, 1, 1)
        self.checkBox_Ft = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_Ft.setObjectName("checkBox_Ft")
        self.gridLayout_2.addWidget(self.checkBox_Ft, 1, 0, 1, 1)
        self.checkBox_GE2 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_GE2.setObjectName("checkBox_GE2")
        self.gridLayout_2.addWidget(self.checkBox_GE2, 2, 0, 1, 1)
        self.checkBox_GE3 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_GE3.setObjectName("checkBox_GE3")
        self.gridLayout_2.addWidget(self.checkBox_GE3, 3, 0, 1, 1)
        self.checkBox_FT = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_FT.setEnabled(False)
        self.checkBox_FT.setObjectName("checkBox_FT")
        self.gridLayout_2.addWidget(self.checkBox_FT, 4, 0, 1, 1)
        self.ComboBox_FT = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_FT.setEnabled(True)
        self.ComboBox_FT.setObjectName("ComboBox_FT")
        self.ComboBox_FT.addItem("")
        self.gridLayout_2.addWidget(self.ComboBox_FT, 4, 1, 1, 1)
        self.checkBox_circuit = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_circuit.setEnabled(False)
        self.checkBox_circuit.setObjectName("checkBox_circuit")
        self.gridLayout_2.addWidget(self.checkBox_circuit, 5, 0, 1, 1)
        self.LineEdit_circuit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.LineEdit_circuit.setEnabled(False)
        self.LineEdit_circuit.setObjectName("LineEdit_circuit")
        self.gridLayout_2.addWidget(self.LineEdit_circuit, 5, 1, 1, 1)
        self.label_obs = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_obs.setObjectName("label_obs")
        self.gridLayout_2.addWidget(self.label_obs, 5, 2, 1, 1)
        self.lineEdit_obs = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_obs.setObjectName("lineEdit_obs")
        self.gridLayout_2.addWidget(self.lineEdit_obs, 5, 3, 1, 1)
        self.LineEdit_Ft = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.LineEdit_Ft.setEnabled(False)
        self.LineEdit_Ft.setMaximumSize(QtCore.QSize(16777215, 60))
        self.LineEdit_Ft.setObjectName("LineEdit_Ft")
        self.gridLayout_2.addWidget(self.LineEdit_Ft, 1, 1, 1, 3)
        self.LineEdit_GE2 = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.LineEdit_GE2.setEnabled(False)
        self.LineEdit_GE2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.LineEdit_GE2.setObjectName("LineEdit_GE2")
        self.gridLayout_2.addWidget(self.LineEdit_GE2, 2, 1, 1, 3)
        self.LineEdit_GE3 = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.LineEdit_GE3.setEnabled(False)
        self.LineEdit_GE3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.LineEdit_GE3.setObjectName("LineEdit_GE3")
        self.gridLayout_2.addWidget(self.LineEdit_GE3, 3, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_lap = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_lap.setEnabled(True)
        self.checkBox_lap.setObjectName("checkBox_lap")
        self.horizontalLayout_14.addWidget(self.checkBox_lap)
        self.spinBox_num = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_num.setEnabled(False)
        self.spinBox_num.setMinimum(2)
        self.spinBox_num.setMaximum(5)
        self.spinBox_num.setObjectName("spinBox_num")
        self.horizontalLayout_14.addWidget(self.spinBox_num)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ComboBox_lap1 = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap1.setEnabled(False)
        self.ComboBox_lap1.setObjectName("ComboBox_lap1")
        self.ComboBox_lap1.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBox_lap1)
        self.spinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox.setEnabled(False)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.ComboBox_lap2 = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap2.setEnabled(False)
        self.ComboBox_lap2.setObjectName("ComboBox_lap2")
        self.ComboBox_lap2.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBox_lap2)
        self.spinBox_2 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.ComboBox_lap3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap3.setEnabled(False)
        self.ComboBox_lap3.setObjectName("ComboBox_lap3")
        self.ComboBox_lap3.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBox_lap3)
        self.spinBox_3 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ComboBox_lap4 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap4.setEnabled(False)
        self.ComboBox_lap4.setObjectName("ComboBox_lap4")
        self.ComboBox_lap4.addItem("")
        self.horizontalLayout_11.addWidget(self.ComboBox_lap4)
        self.spinBox_4 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_11.addWidget(self.spinBox_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ComboBox_lap5 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap5.setEnabled(False)
        self.ComboBox_lap5.setObjectName("ComboBox_lap5")
        self.ComboBox_lap5.addItem("")
        self.horizontalLayout_12.addWidget(self.ComboBox_lap5)
        self.spinBox_5 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_12.addWidget(self.spinBox_5)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pb_ok = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout_6.addWidget(self.pb_ok, 0, 1, 1, 1)
        self.pb_cancel = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_6.addWidget(self.pb_cancel, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(Dialog_PortDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PortDlg)
        Dialog_PortDlg.setTabOrder(self.LineEdit_Name, self.ComboBox_Shadow)
        Dialog_PortDlg.setTabOrder(self.ComboBox_Shadow, self.checkBox_x)
        Dialog_PortDlg.setTabOrder(self.checkBox_x, self.checkBox_y)
        Dialog_PortDlg.setTabOrder(self.checkBox_y, self.checkBox_z)
        Dialog_PortDlg.setTabOrder(self.checkBox_z, self.LineEdit_DX1)
        Dialog_PortDlg.setTabOrder(self.LineEdit_DX1, self.LineEdit_DX2)
        Dialog_PortDlg.setTabOrder(self.LineEdit_DX2, self.LineEdit_DX3)
        Dialog_PortDlg.setTabOrder(self.LineEdit_DX3, self.ComboBox_lap3)
        Dialog_PortDlg.setTabOrder(self.ComboBox_lap3, self.spinBox_3)
        Dialog_PortDlg.setTabOrder(self.spinBox_3, self.spinBox_4)
        Dialog_PortDlg.setTabOrder(self.spinBox_4, self.ComboBox_lap5)
        Dialog_PortDlg.setTabOrder(self.ComboBox_lap5, self.spinBox_5)

    def retranslateUi(self, Dialog_PortDlg):
        Dialog_PortDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_PortDlg", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_PortDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_PortDlg", "AreaPort", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_PortDlg", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_PortDlg", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_PortDlg", " Z", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_PortDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_PortDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_PortDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_PortDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_opposite.setText(QtGui.QApplication.translate("Dialog_PortDlg", "反向", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_forward.setText(QtGui.QApplication.translate("Dialog_PortDlg", "正向", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_PortDlg", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX1.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_vport.setText(QtGui.QApplication.translate("Dialog_PortDlg", "相对相速比.VPORT =", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_vport.setText(QtGui.QApplication.translate("Dialog_PortDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_scale.setText(QtGui.QApplication.translate("Dialog_PortDlg", "法向修正.SCALE =", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_scale.setText(QtGui.QApplication.translate("Dialog_PortDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Ft.setText(QtGui.QApplication.translate("Dialog_PortDlg", "输入场时间分布.F(T) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GE2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "空间分布.GE2(R,P,Z) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GE3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "空间分布.GE3(R,P,Z) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FT.setText(QtGui.QApplication.translate("Dialog_PortDlg", "线上电压归一化为F(T) ", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_FT.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "AreaPort.LINE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_circuit.setText(QtGui.QApplication.translate("Dialog_PortDlg", "circuit输入时间 =   ", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_circuit.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0.002E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_obs.setText(QtGui.QApplication.translate("Dialog_PortDlg", "   OBSERVE名称=", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_lap.setText(QtGui.QApplication.translate("Dialog_PortDlg", "拉普拉斯", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap1.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap2.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap3.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap4.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap5.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_PortDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_PortDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
