# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CntrDlg.ui'
#
# Created: Tue Nov 26 16:24:14 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_CntrDlg(object):
    def setupUi(self, Dialog_CntrDlg):
        Dialog_CntrDlg.setObjectName("Dialog_CntrDlg")
        Dialog_CntrDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_CntrDlg.resize(366, 508)
        Dialog_CntrDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_CntrDlg.setMaximumSize(QtCore.QSize(40700, 41300))
        self.gridLayout = QtGui.QGridLayout(Dialog_CntrDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_CntrDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(Dialog_CntrDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(Dialog_CntrDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_CntrDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(Dialog_CntrDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(Dialog_CntrDlg)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(12000000, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_CntrDlg)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_end_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        self.LineEdit_end_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(False)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        self.LineEdit_end_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(False)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 3, 0, 1, 2)
        self.horizontalLayout_end_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_3.setObjectName("horizontalLayout_end_3")
        self.label_end_3 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_3.setObjectName("label_end_3")
        self.horizontalLayout_end_3.addWidget(self.label_end_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_3, 9, 0, 1, 1)
        self.horizontalLayout_end_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_2.setObjectName("horizontalLayout_end_2")
        self.label_end_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_2.setObjectName("label_end_2")
        self.horizontalLayout_end_2.addWidget(self.label_end_2)
        self.ComboBox = StyledComboBox(self.groupBox_Port)
        self.ComboBox.setObjectName("ComboBox")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.horizontalLayout_end_2.addWidget(self.ComboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_2, 7, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 8, 0, 1, 1)
        self.horizontalLayout_end_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_4.setObjectName("horizontalLayout_end_4")
        self.ComboBox_timer = StyledComboBox(self.groupBox_Port)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.horizontalLayout_end_4.addWidget(self.ComboBox_timer)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_4, 9, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_Port)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 2)
        self.horizontalLayout_end_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_5.setObjectName("horizontalLayout_end_5")
        self.checkBox = QtGui.QCheckBox(self.groupBox_Port)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_end_5.addWidget(self.checkBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_5, 11, 1, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        self.LineEdit_start_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        self.LineEdit_start_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        self.LineEdit_start_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 1, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 10, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_X.sizePolicy().hasHeightForWidth())
        self.label_X.setSizePolicy(sizePolicy)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_3.addWidget(self.label_X)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Y.sizePolicy().hasHeightForWidth())
        self.label_Y.setSizePolicy(sizePolicy)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_3.addWidget(self.label_Y)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Z.sizePolicy().hasHeightForWidth())
        self.label_Z.setSizePolicy(sizePolicy)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_3.addWidget(self.label_Z)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_Port, 3, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 0, 0, 1, 1)

        self.retranslateUi(Dialog_CntrDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_CntrDlg)

    def retranslateUi(self, Dialog_CntrDlg):
        Dialog_CntrDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_CntrDlg", "等位图观测", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "Cntr", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_CntrDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_CntrDlg", "观测面", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_CntrDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_3.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_2.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "观测场：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(0, QtGui.QApplication.translate("Dialog_CntrDlg", "E1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(1, QtGui.QApplication.translate("Dialog_CntrDlg", "E2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(2, QtGui.QApplication.translate("Dialog_CntrDlg", "E3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(3, QtGui.QApplication.translate("Dialog_CntrDlg", "B1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(4, QtGui.QApplication.translate("Dialog_CntrDlg", "B2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(5, QtGui.QApplication.translate("Dialog_CntrDlg", "B3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(6, QtGui.QApplication.translate("Dialog_CntrDlg", "J1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(7, QtGui.QApplication.translate("Dialog_CntrDlg", "J2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(8, QtGui.QApplication.translate("Dialog_CntrDlg", "J3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(9, QtGui.QApplication.translate("Dialog_CntrDlg", "Q0", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(10, QtGui.QApplication.translate("Dialog_CntrDlg", "E1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(11, QtGui.QApplication.translate("Dialog_CntrDlg", "E2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(12, QtGui.QApplication.translate("Dialog_CntrDlg", "E3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(13, QtGui.QApplication.translate("Dialog_CntrDlg", "B1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(14, QtGui.QApplication.translate("Dialog_CntrDlg", "B2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(15, QtGui.QApplication.translate("Dialog_CntrDlg", "B3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(16, QtGui.QApplication.translate("Dialog_CntrDlg", "E1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(17, QtGui.QApplication.translate("Dialog_CntrDlg", "E2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(18, QtGui.QApplication.translate("Dialog_CntrDlg", "E3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(19, QtGui.QApplication.translate("Dialog_CntrDlg", "B1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(20, QtGui.QApplication.translate("Dialog_CntrDlg", "B2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(21, QtGui.QApplication.translate("Dialog_CntrDlg", "B3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(22, QtGui.QApplication.translate("Dialog_CntrDlg", "PHST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(23, QtGui.QApplication.translate("Dialog_CntrDlg", "|B|", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox.setItemText(24, QtGui.QApplication.translate("Dialog_CntrDlg", "|E|", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog_CntrDlg", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog_CntrDlg", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog_CntrDlg", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "等值线填充显示", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_CntrDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_CntrDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
