# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DefaultTimerDlg.ui'
#
# Created: Tue Nov 26 16:24:15 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_DefaultTimerDlg(object):
    def setupUi(self, DefaultTimerDlg):
        DefaultTimerDlg.setObjectName("DefaultTimerDlg")
        DefaultTimerDlg.resize(257, 243)
        DefaultTimerDlg.setMaximumSize(QtCore.QSize(36700, 35500))
        DefaultTimerDlg.setModal(False)
        self.gridLayout = QtGui.QGridLayout(DefaultTimerDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_period_2 = QtGui.QLabel(DefaultTimerDlg)
        self.label_period_2.setObjectName("label_period_2")
        self.horizontalLayout_6.addWidget(self.label_period_2)
        self.LineEdit_Discrete_time = Modeling.Common.Tools.Completer.AutoCompleteEdit(DefaultTimerDlg)
        self.LineEdit_Discrete_time.setReadOnly(False)
        self.LineEdit_Discrete_time.setObjectName("LineEdit_Discrete_time")
        self.horizontalLayout_6.addWidget(self.LineEdit_Discrete_time)
        self.gridLayout.addLayout(self.horizontalLayout_6, 10, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_end = QtGui.QLabel(DefaultTimerDlg)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_3.addWidget(self.label_end)
        self.LineEdit_end = Modeling.Common.Tools.Completer.AutoCompleteEdit(DefaultTimerDlg)
        self.LineEdit_end.setObjectName("LineEdit_end")
        self.horizontalLayout_3.addWidget(self.LineEdit_end)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_setTime = QtGui.QLabel(DefaultTimerDlg)
        self.label_setTime.setObjectName("label_setTime")
        self.horizontalLayout.addWidget(self.label_setTime)
        self.radioButton_step = QtGui.QRadioButton(DefaultTimerDlg)
        self.radioButton_step.setChecked(True)
        self.radioButton_step.setObjectName("radioButton_step")
        self.horizontalLayout.addWidget(self.radioButton_step)
        self.radioButton_simulate = QtGui.QRadioButton(DefaultTimerDlg)
        self.radioButton_simulate.setObjectName("radioButton_simulate")
        self.horizontalLayout.addWidget(self.radioButton_simulate)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_period = QtGui.QLabel(DefaultTimerDlg)
        self.label_period.setObjectName("label_period")
        self.horizontalLayout_4.addWidget(self.label_period)
        self.LineEdit_period = Modeling.Common.Tools.Completer.AutoCompleteEdit(DefaultTimerDlg)
        self.LineEdit_period.setObjectName("LineEdit_period")
        self.horizontalLayout_4.addWidget(self.LineEdit_period)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(DefaultTimerDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(DefaultTimerDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 12, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.typeLabel = QtGui.QLabel(DefaultTimerDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setObjectName("typeLabel")
        self.horizontalLayout_5.addWidget(self.typeLabel)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(DefaultTimerDlg)
        self.LineEdit_Name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_5.addWidget(self.LineEdit_Name)
        self.nameLabel = QtGui.QLabel(DefaultTimerDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_5.addWidget(self.nameLabel)
        self.typeComboBox = StyledComboBox(DefaultTimerDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeComboBox.sizePolicy().hasHeightForWidth())
        self.typeComboBox.setSizePolicy(sizePolicy)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.typeComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_start = QtGui.QLabel(DefaultTimerDlg)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_2.addWidget(self.label_start)
        self.LineEdit_start = Modeling.Common.Tools.Completer.AutoCompleteEdit(DefaultTimerDlg)
        self.LineEdit_start.setObjectName("LineEdit_start")
        self.horizontalLayout_2.addWidget(self.LineEdit_start)
        self.label = QtGui.QLabel(DefaultTimerDlg)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 11, 0, 1, 1)

        self.retranslateUi(DefaultTimerDlg)
        QtCore.QMetaObject.connectSlotsByName(DefaultTimerDlg)
        DefaultTimerDlg.setTabOrder(self.LineEdit_Name, self.typeComboBox)
        DefaultTimerDlg.setTabOrder(self.typeComboBox, self.radioButton_step)
        DefaultTimerDlg.setTabOrder(self.radioButton_step, self.radioButton_simulate)
        DefaultTimerDlg.setTabOrder(self.radioButton_simulate, self.LineEdit_start)
        DefaultTimerDlg.setTabOrder(self.LineEdit_start, self.LineEdit_end)
        DefaultTimerDlg.setTabOrder(self.LineEdit_end, self.LineEdit_period)
        DefaultTimerDlg.setTabOrder(self.LineEdit_period, self.LineEdit_Discrete_time)
        DefaultTimerDlg.setTabOrder(self.LineEdit_Discrete_time, self.pushButton_ok)
        DefaultTimerDlg.setTabOrder(self.pushButton_ok, self.pushButton)

    def retranslateUi(self, DefaultTimerDlg):
        DefaultTimerDlg.setWindowTitle(QtGui.QApplication.translate("DefaultTimerDlg", "Default Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_period_2.setText(QtGui.QApplication.translate("DefaultTimerDlg", "离散时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Discrete_time.setText(QtGui.QApplication.translate("DefaultTimerDlg", "10 12 15 24 85 168 468", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("DefaultTimerDlg", "结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end.setText(QtGui.QApplication.translate("DefaultTimerDlg", "100000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_setTime.setText(QtGui.QApplication.translate("DefaultTimerDlg", "定时基准", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_step.setText(QtGui.QApplication.translate("DefaultTimerDlg", "按时间步数", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_simulate.setText(QtGui.QApplication.translate("DefaultTimerDlg", "按模拟时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_period.setText(QtGui.QApplication.translate("DefaultTimerDlg", "定时周期", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_period.setText(QtGui.QApplication.translate("DefaultTimerDlg", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("DefaultTimerDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DefaultTimerDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("DefaultTimerDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("DefaultTimerDlg", "DefTimer", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("DefaultTimerDlg", "类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(0, QtGui.QApplication.translate("DefaultTimerDlg", "周期型", None, QtGui.QApplication.UnicodeUTF8))
        self.typeComboBox.setItemText(1, QtGui.QApplication.translate("DefaultTimerDlg", "离散型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("DefaultTimerDlg", "起始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start.setText(QtGui.QApplication.translate("DefaultTimerDlg", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DefaultTimerDlg", "步", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
