# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmgDlg.ui'
#
# Created: Wed May  6 19:19:06 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_EmgDlg(object):
    def setupUi(self, Dialog_EmgDlg):
        Dialog_EmgDlg.setObjectName("Dialog_EmgDlg")
        Dialog_EmgDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_EmgDlg.resize(458, 757)
        Dialog_EmgDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_EmgDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_10 = QtGui.QGridLayout(Dialog_EmgDlg)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtGui.QScrollArea(Dialog_EmgDlg)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 421, 757))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Label_Name_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_13.addWidget(self.Label_Name_2)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_EmgDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_13.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_13.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_13.addWidget(self.ComboBox_Shadow)
        self.gridLayout_9.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 6, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 8, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.radioButton_AxiasX = QtGui.QRadioButton(self.groupBox)
        self.radioButton_AxiasX.setChecked(True)
        self.radioButton_AxiasX.setObjectName("radioButton_AxiasX")
        self.horizontalLayout_10.addWidget(self.radioButton_AxiasX)
        self.radioButton_AxiasY = QtGui.QRadioButton(self.groupBox)
        self.radioButton_AxiasY.setObjectName("radioButton_AxiasY")
        self.horizontalLayout_10.addWidget(self.radioButton_AxiasY)
        self.radioButton_AxiasZ = QtGui.QRadioButton(self.groupBox)
        self.radioButton_AxiasZ.setObjectName("radioButton_AxiasZ")
        self.horizontalLayout_10.addWidget(self.radioButton_AxiasZ)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 7, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.LineEdit_LaunchX = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_LaunchX.setEnabled(True)
        self.LineEdit_LaunchX.setObjectName("LineEdit_LaunchX")
        self.horizontalLayout_12.addWidget(self.LineEdit_LaunchX)
        self.LineEdit_LaunchY = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_LaunchY.setObjectName("LineEdit_LaunchY")
        self.horizontalLayout_12.addWidget(self.LineEdit_LaunchY)
        self.LineEdit_LaunchZ = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_LaunchZ.setObjectName("LineEdit_LaunchZ")
        self.horizontalLayout_12.addWidget(self.LineEdit_LaunchZ)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 9, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.LineEdit_IT = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_IT.setEnabled(True)
        self.LineEdit_IT.setObjectName("LineEdit_IT")
        self.horizontalLayout_11.addWidget(self.LineEdit_IT)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.LineEdit_magnetic = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_magnetic.setEnabled(True)
        self.LineEdit_magnetic.setObjectName("LineEdit_magnetic")
        self.horizontalLayout_7.addWidget(self.LineEdit_magnetic)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.LineEdit_radius = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_radius.setObjectName("LineEdit_radius")
        self.horizontalLayout_7.addWidget(self.LineEdit_radius)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.LineEdit_VerticalMomentum = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_VerticalMomentum.setEnabled(True)
        self.LineEdit_VerticalMomentum.setObjectName("LineEdit_VerticalMomentum")
        self.horizontalLayout_9.addWidget(self.LineEdit_VerticalMomentum)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.LineEdit_HorizontalMomentum = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_HorizontalMomentum.setObjectName("LineEdit_HorizontalMomentum")
        self.horizontalLayout_9.addWidget(self.LineEdit_HorizontalMomentum)
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 10, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_surface = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_surface.setObjectName("checkBox_surface")
        self.gridLayout_6.addWidget(self.checkBox_surface, 0, 0, 1, 1)
        self.radioButton_randomm = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_randomm.setEnabled(False)
        self.radioButton_randomm.setChecked(True)
        self.radioButton_randomm.setObjectName("radioButton_randomm")
        self.gridLayout_6.addWidget(self.radioButton_randomm, 0, 1, 1, 1)
        self.radioButton_uniform = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_uniform.setEnabled(False)
        self.radioButton_uniform.setObjectName("radioButton_uniform")
        self.gridLayout_6.addWidget(self.radioButton_uniform, 0, 2, 1, 1)
        self.radioButton_fixed = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_fixed.setEnabled(False)
        self.radioButton_fixed.setObjectName("radioButton_fixed")
        self.gridLayout_6.addWidget(self.radioButton_fixed, 0, 3, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 3, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_strictTiming = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_strictTiming.setEnabled(False)
        self.radioButton_strictTiming.setObjectName("radioButton_strictTiming")
        self.gridLayout_7.addWidget(self.radioButton_strictTiming, 0, 2, 1, 1)
        self.spinBox_timesStep = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_timesStep.setEnabled(False)
        self.spinBox_timesStep.setObjectName("spinBox_timesStep")
        self.gridLayout_7.addWidget(self.spinBox_timesStep, 0, 3, 1, 1)
        self.radioButton_random = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_random.setEnabled(False)
        self.radioButton_random.setChecked(True)
        self.radioButton_random.setObjectName("radioButton_random")
        self.gridLayout_7.addWidget(self.radioButton_random, 0, 1, 1, 1)
        self.checkBox_transmittingInterval = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_transmittingInterval.setObjectName("checkBox_transmittingInterval")
        self.gridLayout_7.addWidget(self.checkBox_transmittingInterval, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 4, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.LineEdit_Dn = QtGui.QTextEdit(self.groupBox_2)
        self.LineEdit_Dn.setEnabled(False)
        self.LineEdit_Dn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.LineEdit_Dn.setObjectName("LineEdit_Dn")
        self.horizontalLayout_5.addWidget(self.LineEdit_Dn)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_randommm = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_randommm.setEnabled(False)
        self.radioButton_randommm.setChecked(True)
        self.radioButton_randommm.setObjectName("radioButton_randommm")
        self.gridLayout.addWidget(self.radioButton_randommm, 0, 1, 1, 1)
        self.radioButton_alongOutsideFixed = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_alongOutsideFixed.setEnabled(False)
        self.radioButton_alongOutsideFixed.setObjectName("radioButton_alongOutsideFixed")
        self.gridLayout.addWidget(self.radioButton_alongOutsideFixed, 0, 2, 1, 1)
        self.checkBox_outSurface = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_outSurface.setObjectName("checkBox_outSurface")
        self.gridLayout.addWidget(self.checkBox_outSurface, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.spinBox_generationRate = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_generationRate.setEnabled(False)
        self.spinBox_generationRate.setObjectName("spinBox_generationRate")
        self.gridLayout_8.addWidget(self.spinBox_generationRate, 0, 3, 1, 1)
        self.ComboBox_particleType = StyledComboBox(self.groupBox_8)
        self.ComboBox_particleType.setEnabled(False)
        self.ComboBox_particleType.setObjectName("ComboBox_particleType")
        self.ComboBox_particleType.addItem("")
        self.ComboBox_particleType.addItem("")
        self.gridLayout_8.addWidget(self.ComboBox_particleType, 0, 1, 1, 1)
        self.checkBox_generationRate = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_generationRate.setObjectName("checkBox_generationRate")
        self.gridLayout_8.addWidget(self.checkBox_generationRate, 0, 2, 1, 1)
        self.checkBox_particleType = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_particleType.setObjectName("checkBox_particleType")
        self.gridLayout_8.addWidget(self.checkBox_particleType, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 4, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 5, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 7, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.ComboBox_notInclued = StyledComboBox(self.groupBox_3)
        self.ComboBox_notInclued.setObjectName("ComboBox_notInclued")
        self.ComboBox_notInclued.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_notInclued)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.ComboBox_notIncludedd = StyledComboBox(self.groupBox_3)
        self.ComboBox_notIncludedd.setObjectName("ComboBox_notIncludedd")
        self.ComboBox_notIncludedd.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_notIncludedd)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 2, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.ComboBox_included = StyledComboBox(self.groupBox_4)
        self.ComboBox_included.setObjectName("ComboBox_included")
        self.ComboBox_included.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_included)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.ComboBox_includedd = StyledComboBox(self.groupBox_4)
        self.ComboBox_includedd.setObjectName("ComboBox_includedd")
        self.ComboBox_includedd.addItem("")
        self.horizontalLayout_17.addWidget(self.ComboBox_includedd)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 3, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 5, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem17, 6, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_ok = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_18.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_18.addWidget(self.pushButton)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog_EmgDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_EmgDlg)

    def retranslateUi(self, Dialog_EmgDlg):
        Dialog_EmgDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_EmgDlg", "回旋发射", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "Emit_Gyro", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "发射体：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_EmgDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_EmgDlg", "回旋发射", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "引导轴线方向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_AxiasX.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_AxiasY.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_AxiasZ.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "发射中心坐标：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_LaunchX.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_LaunchY.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_LaunchZ.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "束电流.I(T)：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_IT.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>A</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "引导磁场：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_magnetic.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>T</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "引导半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_radius.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>mm</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "纵向动量：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_VerticalMomentum.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>m/s</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "横向动量：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_HorizontalMomentum.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>m/s</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_EmgDlg", "发射选项", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_surface.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "沿表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randomm.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_uniform.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "均匀", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fixed.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_strictTiming.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "严格定时", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_random.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "随机分布", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_transmittingInterval.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "发射间隔：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "倍时间步长", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>偏移Dn(T,X,Y,Z)=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Dn.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p><span style=\" font-size:14pt;\">m</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_randommm.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "随机", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_alongOutsideFixed.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "固定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_outSurface.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "沿外表面分布：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(0, QtGui.QApplication.translate("Dialog_EmgDlg", "电子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_particleType.setItemText(1, QtGui.QApplication.translate("Dialog_EmgDlg", "质子", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_generationRate.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "产生率：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_particleType.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "粒子类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "个/网格/步长", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog_EmgDlg", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notInclued.setItemText(0, QtGui.QApplication.translate("Dialog_EmgDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_notIncludedd.setItemText(0, QtGui.QApplication.translate("Dialog_EmgDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>进一步限定发射区域，使不包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog_EmgDlg", "发射区域选项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "<html><head/><body><p>进一步限定发射区域，使包括下列正交投影型区域</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "区域1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_included.setItemText(0, QtGui.QApplication.translate("Dialog_EmgDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "区域2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_includedd.setItemText(0, QtGui.QApplication.translate("Dialog_EmgDlg", "不指定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_EmgDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
