# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObsDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_ObsDlg(object):
    def setupUi(self, Dialog_ObsDlg):
        Dialog_ObsDlg.setObjectName(_fromUtf8("Dialog_ObsDlg"))
        Dialog_ObsDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_ObsDlg.resize(401, 710)
        Dialog_ObsDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_ObsDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_6 = QtGui.QGridLayout(Dialog_ObsDlg)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_name2 = QtGui.QLabel(Dialog_ObsDlg)
        self.label_name2.setObjectName(_fromUtf8("label_name2"))
        self.gridLayout_7.addWidget(self.label_name2, 1, 0, 1, 1)
        self.lineEdit_name2 = QtGui.QLineEdit(Dialog_ObsDlg)
        self.lineEdit_name2.setObjectName(_fromUtf8("lineEdit_name2"))
        self.gridLayout_7.addWidget(self.lineEdit_name2, 1, 1, 1, 1)
        self.Label_Name = QtGui.QLabel(Dialog_ObsDlg)
        font = QtGui.QFont()
        font.setKerning(True)
        self.Label_Name.setFont(font)
        self.Label_Name.setObjectName(_fromUtf8("Label_Name"))
        self.gridLayout_7.addWidget(self.Label_Name, 0, 0, 1, 1)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_ObsDlg)
        self.LineEdit_Name.setObjectName(_fromUtf8("LineEdit_Name"))
        self.gridLayout_7.addWidget(self.LineEdit_Name, 0, 1, 1, 1)
        self.ComboBox_type = StyledComboBox(Dialog_ObsDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_type.sizePolicy().hasHeightForWidth())
        self.ComboBox_type.setSizePolicy(sizePolicy)
        self.ComboBox_type.setObjectName(_fromUtf8("ComboBox_type"))
        self.ComboBox_type.addItem(_fromUtf8(""))
        self.ComboBox_type.addItem(_fromUtf8(""))
        self.ComboBox_type.addItem(_fromUtf8(""))
        self.ComboBox_type.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.ComboBox_type, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog_ObsDlg)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 3, 1, 1)
        self.ComboBox_Shadow = StyledComboBox(Dialog_ObsDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setObjectName(_fromUtf8("ComboBox_Shadow"))
        self.ComboBox_Shadow.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.ComboBox_Shadow, 0, 4, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_ok = QtGui.QPushButton(Dialog_ObsDlg)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(Dialog_ObsDlg)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 4, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog_ObsDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkBox_dataSmooth = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_dataSmooth.setObjectName(_fromUtf8("checkBox_dataSmooth"))
        self.horizontalLayout_8.addWidget(self.checkBox_dataSmooth)
        self.radioButton_time = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_time.setChecked(True)
        self.radioButton_time.setObjectName(_fromUtf8("radioButton_time"))
        self.horizontalLayout_8.addWidget(self.radioButton_time)
        self.radioButton_RC = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_RC.setObjectName(_fromUtf8("radioButton_RC"))
        self.horizontalLayout_8.addWidget(self.radioButton_RC)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.LineEdit_timeParam = QtGui.QLineEdit(self.groupBox_2)
        self.LineEdit_timeParam.setEnabled(False)
        self.LineEdit_timeParam.setObjectName(_fromUtf8("LineEdit_timeParam"))
        self.horizontalLayout_9.addWidget(self.LineEdit_timeParam)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_ObsDlg)
        self.groupBox_Port.setEnabled(True)
        self.groupBox_Port.setObjectName(_fromUtf8("groupBox_Port"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName(_fromUtf8("horizontalLayout_end"))
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName(_fromUtf8("label_end"))
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName(_fromUtf8("LineEdit_end_x"))
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(False)
        self.LineEdit_end_y.setObjectName(_fromUtf8("LineEdit_end_y"))
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(False)
        self.LineEdit_end_z.setObjectName(_fromUtf8("LineEdit_end_z"))
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName(_fromUtf8("ComboBox_end"))
        self.ComboBox_end.addItem(_fromUtf8(""))
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 4, 0, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName(_fromUtf8("horizontalLayout_start"))
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName(_fromUtf8("label_start"))
        self.horizontalLayout_start.addWidget(self.label_start)
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName(_fromUtf8("LineEdit_start_x"))
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName(_fromUtf8("LineEdit_start_y"))
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName(_fromUtf8("LineEdit_start_z"))
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName(_fromUtf8("ComboBox_start"))
        self.ComboBox_start.addItem(_fromUtf8(""))
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_Port)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setEnabled(False)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setAutoExclusive(True)
        self.radioButton_x.setObjectName(_fromUtf8("radioButton_x"))
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setEnabled(False)
        self.radioButton_y.setObjectName(_fromUtf8("radioButton_y"))
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setEnabled(False)
        self.radioButton_z.setObjectName(_fromUtf8("radioButton_z"))
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName(_fromUtf8("label_X"))
        self.horizontalLayout_3.addWidget(self.label_X)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName(_fromUtf8("label_Y"))
        self.horizontalLayout_3.addWidget(self.label_Y)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName(_fromUtf8("label_Z"))
        self.horizontalLayout_3.addWidget(self.label_Z)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_Port, 1, 0, 1, 2)
        self.groupBox_Port_2 = QtGui.QGroupBox(Dialog_ObsDlg)
        self.groupBox_Port_2.setObjectName(_fromUtf8("groupBox_Port_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_Port_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_start_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_start_2.setObjectName(_fromUtf8("horizontalLayout_start_2"))
        self.label_start_2 = QtGui.QLabel(self.groupBox_Port_2)
        self.label_start_2.setObjectName(_fromUtf8("label_start_2"))
        self.horizontalLayout_start_2.addWidget(self.label_start_2)
        self.radioButton_field = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_field.setChecked(True)
        self.radioButton_field.setObjectName(_fromUtf8("radioButton_field"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog_ObsDlg)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_field)
        self.horizontalLayout_start_2.addWidget(self.radioButton_field)
        self.radioButton_integral = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_integral.setEnabled(False)
        self.radioButton_integral.setChecked(False)
        self.radioButton_integral.setAutoExclusive(True)
        self.radioButton_integral.setObjectName(_fromUtf8("radioButton_integral"))
        self.buttonGroup.addButton(self.radioButton_integral)
        self.horizontalLayout_start_2.addWidget(self.radioButton_integral)
        self.radioButton_power = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_power.setEnabled(False)
        self.radioButton_power.setObjectName(_fromUtf8("radioButton_power"))
        self.buttonGroup.addButton(self.radioButton_power)
        self.horizontalLayout_start_2.addWidget(self.radioButton_power)
        self.radioButton_energy = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_energy.setEnabled(False)
        self.radioButton_energy.setObjectName(_fromUtf8("radioButton_energy"))
        self.buttonGroup.addButton(self.radioButton_energy)
        self.horizontalLayout_start_2.addWidget(self.radioButton_energy)
        self.verticalLayout.addLayout(self.horizontalLayout_start_2)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.radioButton_particleStatistics = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_particleStatistics.setEnabled(True)
        self.radioButton_particleStatistics.setObjectName(_fromUtf8("radioButton_particleStatistics"))
        self.buttonGroup.addButton(self.radioButton_particleStatistics)
        self.horizontalLayout_15.addWidget(self.radioButton_particleStatistics)
        self.radioButton_collected = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_collected.setObjectName(_fromUtf8("radioButton_collected"))
        self.buttonGroup.addButton(self.radioButton_collected)
        self.horizontalLayout_15.addWidget(self.radioButton_collected)
        self.radioButton_emitted = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_emitted.setObjectName(_fromUtf8("radioButton_emitted"))
        self.buttonGroup.addButton(self.radioButton_emitted)
        self.horizontalLayout_15.addWidget(self.radioButton_emitted)
        self.radioButton_destroyed = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_destroyed.setObjectName(_fromUtf8("radioButton_destroyed"))
        self.buttonGroup.addButton(self.radioButton_destroyed)
        self.horizontalLayout_15.addWidget(self.radioButton_destroyed)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.groupBox = QtGui.QGroupBox(self.groupBox_Port_2)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ComboBox_E1 = StyledComboBox(self.groupBox)
        self.ComboBox_E1.setEnabled(True)
        self.ComboBox_E1.setObjectName(_fromUtf8("ComboBox_E1"))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.ComboBox_E1.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.ComboBox_E1)
        self.ComboBox_EDL = StyledComboBox(self.groupBox)
        self.ComboBox_EDL.setEnabled(False)
        self.ComboBox_EDL.setObjectName(_fromUtf8("ComboBox_EDL"))
        self.ComboBox_EDL.addItem(_fromUtf8(""))
        self.ComboBox_EDL.addItem(_fromUtf8(""))
        self.ComboBox_EDL.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.ComboBox_EDL)
        self.ComboBox_SDA = StyledComboBox(self.groupBox)
        self.ComboBox_SDA.setEnabled(False)
        self.ComboBox_SDA.setObjectName(_fromUtf8("ComboBox_SDA"))
        self.ComboBox_SDA.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.ComboBox_SDA)
        self.ComboBox_EM = StyledComboBox(self.groupBox)
        self.ComboBox_EM.setEnabled(False)
        self.ComboBox_EM.setObjectName(_fromUtf8("ComboBox_EM"))
        self.ComboBox_EM.addItem(_fromUtf8(""))
        self.ComboBox_EM.addItem(_fromUtf8(""))
        self.ComboBox_EM.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.ComboBox_EM)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.LineEdit_phase1 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_phase1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_phase1.sizePolicy().hasHeightForWidth())
        self.LineEdit_phase1.setSizePolicy(sizePolicy)
        self.LineEdit_phase1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LineEdit_phase1.setObjectName(_fromUtf8("LineEdit_phase1"))
        self.horizontalLayout_14.addWidget(self.LineEdit_phase1)
        self.comboBox_EMIT_EPS = QtGui.QComboBox(self.groupBox)
        self.comboBox_EMIT_EPS.setEnabled(False)
        self.comboBox_EMIT_EPS.setObjectName(_fromUtf8("comboBox_EMIT_EPS"))
        self.comboBox_EMIT_EPS.addItem(_fromUtf8(""))
        self.comboBox_EMIT_EPS.addItem(_fromUtf8(""))
        self.comboBox_EMIT_EPS.addItem(_fromUtf8(""))
        self.comboBox_EMIT_EPS.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.comboBox_EMIT_EPS)
        self.comboBox_CHARGE = QtGui.QComboBox(self.groupBox)
        self.comboBox_CHARGE.setEnabled(False)
        self.comboBox_CHARGE.setObjectName(_fromUtf8("comboBox_CHARGE"))
        self.comboBox_CHARGE.addItem(_fromUtf8(""))
        self.comboBox_CHARGE.addItem(_fromUtf8(""))
        self.comboBox_CHARGE.addItem(_fromUtf8(""))
        self.comboBox_CHARGE.addItem(_fromUtf8(""))
        self.comboBox_CHARGE.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.comboBox_CHARGE)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_Port_2)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_Fourier = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_Fourier.setObjectName(_fromUtf8("checkBox_Fourier"))
        self.gridLayout.addWidget(self.checkBox_Fourier, 1, 0, 1, 1)
        self.radioButton_real = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_real.setEnabled(False)
        self.radioButton_real.setChecked(True)
        self.radioButton_real.setObjectName(_fromUtf8("radioButton_real"))
        self.gridLayout.addWidget(self.radioButton_real, 1, 1, 1, 1)
        self.radioButton_complex = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_complex.setEnabled(False)
        self.radioButton_complex.setObjectName(_fromUtf8("radioButton_complex"))
        self.gridLayout.addWidget(self.radioButton_complex, 1, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.checkBox_freq = QtGui.QCheckBox(self.groupBox_Port_2)
        self.checkBox_freq.setEnabled(True)
        self.checkBox_freq.setObjectName(_fromUtf8("checkBox_freq"))
        self.horizontalLayout_11.addWidget(self.checkBox_freq)
        self.LineEdit_freq1 = QtGui.QLineEdit(self.groupBox_Port_2)
        self.LineEdit_freq1.setEnabled(False)
        self.LineEdit_freq1.setObjectName(_fromUtf8("LineEdit_freq1"))
        self.horizontalLayout_11.addWidget(self.LineEdit_freq1)
        self.label_11 = QtGui.QLabel(self.groupBox_Port_2)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.LineEdit_freq2 = QtGui.QLineEdit(self.groupBox_Port_2)
        self.LineEdit_freq2.setEnabled(False)
        self.LineEdit_freq2.setObjectName(_fromUtf8("LineEdit_freq2"))
        self.horizontalLayout_11.addWidget(self.LineEdit_freq2)
        self.label_12 = QtGui.QLabel(self.groupBox_Port_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_limit = QtGui.QCheckBox(self.groupBox_Port_2)
        self.checkBox_limit.setObjectName(_fromUtf8("checkBox_limit"))
        self.horizontalLayout_7.addWidget(self.checkBox_limit)
        self.LineEdit_limit1 = QtGui.QLineEdit(self.groupBox_Port_2)
        self.LineEdit_limit1.setEnabled(False)
        self.LineEdit_limit1.setObjectName(_fromUtf8("LineEdit_limit1"))
        self.horizontalLayout_7.addWidget(self.LineEdit_limit1)
        self.label_7 = QtGui.QLabel(self.groupBox_Port_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.LineEdit_limit2 = QtGui.QLineEdit(self.groupBox_Port_2)
        self.LineEdit_limit2.setEnabled(False)
        self.LineEdit_limit2.setObjectName(_fromUtf8("LineEdit_limit2"))
        self.horizontalLayout_7.addWidget(self.LineEdit_limit2)
        self.label_8 = QtGui.QLabel(self.groupBox_Port_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.checkBox_interval = QtGui.QCheckBox(self.groupBox_Port_2)
        self.checkBox_interval.setObjectName(_fromUtf8("checkBox_interval"))
        self.horizontalLayout_18.addWidget(self.checkBox_interval)
        self.lineEdit_interval = QtGui.QLineEdit(self.groupBox_Port_2)
        self.lineEdit_interval.setEnabled(False)
        self.lineEdit_interval.setObjectName(_fromUtf8("lineEdit_interval"))
        self.horizontalLayout_18.addWidget(self.lineEdit_interval)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.groupBox.raise_()
        self.groupBox_4.raise_()
        self.radioButton_collected.raise_()
        self.radioButton_emitted.raise_()
        self.checkBox_interval.raise_()
        self.lineEdit_interval.raise_()
        self.gridLayout_6.addWidget(self.groupBox_Port_2, 2, 0, 1, 2)
        self.groupBox_Port.raise_()
        self.groupBox_Port_2.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(Dialog_ObsDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ObsDlg)

    def retranslateUi(self, Dialog_ObsDlg):
        Dialog_ObsDlg.setWindowTitle(_translate("Dialog_ObsDlg", "时间观测设置", None))
        self.label_name2.setText(_translate("Dialog_ObsDlg", "别名：", None))
        self.Label_Name.setText(_translate("Dialog_ObsDlg", "名称：", None))
        self.LineEdit_Name.setText(_translate("Dialog_ObsDlg", "Observe", None))
        self.ComboBox_type.setItemText(0, _translate("Dialog_ObsDlg", "时间观测点", None))
        self.ComboBox_type.setItemText(1, _translate("Dialog_ObsDlg", "时间观测线", None))
        self.ComboBox_type.setItemText(2, _translate("Dialog_ObsDlg", "时间观测面", None))
        self.ComboBox_type.setItemText(3, _translate("Dialog_ObsDlg", "时间观测体", None))
        self.label_6.setText(_translate("Dialog_ObsDlg", "类型：", None))
        self.ComboBox_Shadow.setItemText(0, _translate("Dialog_ObsDlg", "未指定", None))
        self.pushButton_ok.setText(_translate("Dialog_ObsDlg", "确定", None))
        self.pushButton.setText(_translate("Dialog_ObsDlg", "取消", None))
        self.groupBox_2.setTitle(_translate("Dialog_ObsDlg", "参数", None))
        self.checkBox_dataSmooth.setText(_translate("Dialog_ObsDlg", "数据显示平滑处理：", None))
        self.radioButton_time.setText(_translate("Dialog_ObsDlg", "时间平均", None))
        self.radioButton_RC.setText(_translate("Dialog_ObsDlg", "RC分析", None))
        self.label_9.setText(_translate("Dialog_ObsDlg", "过滤时间参数：", None))
        self.LineEdit_timeParam.setText(_translate("Dialog_ObsDlg", "0.05", None))
        self.label_10.setText(_translate("Dialog_ObsDlg", "ns", None))
        self.groupBox_Port.setTitle(_translate("Dialog_ObsDlg", "观测类型", None))
        self.label_end.setText(_translate("Dialog_ObsDlg", "止点：", None))
        self.LineEdit_end_x.setText(_translate("Dialog_ObsDlg", "0mm", None))
        self.LineEdit_end_y.setText(_translate("Dialog_ObsDlg", "0mm", None))
        self.LineEdit_end_z.setText(_translate("Dialog_ObsDlg", "0mm", None))
        self.ComboBox_end.setItemText(0, _translate("Dialog_ObsDlg", "NULL", None))
        self.label_start.setText(_translate("Dialog_ObsDlg", "起点：", None))
        self.LineEdit_start_x.setText(_translate("Dialog_ObsDlg", "0mm", None))
        self.LineEdit_start_y.setText(_translate("Dialog_ObsDlg", "0mm", None))
        self.LineEdit_start_z.setText(_translate("Dialog_ObsDlg", "0mm", None))
        self.ComboBox_start.setItemText(0, _translate("Dialog_ObsDlg", "NULL", None))
        self.label.setText(_translate("Dialog_ObsDlg", "法向：", None))
        self.radioButton_x.setText(_translate("Dialog_ObsDlg", "R", None))
        self.radioButton_y.setText(_translate("Dialog_ObsDlg", "Θ", None))
        self.radioButton_z.setText(_translate("Dialog_ObsDlg", "Z", None))
        self.label_X.setText(_translate("Dialog_ObsDlg", "R", None))
        self.label_Y.setText(_translate("Dialog_ObsDlg", "Θ", None))
        self.label_Z.setText(_translate("Dialog_ObsDlg", "Z", None))
        self.groupBox_Port_2.setTitle(_translate("Dialog_ObsDlg", "观测项", None))
        self.label_start_2.setText(_translate("Dialog_ObsDlg", "分类项：", None))
        self.radioButton_field.setText(_translate("Dialog_ObsDlg", "场", None))
        self.radioButton_integral.setText(_translate("Dialog_ObsDlg", "场积分", None))
        self.radioButton_power.setText(_translate("Dialog_ObsDlg", "场功率", None))
        self.radioButton_energy.setText(_translate("Dialog_ObsDlg", "场能量", None))
        self.radioButton_particleStatistics.setText(_translate("Dialog_ObsDlg", "粒子统计", None))
        self.radioButton_collected.setText(_translate("Dialog_ObsDlg", "收集的粒子", None))
        self.radioButton_emitted.setText(_translate("Dialog_ObsDlg", "发射的粒子", None))
        self.radioButton_destroyed.setText(_translate("Dialog_ObsDlg", "湮灭的粒子", None))
        self.groupBox.setTitle(_translate("Dialog_ObsDlg", "分类子项", None))
        self.ComboBox_E1.setItemText(0, _translate("Dialog_ObsDlg", "E1", None))
        self.ComboBox_E1.setItemText(1, _translate("Dialog_ObsDlg", "E2", None))
        self.ComboBox_E1.setItemText(2, _translate("Dialog_ObsDlg", "E3", None))
        self.ComboBox_E1.setItemText(3, _translate("Dialog_ObsDlg", "B1", None))
        self.ComboBox_E1.setItemText(4, _translate("Dialog_ObsDlg", "B2", None))
        self.ComboBox_E1.setItemText(5, _translate("Dialog_ObsDlg", "B3", None))
        self.ComboBox_E1.setItemText(6, _translate("Dialog_ObsDlg", "J1", None))
        self.ComboBox_E1.setItemText(7, _translate("Dialog_ObsDlg", "J2", None))
        self.ComboBox_E1.setItemText(8, _translate("Dialog_ObsDlg", "J3", None))
        self.ComboBox_E1.setItemText(9, _translate("Dialog_ObsDlg", "Q0", None))
        self.ComboBox_E1.setItemText(10, _translate("Dialog_ObsDlg", "E1AV", None))
        self.ComboBox_E1.setItemText(11, _translate("Dialog_ObsDlg", "E2AV", None))
        self.ComboBox_E1.setItemText(12, _translate("Dialog_ObsDlg", "E3AV", None))
        self.ComboBox_E1.setItemText(13, _translate("Dialog_ObsDlg", "B1AV", None))
        self.ComboBox_E1.setItemText(14, _translate("Dialog_ObsDlg", "B2AV", None))
        self.ComboBox_E1.setItemText(15, _translate("Dialog_ObsDlg", "B3AV", None))
        self.ComboBox_E1.setItemText(16, _translate("Dialog_ObsDlg", "E1ST", None))
        self.ComboBox_E1.setItemText(17, _translate("Dialog_ObsDlg", "E2ST", None))
        self.ComboBox_E1.setItemText(18, _translate("Dialog_ObsDlg", "E3ST", None))
        self.ComboBox_E1.setItemText(19, _translate("Dialog_ObsDlg", "B1ST", None))
        self.ComboBox_E1.setItemText(20, _translate("Dialog_ObsDlg", "B2ST", None))
        self.ComboBox_E1.setItemText(21, _translate("Dialog_ObsDlg", "B3ST", None))
        self.ComboBox_E1.setItemText(22, _translate("Dialog_ObsDlg", "PHST", None))
        self.ComboBox_E1.setItemText(23, _translate("Dialog_ObsDlg", "B", None))
        self.ComboBox_E1.setItemText(24, _translate("Dialog_ObsDlg", "E", None))
        self.ComboBox_EDL.setItemText(0, _translate("Dialog_ObsDlg", "E.DL", None))
        self.ComboBox_EDL.setItemText(1, _translate("Dialog_ObsDlg", "H.DL", None))
        self.ComboBox_EDL.setItemText(2, _translate("Dialog_ObsDlg", "J.DA", None))
        self.ComboBox_SDA.setItemText(0, _translate("Dialog_ObsDlg", "S.DA", None))
        self.ComboBox_EM.setItemText(0, _translate("Dialog_ObsDlg", "EM", None))
        self.ComboBox_EM.setItemText(1, _translate("Dialog_ObsDlg", "ELECTRIC", None))
        self.ComboBox_EM.setItemText(2, _translate("Dialog_ObsDlg", "MAGNETIC", None))
        self.LineEdit_phase1.setText(_translate("Dialog_ObsDlg", "phase1", None))
        self.comboBox_EMIT_EPS.setItemText(0, _translate("Dialog_ObsDlg", "EMIT_EPS", None))
        self.comboBox_EMIT_EPS.setItemText(1, _translate("Dialog_ObsDlg", "CHARGE", None))
        self.comboBox_EMIT_EPS.setItemText(2, _translate("Dialog_ObsDlg", "ENERGY", None))
        self.comboBox_EMIT_EPS.setItemText(3, _translate("Dialog_ObsDlg", "VRATIO", None))
        self.comboBox_CHARGE.setItemText(0, _translate("Dialog_ObsDlg", "CHARGE", None))
        self.comboBox_CHARGE.setItemText(1, _translate("Dialog_ObsDlg", "CURRENT", None))
        self.comboBox_CHARGE.setItemText(2, _translate("Dialog_ObsDlg", "ENERGY", None))
        self.comboBox_CHARGE.setItemText(3, _translate("Dialog_ObsDlg", "POWER", None))
        self.comboBox_CHARGE.setItemText(4, _translate("Dialog_ObsDlg", "VOLTAGE", None))
        self.comboBox.setItemText(0, _translate("Dialog_ObsDlg", "ELECTRON", None))
        self.comboBox.setItemText(1, _translate("Dialog_ObsDlg", "IONS", None))
        self.comboBox.setItemText(2, _translate("Dialog_ObsDlg", "ALL", None))
        self.checkBox_Fourier.setText(_translate("Dialog_ObsDlg", "进行快速傅里叶变换：", None))
        self.radioButton_real.setText(_translate("Dialog_ObsDlg", "实分析", None))
        self.radioButton_complex.setText(_translate("Dialog_ObsDlg", "复分析", None))
        self.checkBox_freq.setText(_translate("Dialog_ObsDlg", "频率范围", None))
        self.LineEdit_freq1.setText(_translate("Dialog_ObsDlg", "0", None))
        self.label_11.setText(_translate("Dialog_ObsDlg", "至", None))
        self.LineEdit_freq2.setText(_translate("Dialog_ObsDlg", "10", None))
        self.label_12.setText(_translate("Dialog_ObsDlg", "GHz", None))
        self.checkBox_limit.setText(_translate("Dialog_ObsDlg", "时间范围", None))
        self.LineEdit_limit1.setText(_translate("Dialog_ObsDlg", "0", None))
        self.label_7.setText(_translate("Dialog_ObsDlg", "至", None))
        self.LineEdit_limit2.setText(_translate("Dialog_ObsDlg", "10", None))
        self.label_8.setText(_translate("Dialog_ObsDlg", " ns", None))
        self.checkBox_interval.setText(_translate("Dialog_ObsDlg", "观察间隔", None))

from StyledComboBox import StyledComboBox
