# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PhaDlg.ui'
#
# Created: Tue Nov 26 16:24:22 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_PhaDlg(object):
    def setupUi(self, Dialog_PhaDlg):
        Dialog_PhaDlg.setObjectName("Dialog_PhaDlg")
        Dialog_PhaDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_PhaDlg.resize(364, 390)
        Dialog_PhaDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_PhaDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog_PhaDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_suffix = QtGui.QCheckBox(Dialog_PhaDlg)
        self.checkBox_suffix.setObjectName("checkBox_suffix")
        self.horizontalLayout_7.addWidget(self.checkBox_suffix)
        self.LineEdit_phase = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PhaDlg)
        self.LineEdit_phase.setEnabled(False)
        self.LineEdit_phase.setObjectName("LineEdit_phase")
        self.horizontalLayout_7.addWidget(self.LineEdit_phase)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(Dialog_PhaDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.ComboBox_Observation_particle = StyledComboBox(Dialog_PhaDlg)
        self.ComboBox_Observation_particle.setObjectName("ComboBox_Observation_particle")
        self.ComboBox_Observation_particle.addItem("")
        self.ComboBox_Observation_particle.addItem("")
        self.ComboBox_Observation_particle.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBox_Observation_particle)
        self.label = QtGui.QLabel(Dialog_PhaDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.ComboBox_timer = StyledComboBox(Dialog_PhaDlg)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBox_timer)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_thick = QtGui.QCheckBox(Dialog_PhaDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_thick.sizePolicy().hasHeightForWidth())
        self.checkBox_thick.setSizePolicy(sizePolicy)
        self.checkBox_thick.setObjectName("checkBox_thick")
        self.horizontalLayout_6.addWidget(self.checkBox_thick)
        self.ComboBox_thick = StyledComboBox(Dialog_PhaDlg)
        self.ComboBox_thick.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_thick.sizePolicy().hasHeightForWidth())
        self.ComboBox_thick.setSizePolicy(sizePolicy)
        self.ComboBox_thick.setObjectName("ComboBox_thick")
        self.ComboBox_thick.addItem("")
        self.ComboBox_thick.addItem("")
        self.ComboBox_thick.addItem("")
        self.horizontalLayout_6.addWidget(self.ComboBox_thick)
        self.LineEdit_thick1 = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PhaDlg)
        self.LineEdit_thick1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_thick1.sizePolicy().hasHeightForWidth())
        self.LineEdit_thick1.setSizePolicy(sizePolicy)
        self.LineEdit_thick1.setObjectName("LineEdit_thick1")
        self.horizontalLayout_6.addWidget(self.LineEdit_thick1)
        self.LineEdit_thick2 = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PhaDlg)
        self.LineEdit_thick2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_thick2.sizePolicy().hasHeightForWidth())
        self.LineEdit_thick2.setSizePolicy(sizePolicy)
        self.LineEdit_thick2.setObjectName("LineEdit_thick2")
        self.horizontalLayout_6.addWidget(self.LineEdit_thick2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(Dialog_PhaDlg)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ComboBox_Horizon = StyledComboBox(Dialog_PhaDlg)
        self.ComboBox_Horizon.setObjectName("ComboBox_Horizon")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.ComboBox_Horizon.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_Horizon)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_Name = QtGui.QLabel(Dialog_PhaDlg)
        self.Label_Name.setObjectName("Label_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_Name)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PhaDlg)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEdit_Name)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(Dialog_PhaDlg)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.ComboBox_Vertical = StyledComboBox(Dialog_PhaDlg)
        self.ComboBox_Vertical.setObjectName("ComboBox_Vertical")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.ComboBox_Vertical.addItem("")
        self.horizontalLayout_5.addWidget(self.ComboBox_Vertical)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_PhaDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(Dialog_PhaDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 10, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 3, 0, 1, 1)

        self.retranslateUi(Dialog_PhaDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PhaDlg)

    def retranslateUi(self, Dialog_PhaDlg):
        Dialog_PhaDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_PhaDlg", "粒子相空间观测", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_suffix.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "后缀：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_phase.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "观测粒子：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Observation_particle.setItemText(0, QtGui.QApplication.translate("Dialog_PhaDlg", "全部", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Observation_particle.setItemText(1, QtGui.QApplication.translate("Dialog_PhaDlg", "电子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Observation_particle.setItemText(2, QtGui.QApplication.translate("Dialog_PhaDlg", "质子", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog_PhaDlg", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog_PhaDlg", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog_PhaDlg", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_thick.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "显示厚度：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_thick.setItemText(0, QtGui.QApplication.translate("Dialog_PhaDlg", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_thick.setItemText(1, QtGui.QApplication.translate("Dialog_PhaDlg", "X2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_thick.setItemText(2, QtGui.QApplication.translate("Dialog_PhaDlg", "X3", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_thick1.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_thick2.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "横轴显示：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(0, QtGui.QApplication.translate("Dialog_PhaDlg", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(1, QtGui.QApplication.translate("Dialog_PhaDlg", "X2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(2, QtGui.QApplication.translate("Dialog_PhaDlg", "X3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(3, QtGui.QApplication.translate("Dialog_PhaDlg", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(4, QtGui.QApplication.translate("Dialog_PhaDlg", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(5, QtGui.QApplication.translate("Dialog_PhaDlg", "P3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(6, QtGui.QApplication.translate("Dialog_PhaDlg", "KE", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(7, QtGui.QApplication.translate("Dialog_PhaDlg", "FX", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(8, QtGui.QApplication.translate("Dialog_PhaDlg", "XR", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(9, QtGui.QApplication.translate("Dialog_PhaDlg", "YR", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(10, QtGui.QApplication.translate("Dialog_PhaDlg", "EPSX", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Horizon.setItemText(11, QtGui.QApplication.translate("Dialog_PhaDlg", "EPSY", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "PhasSpace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "纵轴显示：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(0, QtGui.QApplication.translate("Dialog_PhaDlg", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(1, QtGui.QApplication.translate("Dialog_PhaDlg", "X2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(2, QtGui.QApplication.translate("Dialog_PhaDlg", "X3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(3, QtGui.QApplication.translate("Dialog_PhaDlg", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(4, QtGui.QApplication.translate("Dialog_PhaDlg", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(5, QtGui.QApplication.translate("Dialog_PhaDlg", "P3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(6, QtGui.QApplication.translate("Dialog_PhaDlg", "KE", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(7, QtGui.QApplication.translate("Dialog_PhaDlg", "FX", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(8, QtGui.QApplication.translate("Dialog_PhaDlg", "XR", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(9, QtGui.QApplication.translate("Dialog_PhaDlg", "YR", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(10, QtGui.QApplication.translate("Dialog_PhaDlg", "EPSX", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Vertical.setItemText(11, QtGui.QApplication.translate("Dialog_PhaDlg", "EPSY", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_PhaDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
