# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PortDlg.ui'
#
# Created: Wed May  6 18:58:44 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_PortDlg(object):
    def setupUi(self, Dialog_PortDlg):
        Dialog_PortDlg.setObjectName("Dialog_PortDlg")
        Dialog_PortDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_PortDlg.resize(539, 928)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_PortDlg.sizePolicy().hasHeightForWidth())
        Dialog_PortDlg.setSizePolicy(sizePolicy)
        Dialog_PortDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_PortDlg.setMaximumSize(QtCore.QSize(4160, 6420))
        self.gridLayout_7 = QtGui.QGridLayout(Dialog_PortDlg)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea = QtGui.QScrollArea(Dialog_PortDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 502, 923))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Port.sizePolicy().hasHeightForWidth())
        self.groupBox_Port.setSizePolicy(sizePolicy)
        self.groupBox_Port.setFlat(True)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_end_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        self.LineEdit_end_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        self.LineEdit_end_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_3.addLayout(self.horizontalLayout_end, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_5.addWidget(self.label_X)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_5.addWidget(self.label_Y)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_5.addWidget(self.label_Z)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        self.LineEdit_start_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        self.LineEdit_start_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        self.LineEdit_start_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_3.addLayout(self.horizontalLayout_start, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 8, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.radioButton_opposite = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_opposite.setChecked(True)
        self.radioButton_opposite.setObjectName("radioButton_opposite")
        self.horizontalLayout_4.addWidget(self.radioButton_opposite)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.radioButton_forward = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_forward.setObjectName("radioButton_forward")
        self.horizontalLayout_4.addWidget(self.radioButton_forward)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 7, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 5, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_Port, 1, 0, 1, 2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_x = QtGui.QCheckBox(self.groupBox)
        self.checkBox_x.setObjectName("checkBox_x")
        self.horizontalLayout_6.addWidget(self.checkBox_x)
        self.checkBox_y = QtGui.QCheckBox(self.groupBox)
        self.checkBox_y.setObjectName("checkBox_y")
        self.horizontalLayout_6.addWidget(self.checkBox_y)
        self.checkBox_z = QtGui.QCheckBox(self.groupBox)
        self.checkBox_z.setObjectName("checkBox_z")
        self.horizontalLayout_6.addWidget(self.checkBox_z)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LineEdit_DX1 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_DX1.setEnabled(False)
        self.LineEdit_DX1.setObjectName("LineEdit_DX1")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX1)
        self.LineEdit_DX2 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_DX2.setEnabled(False)
        self.LineEdit_DX2.setObjectName("LineEdit_DX2")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX2)
        self.LineEdit_DX3 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_DX3.setEnabled(False)
        self.LineEdit_DX3.setObjectName("LineEdit_DX3")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX3)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 3, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem14, 5, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 3, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LineEdit_circuit = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PortDlg)
        self.LineEdit_circuit.setEnabled(False)
        self.LineEdit_circuit.setObjectName("LineEdit_circuit")
        self.gridLayout.addWidget(self.LineEdit_circuit, 12, 2, 1, 1)
        self.checkBox_scale = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_scale.setObjectName("checkBox_scale")
        self.gridLayout.addWidget(self.checkBox_scale, 2, 1, 1, 1)
        self.checkBox_Ft = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_Ft.setObjectName("checkBox_Ft")
        self.gridLayout.addWidget(self.checkBox_Ft, 4, 1, 1, 1)
        self.checkBox_GE3 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_GE3.setObjectName("checkBox_GE3")
        self.gridLayout.addWidget(self.checkBox_GE3, 8, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ComboBox_lap2 = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap2.setEnabled(False)
        self.ComboBox_lap2.setObjectName("ComboBox_lap2")
        self.ComboBox_lap2.addItem("")
        self.horizontalLayout_10.addWidget(self.ComboBox_lap2)
        self.spinBox_2 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_10.addWidget(self.spinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_10, 15, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 5, 2, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 20, 2, 1, 1)
        self.checkBox_lap = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_lap.setEnabled(True)
        self.checkBox_lap.setObjectName("checkBox_lap")
        self.gridLayout.addWidget(self.checkBox_lap, 14, 1, 1, 1)
        self.LineEdit_GE3 = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.LineEdit_GE3.setEnabled(False)
        self.LineEdit_GE3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.LineEdit_GE3.setObjectName("LineEdit_GE3")
        self.gridLayout.addWidget(self.LineEdit_GE3, 8, 2, 1, 1)
        self.checkBox_circuit = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_circuit.setEnabled(False)
        self.checkBox_circuit.setObjectName("checkBox_circuit")
        self.gridLayout.addWidget(self.checkBox_circuit, 12, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ComboBox_FT = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_FT.setEnabled(True)
        self.ComboBox_FT.setObjectName("ComboBox_FT")
        self.ComboBox_FT.addItem("")
        self.horizontalLayout_8.addWidget(self.ComboBox_FT)
        self.gridLayout.addLayout(self.horizontalLayout_8, 10, 2, 1, 1)
        self.LineEdit_vport = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PortDlg)
        self.LineEdit_vport.setEnabled(False)
        self.LineEdit_vport.setObjectName("LineEdit_vport")
        self.gridLayout.addWidget(self.LineEdit_vport, 0, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem18, 7, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem19, 11, 2, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ComboBox_lap4 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap4.setEnabled(False)
        self.ComboBox_lap4.setObjectName("ComboBox_lap4")
        self.ComboBox_lap4.addItem("")
        self.horizontalLayout_11.addWidget(self.ComboBox_lap4)
        self.spinBox_4 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_11.addWidget(self.spinBox_4)
        self.gridLayout.addLayout(self.horizontalLayout_11, 17, 2, 1, 1)
        self.LineEdit_scale = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PortDlg)
        self.LineEdit_scale.setEnabled(False)
        self.LineEdit_scale.setObjectName("LineEdit_scale")
        self.gridLayout.addWidget(self.LineEdit_scale, 2, 2, 1, 1)
        self.LineEdit_Ft = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.LineEdit_Ft.setEnabled(False)
        self.LineEdit_Ft.setMaximumSize(QtCore.QSize(16777215, 60))
        self.LineEdit_Ft.setObjectName("LineEdit_Ft")
        self.gridLayout.addWidget(self.LineEdit_Ft, 4, 2, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 3, 2, 1, 1)
        self.checkBox_GE2 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_GE2.setObjectName("checkBox_GE2")
        self.gridLayout.addWidget(self.checkBox_GE2, 6, 1, 1, 1)
        self.checkBox_vport = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_vport.setObjectName("checkBox_vport")
        self.gridLayout.addWidget(self.checkBox_vport, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ComboBox_lap1 = StyledComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap1.setEnabled(False)
        self.ComboBox_lap1.setObjectName("ComboBox_lap1")
        self.ComboBox_lap1.addItem("")
        self.horizontalLayout_9.addWidget(self.ComboBox_lap1)
        self.spinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox.setEnabled(False)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_9.addWidget(self.spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_9, 14, 2, 1, 1)
        self.spinBox_num = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_num.setEnabled(False)
        self.spinBox_num.setMinimum(2)
        self.spinBox_num.setMaximum(5)
        self.spinBox_num.setObjectName("spinBox_num")
        self.gridLayout.addWidget(self.spinBox_num, 15, 1, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem21, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ComboBox_lap3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap3.setEnabled(False)
        self.ComboBox_lap3.setObjectName("ComboBox_lap3")
        self.ComboBox_lap3.addItem("")
        self.horizontalLayout_3.addWidget(self.ComboBox_lap3)
        self.spinBox_3 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 16, 2, 1, 1)
        self.LineEdit_GE2 = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.LineEdit_GE2.setEnabled(False)
        self.LineEdit_GE2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.LineEdit_GE2.setObjectName("LineEdit_GE2")
        self.gridLayout.addWidget(self.LineEdit_GE2, 6, 2, 1, 1)
        self.checkBox_FT = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_FT.setEnabled(False)
        self.checkBox_FT.setObjectName("checkBox_FT")
        self.gridLayout.addWidget(self.checkBox_FT, 10, 1, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem22, 9, 2, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ComboBox_lap5 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBox_lap5.setEnabled(False)
        self.ComboBox_lap5.setObjectName("ComboBox_lap5")
        self.ComboBox_lap5.addItem("")
        self.horizontalLayout_12.addWidget(self.ComboBox_lap5)
        self.spinBox_5 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_12.addWidget(self.spinBox_5)
        self.gridLayout.addLayout(self.horizontalLayout_12, 18, 2, 1, 1)
        self.label_obs = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_obs.setObjectName("label_obs")
        self.gridLayout.addWidget(self.label_obs, 13, 1, 1, 1)
        self.lineEdit_obs = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_PortDlg)
        self.lineEdit_obs.setObjectName("lineEdit_obs")
        self.gridLayout.addWidget(self.lineEdit_obs, 13, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 4, 0, 1, 2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_ok = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout_6.addWidget(self.pushButton_ok, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem23, 6, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog_PortDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PortDlg)

    def retranslateUi(self, Dialog_PortDlg):
        Dialog_PortDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_PortDlg", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_PortDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_PortDlg", "AreaPort", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_PortDlg", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_PortDlg", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_PortDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_PortDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_PortDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_PortDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_opposite.setText(QtGui.QApplication.translate("Dialog_PortDlg", "反向", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_forward.setText(QtGui.QApplication.translate("Dialog_PortDlg", "正向", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_PortDlg", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX1.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_circuit.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0.002E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_scale.setText(QtGui.QApplication.translate("Dialog_PortDlg", "法向修正.SCALE =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Ft.setText(QtGui.QApplication.translate("Dialog_PortDlg", "输入场时间分布.F(T) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GE3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "空间分布.GE3(R,P,Z) =", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap2.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_lap.setText(QtGui.QApplication.translate("Dialog_PortDlg", "拉普拉斯", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_circuit.setText(QtGui.QApplication.translate("Dialog_PortDlg", "circuit输入时间 =", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_FT.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_vport.setText(QtGui.QApplication.translate("Dialog_PortDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap4.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_scale.setText(QtGui.QApplication.translate("Dialog_PortDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GE2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "空间分布.GE2(R,P,Z) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_vport.setText(QtGui.QApplication.translate("Dialog_PortDlg", "相对相速比.VPORT =", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap1.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap3.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FT.setText(QtGui.QApplication.translate("Dialog_PortDlg", "线上电压归一化为F(T)", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_lap5.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_obs.setText(QtGui.QApplication.translate("Dialog_PortDlg", "   OBSERVE名称=", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_PortDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_PortDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
