# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PortDlg.ui'
#
# Created: Thu Jan 24 16:10:51 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_PortDlg(object):
    def setupUi(self, Dialog_PortDlg):
        Dialog_PortDlg.setObjectName("Dialog_PortDlg")
        Dialog_PortDlg.resize(416, 642)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog_PortDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 351, 28))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_Name = QtGui.QLabel(self.horizontalLayoutWidget)
        self.Label_Name.setObjectName("Label_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEdit_Name)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem = QtGui.QSpacerItem(13, 26, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.ComboBox_Shadow = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.ComboBox_Shadow.setEnabled(True)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(69, 16777215))
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ComboBox_Shadow)
        self.Label_Shadow = QtGui.QLabel(self.horizontalLayoutWidget)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_Shadow)
        self.horizontalLayout.addLayout(self.formLayout)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_PortDlg)
        self.groupBox_Port.setGeometry(QtCore.QRect(30, 60, 351, 171))
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_Port)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_start = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_start.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        self.lineEdit_start_x = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_start_x.setObjectName("lineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.lineEdit_start_x)
        self.lineEdit_start_y = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_start_y.setObjectName("lineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.lineEdit_start_y)
        self.lineEdit_start_z = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_start_z.setObjectName("lineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.lineEdit_start_z)
        self.comboBox_start = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_start.setObjectName("comboBox_start")
        self.comboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.comboBox_start)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_Port)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 331, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_end = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_end.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.lineEdit_end_x = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_end_x.setEnabled(False)
        self.lineEdit_end_x.setObjectName("lineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.lineEdit_end_x)
        self.lineEdit_end_y = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_end_y.setObjectName("lineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.lineEdit_end_y)
        self.lineEdit_end_z = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_end_z.setObjectName("lineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.lineEdit_end_z)
        self.comboBox_end = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox_end.setObjectName("comboBox_end")
        self.comboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.comboBox_end)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_Port)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 100, 201, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_Port)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(60, 130, 102, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_opposite = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_opposite.setChecked(True)
        self.radioButton_opposite.setObjectName("radioButton_opposite")
        self.horizontalLayout_4.addWidget(self.radioButton_opposite)
        self.radioButton_forward = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_forward.setObjectName("radioButton_forward")
        self.horizontalLayout_4.addWidget(self.radioButton_forward)
        self.groupBox = QtGui.QGroupBox(Dialog_PortDlg)
        self.groupBox.setGeometry(QtCore.QRect(30, 240, 351, 91))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 331, 21))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_x = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_x.setObjectName("checkBox_x")
        self.horizontalLayout_6.addWidget(self.checkBox_x)
        self.checkBox_y = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_y.setObjectName("checkBox_y")
        self.horizontalLayout_6.addWidget(self.checkBox_y)
        self.checkBox_z = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_z.setObjectName("checkBox_z")
        self.horizontalLayout_6.addWidget(self.checkBox_z)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 50, 331, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_DX1 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_DX1.setEnabled(False)
        self.lineEdit_DX1.setObjectName("lineEdit_DX1")
        self.horizontalLayout_7.addWidget(self.lineEdit_DX1)
        self.lineEdit_DX2 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_DX2.setEnabled(False)
        self.lineEdit_DX2.setObjectName("lineEdit_DX2")
        self.horizontalLayout_7.addWidget(self.lineEdit_DX2)
        self.lineEdit_DX3 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_DX3.setEnabled(False)
        self.lineEdit_DX3.setObjectName("lineEdit_DX3")
        self.horizontalLayout_7.addWidget(self.lineEdit_DX3)
        self.gridLayoutWidget = QtGui.QWidget(Dialog_PortDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 340, 351, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Ft = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_Ft.setObjectName("checkBox_Ft")
        self.gridLayout.addWidget(self.checkBox_Ft, 2, 1, 1, 1)
        self.lineEdit_vport = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vport.setEnabled(False)
        self.lineEdit_vport.setObjectName("lineEdit_vport")
        self.gridLayout.addWidget(self.lineEdit_vport, 0, 2, 1, 1)
        self.checkBox_scale = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_scale.setObjectName("checkBox_scale")
        self.gridLayout.addWidget(self.checkBox_scale, 1, 1, 1, 1)
        self.lineEdit_Ft = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Ft.setEnabled(False)
        self.lineEdit_Ft.setObjectName("lineEdit_Ft")
        self.gridLayout.addWidget(self.lineEdit_Ft, 2, 2, 1, 1)
        self.checkBox_GE3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_GE3.setObjectName("checkBox_GE3")
        self.gridLayout.addWidget(self.checkBox_GE3, 4, 1, 1, 1)
        self.checkBox_GE2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_GE2.setObjectName("checkBox_GE2")
        self.gridLayout.addWidget(self.checkBox_GE2, 3, 1, 1, 1)
        self.checkBox_circuit = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_circuit.setEnabled(False)
        self.checkBox_circuit.setObjectName("checkBox_circuit")
        self.gridLayout.addWidget(self.checkBox_circuit, 6, 1, 1, 1)
        self.checkBox_lap = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_lap.setEnabled(True)
        self.checkBox_lap.setObjectName("checkBox_lap")
        self.gridLayout.addWidget(self.checkBox_lap, 7, 1, 1, 1)
        self.lineEdit_circuit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_circuit.setEnabled(False)
        self.lineEdit_circuit.setObjectName("lineEdit_circuit")
        self.gridLayout.addWidget(self.lineEdit_circuit, 6, 2, 1, 1)
        self.lineEdit_scale = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_scale.setEnabled(False)
        self.lineEdit_scale.setObjectName("lineEdit_scale")
        self.gridLayout.addWidget(self.lineEdit_scale, 1, 2, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_FT_x2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_FT_x2.setEnabled(False)
        self.radioButton_FT_x2.setChecked(True)
        self.radioButton_FT_x2.setObjectName("radioButton_FT_x2")
        self.horizontalLayout_8.addWidget(self.radioButton_FT_x2)
        self.radioButton_FT_x3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_FT_x3.setEnabled(False)
        self.radioButton_FT_x3.setObjectName("radioButton_FT_x3")
        self.horizontalLayout_8.addWidget(self.radioButton_FT_x3)
        self.comboBox_FT = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_FT.setEnabled(False)
        self.comboBox_FT.setObjectName("comboBox_FT")
        self.comboBox_FT.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_FT)
        self.gridLayout.addLayout(self.horizontalLayout_8, 5, 2, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBox_lap1 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_lap1.setEnabled(False)
        self.comboBox_lap1.setObjectName("comboBox_lap1")
        self.comboBox_lap1.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_lap1)
        self.comboBox_lap2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_lap2.setEnabled(False)
        self.comboBox_lap2.setObjectName("comboBox_lap2")
        self.comboBox_lap2.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_lap2)
        self.gridLayout.addLayout(self.horizontalLayout_9, 7, 2, 1, 1)
        self.lineEdit_GE3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_GE3.setEnabled(False)
        self.lineEdit_GE3.setObjectName("lineEdit_GE3")
        self.gridLayout.addWidget(self.lineEdit_GE3, 4, 2, 1, 1)
        self.checkBox_FT = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_FT.setEnabled(False)
        self.checkBox_FT.setObjectName("checkBox_FT")
        self.gridLayout.addWidget(self.checkBox_FT, 5, 1, 1, 1)
        self.lineEdit_GE2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_GE2.setEnabled(False)
        self.lineEdit_GE2.setObjectName("lineEdit_GE2")
        self.gridLayout.addWidget(self.lineEdit_GE2, 3, 2, 1, 1)
        self.checkBox_vport = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_vport.setObjectName("checkBox_vport")
        self.gridLayout.addWidget(self.checkBox_vport, 0, 1, 1, 1)
        self.horizontalLayoutWidget_10 = QtGui.QWidget(Dialog_PortDlg)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(220, 590, 160, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)

        self.retranslateUi(Dialog_PortDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PortDlg)

    def retranslateUi(self, Dialog_PortDlg):
        Dialog_PortDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_PortDlg", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_PortDlg", "名称", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_PortDlg", "AreaPort", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_PortDlg", "正交投影面", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_PortDlg", "波导端口", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_PortDlg", "起点", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_PortDlg", "止点", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_PortDlg", "法向", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_opposite.setText(QtGui.QApplication.translate("Dialog_PortDlg", "反向", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_forward.setText(QtGui.QApplication.translate("Dialog_PortDlg", "正向", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_PortDlg", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_x.setText(QtGui.QApplication.translate("Dialog_PortDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_y.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_z.setText(QtGui.QApplication.translate("Dialog_PortDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DX1.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DX2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DX3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Ft.setText(QtGui.QApplication.translate("Dialog_PortDlg", "输入场时间分布.F(T) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_scale.setText(QtGui.QApplication.translate("Dialog_PortDlg", "法向修正.SCALE =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GE3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "空间分布.GE3(X,Y,Z) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GE2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "空间分布.GE2(X,Y,Z) =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_circuit.setText(QtGui.QApplication.translate("Dialog_PortDlg", "circuit输入时间 =", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_lap.setText(QtGui.QApplication.translate("Dialog_PortDlg", "拉普拉斯", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_circuit.setText(QtGui.QApplication.translate("Dialog_PortDlg", "0.002E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_FT_x2.setText(QtGui.QApplication.translate("Dialog_PortDlg", "x2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_FT_x3.setText(QtGui.QApplication.translate("Dialog_PortDlg", "x3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_FT.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_lap1.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_lap2.setItemText(0, QtGui.QApplication.translate("Dialog_PortDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FT.setText(QtGui.QApplication.translate("Dialog_PortDlg", "线上电压归一化为F(T)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_vport.setText(QtGui.QApplication.translate("Dialog_PortDlg", "相对相速比.VPORT =", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_PortDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_PortDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

