# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RanDlg.ui'
#
# Created: Tue Nov 26 16:24:23 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_RanDlg(object):
    def setupUi(self, Dialog_RanDlg):
        Dialog_RanDlg.setObjectName("Dialog_RanDlg")
        Dialog_RanDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_RanDlg.resize(393, 492)
        Dialog_RanDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_RanDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_7 = QtGui.QGridLayout(Dialog_RanDlg)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Name = QtGui.QLabel(Dialog_RanDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout.addWidget(self.Label_Name)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_RanDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(Dialog_RanDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(Dialog_RanDlg)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout.addWidget(self.ComboBox_Shadow)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_RanDlg)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        self.LineEdit_start_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        self.LineEdit_start_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        self.LineEdit_start_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_3.addWidget(self.label_X)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_3.addWidget(self.label_Y)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_3.addWidget(self.label_Z)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_Port)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_x.sizePolicy().hasHeightForWidth())
        self.radioButton_x.setSizePolicy(sizePolicy)
        self.radioButton_x.setCheckable(True)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_y.sizePolicy().hasHeightForWidth())
        self.radioButton_y.setSizePolicy(sizePolicy)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_z.sizePolicy().hasHeightForWidth())
        self.radioButton_z.setSizePolicy(sizePolicy)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_end_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(True)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        self.LineEdit_end_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(False)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        self.LineEdit_end_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(False)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 5, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 6, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 8, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Port, 1, 0, 1, 2)
        self.groupBox_Port_2 = QtGui.QGroupBox(Dialog_RanDlg)
        self.groupBox_Port_2.setObjectName("groupBox_Port_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_Port_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 8, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_Port_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Fourier = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_Fourier.setObjectName("checkBox_Fourier")
        self.gridLayout.addWidget(self.checkBox_Fourier, 1, 0, 1, 1)
        self.radioButton_real = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_real.setEnabled(False)
        self.radioButton_real.setChecked(True)
        self.radioButton_real.setObjectName("radioButton_real")
        self.gridLayout.addWidget(self.radioButton_real, 1, 1, 1, 1)
        self.radioButton_complex = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_complex.setEnabled(False)
        self.radioButton_complex.setObjectName("radioButton_complex")
        self.gridLayout.addWidget(self.radioButton_complex, 1, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_end_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_4.setObjectName("horizontalLayout_end_4")
        self.label_end_3 = QtGui.QLabel(self.groupBox_Port_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_end_3.sizePolicy().hasHeightForWidth())
        self.label_end_3.setSizePolicy(sizePolicy)
        self.label_end_3.setObjectName("label_end_3")
        self.horizontalLayout_end_4.addWidget(self.label_end_3)
        self.ComboBox_timer = StyledComboBox(self.groupBox_Port_2)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.horizontalLayout_end_4.addWidget(self.ComboBox_timer)
        self.gridLayout_3.addLayout(self.horizontalLayout_end_4, 7, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 4, 0, 1, 1)
        self.horizontalLayout_start_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_start_2.setObjectName("horizontalLayout_start_2")
        self.label_start_2 = QtGui.QLabel(self.groupBox_Port_2)
        self.label_start_2.setObjectName("label_start_2")
        self.horizontalLayout_start_2.addWidget(self.label_start_2)
        self.radioButton_field = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_field.setChecked(True)
        self.radioButton_field.setObjectName("radioButton_field")
        self.horizontalLayout_start_2.addWidget(self.radioButton_field)
        self.radioButton_integral = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_integral.setObjectName("radioButton_integral")
        self.horizontalLayout_start_2.addWidget(self.radioButton_integral)
        self.radioButton_power = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_power.setObjectName("radioButton_power")
        self.horizontalLayout_start_2.addWidget(self.radioButton_power)
        self.radioButton_energy = QtGui.QRadioButton(self.groupBox_Port_2)
        self.radioButton_energy.setObjectName("radioButton_energy")
        self.horizontalLayout_start_2.addWidget(self.radioButton_energy)
        self.gridLayout_3.addLayout(self.horizontalLayout_start_2, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_Port_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ComboBox_E1 = StyledComboBox(self.groupBox)
        self.ComboBox_E1.setEnabled(True)
        self.ComboBox_E1.setObjectName("ComboBox_E1")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.ComboBox_E1.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_E1)
        self.ComboBox_EDL = StyledComboBox(self.groupBox)
        self.ComboBox_EDL.setEnabled(False)
        self.ComboBox_EDL.setObjectName("ComboBox_EDL")
        self.ComboBox_EDL.addItem("")
        self.ComboBox_EDL.addItem("")
        self.ComboBox_EDL.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_EDL)
        self.ComboBox_SDA = StyledComboBox(self.groupBox)
        self.ComboBox_SDA.setEnabled(False)
        self.ComboBox_SDA.setObjectName("ComboBox_SDA")
        self.ComboBox_SDA.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_SDA)
        self.ComboBox_EM = StyledComboBox(self.groupBox)
        self.ComboBox_EM.setEnabled(False)
        self.ComboBox_EM.setObjectName("ComboBox_EM")
        self.ComboBox_EM.addItem("")
        self.ComboBox_EM.addItem("")
        self.ComboBox_EM.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_EM)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem14, 0, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Port_2, 2, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog_RanDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_RanDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(Dialog_RanDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 4, 0, 1, 2)

        self.retranslateUi(Dialog_RanDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_RanDlg)

    def retranslateUi(self, Dialog_RanDlg):
        Dialog_RanDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_RanDlg", "空间观测设置", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_RanDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_RanDlg", "AreaRan", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_RanDlg", "类型：空间观测线", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_RanDlg", "观测类型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_RanDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_RanDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_RanDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_RanDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_RanDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_RanDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_RanDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_RanDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_RanDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_RanDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_RanDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_RanDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_RanDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_RanDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_RanDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port_2.setTitle(QtGui.QApplication.translate("Dialog_RanDlg", "观测项", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Fourier.setText(QtGui.QApplication.translate("Dialog_RanDlg", "进行快速傅里叶变换：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_real.setText(QtGui.QApplication.translate("Dialog_RanDlg", "实分析", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_complex.setText(QtGui.QApplication.translate("Dialog_RanDlg", "复分析", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_3.setText(QtGui.QApplication.translate("Dialog_RanDlg", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog_RanDlg", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog_RanDlg", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start_2.setText(QtGui.QApplication.translate("Dialog_RanDlg", "分类项：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_field.setText(QtGui.QApplication.translate("Dialog_RanDlg", "场", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_integral.setText(QtGui.QApplication.translate("Dialog_RanDlg", "场积分", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_power.setText(QtGui.QApplication.translate("Dialog_RanDlg", "场功率", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_energy.setText(QtGui.QApplication.translate("Dialog_RanDlg", "场能量", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_RanDlg", "分类子项", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "E1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(1, QtGui.QApplication.translate("Dialog_RanDlg", "E2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(2, QtGui.QApplication.translate("Dialog_RanDlg", "E3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(3, QtGui.QApplication.translate("Dialog_RanDlg", "B1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(4, QtGui.QApplication.translate("Dialog_RanDlg", "B2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(5, QtGui.QApplication.translate("Dialog_RanDlg", "B3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(6, QtGui.QApplication.translate("Dialog_RanDlg", "J1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(7, QtGui.QApplication.translate("Dialog_RanDlg", "J2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(8, QtGui.QApplication.translate("Dialog_RanDlg", "J3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(9, QtGui.QApplication.translate("Dialog_RanDlg", "Q0", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(10, QtGui.QApplication.translate("Dialog_RanDlg", "E1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(11, QtGui.QApplication.translate("Dialog_RanDlg", "E2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(12, QtGui.QApplication.translate("Dialog_RanDlg", "E3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(13, QtGui.QApplication.translate("Dialog_RanDlg", "B1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(14, QtGui.QApplication.translate("Dialog_RanDlg", "B2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(15, QtGui.QApplication.translate("Dialog_RanDlg", "B3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(16, QtGui.QApplication.translate("Dialog_RanDlg", "E1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(17, QtGui.QApplication.translate("Dialog_RanDlg", "E2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(18, QtGui.QApplication.translate("Dialog_RanDlg", "E3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(19, QtGui.QApplication.translate("Dialog_RanDlg", "B1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(20, QtGui.QApplication.translate("Dialog_RanDlg", "B2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(21, QtGui.QApplication.translate("Dialog_RanDlg", "B3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(22, QtGui.QApplication.translate("Dialog_RanDlg", "PHST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(23, QtGui.QApplication.translate("Dialog_RanDlg", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_E1.setItemText(24, QtGui.QApplication.translate("Dialog_RanDlg", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EDL.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "E.DL", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EDL.setItemText(1, QtGui.QApplication.translate("Dialog_RanDlg", "H.DL", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EDL.setItemText(2, QtGui.QApplication.translate("Dialog_RanDlg", "J.DA", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_SDA.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "S.DA", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EM.setItemText(0, QtGui.QApplication.translate("Dialog_RanDlg", "EM", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EM.setItemText(1, QtGui.QApplication.translate("Dialog_RanDlg", "ELECTRIC", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_EM.setItemText(2, QtGui.QApplication.translate("Dialog_RanDlg", "MAGNETIC", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_RanDlg", "参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_RanDlg", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_RanDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_RanDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
