# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SolDlg.ui'
#
# Created: Tue Nov 26 16:24:24 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_SolDlg(object):
    def setupUi(self, Dialog_SolDlg):
        Dialog_SolDlg.setObjectName("Dialog_SolDlg")
        Dialog_SolDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_SolDlg.resize(400, 605)
        Dialog_SolDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_SolDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog_SolDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_Name = QtGui.QLabel(Dialog_SolDlg)
        self.Label_Name.setObjectName("Label_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label_Name)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_SolDlg)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEdit_Name)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_2.addLayout(self.formLayout, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog_SolDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 6, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 8, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 10, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 18, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 14, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem8, 16, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 12, 0, 1, 1)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_31.addWidget(self.label_34)
        self.LineEdit_current = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_current.setEnabled(True)
        self.LineEdit_current.setObjectName("LineEdit_current")
        self.horizontalLayout_31.addWidget(self.LineEdit_current)
        self.gridLayout_8.addLayout(self.horizontalLayout_31, 15, 0, 1, 1)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_33.addWidget(self.label_36)
        self.LineEdit_phi = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_phi.setEnabled(True)
        self.LineEdit_phi.setObjectName("LineEdit_phi")
        self.horizontalLayout_33.addWidget(self.LineEdit_phi)
        self.gridLayout_8.addLayout(self.horizontalLayout_33, 19, 0, 1, 1)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_30.addWidget(self.label_33)
        self.LineEdit_Permeability = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_Permeability.setEnabled(False)
        self.LineEdit_Permeability.setObjectName("LineEdit_Permeability")
        self.horizontalLayout_30.addWidget(self.LineEdit_Permeability)
        self.gridLayout_8.addLayout(self.horizontalLayout_30, 13, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_25.addWidget(self.label_28)
        self.LineEdit_Rparam = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_Rparam.setEnabled(False)
        self.LineEdit_Rparam.setObjectName("LineEdit_Rparam")
        self.horizontalLayout_25.addWidget(self.LineEdit_Rparam)
        self.gridLayout_8.addLayout(self.horizontalLayout_25, 3, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_26.addWidget(self.label_29)
        self.LineEdit_Zparam = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_Zparam.setEnabled(False)
        self.LineEdit_Zparam.setObjectName("LineEdit_Zparam")
        self.horizontalLayout_26.addWidget(self.LineEdit_Zparam)
        self.gridLayout_8.addLayout(self.horizontalLayout_26, 5, 0, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_32.addWidget(self.label_35)
        self.LineEdit_theta = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_theta.setEnabled(True)
        self.LineEdit_theta.setObjectName("LineEdit_theta")
        self.horizontalLayout_32.addWidget(self.LineEdit_theta)
        self.gridLayout_8.addLayout(self.horizontalLayout_32, 17, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.ComboBox_uniformParam = StyledComboBox(self.groupBox_2)
        self.ComboBox_uniformParam.setObjectName("ComboBox_uniformParam")
        self.ComboBox_uniformParam.addItem("")
        self.ComboBox_uniformParam.addItem("")
        self.ComboBox_uniformParam.addItem("")
        self.horizontalLayout_15.addWidget(self.ComboBox_uniformParam)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_27.addWidget(self.label_30)
        self.LineEdit_duty = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_duty.setEnabled(False)
        self.LineEdit_duty.setObjectName("LineEdit_duty")
        self.horizontalLayout_27.addWidget(self.LineEdit_duty)
        self.gridLayout_8.addLayout(self.horizontalLayout_27, 7, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_28.addWidget(self.label_31)
        self.LineEdit_RadiusIn = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_RadiusIn.setEnabled(False)
        self.LineEdit_RadiusIn.setObjectName("LineEdit_RadiusIn")
        self.horizontalLayout_28.addWidget(self.LineEdit_RadiusIn)
        self.gridLayout_8.addLayout(self.horizontalLayout_28, 9, 0, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_29.addWidget(self.label_32)
        self.LineEdit_RadiusOut = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_2)
        self.LineEdit_RadiusOut.setEnabled(False)
        self.LineEdit_RadiusOut.setObjectName("LineEdit_RadiusOut")
        self.horizontalLayout_29.addWidget(self.LineEdit_RadiusOut)
        self.gridLayout_8.addLayout(self.horizontalLayout_29, 11, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 20, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 3, 1)
        self.groupBox = QtGui.QGroupBox(Dialog_SolDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 6, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 10, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 4, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem16, 8, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.LineEdit_CenterR = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_CenterR.setEnabled(True)
        self.LineEdit_CenterR.setObjectName("LineEdit_CenterR")
        self.horizontalLayout_12.addWidget(self.LineEdit_CenterR)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.LineEdit_halfRadius = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_halfRadius.setEnabled(True)
        self.LineEdit_halfRadius.setObjectName("LineEdit_halfRadius")
        self.horizontalLayout_13.addWidget(self.LineEdit_halfRadius)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.LineEdit_radiusIn = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_radiusIn.setEnabled(True)
        self.LineEdit_radiusIn.setObjectName("LineEdit_radiusIn")
        self.horizontalLayout_19.addWidget(self.LineEdit_radiusIn)
        self.ComboBox_2 = StyledComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_2.sizePolicy().hasHeightForWidth())
        self.ComboBox_2.setSizePolicy(sizePolicy)
        self.ComboBox_2.setObjectName("ComboBox_2")
        self.ComboBox_2.addItem("")
        self.horizontalLayout_19.addWidget(self.ComboBox_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 7, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.LineEdit_radiusOut = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_radiusOut.setEnabled(True)
        self.LineEdit_radiusOut.setObjectName("LineEdit_radiusOut")
        self.horizontalLayout_20.addWidget(self.LineEdit_radiusOut)
        self.ComboBox_7 = StyledComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_7.sizePolicy().hasHeightForWidth())
        self.ComboBox_7.setSizePolicy(sizePolicy)
        self.ComboBox_7.setObjectName("ComboBox_7")
        self.ComboBox_7.addItem("")
        self.horizontalLayout_20.addWidget(self.ComboBox_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_20, 9, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        self.LineEdit_num = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_num.setEnabled(True)
        self.LineEdit_num.setObjectName("LineEdit_num")
        self.horizontalLayout_21.addWidget(self.LineEdit_num)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 11, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.LineEdit_CenterZ = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox)
        self.LineEdit_CenterZ.setEnabled(True)
        self.LineEdit_CenterZ.setObjectName("LineEdit_CenterZ")
        self.horizontalLayout_11.addWidget(self.LineEdit_CenterZ)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem17, 12, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(Dialog_SolDlg)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem18, 0, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem19, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LineEdit_DX1 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_5)
        self.LineEdit_DX1.setEnabled(False)
        self.LineEdit_DX1.setObjectName("LineEdit_DX1")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX1)
        self.LineEdit_DX2 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_5)
        self.LineEdit_DX2.setEnabled(False)
        self.LineEdit_DX2.setObjectName("LineEdit_DX2")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX2)
        self.LineEdit_DX3 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_5)
        self.LineEdit_DX3.setEnabled(False)
        self.LineEdit_DX3.setObjectName("LineEdit_DX3")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX3)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_x = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_x.setObjectName("checkBox_x")
        self.horizontalLayout_6.addWidget(self.checkBox_x)
        self.checkBox_y = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_y.setObjectName("checkBox_y")
        self.horizontalLayout_6.addWidget(self.checkBox_y)
        self.checkBox_z = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_z.setObjectName("checkBox_z")
        self.horizontalLayout_6.addWidget(self.checkBox_z)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem20, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(Dialog_SolDlg)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem21, 2, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem22, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ComboBox_material = StyledComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_material.sizePolicy().hasHeightForWidth())
        self.ComboBox_material.setSizePolicy(sizePolicy)
        self.ComboBox_material.setMinimumSize(QtCore.QSize(150, 0))
        self.ComboBox_material.setObjectName("ComboBox_material")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.ComboBox_material.addItem("")
        self.horizontalLayout_9.addWidget(self.ComboBox_material)
        self.pushButton_color = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color.sizePolicy().hasHeightForWidth())
        self.pushButton_color.setSizePolicy(sizePolicy)
        self.pushButton_color.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_color.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_color.setObjectName("pushButton_color")
        self.horizontalLayout_9.addWidget(self.pushButton_color)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtGui.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.LineEdit_color = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_6)
        self.LineEdit_color.setEnabled(True)
        self.LineEdit_color.setText("")
        self.LineEdit_color.setObjectName("LineEdit_color")
        self.horizontalLayout_10.addWidget(self.LineEdit_color)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 3, 0, 1, 2)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem23, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(Dialog_SolDlg)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem24, 0, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem25, 2, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_7)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_6.addWidget(self.horizontalSlider, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.LineEdit_transparency = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_7)
        self.LineEdit_transparency.setEnabled(True)
        self.LineEdit_transparency.setText("")
        self.LineEdit_transparency.setObjectName("LineEdit_transparency")
        self.horizontalLayout_14.addWidget(self.LineEdit_transparency)
        self.gridLayout_6.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem26, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_ok = QtGui.QPushButton(Dialog_SolDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ok.sizePolicy().hasHeightForWidth())
        self.pushButton_ok.setSizePolicy(sizePolicy)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout_7.addWidget(self.pushButton_ok, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(Dialog_SolDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 4, 1, 1, 1)

        self.retranslateUi(Dialog_SolDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_SolDlg)

    def retranslateUi(self, Dialog_SolDlg):
        Dialog_SolDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_SolDlg", "螺旋线线圈", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_SolDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_SolDlg", "Solend", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog_SolDlg", "线圈电磁参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog_SolDlg", "线圈电流：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_current.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Dialog_SolDlg", "phi角度：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_phi.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog_SolDlg", "磁导率：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Permeability.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog_SolDlg", "R因子：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Rparam.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog_SolDlg", "Z因子：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Zparam.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog_SolDlg", "theta角度：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_theta.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog_SolDlg", "匀场环因子：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_uniformParam.setItemText(0, QtGui.QApplication.translate("Dialog_SolDlg", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_uniformParam.setItemText(1, QtGui.QApplication.translate("Dialog_SolDlg", "RZ因子", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_uniformParam.setItemText(2, QtGui.QApplication.translate("Dialog_SolDlg", "其他", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog_SolDlg", "占空比：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_duty.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog_SolDlg", "内半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_RadiusIn.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog_SolDlg", "外半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_RadiusOut.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_SolDlg", "线圈空间参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog_SolDlg", "R中心：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_CenterR.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog_SolDlg", "线圈半长：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_halfRadius.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog_SolDlg", "内半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_radiusIn.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_2.setItemText(0, QtGui.QApplication.translate("Dialog_SolDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog_SolDlg", "外半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_radiusOut.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_7.setItemText(0, QtGui.QApplication.translate("Dialog_SolDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog_SolDlg", "线圈匝数：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_num.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog_SolDlg", "Z中心：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_CenterZ.setText(QtGui.QApplication.translate("Dialog_SolDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog_SolDlg", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX1.setText(QtGui.QApplication.translate("Dialog_SolDlg", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX2.setText(QtGui.QApplication.translate("Dialog_SolDlg", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX3.setText(QtGui.QApplication.translate("Dialog_SolDlg", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_x.setText(QtGui.QApplication.translate("Dialog_SolDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_y.setText(QtGui.QApplication.translate("Dialog_SolDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_z.setText(QtGui.QApplication.translate("Dialog_SolDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog_SolDlg", "材料设置", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(0, QtGui.QApplication.translate("Dialog_SolDlg", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(1, QtGui.QApplication.translate("Dialog_SolDlg", "Aluminium", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(2, QtGui.QApplication.translate("Dialog_SolDlg", "Brass", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(3, QtGui.QApplication.translate("Dialog_SolDlg", "Bronze", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(4, QtGui.QApplication.translate("Dialog_SolDlg", "Chrome", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(5, QtGui.QApplication.translate("Dialog_SolDlg", "Copper", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(6, QtGui.QApplication.translate("Dialog_SolDlg", "Emerald", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(7, QtGui.QApplication.translate("Dialog_SolDlg", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(8, QtGui.QApplication.translate("Dialog_SolDlg", "Jade", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(9, QtGui.QApplication.translate("Dialog_SolDlg", "Metalized", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(10, QtGui.QApplication.translate("Dialog_SolDlg", "Neon GNC", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(11, QtGui.QApplication.translate("Dialog_SolDlg", "Neon PHC", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(12, QtGui.QApplication.translate("Dialog_SolDlg", "Obsidian", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(13, QtGui.QApplication.translate("Dialog_SolDlg", "Pewter", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(14, QtGui.QApplication.translate("Dialog_SolDlg", "Plaster", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(15, QtGui.QApplication.translate("Dialog_SolDlg", "Plastic", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(16, QtGui.QApplication.translate("Dialog_SolDlg", "Ruby", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(17, QtGui.QApplication.translate("Dialog_SolDlg", "Satin", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(18, QtGui.QApplication.translate("Dialog_SolDlg", "Shinny plastic", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(19, QtGui.QApplication.translate("Dialog_SolDlg", "Silver", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(20, QtGui.QApplication.translate("Dialog_SolDlg", "Steel", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_material.setItemText(21, QtGui.QApplication.translate("Dialog_SolDlg", "Stone", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_color.setText(QtGui.QApplication.translate("Dialog_SolDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_SolDlg", "模型颜色：", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog_SolDlg", "透明度", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_SolDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_SolDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
