# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VectorDlg.ui'
#
# Created: Tue Nov 26 16:24:26 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Modeling
class Ui_Dialog_VectorDlg(object):
    def setupUi(self, Dialog_VectorDlg):
        Dialog_VectorDlg.setObjectName("Dialog_VectorDlg")
        Dialog_VectorDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_VectorDlg.resize(366, 484)
        Dialog_VectorDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_VectorDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog_VectorDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Label_Name_2 = QtGui.QLabel(Dialog_VectorDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_4.addWidget(self.Label_Name_2)
        self.LineEdit_Name = Modeling.Common.Tools.Completer.AutoCompleteEdit(Dialog_VectorDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_4.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(Dialog_VectorDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_4.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow = StyledComboBox(Dialog_VectorDlg)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_4.addWidget(self.ComboBox_Shadow)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ok = QtGui.QPushButton(Dialog_VectorDlg)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_ok)
        self.pushButton = QtGui.QPushButton(Dialog_VectorDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_VectorDlg)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_end_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_4.setObjectName("horizontalLayout_end_4")
        self.label_end_3 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_3.setObjectName("label_end_3")
        self.horizontalLayout_end_4.addWidget(self.label_end_3)
        self.ComboBox_timer = StyledComboBox(self.groupBox_Port)
        self.ComboBox_timer.setObjectName("ComboBox_timer")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.ComboBox_timer.addItem("")
        self.horizontalLayout_end_4.addWidget(self.ComboBox_timer)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_4, 11, 0, 1, 1)
        self.horizontalLayout_end_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_3.setObjectName("horizontalLayout_end_3")
        self.checkBox_vector = QtGui.QCheckBox(self.groupBox_Port)
        self.checkBox_vector.setObjectName("checkBox_vector")
        self.horizontalLayout_end_3.addWidget(self.checkBox_vector)
        self.LineEdit_SL1 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_SL1.setEnabled(False)
        self.LineEdit_SL1.setObjectName("LineEdit_SL1")
        self.horizontalLayout_end_3.addWidget(self.LineEdit_SL1)
        self.label_5 = QtGui.QLabel(self.groupBox_Port)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_end_3.addWidget(self.label_5)
        self.LineEdit_SL2 = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_SL2.setEnabled(False)
        self.LineEdit_SL2.setObjectName("LineEdit_SL2")
        self.horizontalLayout_end_3.addWidget(self.LineEdit_SL2)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_3, 13, 0, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        self.LineEdit_start_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        self.LineEdit_start_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        self.LineEdit_start_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_2.addLayout(self.horizontalLayout_start, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_3.addWidget(self.label_X)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_3.addWidget(self.label_Y)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_3.addWidget(self.label_Z)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_Port)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 12, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 10, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 8, 0, 1, 1)
        self.horizontalLayout_end_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_2.setObjectName("horizontalLayout_end_2")
        self.label_end_2 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_2.setObjectName("label_end_2")
        self.horizontalLayout_end_2.addWidget(self.label_end_2)
        self.ComboBox_C1 = StyledComboBox(self.groupBox_Port)
        self.ComboBox_C1.setObjectName("ComboBox_C1")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.ComboBox_C1.addItem("")
        self.horizontalLayout_end_2.addWidget(self.ComboBox_C1)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_2, 7, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_end_x = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        self.LineEdit_end_y = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_y.setEnabled(False)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        self.LineEdit_end_z = Modeling.Common.Tools.Completer.AutoCompleteEdit(self.groupBox_Port)
        self.LineEdit_end_z.setEnabled(False)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_2.addLayout(self.horizontalLayout_end, 3, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 14, 0, 1, 1)
        self.horizontalLayout_end_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_6.setObjectName("horizontalLayout_end_6")
        self.label_end_4 = QtGui.QLabel(self.groupBox_Port)
        self.label_end_4.setObjectName("label_end_4")
        self.horizontalLayout_end_6.addWidget(self.label_end_4)
        self.ComboBox_C2 = StyledComboBox(self.groupBox_Port)
        self.ComboBox_C2.setObjectName("ComboBox_C2")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.ComboBox_C2.addItem("")
        self.horizontalLayout_end_6.addWidget(self.ComboBox_C2)
        self.gridLayout_2.addLayout(self.horizontalLayout_end_6, 9, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 4, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 6, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Port, 3, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 0, 0, 1, 1)

        self.retranslateUi(Dialog_VectorDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_VectorDlg)

    def retranslateUi(self, Dialog_VectorDlg):
        Dialog_VectorDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_VectorDlg", "矢量图观测", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_VectorDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_VectorDlg", "观测面", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_3.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "定时器：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(0, QtGui.QApplication.translate("Dialog_VectorDlg", "默认定时器", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(1, QtGui.QApplication.translate("Dialog_VectorDlg", "仅开始时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_timer.setItemText(2, QtGui.QApplication.translate("Dialog_VectorDlg", "仅结束时刻", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_vector.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "指定矢量个数", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_SL1.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_SL2.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_VectorDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_2.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "观测场1：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(0, QtGui.QApplication.translate("Dialog_VectorDlg", "E1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(1, QtGui.QApplication.translate("Dialog_VectorDlg", "E2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(2, QtGui.QApplication.translate("Dialog_VectorDlg", "E3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(3, QtGui.QApplication.translate("Dialog_VectorDlg", "B1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(4, QtGui.QApplication.translate("Dialog_VectorDlg", "B2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(5, QtGui.QApplication.translate("Dialog_VectorDlg", "B3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(6, QtGui.QApplication.translate("Dialog_VectorDlg", "J1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(7, QtGui.QApplication.translate("Dialog_VectorDlg", "J2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(8, QtGui.QApplication.translate("Dialog_VectorDlg", "J3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(9, QtGui.QApplication.translate("Dialog_VectorDlg", "Q0", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(10, QtGui.QApplication.translate("Dialog_VectorDlg", "E1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(11, QtGui.QApplication.translate("Dialog_VectorDlg", "E2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(12, QtGui.QApplication.translate("Dialog_VectorDlg", "E3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(13, QtGui.QApplication.translate("Dialog_VectorDlg", "B1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(14, QtGui.QApplication.translate("Dialog_VectorDlg", "B2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(15, QtGui.QApplication.translate("Dialog_VectorDlg", "B3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(16, QtGui.QApplication.translate("Dialog_VectorDlg", "E1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(17, QtGui.QApplication.translate("Dialog_VectorDlg", "E2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(18, QtGui.QApplication.translate("Dialog_VectorDlg", "E3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(19, QtGui.QApplication.translate("Dialog_VectorDlg", "B1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(20, QtGui.QApplication.translate("Dialog_VectorDlg", "B2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(21, QtGui.QApplication.translate("Dialog_VectorDlg", "B3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(22, QtGui.QApplication.translate("Dialog_VectorDlg", "PHST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(23, QtGui.QApplication.translate("Dialog_VectorDlg", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C1.setItemText(24, QtGui.QApplication.translate("Dialog_VectorDlg", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_VectorDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_4.setText(QtGui.QApplication.translate("Dialog_VectorDlg", "观测场2：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(0, QtGui.QApplication.translate("Dialog_VectorDlg", "E1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(1, QtGui.QApplication.translate("Dialog_VectorDlg", "E2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(2, QtGui.QApplication.translate("Dialog_VectorDlg", "E3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(3, QtGui.QApplication.translate("Dialog_VectorDlg", "B1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(4, QtGui.QApplication.translate("Dialog_VectorDlg", "B2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(5, QtGui.QApplication.translate("Dialog_VectorDlg", "B3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(6, QtGui.QApplication.translate("Dialog_VectorDlg", "J1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(7, QtGui.QApplication.translate("Dialog_VectorDlg", "J2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(8, QtGui.QApplication.translate("Dialog_VectorDlg", "J3", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(9, QtGui.QApplication.translate("Dialog_VectorDlg", "Q0", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(10, QtGui.QApplication.translate("Dialog_VectorDlg", "E1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(11, QtGui.QApplication.translate("Dialog_VectorDlg", "E2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(12, QtGui.QApplication.translate("Dialog_VectorDlg", "E3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(13, QtGui.QApplication.translate("Dialog_VectorDlg", "B1AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(14, QtGui.QApplication.translate("Dialog_VectorDlg", "B2AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(15, QtGui.QApplication.translate("Dialog_VectorDlg", "B3AV", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(16, QtGui.QApplication.translate("Dialog_VectorDlg", "E1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(17, QtGui.QApplication.translate("Dialog_VectorDlg", "E2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(18, QtGui.QApplication.translate("Dialog_VectorDlg", "E3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(19, QtGui.QApplication.translate("Dialog_VectorDlg", "B1ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(20, QtGui.QApplication.translate("Dialog_VectorDlg", "B2ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(21, QtGui.QApplication.translate("Dialog_VectorDlg", "B3ST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(22, QtGui.QApplication.translate("Dialog_VectorDlg", "PHST", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(23, QtGui.QApplication.translate("Dialog_VectorDlg", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_C2.setItemText(24, QtGui.QApplication.translate("Dialog_VectorDlg", "E", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
