# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModeInfoDialog.ui'
#
# Created: Mon Nov 30 11:27:44 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_ModelingInfoDlg(object):
    def setupUi(self, Dialog_ModelingInfoDlg):
        Dialog_ModelingInfoDlg.setObjectName("Dialog_ModelingInfoDlg")
        Dialog_ModelingInfoDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_ModelingInfoDlg.resize(300, 210)
        Dialog_ModelingInfoDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_ModelingInfoDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_ModelingInfoDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(Dialog_ModelingInfoDlg)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_modeling = QtGui.QLineEdit(Dialog_ModelingInfoDlg)
        self.lineEdit_modeling.setObjectName("lineEdit_modeling")
        self.horizontalLayout_3.addWidget(self.lineEdit_modeling)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(Dialog_ModelingInfoDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_author = QtGui.QLineEdit(Dialog_ModelingInfoDlg)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.horizontalLayout_4.addWidget(self.lineEdit_author)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(Dialog_ModelingInfoDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_company = QtGui.QLineEdit(Dialog_ModelingInfoDlg)
        self.lineEdit_company.setObjectName("lineEdit_company")
        self.horizontalLayout_5.addWidget(self.lineEdit_company)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtGui.QLabel(Dialog_ModelingInfoDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_remarks = QtGui.QLineEdit(Dialog_ModelingInfoDlg)
        self.lineEdit_remarks.setObjectName("lineEdit_remarks")
        self.horizontalLayout_7.addWidget(self.lineEdit_remarks)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.pb_ok = QtGui.QPushButton(Dialog_ModelingInfoDlg)
        self.pb_ok.setObjectName("pb_ok")
        self.verticalLayout_2.addWidget(self.pb_ok)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_ModelingInfoDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ModelingInfoDlg)
        Dialog_ModelingInfoDlg.setTabOrder(self.lineEdit_modeling, self.lineEdit_author)
        Dialog_ModelingInfoDlg.setTabOrder(self.lineEdit_author, self.lineEdit_company)
        Dialog_ModelingInfoDlg.setTabOrder(self.lineEdit_company, self.lineEdit_remarks)

    def retranslateUi(self, Dialog_ModelingInfoDlg):
        Dialog_ModelingInfoDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "模型信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "模型：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_modeling.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "作者：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_author.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "机构：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_company.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "备注：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_remarks.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_ModelingInfoDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))

