# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\"\x9f\x03\n\x04\x44\x61ta\x12\x1b\n\x04type\x18\x01 \x02(\x0e\x32\r.Data.figType\x12\x10\n\x08location\x18\x02 \x03(\t\x12$\n\nattributes\x18\x03 \x01(\x0b\x32\x10.Data.Attributes\x12#\n\ndata_lists\x18\x04 \x03(\x0b\x32\x0f.Data.dataLists\x12\n\n\x02id\x18\x05 \x01(\t\x1ar\n\nAttributes\x12\x32\n\tattribute\x18\x01 \x03(\x0b\x32\x1f.Data.Attributes.AttributeEntry\x1a\x30\n\x0e\x41ttributeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x34\n\tdataLists\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04list\x18\x02 \x03(\x01\x12\x0b\n\x03\x64im\x18\x03 \x02(\x05\"g\n\x07\x66igType\x12\x0b\n\x07\x43ONTOUR\x10\x00\x12\x0b\n\x07OBSERVE\x10\x01\x12\x0e\n\nPHASESPACE\x10\x02\x12\t\n\x05RANGE\x10\x03\x12\n\n\x06VECTOR\x10\x04\x12\r\n\tCONTOUR3D\x10\x05\x12\x0c\n\x08VECTOR3D\x10\x06\"\x1e\n\x07\x61llData\x12\x13\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x05.Data')
)



_DATA_FIGTYPE = _descriptor.EnumDescriptor(
  name='figType',
  full_name='Data.figType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTOUR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBSERVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHASESPACE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VECTOR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTOUR3D', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VECTOR3D', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=327,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_DATA_FIGTYPE)


_DATA_ATTRIBUTES_ATTRIBUTEENTRY = _descriptor.Descriptor(
  name='AttributeEntry',
  full_name='Data.Attributes.AttributeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Data.Attributes.AttributeEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Data.Attributes.AttributeEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=271,
)

_DATA_ATTRIBUTES = _descriptor.Descriptor(
  name='Attributes',
  full_name='Data.Attributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute', full_name='Data.Attributes.attribute', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_ATTRIBUTES_ATTRIBUTEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=271,
)

_DATA_DATALISTS = _descriptor.Descriptor(
  name='dataLists',
  full_name='Data.dataLists',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Data.dataLists.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='Data.dataLists.list', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='Data.dataLists.dim', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=325,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Data.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='Data.location', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='Data.attributes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_lists', full_name='Data.data_lists', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Data.id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_ATTRIBUTES, _DATA_DATALISTS, ],
  enum_types=[
    _DATA_FIGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=430,
)


_ALLDATA = _descriptor.Descriptor(
  name='allData',
  full_name='allData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='allData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=462,
)

_DATA_ATTRIBUTES_ATTRIBUTEENTRY.containing_type = _DATA_ATTRIBUTES
_DATA_ATTRIBUTES.fields_by_name['attribute'].message_type = _DATA_ATTRIBUTES_ATTRIBUTEENTRY
_DATA_ATTRIBUTES.containing_type = _DATA
_DATA_DATALISTS.containing_type = _DATA
_DATA.fields_by_name['type'].enum_type = _DATA_FIGTYPE
_DATA.fields_by_name['attributes'].message_type = _DATA_ATTRIBUTES
_DATA.fields_by_name['data_lists'].message_type = _DATA_DATALISTS
_DATA_FIGTYPE.containing_type = _DATA
_ALLDATA.fields_by_name['data'].message_type = _DATA
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['allData'] = _ALLDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(

  Attributes = _reflection.GeneratedProtocolMessageType('Attributes', (_message.Message,), dict(

    AttributeEntry = _reflection.GeneratedProtocolMessageType('AttributeEntry', (_message.Message,), dict(
      DESCRIPTOR = _DATA_ATTRIBUTES_ATTRIBUTEENTRY,
      __module__ = 'data_pb2'
      # @@protoc_insertion_point(class_scope:Data.Attributes.AttributeEntry)
      ))
    ,
    DESCRIPTOR = _DATA_ATTRIBUTES,
    __module__ = 'data_pb2'
    # @@protoc_insertion_point(class_scope:Data.Attributes)
    ))
  ,

  dataLists = _reflection.GeneratedProtocolMessageType('dataLists', (_message.Message,), dict(
    DESCRIPTOR = _DATA_DATALISTS,
    __module__ = 'data_pb2'
    # @@protoc_insertion_point(class_scope:Data.dataLists)
    ))
  ,
  DESCRIPTOR = _DATA,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  ))
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.Attributes)
_sym_db.RegisterMessage(Data.Attributes.AttributeEntry)
_sym_db.RegisterMessage(Data.dataLists)

allData = _reflection.GeneratedProtocolMessageType('allData', (_message.Message,), dict(
  DESCRIPTOR = _ALLDATA,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:allData)
  ))
_sym_db.RegisterMessage(allData)


_DATA_ATTRIBUTES_ATTRIBUTEENTRY._options = None
# @@protoc_insertion_point(module_scope)
