# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DraftModeling_RevolutionDlg.ui'
#
# Created: Wed Jan 15 17:05:15 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_DraftModeling_Revolution(object):
    def setupUi(self, Dialog_DraftModeling_Revolution):
        Dialog_DraftModeling_Revolution.setObjectName("Dialog_DraftModeling_Revolution")
        Dialog_DraftModeling_Revolution.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_DraftModeling_Revolution.resize(542, 283)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_DraftModeling_Revolution.sizePolicy().hasHeightForWidth())
        Dialog_DraftModeling_Revolution.setSizePolicy(sizePolicy)
        Dialog_DraftModeling_Revolution.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_DraftModeling_Revolution.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_3 = QtGui.QGridLayout(Dialog_DraftModeling_Revolution)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_type = QtGui.QHBoxLayout()
        self.horizontalLayout_type.setSpacing(5)
        self.horizontalLayout_type.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_type.setObjectName("horizontalLayout_type")
        self.label = QtGui.QLabel(Dialog_DraftModeling_Revolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_type.addWidget(self.label)
        self.comboBox_Areas = StyledComboBox(Dialog_DraftModeling_Revolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Areas.sizePolicy().hasHeightForWidth())
        self.comboBox_Areas.setSizePolicy(sizePolicy)
        self.comboBox_Areas.setObjectName("comboBox_Areas")
        self.horizontalLayout_type.addWidget(self.comboBox_Areas)
        self.gridLayout_3.addLayout(self.horizontalLayout_type, 0, 0, 1, 1)
        self.horizontalLayout_name = QtGui.QHBoxLayout()
        self.horizontalLayout_name.setObjectName("horizontalLayout_name")
        self.Label_Name_2 = QtGui.QLabel(Dialog_DraftModeling_Revolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_name.addWidget(self.Label_Name_2)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_DraftModeling_Revolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_name.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(Dialog_DraftModeling_Revolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_name.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow_Attribute = StyledComboBox(Dialog_DraftModeling_Revolution)
        self.ComboBox_Shadow_Attribute.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow_Attribute.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow_Attribute.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow_Attribute.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow_Attribute.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow_Attribute.setEditable(False)
        self.ComboBox_Shadow_Attribute.setObjectName("ComboBox_Shadow_Attribute")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.horizontalLayout_name.addWidget(self.ComboBox_Shadow_Attribute)
        self.gridLayout_3.addLayout(self.horizontalLayout_name, 1, 0, 1, 1)
        self.groupBox_main = QtGui.QGroupBox(Dialog_DraftModeling_Revolution)
        self.groupBox_main.setObjectName("groupBox_main")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_main)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtGui.QLabel(self.groupBox_main)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_PointBaseY = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_PointBaseY.setObjectName("lineEdit_PointBaseY")
        self.gridLayout_5.addWidget(self.lineEdit_PointBaseY, 1, 2, 1, 1)
        self.lineEdit_PointBaseX = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_PointBaseX.setObjectName("lineEdit_PointBaseX")
        self.gridLayout_5.addWidget(self.lineEdit_PointBaseX, 1, 1, 1, 1)
        self.lineEdit_PointTopZ = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_PointTopZ.setObjectName("lineEdit_PointTopZ")
        self.gridLayout_5.addWidget(self.lineEdit_PointTopZ, 3, 3, 1, 1)
        self.lineEdit_PointBaseZ = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_PointBaseZ.setObjectName("lineEdit_PointBaseZ")
        self.gridLayout_5.addWidget(self.lineEdit_PointBaseZ, 1, 3, 1, 1)
        self.lineEdit_PointTopX = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_PointTopX.setObjectName("lineEdit_PointTopX")
        self.gridLayout_5.addWidget(self.lineEdit_PointTopX, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_main)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_PointTopY = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_PointTopY.setObjectName("lineEdit_PointTopY")
        self.gridLayout_5.addWidget(self.lineEdit_PointTopY, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_main)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_main)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_main)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_main, 2, 0, 1, 1)
        self.groupBox_NonUniform = QtGui.QGroupBox(Dialog_DraftModeling_Revolution)
        self.groupBox_NonUniform.setObjectName("groupBox_NonUniform")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_NonUniform)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_UniformY = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformY.setChecked(True)
        self.checkBox_UniformY.setObjectName("checkBox_UniformY")
        self.gridLayout.addWidget(self.checkBox_UniformY, 0, 1, 1, 1)
        self.checkBox_UniformZ = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformZ.setChecked(True)
        self.checkBox_UniformZ.setObjectName("checkBox_UniformZ")
        self.gridLayout.addWidget(self.checkBox_UniformZ, 0, 2, 1, 1)
        self.checkBox_UniformX = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformX.setChecked(True)
        self.checkBox_UniformX.setObjectName("checkBox_UniformX")
        self.gridLayout.addWidget(self.checkBox_UniformX, 0, 0, 1, 1)
        self.lineEdit_UniformX = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformX.setObjectName("lineEdit_UniformX")
        self.gridLayout.addWidget(self.lineEdit_UniformX, 1, 0, 1, 1)
        self.lineEdit_UniformY = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformY.setObjectName("lineEdit_UniformY")
        self.gridLayout.addWidget(self.lineEdit_UniformY, 1, 1, 1, 1)
        self.lineEdit_UniformZ = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformZ.setObjectName("lineEdit_UniformZ")
        self.gridLayout.addWidget(self.lineEdit_UniformZ, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_NonUniform, 3, 0, 1, 1)
        self.horizontalLayout_okAndCancel = QtGui.QHBoxLayout()
        self.horizontalLayout_okAndCancel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_okAndCancel.setObjectName("horizontalLayout_okAndCancel")
        self.pushButton_ok = QtGui.QPushButton(Dialog_DraftModeling_Revolution)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog_DraftModeling_Revolution)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout_okAndCancel, 4, 0, 1, 1)

        self.retranslateUi(Dialog_DraftModeling_Revolution)
        QtCore.QMetaObject.connectSlotsByName(Dialog_DraftModeling_Revolution)
        Dialog_DraftModeling_Revolution.setTabOrder(self.comboBox_Areas, self.LineEdit_Name)
        Dialog_DraftModeling_Revolution.setTabOrder(self.LineEdit_Name, self.ComboBox_Shadow_Attribute)
        Dialog_DraftModeling_Revolution.setTabOrder(self.ComboBox_Shadow_Attribute, self.checkBox_UniformX)
        Dialog_DraftModeling_Revolution.setTabOrder(self.checkBox_UniformX, self.lineEdit_UniformX)
        Dialog_DraftModeling_Revolution.setTabOrder(self.lineEdit_UniformX, self.checkBox_UniformY)
        Dialog_DraftModeling_Revolution.setTabOrder(self.checkBox_UniformY, self.lineEdit_UniformY)
        Dialog_DraftModeling_Revolution.setTabOrder(self.lineEdit_UniformY, self.checkBox_UniformZ)
        Dialog_DraftModeling_Revolution.setTabOrder(self.checkBox_UniformZ, self.lineEdit_UniformZ)
        Dialog_DraftModeling_Revolution.setTabOrder(self.lineEdit_UniformZ, self.pushButton_ok)
        Dialog_DraftModeling_Revolution.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Dialog_DraftModeling_Revolution):
        Dialog_DraftModeling_Revolution.setWindowTitle(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "草图建模-旋转", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "基础面：", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "属性：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(0, QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "未定义", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(1, QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "理想导体", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(2, QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "自定义", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(3, QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "真空", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_main.setTitle(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "结构类型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Point_Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_PointBaseX.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "2.0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_PointTopX.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "2.0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Point_Top:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_NonUniform.setTitle(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformY.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformZ.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformX.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformX.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "dx1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformY.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "dx2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_UniformZ.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "dx2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog_DraftModeling_Revolution", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
