# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AreaFunctionDialog.ui'
#
# Created: Tue Jan  5 21:19:29 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Sector(object):
    def setupUi(self, Sector):
        Sector.setObjectName("Sector")
        Sector.resize(429, 339)
        self.gridLayout_3 = QtGui.QGridLayout(Sector)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtGui.QGroupBox(Sector)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_name = QtGui.QLineEdit(self.groupBox)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.le_order = QtGui.QLineEdit(self.groupBox)
        self.le_order.setObjectName("le_order")
        self.horizontalLayout.addWidget(self.le_order)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Sector)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.cb_attribute = QtGui.QComboBox(self.groupBox_2)
        self.cb_attribute.setObjectName("cb_attribute")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.cb_attribute.addItem("")
        self.gridLayout_2.addWidget(self.cb_attribute, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(Sector)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_x = QtGui.QLabel(self.groupBox_3)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.le_markx = QtGui.QLineEdit(self.groupBox_3)
        self.le_markx.setObjectName("le_markx")
        self.gridLayout.addWidget(self.le_markx, 1, 1, 1, 3)
        self.label_y = QtGui.QLabel(self.groupBox_3)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        self.le_marky = QtGui.QLineEdit(self.groupBox_3)
        self.le_marky.setObjectName("le_marky")
        self.gridLayout.addWidget(self.le_marky, 1, 4, 1, 3)
        self.checkBox_isMarkX = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkX.setObjectName("checkBox_isMarkX")
        self.gridLayout.addWidget(self.checkBox_isMarkX, 2, 1, 1, 3)
        self.checkBox_isMarkY = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isMarkY.setObjectName("checkBox_isMarkY")
        self.gridLayout.addWidget(self.checkBox_isMarkY, 2, 4, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(Sector)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.le_expression = QtGui.QLineEdit(self.groupBox_4)
        self.le_expression.setObjectName("le_expression")
        self.horizontalLayout_3.addWidget(self.le_expression)
        self.gridLayout_3.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.pb_ok = QtGui.QPushButton(Sector)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout_3.addWidget(self.pb_ok, 4, 0, 1, 1)
        self.pb_cancel = QtGui.QPushButton(Sector)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout_3.addWidget(self.pb_cancel, 4, 1, 1, 1)

        self.retranslateUi(Sector)
        QtCore.QMetaObject.connectSlotsByName(Sector)

    def retranslateUi(self, Sector):
        Sector.setWindowTitle(QtGui.QApplication.translate("Sector", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Sector", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Sector", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Sector", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Sector", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Sector", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(0, QtGui.QApplication.translate("Sector", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(1, QtGui.QApplication.translate("Sector", "Conductor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(2, QtGui.QApplication.translate("Sector", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attribute.setItemText(3, QtGui.QApplication.translate("Sector", "Void", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Sector", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x.setText(QtGui.QApplication.translate("Sector", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Sector", "Value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y.setText(QtGui.QApplication.translate("Sector", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkX.setText(QtGui.QApplication.translate("Sector", "isMarkX", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isMarkY.setText(QtGui.QApplication.translate("Sector", "isMarkY", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Sector", "Object of Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Sector", "Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Sector", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Sector", "取消", None, QtGui.QApplication.UnicodeUTF8))

