# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SphericalDialog.ui'
#
# Created: Wed Mar 18 14:13:43 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Modeling.Common.Tools import Completer

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(528, 100)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Base_label_1 = QtGui.QLabel(self.groupBox)
        self.Base_label_1.setObjectName("Base_label_1")
        self.horizontalLayout.addWidget(self.Base_label_1)
        self.Base_lineEdit_1 = QtGui.QLineEdit(self.groupBox)
        self.Base_lineEdit_1.setObjectName("Base_lineEdit_1")
        self.horizontalLayout.addWidget(self.Base_lineEdit_1)
        self.Base_label_2 = QtGui.QLabel(self.groupBox)
        self.Base_label_2.setObjectName("Base_label_2")
        self.horizontalLayout.addWidget(self.Base_label_2)
        self.Base_lineEdit_2 = QtGui.QSpinBox(self.groupBox)
        self.Base_lineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.Base_lineEdit_2.setObjectName("Base_lineEdit_2")
        self.horizontalLayout.addWidget(self.Base_lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(9999, 9999))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Att_label = QtGui.QLabel(self.groupBox_2)
        self.Att_label.setObjectName("Att_label")
        self.horizontalLayout_2.addWidget(self.Att_label)
        self.comboBox = QtGui.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame = QtGui.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_3 = QtGui.QComboBox(self.frame)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 0, 3, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.frame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_00 = QtGui.QLineEdit(self.frame)
        self.lineEdit_00.setObjectName("lineEdit_00")
        self.gridLayout_3.addWidget(self.lineEdit_00, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.lineEdit_01 = QtGui.QLineEdit(self.frame)
        self.lineEdit_01.setObjectName("lineEdit_01")
        self.gridLayout_3.addWidget(self.lineEdit_01, 1, 3, 1, 1)
        self.lineEdit_02 = QtGui.QLineEdit(self.frame)
        self.lineEdit_02.setObjectName("lineEdit_02")
        self.gridLayout_3.addWidget(self.lineEdit_02, 2, 3, 1, 1)
        self.lineEdit_03 = QtGui.QLineEdit(self.frame)
        self.lineEdit_03.setObjectName("lineEdit_03")
        self.gridLayout_3.addWidget(self.lineEdit_03, 3, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.lineEdit_04 = QtGui.QLineEdit(self.frame)
        self.lineEdit_04.setObjectName("lineEdit_04")
        self.gridLayout_3.addWidget(self.lineEdit_04, 2, 1, 1, 1)
        self.lineEdit_05 = QtGui.QLineEdit(self.frame)
        self.lineEdit_05.setObjectName("lineEdit_05")
        self.gridLayout_3.addWidget(self.lineEdit_05, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.NUG_lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.NUG_lineEdit_3.setObjectName("NUG_lineEdit_3")
        self.gridLayout.addWidget(self.NUG_lineEdit_3, 1, 3, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 3, 1, 1)
        self.NUG_label_1 = QtGui.QLabel(self.groupBox_3)
        self.NUG_label_1.setObjectName("NUG_label_1")
        self.gridLayout.addWidget(self.NUG_label_1, 0, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 2, 1, 1)
        self.NUG_label_2 = QtGui.QLabel(self.groupBox_3)
        self.NUG_label_2.setObjectName("NUG_label_2")
        self.gridLayout.addWidget(self.NUG_label_2, 0, 2, 1, 1)
        self.NUG_label_3 = QtGui.QLabel(self.groupBox_3)
        self.NUG_label_3.setObjectName("NUG_label_3")
        self.gridLayout.addWidget(self.NUG_label_3, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.NUG_lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.NUG_lineEdit_2.setObjectName("NUG_lineEdit_2")
        self.gridLayout.addWidget(self.NUG_lineEdit_2, 1, 2, 1, 1)
        self.NUG_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.NUG_lineEdit.setObjectName("NUG_lineEdit")
        self.gridLayout.addWidget(self.NUG_lineEdit, 1, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 3)
        self.gridLayout.setRowStretch(2, 3)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.C_label_1 = QtGui.QLabel(self.groupBox_4)
        self.C_label_1.setObjectName("C_label_1")
        self.gridLayout_2.addWidget(self.C_label_1, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_5 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 2, 1, 1)
        self.lineEdit_7 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.C_label_2 = QtGui.QLabel(self.groupBox_4)
        self.C_label_2.setObjectName("C_label_2")
        self.gridLayout_2.addWidget(self.C_label_2, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.C_label_3 = QtGui.QLabel(self.groupBox_4)
        self.C_label_3.setObjectName("C_label_3")
        self.gridLayout_2.addWidget(self.C_label_3, 0, 3, 1, 1)
        self.lineEdit_6 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.lineEdit_4 = Completer.AutoCompleteEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.OK_pushButton = QtGui.QPushButton(Dialog)
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout_3.addWidget(self.OK_pushButton)
        self.Cancel_pushButton = QtGui.QPushButton(Dialog)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.horizontalLayout_3.addWidget(self.Cancel_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Dialog.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        Dialog.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Dialog.setTabOrder(self.lineEdit_7, self.Base_lineEdit_1)
        Dialog.setTabOrder(self.Base_lineEdit_1, self.NUG_lineEdit)
        Dialog.setTabOrder(self.NUG_lineEdit, self.NUG_lineEdit_2)
        Dialog.setTabOrder(self.NUG_lineEdit_2, self.NUG_lineEdit_3)
        Dialog.setTabOrder(self.NUG_lineEdit_3, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.checkBox_2)
        Dialog.setTabOrder(self.checkBox_2, self.checkBox_3)
        Dialog.setTabOrder(self.checkBox_3, self.OK_pushButton)
        Dialog.setTabOrder(self.OK_pushButton, self.Cancel_pushButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.Base_label_1.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.Base_label_2.setText(QtGui.QApplication.translate("Dialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.Att_label.setText(QtGui.QApplication.translate("Dialog", "          Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("Dialog", "Isotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("Dialog", "Anisotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("Dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Dialog", "Isotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Dialog", "Anisotropy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("Dialog", "NotDefine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "RelativeDielectricConstant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Conductivity  SIGMA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "SIGMA1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Set EPS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Set EPS2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Set EPS3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "SIGMA2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "SIGMAS3:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Non Uniform Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Dialog", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.NUG_label_1.setText(QtGui.QApplication.translate("Dialog", "          X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Dialog", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.NUG_label_2.setText(QtGui.QApplication.translate("Dialog", "          Y ", None, QtGui.QApplication.UnicodeUTF8))
        self.NUG_label_3.setText(QtGui.QApplication.translate("Dialog", "          Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Object of Specrical", None, QtGui.QApplication.UnicodeUTF8))
        self.C_label_1.setText(QtGui.QApplication.translate("Dialog", "          X", None, QtGui.QApplication.UnicodeUTF8))
        self.C_label_2.setText(QtGui.QApplication.translate("Dialog", "          Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.C_label_3.setText(QtGui.QApplication.translate("Dialog", "          Z", None, QtGui.QApplication.UnicodeUTF8))
        self.OK_pushButton.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel_pushButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

