# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SymDialog.ui'
#
# Created: Tue Nov 17 22:13:22 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_SymDlg(object):
    def setupUi(self, Dialog_SymDlg):
        Dialog_SymDlg.setObjectName("Dialog_SymDlg")
        Dialog_SymDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_SymDlg.resize(411, 543)
        Dialog_SymDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_SymDlg.setMaximumSize(QtCore.QSize(100000, 100000))
        self.gridLayout = QtGui.QGridLayout(Dialog_SymDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(Dialog_SymDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LineEdit_DX1 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_DX1.setEnabled(False)
        self.LineEdit_DX1.setObjectName("LineEdit_DX1")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX1)
        self.LineEdit_DX2 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_DX2.setEnabled(False)
        self.LineEdit_DX2.setObjectName("LineEdit_DX2")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX2)
        self.LineEdit_DX3 = QtGui.QLineEdit(self.groupBox)
        self.LineEdit_DX3.setEnabled(False)
        self.LineEdit_DX3.setObjectName("LineEdit_DX3")
        self.horizontalLayout_7.addWidget(self.LineEdit_DX3)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_x = QtGui.QCheckBox(self.groupBox)
        self.checkBox_x.setObjectName("checkBox_x")
        self.horizontalLayout_6.addWidget(self.checkBox_x)
        self.checkBox_y = QtGui.QCheckBox(self.groupBox)
        self.checkBox_y.setObjectName("checkBox_y")
        self.horizontalLayout_6.addWidget(self.checkBox_y)
        self.checkBox_z = QtGui.QCheckBox(self.groupBox)
        self.checkBox_z.setObjectName("checkBox_z")
        self.horizontalLayout_6.addWidget(self.checkBox_z)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Label_Name = QtGui.QLabel(Dialog_SymDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name.sizePolicy().hasHeightForWidth())
        self.Label_Name.setSizePolicy(sizePolicy)
        self.Label_Name.setObjectName("Label_Name")
        self.horizontalLayout_5.addWidget(self.Label_Name)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_SymDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_5.addWidget(self.LineEdit_Name)
        self.Label_Shadow = QtGui.QLabel(Dialog_SymDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow.sizePolicy().hasHeightForWidth())
        self.Label_Shadow.setSizePolicy(sizePolicy)
        self.Label_Shadow.setObjectName("Label_Shadow")
        self.horizontalLayout_5.addWidget(self.Label_Shadow)
        self.ComboBox_Shadow = StyledComboBox(Dialog_SymDlg)
        self.ComboBox_Shadow.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow.setMaximumSize(QtCore.QSize(30000, 16777215))
        self.ComboBox_Shadow.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow.setEditable(False)
        self.ComboBox_Shadow.setObjectName("ComboBox_Shadow")
        self.ComboBox_Shadow.addItem("")
        self.horizontalLayout_5.addWidget(self.ComboBox_Shadow)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pb_ok = QtGui.QPushButton(Dialog_SymDlg)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_10.addWidget(self.pb_ok)
        self.pb_cancel = QtGui.QPushButton(Dialog_SymDlg)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_10.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.groupBox_Port = QtGui.QGroupBox(Dialog_SymDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Port.sizePolicy().hasHeightForWidth())
        self.groupBox_Port.setSizePolicy(sizePolicy)
        self.groupBox_Port.setFlat(True)
        self.groupBox_Port.setObjectName("groupBox_Port")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_Port)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_x = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_x.setChecked(True)
        self.radioButton_x.setObjectName("radioButton_x")
        self.horizontalLayout_2.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_y.setObjectName("radioButton_y")
        self.horizontalLayout_2.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.groupBox_Port)
        self.radioButton_z.setObjectName("radioButton_z")
        self.horizontalLayout_2.addWidget(self.radioButton_z)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_end = QtGui.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.label_end = QtGui.QLabel(self.groupBox_Port)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_end.addWidget(self.label_end)
        self.LineEdit_end_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_x.setEnabled(False)
        self.LineEdit_end_x.setObjectName("LineEdit_end_x")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_x)
        self.LineEdit_end_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_y.setObjectName("LineEdit_end_y")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_y)
        self.LineEdit_end_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_end_z.setObjectName("LineEdit_end_z")
        self.horizontalLayout_end.addWidget(self.LineEdit_end_z)
        self.ComboBox_end = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_end.sizePolicy().hasHeightForWidth())
        self.ComboBox_end.setSizePolicy(sizePolicy)
        self.ComboBox_end.setObjectName("ComboBox_end")
        self.ComboBox_end.addItem("")
        self.horizontalLayout_end.addWidget(self.ComboBox_end)
        self.gridLayout_4.addLayout(self.horizontalLayout_end, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.radioButton_opposite = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_opposite.setChecked(True)
        self.radioButton_opposite.setObjectName("radioButton_opposite")
        self.horizontalLayout_4.addWidget(self.radioButton_opposite)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.radioButton_forward = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_forward.setObjectName("radioButton_forward")
        self.horizontalLayout_4.addWidget(self.radioButton_forward)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 0, 1, 1)
        self.horizontalLayout_start = QtGui.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.label_start = QtGui.QLabel(self.groupBox_Port)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_start.addWidget(self.label_start)
        self.LineEdit_start_x = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_x.setObjectName("LineEdit_start_x")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_x)
        self.LineEdit_start_y = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_y.setObjectName("LineEdit_start_y")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_y)
        self.LineEdit_start_z = QtGui.QLineEdit(self.groupBox_Port)
        self.LineEdit_start_z.setObjectName("LineEdit_start_z")
        self.horizontalLayout_start.addWidget(self.LineEdit_start_z)
        self.ComboBox_start = StyledComboBox(self.groupBox_Port)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_start.sizePolicy().hasHeightForWidth())
        self.ComboBox_start.setSizePolicy(sizePolicy)
        self.ComboBox_start.setObjectName("ComboBox_start")
        self.ComboBox_start.addItem("")
        self.horizontalLayout_start.addWidget(self.ComboBox_start)
        self.gridLayout_4.addLayout(self.horizontalLayout_start, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label_X = QtGui.QLabel(self.groupBox_Port)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_8.addWidget(self.label_X)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.label_Y = QtGui.QLabel(self.groupBox_Port)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_8.addWidget(self.label_Y)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_Z = QtGui.QLabel(self.groupBox_Port)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_8.addWidget(self.label_Z)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Port, 1, 0, 1, 1)
        self.groupBox_Port2 = QtGui.QGroupBox(Dialog_SymDlg)
        self.groupBox_Port2.setTitle("")
        self.groupBox_Port2.setFlat(True)
        self.groupBox_Port2.setObjectName("groupBox_Port2")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_Port2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_end_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_2.setObjectName("horizontalLayout_end_2")
        self.label_end_2 = QtGui.QLabel(self.groupBox_Port2)
        self.label_end_2.setObjectName("label_end_2")
        self.horizontalLayout_end_2.addWidget(self.label_end_2)
        self.ComboBox_symmetric = StyledComboBox(self.groupBox_Port2)
        self.ComboBox_symmetric.setObjectName("ComboBox_symmetric")
        self.ComboBox_symmetric.addItem("")
        self.ComboBox_symmetric.addItem("")
        self.ComboBox_symmetric.addItem("")
        self.horizontalLayout_end_2.addWidget(self.ComboBox_symmetric)
        self.ComboBox_type = StyledComboBox(self.groupBox_Port2)
        self.ComboBox_type.setEnabled(False)
        self.ComboBox_type.setObjectName("ComboBox_type")
        self.ComboBox_type.addItem("")
        self.horizontalLayout_end_2.addWidget(self.ComboBox_type)
        self.gridLayout_6.addLayout(self.horizontalLayout_end_2, 0, 0, 1, 1)
        self.horizontalLayout_end_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_end_3.setObjectName("horizontalLayout_end_3")
        self.label_6 = QtGui.QLabel(self.groupBox_Port2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_end_3.addWidget(self.label_6)
        self.LineEdit_Normal = QtGui.QLineEdit(self.groupBox_Port2)
        self.LineEdit_Normal.setObjectName("LineEdit_Normal")
        self.horizontalLayout_end_3.addWidget(self.LineEdit_Normal)
        self.gridLayout_6.addLayout(self.horizontalLayout_end_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Port2, 2, 0, 1, 1)

        self.retranslateUi(Dialog_SymDlg)
        QtCore.QMetaObject.connectSlotsByName(Dialog_SymDlg)

    def retranslateUi(self, Dialog_SymDlg):
        Dialog_SymDlg.setWindowTitle(QtGui.QApplication.translate("Dialog_SymDlg", "对称边界", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog_SymDlg", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX1.setText(QtGui.QApplication.translate("Dialog_SymDlg", "DX1", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX2.setText(QtGui.QApplication.translate("Dialog_SymDlg", "DX2", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_DX3.setText(QtGui.QApplication.translate("Dialog_SymDlg", "DX3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_x.setText(QtGui.QApplication.translate("Dialog_SymDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_y.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_z.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name.setText(QtGui.QApplication.translate("Dialog_SymDlg", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Symtry", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow.setText(QtGui.QApplication.translate("Dialog_SymDlg", "正交投影面：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow.setItemText(0, QtGui.QApplication.translate("Dialog_SymDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Dialog_SymDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Dialog_SymDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Port.setTitle(QtGui.QApplication.translate("Dialog_SymDlg", "观测面", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_SymDlg", "法向：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setText(QtGui.QApplication.translate("Dialog_SymDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end.setText(QtGui.QApplication.translate("Dialog_SymDlg", "止点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_x.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_y.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_end_z.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_end.setItemText(0, QtGui.QApplication.translate("Dialog_SymDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_opposite.setText(QtGui.QApplication.translate("Dialog_SymDlg", "反向", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_forward.setText(QtGui.QApplication.translate("Dialog_SymDlg", "正向", None, QtGui.QApplication.UnicodeUTF8))
        self.label_start.setText(QtGui.QApplication.translate("Dialog_SymDlg", "起点：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_x.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_y.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_start_z.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0mm", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_start.setItemText(0, QtGui.QApplication.translate("Dialog_SymDlg", "NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Dialog_SymDlg", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Θ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Dialog_SymDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_end_2.setText(QtGui.QApplication.translate("Dialog_SymDlg", "对称类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_symmetric.setItemText(0, QtGui.QApplication.translate("Dialog_SymDlg", "轴对称", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_symmetric.setItemText(1, QtGui.QApplication.translate("Dialog_SymDlg", "镜像对称", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_symmetric.setItemText(2, QtGui.QApplication.translate("Dialog_SymDlg", "周期对称", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_type.setItemText(0, QtGui.QApplication.translate("Dialog_SymDlg", "未指定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_SymDlg", "法向周期：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Normal.setText(QtGui.QApplication.translate("Dialog_SymDlg", "0deg", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
