# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PointWidget.ui'
#
# Created: Thu Mar  4 09:34:31 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Model3D.Tools import Completer

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 248)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_x2 = QtGui.QLabel(Form)
        self.label_x2.setObjectName("label_x2")
        self.gridLayout.addWidget(self.label_x2, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.label_y2 = QtGui.QLabel(Form)
        self.label_y2.setObjectName("label_y2")
        self.gridLayout.addWidget(self.label_y2, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 7, 1, 1)
        self.label_z2 = QtGui.QLabel(Form)
        self.label_z2.setObjectName("label_z2")
        self.gridLayout.addWidget(self.label_z2, 0, 8, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 9, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_point1x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point1x.setObjectName("lineEdit_point1x")
        self.gridLayout.addWidget(self.lineEdit_point1x, 1, 1, 1, 3)
        self.lineEdit_point1y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point1y.setObjectName("lineEdit_point1y")
        self.gridLayout.addWidget(self.lineEdit_point1y, 1, 4, 1, 3)
        self.lineEdit_point1z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point1z.setObjectName("lineEdit_point1z")
        self.gridLayout.addWidget(self.lineEdit_point1z, 1, 7, 1, 3)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_point2x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point2x.setObjectName("lineEdit_point2x")
        self.gridLayout.addWidget(self.lineEdit_point2x, 2, 1, 1, 3)
        self.lineEdit_point2y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point2y.setObjectName("lineEdit_point2y")
        self.gridLayout.addWidget(self.lineEdit_point2y, 2, 4, 1, 3)
        self.lineEdit_point2z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point2z.setObjectName("lineEdit_point2z")
        self.gridLayout.addWidget(self.lineEdit_point2z, 2, 7, 1, 3)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_point3x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point3x.setObjectName("lineEdit_point3x")
        self.gridLayout.addWidget(self.lineEdit_point3x, 3, 1, 1, 3)
        self.lineEdit_point3y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point3y.setObjectName("lineEdit_point3y")
        self.gridLayout.addWidget(self.lineEdit_point3y, 3, 4, 1, 3)
        self.lineEdit_point3z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point3z.setObjectName("lineEdit_point3z")
        self.gridLayout.addWidget(self.lineEdit_point3z, 3, 7, 1, 3)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_point4x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point4x.setObjectName("lineEdit_point4x")
        self.gridLayout.addWidget(self.lineEdit_point4x, 4, 1, 1, 3)
        self.lineEdit_point4y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point4y.setObjectName("lineEdit_point4y")
        self.gridLayout.addWidget(self.lineEdit_point4y, 4, 4, 1, 3)
        self.lineEdit_point4z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point4z.setObjectName("lineEdit_point4z")
        self.gridLayout.addWidget(self.lineEdit_point4z, 4, 7, 1, 3)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_point5x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point5x.setObjectName("lineEdit_point5x")
        self.gridLayout.addWidget(self.lineEdit_point5x, 5, 1, 1, 3)
        self.lineEdit_point5y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point5y.setObjectName("lineEdit_point5y")
        self.gridLayout.addWidget(self.lineEdit_point5y, 5, 4, 1, 3)
        self.lineEdit_point5z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point5z.setObjectName("lineEdit_point5z")
        self.gridLayout.addWidget(self.lineEdit_point5z, 5, 7, 1, 3)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.lineEdit_point6x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point6x.setObjectName("lineEdit_point6x")
        self.gridLayout.addWidget(self.lineEdit_point6x, 6, 1, 1, 3)
        self.lineEdit_point6y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point6y.setObjectName("lineEdit_point6y")
        self.gridLayout.addWidget(self.lineEdit_point6y, 6, 4, 1, 3)
        self.lineEdit_point6z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point6z.setObjectName("lineEdit_point6z")
        self.gridLayout.addWidget(self.lineEdit_point6z, 6, 7, 1, 3)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.lineEdit_point7x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point7x.setObjectName("lineEdit_point7x")
        self.gridLayout.addWidget(self.lineEdit_point7x, 7, 1, 1, 3)
        self.lineEdit_point7y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point7y.setObjectName("lineEdit_point7y")
        self.gridLayout.addWidget(self.lineEdit_point7y, 7, 4, 1, 3)
        self.lineEdit_point7z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point7z.setObjectName("lineEdit_point7z")
        self.gridLayout.addWidget(self.lineEdit_point7z, 7, 7, 1, 3)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.lineEdit_point8x = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point8x.setObjectName("lineEdit_point8x")
        self.gridLayout.addWidget(self.lineEdit_point8x, 8, 1, 1, 3)
        self.lineEdit_point8y = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point8y.setObjectName("lineEdit_point8y")
        self.gridLayout.addWidget(self.lineEdit_point8y, 8, 4, 1, 3)
        self.lineEdit_point8z = Completer.AutoCompleteEdit(Form)
        self.lineEdit_point8z.setObjectName("lineEdit_point8z")
        self.gridLayout.addWidget(self.lineEdit_point8z, 8, 7, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_x2.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_y2.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_z2.setText(QtGui.QApplication.translate("Form", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Point_1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Point_2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Point_3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Point_4:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Point_5:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Point_6:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Point_7:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Point_8:", None, QtGui.QApplication.UnicodeUTF8))

