# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vol_Array_Dlg.ui'
#
# Created: Tue Nov 26 16:05:44 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_Vol_Array(object):
    def setupUi(self, Dialog_Vol_Array):
        Dialog_Vol_Array.setObjectName("Dialog_Vol_Array")
        Dialog_Vol_Array.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_Vol_Array.resize(702, 567)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Vol_Array.sizePolicy().hasHeightForWidth())
        Dialog_Vol_Array.setSizePolicy(sizePolicy)
        Dialog_Vol_Array.setMinimumSize(QtCore.QSize(0, 0))
        Dialog_Vol_Array.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_4 = QtGui.QGridLayout(Dialog_Vol_Array)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_type = QtGui.QHBoxLayout()
        self.horizontalLayout_type.setSpacing(5)
        self.horizontalLayout_type.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_type.setObjectName("horizontalLayout_type")
        self.label = QtGui.QLabel(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_type.addWidget(self.label)
        self.comboBox_type = StyledComboBox(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type.sizePolicy().hasHeightForWidth())
        self.comboBox_type.setSizePolicy(sizePolicy)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_type.addWidget(self.comboBox_type)
        self.gridLayout_4.addLayout(self.horizontalLayout_type, 0, 0, 1, 1)
        self.horizontalLayout_name = QtGui.QHBoxLayout()
        self.horizontalLayout_name.setObjectName("horizontalLayout_name")
        self.Label_Name_2 = QtGui.QLabel(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Name_2.sizePolicy().hasHeightForWidth())
        self.Label_Name_2.setSizePolicy(sizePolicy)
        self.Label_Name_2.setObjectName("Label_Name_2")
        self.horizontalLayout_name.addWidget(self.Label_Name_2)
        self.LineEdit_Name = QtGui.QLineEdit(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Name.sizePolicy().hasHeightForWidth())
        self.LineEdit_Name.setSizePolicy(sizePolicy)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.horizontalLayout_name.addWidget(self.LineEdit_Name)
        self.Label_Shadow_2 = QtGui.QLabel(Dialog_Vol_Array)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Shadow_2.sizePolicy().hasHeightForWidth())
        self.Label_Shadow_2.setSizePolicy(sizePolicy)
        self.Label_Shadow_2.setObjectName("Label_Shadow_2")
        self.horizontalLayout_name.addWidget(self.Label_Shadow_2)
        self.ComboBox_Shadow_Attribute = StyledComboBox(Dialog_Vol_Array)
        self.ComboBox_Shadow_Attribute.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Shadow_Attribute.sizePolicy().hasHeightForWidth())
        self.ComboBox_Shadow_Attribute.setSizePolicy(sizePolicy)
        self.ComboBox_Shadow_Attribute.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_Shadow_Attribute.setSizeIncrement(QtCore.QSize(1, 0))
        self.ComboBox_Shadow_Attribute.setEditable(False)
        self.ComboBox_Shadow_Attribute.setObjectName("ComboBox_Shadow_Attribute")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.ComboBox_Shadow_Attribute.addItem("")
        self.horizontalLayout_name.addWidget(self.ComboBox_Shadow_Attribute)
        self.gridLayout_4.addLayout(self.horizontalLayout_name, 1, 0, 1, 1)
        self.groupBox_main = QtGui.QGroupBox(Dialog_Vol_Array)
        self.groupBox_main.setObjectName("groupBox_main")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_main)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_main)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_start_i = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_start_i.setObjectName("lineEdit_start_i")
        self.horizontalLayout.addWidget(self.lineEdit_start_i)
        self.label_7 = QtGui.QLabel(self.groupBox_main)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEdit_endi = QtGui.QLineEdit(self.groupBox_main)
        self.lineEdit_endi.setObjectName("lineEdit_endi")
        self.horizontalLayout.addWidget(self.lineEdit_endi)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.groupBox_main)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 611, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_Point_pntX = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Point_pntX.setObjectName("lineEdit_Point_pntX")
        self.horizontalLayout_3.addWidget(self.lineEdit_Point_pntX)
        self.lineEdit_Point_pntY = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Point_pntY.setObjectName("lineEdit_Point_pntY")
        self.horizontalLayout_3.addWidget(self.lineEdit_Point_pntY)
        self.lineEdit_Point_pntZ = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Point_pntZ.setObjectName("lineEdit_Point_pntZ")
        self.horizontalLayout_3.addWidget(self.lineEdit_Point_pntZ)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(18, 10, 591, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_Annular_Ptn1X = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn1X.setObjectName("lineEdit_Annular_Ptn1X")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn1X, 0, 1, 1, 1)
        self.lineEdit_Annular_Ptn2X = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn2X.setObjectName("lineEdit_Annular_Ptn2X")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn2X, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_Annular_Ptn1Y = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn1Y.setObjectName("lineEdit_Annular_Ptn1Y")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn1Y, 0, 2, 1, 1)
        self.lineEdit_Annular_Ptn1Z = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn1Z.setObjectName("lineEdit_Annular_Ptn1Z")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn1Z, 0, 3, 1, 1)
        self.lineEdit_Annular_Ptn2Y = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn2Y.setObjectName("lineEdit_Annular_Ptn2Y")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn2Y, 1, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineEdit_Annular_Ptn2Z = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_Ptn2Z.setObjectName("lineEdit_Annular_Ptn2Z")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_Ptn2Z, 1, 3, 1, 1)
        self.lineEdit_Annular_RadOuter = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_RadOuter.setObjectName("lineEdit_Annular_RadOuter")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_RadOuter, 3, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 3, 0, 1, 1)
        self.lineEdit_Annular_RadInner = QtGui.QLineEdit(self.tab)
        self.lineEdit_Annular_RadInner.setObjectName("lineEdit_Annular_RadInner")
        self.gridLayout_7.addWidget(self.lineEdit_Annular_RadInner, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 4, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 541, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 601, 251))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_Cylinder_Ptn1X = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Ptn1X.setObjectName("lineEdit_Cylinder_Ptn1X")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Ptn1X, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_Cylinder_Ptn2Y = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Ptn2Y.setObjectName("lineEdit_Cylinder_Ptn2Y")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Ptn2Y, 1, 2, 1, 1)
        self.lineEdit_Cylinder_Ptn2X = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Ptn2X.setObjectName("lineEdit_Cylinder_Ptn2X")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Ptn2X, 1, 1, 1, 1)
        self.lineEdit_Cylinder_Ptn1Y = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Ptn1Y.setObjectName("lineEdit_Cylinder_Ptn1Y")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Ptn1Y, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_Cylinder_Ptn1Z = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Ptn1Z.setObjectName("lineEdit_Cylinder_Ptn1Z")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Ptn1Z, 0, 3, 1, 1)
        self.lineEdit_Cylinder_Ptn2Z = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Ptn2Z.setObjectName("lineEdit_Cylinder_Ptn2Z")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Ptn2Z, 1, 3, 1, 1)
        self.lineEdit_Cylinder_Rad = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cylinder_Rad.setObjectName("lineEdit_Cylinder_Rad")
        self.gridLayout_6.addWidget(self.lineEdit_Cylinder_Rad, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_main, 2, 0, 1, 1)
        self.groupBox_NonUniform = QtGui.QGroupBox(Dialog_Vol_Array)
        self.groupBox_NonUniform.setObjectName("groupBox_NonUniform")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_NonUniform)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_UniformY = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformY.setObjectName("checkBox_UniformY")
        self.gridLayout.addWidget(self.checkBox_UniformY, 0, 1, 1, 1)
        self.checkBox_UniformZ = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformZ.setObjectName("checkBox_UniformZ")
        self.gridLayout.addWidget(self.checkBox_UniformZ, 0, 2, 1, 1)
        self.checkBox_UniformX = QtGui.QCheckBox(self.groupBox_NonUniform)
        self.checkBox_UniformX.setObjectName("checkBox_UniformX")
        self.gridLayout.addWidget(self.checkBox_UniformX, 0, 0, 1, 1)
        self.lineEdit_UniformX = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformX.setObjectName("lineEdit_UniformX")
        self.gridLayout.addWidget(self.lineEdit_UniformX, 1, 0, 1, 1)
        self.lineEdit_UniformY = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformY.setObjectName("lineEdit_UniformY")
        self.gridLayout.addWidget(self.lineEdit_UniformY, 1, 1, 1, 1)
        self.lineEdit_UniformZ = QtGui.QLineEdit(self.groupBox_NonUniform)
        self.lineEdit_UniformZ.setObjectName("lineEdit_UniformZ")
        self.gridLayout.addWidget(self.lineEdit_UniformZ, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_NonUniform, 3, 0, 1, 1)
        self.horizontalLayout_okAndCancel = QtGui.QHBoxLayout()
        self.horizontalLayout_okAndCancel.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_okAndCancel.setObjectName("horizontalLayout_okAndCancel")
        self.pushButton_ok = QtGui.QPushButton(Dialog_Vol_Array)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog_Vol_Array)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_okAndCancel.addWidget(self.pushButton_cancel)
        self.gridLayout_4.addLayout(self.horizontalLayout_okAndCancel, 4, 0, 1, 1)

        self.retranslateUi(Dialog_Vol_Array)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Vol_Array)

    def retranslateUi(self, Dialog_Vol_Array):
        Dialog_Vol_Array.setWindowTitle(QtGui.QApplication.translate("Dialog_Vol_Array", "束发射", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "循环体结构类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(0, QtGui.QApplication.translate("Dialog_Vol_Array", "点", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(1, QtGui.QApplication.translate("Dialog_Vol_Array", "正投影线", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(2, QtGui.QApplication.translate("Dialog_Vol_Array", "斜线", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(3, QtGui.QApplication.translate("Dialog_Vol_Array", "正投影面", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(4, QtGui.QApplication.translate("Dialog_Vol_Array", "矩形面", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(5, QtGui.QApplication.translate("Dialog_Vol_Array", "正投影体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(6, QtGui.QApplication.translate("Dialog_Vol_Array", "环形体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(7, QtGui.QApplication.translate("Dialog_Vol_Array", "圆柱体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(8, QtGui.QApplication.translate("Dialog_Vol_Array", "圆台体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(9, QtGui.QApplication.translate("Dialog_Vol_Array", "平行六面体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(10, QtGui.QApplication.translate("Dialog_Vol_Array", "球形体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(11, QtGui.QApplication.translate("Dialog_Vol_Array", "楔形体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(12, QtGui.QApplication.translate("Dialog_Vol_Array", "金字塔体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(13, QtGui.QApplication.translate("Dialog_Vol_Array", "菱形体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(14, QtGui.QApplication.translate("Dialog_Vol_Array", "四面体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(15, QtGui.QApplication.translate("Dialog_Vol_Array", "半圆环体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(16, QtGui.QApplication.translate("Dialog_Vol_Array", "环形区域体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(17, QtGui.QApplication.translate("Dialog_Vol_Array", "挤出体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(18, QtGui.QApplication.translate("Dialog_Vol_Array", "螺旋体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(19, QtGui.QApplication.translate("Dialog_Vol_Array", "阵列体", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_type.setItemText(20, QtGui.QApplication.translate("Dialog_Vol_Array", "函数体", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Name_2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_Name.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Emit_Beam", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_Shadow_2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "属性：", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(0, QtGui.QApplication.translate("Dialog_Vol_Array", "未定义", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(1, QtGui.QApplication.translate("Dialog_Vol_Array", "理想导体", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(2, QtGui.QApplication.translate("Dialog_Vol_Array", "自定义", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboBox_Shadow_Attribute.setItemText(3, QtGui.QApplication.translate("Dialog_Vol_Array", "理想导体", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_main.setTitle(QtGui.QApplication.translate("Dialog_Vol_Array", "结构类型", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "变量i起始：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "变量i结束：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "点", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog_Vol_Array", "点", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog_Vol_Array", "正投影线", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog_Vol_Array", "斜线", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog_Vol_Array", "正投影面", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Dialog_Vol_Array", "矩形面", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("Dialog_Vol_Array", "正投影体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点2：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "内半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "外半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog_Vol_Array", "环形体", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "中心点2：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "半径：", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog_Vol_Array", "圆柱体", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_NonUniform.setTitle(QtGui.QApplication.translate("Dialog_Vol_Array", "非均匀网格", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformY.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformZ.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_UniformX.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("Dialog_Vol_Array", "取消", None, QtGui.QApplication.UnicodeUTF8))

from StyledComboBox import StyledComboBox
